### ISSUE TITLE
Do Not Disturb

### ISSUE THREAD

**Issue by JPUnix** [BelledonneCommunications/linphone-desktop#10]
Please re-consider the "Do Not Disturb" feature! There are MANY instances where one would wish to have calls sent to VM. There are many other status modes that will allow calls to ring through. Please allow at least one mode to send calls to Voice Mail.

**Comment by julonexus** [comment]
DND is implemented in the current version .

**Comment by twoelfer** [comment]
hi. I just tried "do not disturb" and "offline" (as status setting) but in both cases, connections still get through and the ring tone is played. am i missing something? thx!
