### ISSUE TITLE
No sound when calling a conference server.

### ISSUE THREAD

**Issue by thilo-fester** [BelledonneCommunications/linphone-desktop#100]
I just freshly installed Linphone Desktop 4.1.1 (Qt 5.9.0, Core 3.12.0) on Ubuntu 16.04 using flatpak as described in the official documentation.

Linphone is connected as WLAN client to my local router (FRITZ!Box 7412, FRITZ!OS: 06.83). There also are a Zoiper client next to Linphone on the same machine and a FRITZ!Fon (DECT) connected to the same router, which I both used to check my tests.

Using Linphone it is possible to start and receive calls to/from my mobile phone or other usual phone lines without any problems (its awesome btw! I had lots of trouble with other sip clients before).

Today, I tried to call a conference server in my company and did not hear anything. The call was automatically stopped after 30 seconds (by Linphone I guess). When I use Zoiper or FRITZ!Fon, it is possible to hear the conference server asking me to enter the conference server password. Additionally I tried to leave the password empty by typing nothing with the FRITZ!Fon and noticed, that the conference server is not finishing the call after more than a minute (this is, why I think Linphone is closing the connection after 30 seconds of silence).

Linphone's log output is attached.

[linphone-2017-10-26.log](https://github.com/BelledonneCommunications/linphone-desktop/files/1417590/linphone-2017-10-26.log)

**Comment by Viish** [comment]
Hi,
Indeed if the client doesn't receive audio for 30 seconds it shuts down the call.
You can change this behavior by setting the number of seconds (or 0 to disable it) in the [sip] section of the linphonerc with the in_call_timeout parameter.
Cheers,

**Comment by thilo-fester** [comment]
Hi,

thanks for your reply. Sadly this is not solving the problem. The call is answered immediately whenever I use an alternative client or phone.

Regards

**Comment by S0U1SB4N3** [comment]
please ensure your keep alive is being read by your asterisk server the 30 second kill is due to no response from your server, watch your console output when testing and you can see no reply and a hangup is being sent, I had to modify what was being sent to my personal server ignorer for the handshake to occur. you may need to do the same.

**Comment by Wescoeur** [comment]
It's a server problem. The packets are not receiving by the app.
