### ISSUE TITLE
no history for missed call ?

### ISSUE THREAD

**Issue by krodelabestiole** [BelledonneCommunications/linphone-desktop#102]
I can't see no missed incoming call in history for my SIP accounts, in Linphone desktop 4.1.1.
The log doesn't show anything about that either.

I think it's a major functionality that lacks.

- plus I've just had a bug with an incoming call ringing but no popup showing so I could not answer, neither know who was calling. I can't document it yet because I can't reproduce it after having relaunched the app, still this might be very annoying considering this missing functionality.

**Comment by krodelabestiole** [comment]
ok now i can see missed calls in history.
I guess the absence of missed call in history and the absence of popup during the incoming call were part of the same bug then.
I'm closing this issue for now, I might reopen it if I run into this bug again and I can documente it.

**Comment by S0U1SB4N3** [comment]
is this an apple iOS build ?

**Comment by Lilian-Sash** [comment]
I have this issue, how was this resolved?
