### ISSUE TITLE
call a number without adding a contact

### ISSUE THREAD

**Issue by krodelabestiole** [BelledonneCommunications/linphone-desktop#103]
I use Linphone desktop 4 mainly as an SIP client with two phone lines.

I think it would be nice to be able to call a new phone number without necessarily having to add a contact every time (just by typing the number and selecting the SIP account i.e.).

**Comment by S0U1SB4N3** [comment]
you can from the search bar at the top just type the number and click the call button 
![screen shot 2017-11-02 at 5 32 26 pm](https://user-images.githubusercontent.com/22788570/32353551-dec336c6-bff3-11e7-8728-4604c766d49f.png)

**Comment by krodelabestiole** [comment]
oooOOOOOooOOOHHH

my bad ! thanks a lot !  ;)
