### ISSUE TITLE
I need to remove the "sip:" and the "@domain.com" just from the view 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-desktop#104]
I need to change sip:1235551234@domain.com to just 1235551234 on the UI but leave the sip address fully intact internally. please help. I've ran a few strings in QT in a separate program however it crashes your program. 

(sipAddress.replace(/.*\:|\@.*/g, ‘’))
is what im using

**Comment by S0U1SB4N3** [comment]
Can someone please assist me with this

**Comment by systemcrash** [comment]
This is what display portions are for - and form part of a URI. Removing any part of the sip: URI will make it an illegal URI, and break things. 

"display portion" <sip:..blah..@domain.com>

**Comment by S0U1SB4N3** [comment]
This is just at the UI level not the core

**Comment by S0U1SB4N3** [comment]
I got this working fine you can close

**Comment by S0U1SB4N3** [comment]
I’m making a more user friendly version because most people just want to see their phone number, like in a normal caller ID like on your cell phone just the name and number 

And the phone book can store and append the sip: internally but the enduser really doesn’t need to see it. 

Just:
John smith
123-555-1234

**Comment by LiamKarlMitchell** [comment]
Yes please remove this sip stuff for normal cell/phone numbers.
I understand its still routed through some sip address but it is unnecessary to see.

sip:021123456789@kamailio.netfone.co.nz

**Comment by Zulkifilyusuf750** [comment]
Set `replace_sip_uri_by_username=1` in the `[app]` section of the **assets\linphonerc_default** file.

**Comment by tamartelecom** [comment]
Does anyone know the iPhone alternative? This doesn't seem to work on iPhone but works perfectly on Android
