### ISSUE TITLE
WHY Can no one compile the windows version ?? 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-desktop#110]
if linphone is available for desktop Windows, then why can't myself or anyone recently involved get it to compile on their PC ???

**Comment by Wescoeur** [comment]
Because we are a very small company, the windows development has been frozen since several months:
- We are working on a big c++ reworking, you can look here: [c++ refactoring](https://github.com/BelledonneCommunications/linphone/commits/dev_refactor_cpp)
- We are working on new features like multi-file transfer, group chat, ...
- An other things...

I think (and I hope) the windows build will be available in one month. But for the moment 80% of our team work on the Linphone Core.

**Comment by mossabkhabbaz** [comment]
thanks very much for response @Wescoeur ,
how can build or what brunch of the current .exe available on site and work,

please advice for the step if we can....

**Comment by S0U1SB4N3** [comment]
thank you dos much for the response, I've found and fixed a bug in your linphone iPhone since the upgrade to Xcode 9 and iOS 11.1.1 your voicemail leaves a null even if a predefined string is in place, ill post the correction shortly

**Comment by S0U1SB4N3** [comment]
how is the progress on this issue going ?

**Comment by S0U1SB4N3** [comment]
do you have an update as to the ETA for completion ? Im still having issues on both desktop and windows 10 versions as well as macOS dial-pad long press

**Comment by S0U1SB4N3** [comment]
Do we have an update on this projects progress ? also as of 15dec2017 at 11:52 am or 1152 the project errors out as follows on the macOS version 

[  1%] Built target ms2-basedescs-header
Scanning dependencies of target ms2-git-version
fatal: Not a git repository: ../../.git/modules/submodules/mediastreamer2
fatal: Not a git repository: ../../.git/modules/submodules/mediastreamer2
fatal: Not a git repository: ../../.git/modules/submodules/mediastreamer2
[  1%] Built target ms2-git-version
Scanning dependencies of target mediastreamer_base
[  1%] Building C object src/CMakeFiles/mediastreamer_base.dir/base/eventqueue.c.o
[  2%] Building C object src/CMakeFiles/mediastreamer_base.dir/base/mscommon.c.o
[  3%] Building C object src/CMakeFiles/mediastreamer_base.dir/base/msfactory.c.o
/Users/S0U1SB4N3/test006/linphone-desktop/submodules/mediastreamer2/src/base/msfactory.c:177:71: error: expected ')'
        ms_message("Mediastreamer2 factory " MEDIASTREAMER_VERSION " (git: " MS2_GIT_VERSION ") initialized.");
                                                                             ^
/Users/S0U1SB4N3/test006/linphone-desktop/submodules/mediastreamer2/src/base/msfactory.c:177:12: note: to match this '('
        ms_message("Mediastreamer2 factory " MEDIASTREAMER_VERSION " (git: " MS2_GIT_VERSION ") initialized.");
                  ^
1 error generated.
make[6]: *** [src/CMakeFiles/mediastreamer_base.dir/base/msfactory.c.o] Error 1
make[5]: *** [src/CMakeFiles/mediastreamer_base.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/S0U1SB4N3/test006/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-build] Error 2
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [desktop-build] Error 2


@Wescoeur @DatBewar
