### ISSUE TITLE
Getting the UI to display just the caller ID and just the phone number 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-desktop#112]
the caller ID just shows the name and the sip:1125551234@linphone.org 

Linphone HQ 
sip:1125551234@linphone.org 

as an example however sip:1125551234@linphone.org is everywhere and I just want it to read 
Linphone HQ 
1125551234

for all entries in the contacts, address book, history UI 

I understand it needs thesip:1125551234@linphone.org internally, but we should be able to strip this out prior to it hitting the GUI 

I have made the necessary code to strip out in multiple formats' but it keeps either being overwritten or errors out. 

please help 

c++ 
#include <iostream>

using namespace std;

int main() {
	std::string sipAddress("sip:1235551234@linphone.org");
sipAddress.erase(sipAddress.find('@')); 
sipAddress.erase(0,sipAddress.find(':')+1);
cout << sipAddress;
}

QT
QString s = "sip:+01112126607300@Linphone.org";
int index = s.lastIndexOf(":")+1;
 if (index > 0)
 s = s.remove(0, index);
 s = s.mid(0, s.indexOf("@"));

 QPushButton button (s);
 button.show();

QT filename.qml file 
Corrected within QML String inline
text: (AccountSettingsModel.sipAddress.replace(/.*\:|\@.*/g, ‘’))

QT filename.cpp 
QString AccountSettingsModel::getSipNumber () const  {
  sipNumber = Utils::coreStringToAppString(getUsedSipAddress()->asStringUriOnly());
  int index = sipNumber.lastIndexOf(":")+1;
 	if (index > 0)
 	sipNumber = sipNumber.remove(0, index);
 	sipNumber = sipNumber.mid(0, sipNumber.indexOf("@"));
	
}

I have successfully stripped out the username but not the sip addresses there is no differences I can see from sip:username@linphone.org and sip:1125551234@linphone.org 

my code strips out the @ and the sip: leavings only the desired output remaining. 

can you point me to the right file to get the desired end results ? Please? 
I was able to do this on the iOS and the android versions without problems, however I can't find it in the desktop macOS

**Comment by S0U1SB4N3** [comment]
I finally found the location to do this and leave the core intact, thank you you may close this now.

**Comment by varma86** [comment]
does anybody inserted the solution of this bug inside the source code?
is this problem the same I signalled in this email?

"I noticed that the new Windows  4.x versions are affected by this annoying problem.
Either Pop-Up and software GUI, when receiving a call from an extension, display only the Extension number and not the Name.
With Android version and 3.11 Windows Desktop version the name appears correctly, so it has to be a bug made in the new version.
But unfortunately I really like the popup that you introduced in version 4.x "

Thank you again

**Comment by pdarcos** [comment]
@S0U1SB4N3 Can you share what you learned?
I'd like to do the same.

Thanks

**Comment by S0U1SB4N3** [comment]
there are several places to modify @pdarcos 

the line number will be different on the new build 4.1.1  this one was for 4.1 
linphone-desktop/ui/modules/Linphone/Contact/ContactDescription.qml
	
	[Line 32] text: (SipAddressesModel.cleanSipAddress(sipAddress).replace(/.*\:|\@.*/g, ''))

		This removed sip@domain from the incoming calls UI 
this leaves the core intact but changes at the UI Level. I need the phone book to do the same but haven't been able to yet without breaking the core.
