### ISSUE TITLE
MKV video recording does not work on Windows

### ISSUE THREAD

**Issue by mdanh2002** [BelledonneCommunications/linphone-desktop#115]
Video recording into MKV does not work in Linphone for Windows v4.1.1. This is simply because the program generates the recording filename using the format string 'yyyy-mm-dd_hh:mm:ss.mkv' that has the colon character (disallowed in Windows). The responsible code is in method setRecordFile() in CallModel.cpp and method startRecording() in ConferenceModel.cpp. Just changing the format strings to 'yyyy-mm-dd_hh_mm_ss.mkv' allows the recording to work properly.

I wrote about this issue in details here: http://www.toughdev.com/content/2017/10/fixing-video-recording-bug-with-linphone-v4-1-1-for-windows/

**Comment by Wescoeur** [comment]
Thank you very much for your report. Great investigation. ;)

**Comment by l1m3r** [comment]
Thanks for the fixed "linphone.exe" binary from your blog post - it works perfectly (and doesn't contain any nefarious other changes - I checked).
