### ISSUE TITLE
 file RENAME failed to rename when run python

### ISSUE THREAD

**Issue by akiJoin** [BelledonneCommunications/linphone-desktop#120]
hi,I got error message like below. the files is exit. but just failed. And it is success when i copy with  "cmd". Please help!

CMake Error at cmake/CheckBuildTools.cmake:133 (file):
  file RENAME failed to rename

    E:/Codes/C/linphone_d/linphone-desktop/WORK/desktop/cmake/pkg-config/bin/pkg-config.exe

  to

    C:/MinGW/bin/pkg-config.exe

  because: No error

CMake Error at cmake/CheckBuildTools.cmake:134 (file):
  file RENAME failed to rename

    E:/Codes/C/linphone_d/linphone-desktop/WORK/desktop/cmake/pkg-config/share/aclocal/pkg.m4

  to

    C:/MinGW/share/aclocal/pkg.m4

  because: No error

CMake Error at builders/vpx.cmake:77 (file):
  file failed to open for reading (No such file or directory):

    E:/Codes/C/linphone_d/linphone-desktop/WORK/desktop/cmake/windowsenv_path.txt
Call Stack (most recent call first):
  cmake/CMakeLists.txt:284 (include)
  cmake/CMakeLists.txt:298 (linphone_builder_include_builder)
  cmake/CMakeLists.txt:339 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:254 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:261 (lcb_declare_target)
  builders/CMakeLists.txt:76 (lcb_declare_targets)
  configs/config-desktop-common.cmake:92 (include)
  configs/config-desktop.cmake:53 (include)
  CMakeLists.txt:64 (include)

**Comment by Faik-man** [comment]
try to run in cmd "git submodule update --init --recursive" (without quotes) after "git clone" in folder "linphone-desktop"

**Comment by moisesynfam** [comment]
I'm experiencing the same issue. Can somebody help us?

**Comment by LAOMENGA** [comment]
so,have you finished it ?

**Comment by LAOMENGA** [comment]
copy  Manually

**Comment by Shaw666** [comment]
cmake file(RENAME, oldfile, newfile),if you got this error:file RENAME failed to rename, just you move code to C: if you MinGW in C:.就是我测试cmake的file()操作中重命名并不能跨盘符。我把代码移到MinGW同一目录后也就是C盘，prepare.py之后错误解决

**Comment by pmtoan** [comment]
I get same this error when building Linphone from source. Help me, please!

**Comment by xiedong2002** [comment]
I also run into the same issue . As mentioned from Shaw666's reply , the error is caused by the different driver names when executing file rename in cmake . As a solution , just copy project to the driver where mingw is installed. Thanks to Shaw666 for the tip.
