### ISSUE TITLE
how i know the connection is with zrtp

### ISSUE THREAD

**Issue by whitetornado** [BelledonneCommunications/linphone-desktop#122]
on both phones i select under Settngs ==> Call ==> Media encryption ZRTP, but how i know that we are talking under this encryption??

**Comment by Wescoeur** [comment]
A confirmation question must be asked in the call view and the padelock in the lop left corner must be grey.

**Comment by whitetornado** [comment]
is there a walktrough with our own sip server how to get voice with zrtp ?
and settings in linphone with some screenshots?

2018-01-16 14:46 GMT+01:00 Ronan Abhamon <notifications@github.com>:

**Comment by Wescoeur** [comment]
ZRTP should work directly with your own server.

**Comment by whitetornado** [comment]
it's a peer to peer solution? but the server shall have also some settings
for this? Now i only get a cross through a lock in the upper right corner..

2018-01-17 11:59 GMT+01:00 Ronan Abhamon <notifications@github.com>:
