### ISSUE TITLE
Recorded calls path in windows?

### ISSUE THREAD

**Issue by fightforge** [BelledonneCommunications/linphone-desktop#127]
Hi,
i cannot found recorded call files in windows. Could you give the path?

Thanks

**Comment by Wescoeur** [comment]
In the Preferences -> User Interface -> Saved videos folder, you have the path of video/audio files. But it was an issue on windows, you can see here : #115.

The problem is fixed in the master branch. You can build the project or wait the next 4.2 release. :)
