### ISSUE TITLE
ubuntu build fails on ms compilation

### ISSUE THREAD

**Issue by pdarcos** [BelledonneCommunications/linphone-desktop#129]
ubuntu 16.0.4 LTS.
Everything seems OK until the very end of make where it complains about missing ALSA and PulseAudio (both are actually installed so don't know why it can't find them)

-- Check if the system is big endian - little endian
-- Found SRTP: /home/solo/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
-- Found GSM: /home/solo/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
-- Found bv16: /home/solo/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
-- Found Opus: /home/solo/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
-- Found Speex: /home/solo/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
-- Found SpeexDsp: /home/solo/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
-- Could NOT find ALSA (missing:  ALSA_INCLUDE_DIRS ALSA_LIBRARIES HAVE_ALSA_ASOUNDLIB_H HAVE_SND_PCM_OPEN) 
-- Could NOT find PulseAudio (missing:  PULSEAUDIO_INCLUDE_DIRS PULSEAUDIO_LIBRARIES HAVE_PULSE_PULSEAUDIO_H HAVE_PA_MAINLOOP_NEW) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for avcodec_get_context_defaults3
-- Looking for avcodec_get_context_defaults3 - found
-- Looking for avcodec_open2
-- Looking for avcodec_open2 - found
-- Looking for avcodec_encode_video2
-- Looking for avcodec_encode_video2 - not found
-- Looking for av_frame_alloc
-- Looking for av_frame_alloc - not found
-- Looking for av_frame_free
-- Looking for av_frame_free - not found
-- Looking for av_frame_unref
-- Looking for av_frame_unref - not found
-- Found FFMpeg: /home/solo/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
-- Found V4L: /usr/include  
-- Found X11: /usr/include  
-- Could NOT find Xv (missing:  HAVE_X11_EXTENSIONS_XV_H HAVE_X11_EXTENSIONS_XVLIB_H HAVE_XV_CREATE_IMAGE) 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Looking for GL/gl.h
-- Looking for GL/gl.h - found
-- Looking for GL/glx.h
-- Looking for GL/glx.h - found
-- Could NOT find GLX (missing:  GLX_LIBRARIES) 
-- Found VPX: /home/solo/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
CMake Error at CMakeLists.txt:321 (message):
  Could not find a support sound driver API.  Use -DENABLE_SOUND=NO if you
  don't care about having sound.

-- Configuring incomplete, errors occurred!
See also "/home/solo/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
See also "/home/solo/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeError.log".
CMakeFiles/EP_ms2.dir/build.make:119: recipe for target '/home/solo/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure' failed
make[3]: *** [/home/solo/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[3]: Leaving directory '/home/solo/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
CMakeFiles/Makefile2:116: recipe for target 'CMakeFiles/EP_ms2.dir/all' failed
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[2]: Leaving directory '/home/solo/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/solo/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:14: recipe for target 'desktop-build' failed
make: *** [desktop-build] Error 2

I've pasted the CMake logs at pastebin here https://pastebin.com/8tyTjvJT

Any help?

Thanks

**Comment by pdarcos** [comment]
I tried removing sound to see if at least it would compile: 
./prepare.py -DENABLE_SOUND=NO
then ran make and got the same error

CMake Error at CMakeLists.txt:321 (message):
  Could not find a support sound driver API.  Use -DENABLE_SOUND=NO if you
  don't care about having sound.

The weird part is that I do have Alsa and PulseAudio installed:
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 0: ALC892 Analog [ALC892 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 1: ALC892 Digital [ALC892 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

cat /proc/asound/version
Advanced Linux Sound Architecture Driver Version k4.4.0-109-generic.

Any clues?

Thanks

**Comment by pdarcos** [comment]
Anyone have any clue/hint?

Is it just me that can't compile on ubuntu?

**Comment by pdarcos** [comment]
Tried on another machine running ubuntu and got the same problem:

CMake Error at CMakeLists.txt:321 (message):
  Could not find a support sound driver API.  Use -DENABLE_SOUND=NO if you
  don't care about having sound.


-- Configuring incomplete, errors occurred!
See also "/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
See also "/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeError.log".
CMakeFiles/EP_ms2.dir/build.make:119: recipe for target '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure' failed
make[3]: *** [/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[3]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
CMakeFiles/Makefile2:116: recipe for target 'CMakeFiles/EP_ms2.dir/all' failed
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[2]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:14: recipe for target 'desktop-build' failed
make: *** [desktop-build] Error 2

Anyone else?

**Comment by pdarcos** [comment]
Just did a fresh git clone and the problem remains. I also get some warnings when compiling:

libtool: warning: '-version-info/-version-number' is ignored for convenience libraries


make[7]: Entering directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/v4l/lib/libv4l2'
 /bin/mkdir -p '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/lib'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   libv4l2.la '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/lib'
libtool: warning: relinking 'libv4l2.la'


make[8]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/v4l/lib/libv4l2'
 /bin/mkdir -p '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include'
 /usr/bin/install -c -m 644 /home/john/Documents/testbuild/linphone-desktop/submodules/externals/v4l-utils/lib/libv4l2/../include/libv4l2.h /home/john/Documents/testbuild/linphone-desktop/submodules/externals/v4l-utils/lib/libv4l2/../include/libv4l-plugin.h '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include'
 /bin/mkdir -p '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/lib/libv4l'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   v4l2convert.la '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/lib/libv4l'
libtool: warning: relinking 'v4l2convert.la'


make[7]: Entering directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/v4l/lib/libv4l1'
 /bin/mkdir -p '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/lib'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   libv4l1.la '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/lib'
libtool: warning: relinking 'libv4l1.la'


/usr/bin/install -c -m 644 /home/john/Documents/testbuild/linphone-desktop/submodules/externals/v4l-utils/lib/libv4l1/../include/libv4l1.h /home/john/Documents/testbuild/linphone-desktop/submodules/externals/v4l-utils/lib/libv4l1/../include/libv4l1-videodev.h '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include'
 /bin/mkdir -p '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/lib/libv4l'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   v4l1compat.la '/home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/lib/libv4l'
libtool: warning: relinking 'v4l1compat.la'


-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Looking for GL/gl.h
-- Looking for GL/gl.h - found
-- Looking for GL/glx.h
-- Looking for GL/glx.h - found
-- Could NOT find GLX (missing:  GLX_LIBRARIES) 
-- Found VPX: /home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
CMake Error at CMakeLists.txt:321 (message):
  Could not find a support sound driver API.  Use -DENABLE_SOUND=NO if you
  don't care about having sound.


-- Configuring incomplete, errors occurred!
See also "/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
See also "/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeError.log".
CMakeFiles/EP_ms2.dir/build.make:119: recipe for target '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure' failed
make[3]: *** [/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[3]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
CMakeFiles/Makefile2:116: recipe for target 'CMakeFiles/EP_ms2.dir/all' failed
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[2]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:14: recipe for target 'desktop-build' failed
make: *** [desktop-build] Error 2

Any help?

**Comment by ghismary** [comment]
You need to install either alsa or pulse audio developpement package on your system.

**Comment by pdarcos** [comment]
Thanks @ghismary 

Unfortunately it still gives me compilation errors:

sudo apt-get install libpulse-dev
sudo apt-get install pulseaudio
sudo apt-get install libasound2-dev
sudo apt-get install pavucontrol
sudo apt install alsa-lib


-- Could NOT find Xv (missing:  HAVE_X11_EXTENSIONS_XV_H HAVE_X11_EXTENSIONS_XVLIB_H HAVE_XV_CREATE_IMAGE) 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Looking for GL/gl.h
-- Looking for GL/gl.h - found
-- Looking for GL/glx.h
-- Looking for GL/glx.h - found
-- Could NOT find GLX (missing:  GLX_LIBRARIES) 
-- Found VPX: /home/john/Documents/testbuild/linphone-desktop/OUTPUT/desktop/include  
-- Performing Test TURBOJPEG_USE_CONST_BUFFERS
-- Performing Test TURBOJPEG_USE_CONST_BUFFERS - Failed
-- Found TurboJpeg: /usr/include  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Found Git: /usr/bin/git (found version "2.7.4") 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Glew (missing: GLEW_INCLUDE_DIRS GLEW_LIBRARIES
  HAVE_GL_GLEW_H)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGlew.cmake:45 (find_package_handle_standard_args)
  src/CMakeLists.txt:430 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
See also "/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeError.log".
CMakeFiles/EP_ms2.dir/build.make:119: recipe for target '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure' failed
make[3]: *** [/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[3]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
CMakeFiles/Makefile2:116: recipe for target 'CMakeFiles/EP_ms2.dir/all' failed
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[2]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:14: recipe for target 'desktop-build' failed
make: *** [desktop-build] Error 2

What else can I do?

**Comment by pdarcos** [comment]
Tried the obvious: sudo apt-get install libglew-dev

But still getting compiler errors:

[ 88%] Building C object src/CMakeFiles/mediastreamer_voip.dir/utils/mkv_reader.c.o
[ 89%] Linking CXX shared library libmediastreamer_voip.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/mediastreamer_voip.dir/build.make:2374: recipe for target 'src/libmediastreamer_voip.so.10' failed
make[6]: *** [src/libmediastreamer_voip.so.10] Error 1
make[6]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2'
CMakeFiles/Makefile2:239: recipe for target 'src/CMakeFiles/mediastreamer_voip.dir/all' failed
make[5]: *** [src/CMakeFiles/mediastreamer_voip.dir/all] Error 2
make[5]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2'
Makefile:149: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/ms2'
CMakeFiles/EP_ms2.dir/build.make:125: recipe for target '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-build' failed
make[3]: *** [/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-build] Error 2
make[3]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
CMakeFiles/Makefile2:116: recipe for target 'CMakeFiles/EP_ms2.dir/all' failed
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[2]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:14: recipe for target 'desktop-build' failed
make: *** [desktop-build] Error 2

**Comment by pdarcos** [comment]
Here's where it fails:
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): **relocation R_X86_64_32 against `.data' can not be used when making a shared object**; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/mediastreamer_voip.dir/build.make:2374: **recipe for target 'src/libmediastreamer_voip.so.10' failed**
make[6]: *** [src/libmediastreamer_voip.so.10] Error 1

**Comment by rdiez** [comment]
This appears to be covered in the following issue: #58

**Comment by rudy2steiner** [comment]
i met the same problem

**Comment by hendryw** [comment]
try "sudo apt-get install libpulse-dev pulseaudio apulse", it works for me

**Comment by fengqz627** [comment]
Hello, 
The linphone-desktop I downloaded yesterday encountered the same problem in compiling,
But I executed the following three commands, and the problem still exists. Please help :

sudo apt-get install libpulse-dev
sudo apt-get install pulseaudio
sudo apt-get install apulse

-----------------------------------------------
CMake Error at CMakeLists.txt:369 (message):
  Could not find a support sound driver API.  Use -DENABLE_SOUND=NO if you
  don't care about having sound.


-- Configuring incomplete, errors occurred!
See also "/home/fqz/linphoneD/linphone-desktop/build/WORK/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
See also "/home/fqz/linphoneD/linphone-desktop/build/WORK/WORK/desktop/Build/ms2/CMakeFiles/CMakeError.log".
make[8]: *** [CMakeFiles/EP_ms2.dir/build.make:108: /home/fqz/linphoneD/linphone-desktop/build/WORK/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[7]: *** [CMakeFiles/Makefile2:953: CMakeFiles/EP_ms2.dir/all] Error 2

thanks.
Best Regards.
