### ISSUE TITLE
DNS: resoving domain names fail

### ISSUE THREAD

**Issue by Hc10b** [BelledonneCommunications/linphone-desktop#13]
Recently linphone stopped working for me. Neither registration nor calling outwards is possible anymore. Calling results in an IO Error.
Starting `linphone --verbose` revealed:

```
linphone-message : transaction [0xd0cdd0] channel state changed to [RES_IN_PROGRESS]
linphone-message : Resolver is using DNS server(s):
linphone-message : 	192.168.1.1
linphone-message : No SRV result for [_sip._tcp.sip.easybell.de], trying A/AAAA.
linphone-message : Resolver is using DNS server(s):
linphone-message : 	192.168.1.1
linphone-error : channel_res_done: DNS resolution failed for sip.easybell.de
linphone-message : channel 0xd31750: state ERROR
```

So it seems to be an DNS resolving problem. Indeed it's true that there is no SRV, but an A entry for sip.easybell.de and it had worked before (at least with linphone 3.9).

Actually there are more people experiencing the same issue [at the Arch Linux forum](https://bbs.archlinux.org/viewtopic.php?id=222307).

Is this a bug or a configuration issue? Please let me know if I can provide you with more information.
Thanks a lot in advance.

Edit:
Linphone 3.10.2-3 on Arch Linux.

**Comment by marmistrz** [comment]
The same problem happens for me under Arch Linux with the official linphone server.
```
message: 2017-02-01 17:35:18:304 New local ip address is 192.168.0.106
message: 2017-02-01 17:35:18:304 SIP network reachability state is now [UP]
message: 2017-02-01 17:35:18:304 Resolver is using DNS server(s):
message: 2017-02-01 17:35:18:304 	208.67.222.222
message: 2017-02-01 17:35:18:304 	208.67.220.220
message: 2017-02-01 17:35:18:304 	192.168.0.1
message: 2017-02-01 17:35:18:304 No SRV result for [_stun._udp.stun.linphone.org], trying A/AAAA.
message: 2017-02-01 17:35:18:304 Resolver is using DNS server(s):
message: 2017-02-01 17:35:18:304 	208.67.222.222
message: 2017-02-01 17:35:18:304 	208.67.220.220
message: 2017-02-01 17:35:18:304 	192.168.0.1
warning: 2017-02-01 17:35:18:304 Stun server resolution failed.
message: 2017-02-01 17:35:18:304 Media network reachability state is now [UP]
message: 2017-02-01 17:35:18:305 LinphoneProxyConfig [0xa7eb40] about to register (LinphoneCore version: 3.10.2)
message: 2017-02-01 17:35:18:404 belle_sip_client_transaction_send_request(): waiting channel to be ready
message: 2017-02-01 17:35:18:404 channel [0xbbd4e0]: starting resolution of sip.linphone.org
message: 2017-02-01 17:35:18:404 channel 0xbbd4e0: state RES_IN_PROGRESS
message: 2017-02-01 17:35:18:404 transaction [0xb7a3a0] channel state changed to [RES_IN_PROGRESS]
message: 2017-02-01 17:35:18:404 Resolver is using DNS server(s):
message: 2017-02-01 17:35:18:404 	208.67.222.222
message: 2017-02-01 17:35:18:404 	208.67.220.220
message: 2017-02-01 17:35:18:404 	192.168.0.1
message: 2017-02-01 17:35:18:404 No SRV result for [_sips._tcp.sip.linphone.org], trying A/AAAA.
message: 2017-02-01 17:35:18:404 Resolver is using DNS server(s):
message: 2017-02-01 17:35:18:404 	208.67.222.222
message: 2017-02-01 17:35:18:404 	208.67.220.220
message: 2017-02-01 17:35:18:404 	192.168.0.1
error: 2017-02-01 17:35:18:404 channel_res_done: DNS resolution failed for sip.linphone.org
message: 2017-02-01 17:35:18:404 channel 0xbbd4e0: state ERROR
message: 2017-02-01 17:35:18:404 Neither Expires header nor corresponding Contact header found, checking from original request
```
Linphone 3.6 on Linux Mint 17.x works as expected.

**Comment by Hc10b** [comment]
After further investigation I believe that linphone has worked on 4th Dezember. At that time linphone 3.10.2-2 had already been installed.

**Comment by marmistrz** [comment]
Related: https://bugs.archlinux.org/task/52661?project=5&cat%5B0%5D=33&string=linphone

**Comment by sebalis** [comment]
The same issue was raised by me on the linphone-dev mailing list, with some details from my debug window: http://lists.nongnu.org/archive/html/linphone-users/2017-01/msg00037.html

As can be seen from the debug output, Linphone tries two DNS requests: one for a SRV record and one for an A/AAAA record – and both fail while I could show that these requests can be resolved on my system outside of Linphone. The workaround suggested by Russell Treleaven (which I didn’t understand at first because I had overlooked the A/AAAA request) was to add the A data to /etc/hosts. I am hoping that with a new Linphone version, I will be able to abandon this workaround.

**Comment by vasisualiy** [comment]
The problem is a buggy systemd-resolved. The workaround is to utilize any other resolver. For example mdns or dns-server from resolve.conf

Try to change the hosts: line of /etc/nsswitch.conf from this one (for example)
hosts: files mymachines resolve [!UNAVAIL=return] dns myhostname

to this one:
hosts: files mymachines dns

the "resolve" keyword seems to stay for a systemd-resolved

**Comment by sebalis** [comment]
As I wrote on linphone-users (link in my previous comment), I was able to resolve the SRV records using dig on the command line. So the statement that resolved is buggy seems a bit too general to me.

**Comment by jethrogb** [comment]
This is not a bug in systemd-resolved. This is a bug in belle-sip's nsswitch.conf parser. This is completely valid syntax that `dns.c:dns_nssconf_loadfile` chokes on:
```
hosts: files mymachines resolve [!UNAVAIL=return] dns myhostname
```

**Comment by sebalis** [comment]
Are the developers aware of this now? I was considering opening a bug on the belle-sip Github project but that does not seem to be possible.

**Comment by ghismary** [comment]
We are following this thread and are investigating this issue. It indeed seems to be a bug in the nsswitch.conf parsing. Thanks for spotting this!

**Comment by sebalis** [comment]
Thanks to @jethrogb from me too, and to the developers!

**Comment by ghismary** [comment]
Alright, I have just commited a fix in belle-sip. It is now working correctly with the new default nsswitch.conf file from Arch Linux.

**Comment by Hc10b** [comment]
Thanks to all pushing the issue forward, especially to @jethrogb and the developers. As the fix found its way to the arch repository and linphone is working again the issue is done. Thanks a lot again!

**Comment by sebalis** [comment]
With the update it’s working for me as well, I was able to remove the entries I had to add to /etc/hosts. I’ve now also checked Linphone’s debug output and was able to confirm that both the SRV and A/AAAA queries for my three SIP accounts are working correctly. Thanks!

**Comment by marmistrz** [comment]
Thanks a lot!
