### ISSUE TITLE
Account assistant will not add an existing SIP account 

### ISSUE THREAD

**Issue by ethoms** [BelledonneCommunications/linphone-desktop#131]
I've built Linphone 3.12.0 on both Slackware 14.2 and Gentoo (current as of writing) and in both cases the add account assistant/wizard does not add the account. It appears to complete successfully, no error message, but the account list is empty. I've tried different SIP accounts on different servers. If I add the account manually (without the wizard) it works fine. This feature was working fine in version 3.9.1. There is not much to go on, no error, even when running the binary from a terminal window.

**Comment by Wescoeur** [comment]
Sorry but the 3.x version is no longer supported. Please use the last 4.x version. ;)

**Comment by ethoms** [comment]
I'd love to try out the new Qt version, but both Linux distros I use (Slackware and Gentoo) have only Qt5.7 available in their repos. I think requiring Qt version 5.9 so early on really made the majority of Linux users unable to use it. I think the flatpack was a great idea, and if possible a snap would be great for all those Ubuntu (and derivatives) users that have been stuck with Linphone v3.6.x for the longest time.

**Comment by callegar** [comment]
Indeed... in 2020 most linux distros are still at 3.12 and there does not seem to be a quick path to move to 4.x. Even the just released ubuntu 20.04 LTS provides linphone 3.12  I have tried the 4.2 appimage that has recently been provided on the linphone site but it almost immediately crashed.
