### ISSUE TITLE
still failing to compile on ubuntu

### ISSUE THREAD

**Issue by pdarcos** [BelledonneCommunications/linphone-desktop#133]
Starting another ticket because the previous one was closed even though compilation still fails.

I've worked through all the different errors and now I think I'm almost there but not quite.
I have installed Qt5.9 so I'm not sure why it's throwing up an error.

Any help?

Generating moc_UrlHandlers.cpp
make[6]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/linphoneqt'
[  6%] Built target app-library_automoc
make[6]: Entering directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/linphoneqt'
[  8%] Generating qrc_i18n.cpp
[  9%] Generating qrc_resources.cpp
Scanning dependencies of target app-library
make[6]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/linphoneqt'
make[6]: Entering directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/linphoneqt'
[ 10%] Building CXX object CMakeFiles/app-library.dir/src/app/App.cpp.o
/home/john/Documents/testbuild/linphone-desktop/src/app/App.cpp: In member function ‘void App::initContentApp()’:
/home/john/Documents/testbuild/linphone-desktop/src/app/App.cpp:205:11: error: ‘QVersionNumber’ does not name a type
     const QVersionNumber &version = QLibraryInfo::version();
           ^
/home/john/Documents/testbuild/linphone-desktop/src/app/App.cpp:206:9: error: ‘version’ was not declared in this scope
     if (version.majorVersion() == 5 && version.minorVersion() == 9)
         ^
/home/john/Documents/testbuild/linphone-desktop/src/app/App.cpp:210:88: error: ‘class QQmlFileSelector’ has no member named ‘selector’
   qInfo() << QStringLiteral("Activated selectors:") << QQmlFileSelector::get(mEngine)->selector()->allSelectors();
                                                                                        ^
CMakeFiles/app-library.dir/build.make:542: recipe for target 'CMakeFiles/app-library.dir/src/app/App.cpp.o' failed
make[6]: *** [CMakeFiles/app-library.dir/src/app/App.cpp.o] Error 1
make[6]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/linphoneqt'
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/app-library.dir/all' failed
make[5]: *** [CMakeFiles/app-library.dir/all] Error 2
make[5]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/linphoneqt'
Makefile:149: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Build/linphoneqt'
CMakeFiles/EP_linphoneqt.dir/build.make:115: recipe for target '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_linphoneqt/EP_linphoneqt-build' failed
make[3]: *** [/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/Stamp/EP_linphoneqt/EP_linphoneqt-build] Error 2
make[3]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/EP_linphoneqt.dir/all' failed
make[2]: *** [CMakeFiles/EP_linphoneqt.dir/all] Error 2
make[2]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/john/Documents/testbuild/linphone-desktop/WORK/desktop/cmake'
Makefile:14: recipe for target 'desktop-build' failed
make: *** [desktop-build] Error 2

**Comment by pdarcos** [comment]
Anyone? Can someone please confirm they can compile latest master on ubuntu 16.04 LTS so that I can confirm the problem is with my build environment?

Right now it seems to me that compilation is broken and no one can compile the linux version, but it would help if others in the community could confirm or deny this hypothesis so we can pinpoint the problem.

Thanks

**Comment by pdarcos** [comment]
Am I the only one that has tried to compile for linux?

Can someone please help?

Thanks

**Comment by pdarcos** [comment]
Just did a fresh git pull and the same error as always.

Can someone please confirm they're getting the same error (or not) so I can debug the issue better?

Thanks

-- Performing Test SUGGEST_OVERRIDE - Success
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5QuickControls2"
  with any of the following names:

    Qt5QuickControls2Config.cmake
    qt5quickcontrols2-config.cmake

  Add the installation prefix of "Qt5QuickControls2" to CMAKE_PREFIX_PATH or
  set "Qt5QuickControls2_DIR" to a directory containing one of the above
  files.  If "Qt5QuickControls2" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:329 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by Wescoeur** [comment]
The `Qt5_DIR` and `PATH` variables must be set before the `prepare.py` command.
Set correctly these variables to use your Qt 5.9 version (See `README.md`) and rebuild with: `./prepare.py -c && ./prepare.py`

**Comment by pdarcos** [comment]
Hi @Wescoeur 
Thanks for your help!

I have already set those environment variables as per the readme, which is why I don't understand the error. I have these set in my .profile:

Qt5_DIR="~/Qt/5.9/gcc_64/lib/cmake"
Qt5Quick_DIR="/opt/qt59/lib/cmake/Qt5Quick"
PATH="~/Qt/5.9/gcc_64/bin/:$PATH"

I have also tried setting Qt5QuickControls2_DIR to the proper directory in CMAKE and it passes that part fine but then compilation breaks again asking for different directories until I get to the error posted up above:
 home/john/Documents/testbuild/linphone-desktop/src/app/App.cpp:205:11: error: ‘QVersionNumber’ does not name a type
const QVersionNumber &version = QLibraryInfo::version();

I think there must be something wrong with my Qt5.9 installation but I can't figure out where the problem is.

Any clue?

Thanks

**Comment by Wescoeur** [comment]
Are you sure your env variables in `.profile` are correctly loaded in your shell? It's seems weird...
If you get this error I think your Qt system lib is used. (Without the `QtQuickControls2` module.)

**Comment by pdarcos** [comment]
Yeah, I'm confused too as to what's happening.

In my .bash_profile  I have:

export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export Qt5_DIR=~/Qt/5.9/gcc_64/lib/cmake
export PATH=~/Qt/5.9/gcc_64/bin/:$PATH
export Qt5Quick_DIR=/opt/qt59/lib/cmake/Qt5Quick

And in my .profile

# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"

Qt5_DIR="~/Qt/5.9/gcc_64/lib/cmake"
Qt5Quick_DIR="/opt/qt59/lib/cmake/Qt5Quick"
PATH="~/Qt/5.9/gcc_64/bin/:$PATH"

Not sure what else I can do. Should I install some other version of Qt?

Thanks

**Comment by pdarcos** [comment]
My environment variables seem to be correctly set

echo $PATH
~/Qt/5.9/gcc_64/bin/:/home/john/bin:/home/john/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

echo $Qt5_DIR
~/Qt/5.9/gcc_64/lib/cmake

But I still get the same error:

-- Performing Test SUGGEST_OVERRIDE - Success
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5QuickControls2"
  with any of the following names:

    Qt5QuickControls2Config.cmake
    qt5quickcontrols2-config.cmake

  Add the installation prefix of "Qt5QuickControls2" to CMAKE_PREFIX_PATH or
  set "Qt5QuickControls2_DIR" to a directory containing one of the above
  files.  If "Qt5QuickControls2" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:329 (find_package)


Is Qt5QuickControls2 not installed by Qt5.9 installer? I mean it seems it is but for some reason CMAKE can't find it. I installed Qt5.9 on ubuntu 16.04 LTS by running the Qt linux x64 installer here https://www.qt.io/download-qt-installer?hsCtaTracking=9f6a2170-a938-42df-a8e2-a9f0b1d6cdce%7C6cb0de4f-9bb5-4778-ab02-bfb62735f3e5
Is there a compatibility problem with your code? How do you recommend I debug this further?

sudo find / -iname 'Qt5QuickControls2Config.cmake'
find: ‘/run/user/1000/gvfs’: Permission denied
/home/john/Qt/5.9.3/android_x86/lib/cmake/Qt5QuickControls2/Qt5QuickControls2Config.cmake
/home/john/Qt/5.9.3/android_armv7/lib/cmake/Qt5QuickControls2/Qt5QuickControls2Config.cmake
/home/john/Qt/5.9.3/gcc_64/lib/cmake/Qt5QuickControls2/Qt5QuickControls2Config.cmake

Thanks

**Comment by ghismary** [comment]
Qt5QuickControls2Config.cmake is located in ~/Qt/5.9.3/gcc_64/lib/cmake as your find command shows. So this is the path you have to set in Qt5_DIR. Or if you have your main QT stuff in ~/Qt/5.9/gcc_64/lib/cmake try to put both in Qt5_DIR:
Qt5_DIR="~/Qt/5.9/gcc_64/lib/cmake:~/Qt/5.9.3/gcc_64/lib/cmake"

**Comment by pdarcos** [comment]
Hi @ghismary 

I understand what you're saying, the problem is that it seems CMAKE ignores it.

My current Qt5_DIR

echo $Qt5_DIR
~/Qt/5.9/gcc_64/lib/cmake

I've added your suggestion to /etc/environment to make sure it is permanent:

Qt5_DIR="~/Qt/5.9/gcc_64/lib/cmake:~/Qt/5.9.3/gcc_64/lib/cmake"

And still the damn Qt5QuickControls2 error on compiling.

I'm next going to add the Qt5QuickControls2_DIR variable too and I know it'll resolve this error (I've tried manually exporting that variable before), but it will just give me a bunch of other Qt5 related errors which I'll post here (should be the same errors in my first post)

**Comment by pdarcos** [comment]
I ended up reinstalling Qt5 and now it compiles fine. :)

Thanks for all your help!
