### ISSUE TITLE
Linphone 4.0 keeps asking for authenticating an account despite pressing "cancel"

### ISSUE THREAD

**Issue by WPFilmmaker** [BelledonneCommunications/linphone-desktop#134]
On my Linphone 4.0 for some unknown reasons I couldn't create an account via the software menu, so I tried making another one changing email and it worked. 

However after being logged in with my working account, I keep getting a "unable to authenticate, please verify your password" popup from the previous account (which I couldn't created). I press "cancel" yet after some time it pops up again.

IMHO if the user presses cancel the poup should be dismissed for good.

I am using Linphone Desktop 4.0 Core 3.11.2-158-g4c291e2 on Lubuntu 16.04.03.

**Comment by rtreleaven** [comment]
seeing the same thing on osx

**Comment by Wescoeur** [comment]
You must remove your "bad" account from the sip account settings. If the popup occurs it's because linphone needs it for chat, call, ... Or you try to use it as default address.
