### ISSUE TITLE
Build failing on mac after mac update

### ISSUE THREAD

**Issue by andrewsemloh** [BelledonneCommunications/linphone-desktop#138]
I have been using 4.1.1 to build linphone desktop on my mac and it last built in September. Trying to build it again this week and the build is failing (full error code in https://pastebin.com/sXcVtAgs) but seeing lots of these at the end.

_/Users/andrewholmes/Documents/telsisGit/linphone-desktop/WORK/desktop/Build/bellesip/src/grammars/belle_sdpParser.c:9205:35: error: use of undeclared identifier '_empty'
    dfa10_T3, dfa10_T0, dfa10_T0, _empty, dfa10_T1, dfa10_T2, dfa10_T2,_

 I have only upgraded the mac os since the last build. the path is the same 
**~/Qt/5.9.1/clang_64/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/Applications/Wireshark.app/Contents/MacOS**

as is the Qt5_DIR = **~/Qt/5.9.1/clang_64/lib/cmake/**

I have pulled the latest code (although I would like to stay on a released version) and submodules but it's also not building. https://pastebin.com/TTnhbarv 

_error: 'sys/vfs.h' file not found_

**Comment by Wescoeur** [comment]
It seems invalid now. Please open a new issue instead.
