### ISSUE TITLE
Linphone on Raspberry Pi

### ISSUE THREAD

**Issue by MINDoSOFT** [BelledonneCommunications/linphone-desktop#139]
Hello everyone,

I am trying to follow this [guide](https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Linphone%20and%20Raspberry%20Pi/) and get linphone and specifically linphonec up and running on a Raspberry Pi Model B Rev 2 running Raspbian Stretch Lite kernel version 4.9.

But I am facing a problem while trying to compile belle-sip version [1.6.3](https://github.com/BelledonneCommunications/belle-sip/commit/647393a5e4b49551f34e213c91d80b675c60a7f6) these are the commands I run to compile belle-sip:
```
git clone git://git.linphone.org/belle-sip.git
cd belle-sip
git checkout 1.6.3
./autogen.sh && ./configure && make -j4
```

When running make I get the following exception:

`[  1%] Generating grammars/belle_sip_messageLexer.c, grammars/belle_sip_messageLexer.h, grammars/belle_sip_messageParser.c, grammars/belle_sip_messageParser.h
two-threaded DFA conversion
Exception in thread "Thread-0" java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.resize(HashMap.java:704)
        at java.util.HashMap.putVal(HashMap.java:663)
        at java.util.HashMap.put(HashMap.java:612)
        at java.util.HashSet.add(HashSet.java:220)`

I have tried to increase the Java Max Heap Space to 1GB which is 100% of the RAM of the Raspberry and I am getting the following exception:

```
belle_sip_messageParser.c:193506:76: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               else if ( (synpred13_belle_sip_message(ctx)) && (LA161_1 == EOF))
                                                                        
cc1: out of memory allocating 33648840 bytes after a total of 93216768 bytes
Makefile:436: recipe for target 'libbellesip_generated_la-belle_sip_messageParser.lo' failed
```

Has anyone else came across problems this kind of problem while trying to compile linphone for raspberry?

Thank you very much for your help.

**Comment by kwirk** [comment]
Recently successfully compiled on a Raspberry Pi myself. You'll need to temporarily create a swap file in order to increase memory available: https://wiki.archlinux.org/index.php/swap#Manually

**Comment by MINDoSOFT** [comment]
Thank you very much for your help.

I was able to compile belle-sip after making a swap file of 1024 MB and increasing the Java Max Heap Size to 1024 MB using the following command:

`export _JAVA_OPTIONS="-Xmx1024m"`

And then running: 

`./autogen.sh && ./configure && make -j4 ;`

The compilation finished after about two hours.

Note that I am using the Oracle JDK not OpenJDK.

I'll leave this issue open to let you know how the rest of the steps progressed, in case it is helpful to someone.

**Comment by MINDoSOFT** [comment]
OK so I have successfully compiled and installed:

- libvpx
- ffmpeg
- bcunit 3.0.2
- bctoolbox 0.6.0
- belle-sip 1.6.3
- ortp 1.0.2
- mediastreamer2 2.16.1

And now I am trying to compile linphone.

So I run the following:
```sh
git clone git://git.linphone.org/linphone.git --recursive
cd linphone
git checkout 3.12.0
./autogen.sh && ./configure --disable-gtk_ui --disable-x11 && make -j4
```

And I get the following exception:
```sh
make[2]: Entering directory '/openivs/openivs-new-minimal/linphone/coreapi'
if test -n "`cd .. && git log -1 --pretty=format:%H configure.ac`" ; then  \
        if test "`cd .. && git describe --always`" != "" ; then \
                if [ "`cd .. && git describe --abbrev=0`" != "3.11.2" ]; then \
                        /bin/echo "*** PACKAGE_VERSION and git tag differ. Please put them identical."; \
                        exit 1; \
                fi ; \
                printf "#define LIBLINPHONE_GIT_VERSION \"`cd .. && git describe --always`\"\n" > ./liblinphone_gitversion.h.tmp ; \
        elif test "`cd .. && git rev-parse HEAD`" != "" ; then \
                printf "#define LIBLINPHONE_GIT_VERSION \"3.11.2_`cd .. && git rev-parse HEAD`\"\n" > ./liblinphone_gitversion.h.tmp ; \
        else \
                printf "" > ./liblinphone_gitversion.h.tmp ; \
        fi ; \
        if ! test -f ./liblinphone_gitversion.h ; then \
                cp -f ./liblinphone_gitversion.h.tmp ./liblinphone_gitversion.h ; \
        fi ; \
        if test "`cat ./liblinphone_gitversion.h.tmp`" != "`cat ./liblinphone_gitversion.h`" ; then \
                cp -f ./liblinphone_gitversion.h.tmp ./liblinphone_gitversion.h ; \
        fi ; \
        rm -f ./liblinphone_gitversion.h.tmp ; \
else \
        touch liblinphone_gitversion.h ; \
fi
*** PACKAGE_VERSION and git tag differ. Please put them identical.
```

So I try to checkout version 3.11.2 of linphone. And then try to make again, and I get the following exception:
```sh
linphonecall.c: In function ‘linphone_call_handle_stream_events’:
linphonecall.c:4744:63: error: ‘union <anonymous>’ has no member named ‘zrtp_sas’; did you mean ‘zrtp_info’?
     linphone_call_audiostream_auth_token_ready(call, evd->info.zrtp_sas.sas, evd->info.zrtp_sas.verified);
                                                               ^
linphonecall.c:4744:87: error: ‘union <anonymous>’ has no member named ‘zrtp_sas’; did you mean ‘zrtp_info’?
     linphone_call_audiostream_auth_token_ready(call, evd->info.zrtp_sas.sas, evd->info.zrtp_sas.verified);
```

I have tried compiling and installing bzrtp 1.0.6 but still the error remains.

Any ideas on how to overcome this? Thank you for your time.

**Comment by MedGuerrero** [comment]
Hi. 
I have the same problem...
Did you find any solution?

**Comment by perparim-m** [comment]
Hi,

I was unable to compile belle-sip on Raspbian Stretch Lite kernel version 4.9  after making a swap file of 1024 MB and increasing the Java Max Heap Size to 1024 `MB`.

[cc1: all warnings being treated as errors
Makefile:721: recipe for target 'libbellesip_la-belle_sip_headers_impl.lo' failed
make[3]: *** [libbellesip_la-belle_sip_headers_impl.lo] Error 1
make[3]: Leaving directory '/home/pi/linphone/belle-sip/src'
Makefile:1055: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/pi/linphone/belle-sip/src'
Makefile:510: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/linphone/belle-sip'
Makefile:417: recipe for target 'all' failed
make: *** [all] Error 2](url)

http://nongnu.13855.n7.nabble.com/Belle-sip-compilation-fails-on-Raspberry-Pi-ANTLR3-ENC-8BIT-undefined-td227879.html

Any ideas on how to overcome this?

Regards
