### ISSUE TITLE
IO error on call

### ISSUE THREAD

**Issue by IzzySoft** [BelledonneCommunications/linphone-desktop#14]
I've just installed the latest Linphone from the PPA (3.9.1-1) on a Linux Mint machine. Created an account with sip.linphone.org, and the client shows it's registered. However: If I call to my other account used on my Android phone (different SIP provider), I only get an "IO error". Same the other way around (calling this SIP account from the Android device).

As both devices are currently in the same WiFi, I tried via UDP at the user@192* local address. That works without issues. But as we want that installation for calls from/to abroad, a local address is not really helpful.

I've configured Linphone to use a STUN server (stun.linphone.org) and told it I'm behind a firewall and it should use that STUN. No dice, it keeps complaining "IO error" and doesn't establish a single call from/to outside.

Any ideas?

**Comment by IzzySoft** [comment]
Ahem: Closed in terms of "fixed, please update" – or in terms of "wontfix"? A little note would be nice. Thanks!

**Comment by Wescoeur** [comment]
I'm sorry, we have released a new version of the Linphone Desktop application (4.0). It uses now Qt5 and the oldest 3.9 version will no longer be supported.

You can check if your problem is fixed is this new release.

Best regards.

**Comment by IzzySoft** [comment]
I see, thanks. So you're not sure if it's fixed. To be honest: After not receiving a single update on this issue, I've meanwhile switched to a different software for this purpose – and with "the other device" meanwhile being located in a different country used by non-tech-savvy people this setup was intended for, it's not an option to try a "maybe solution". So I might check again some day when the need arises again – but currently, I can't spare time on "maybes".

No offense meant, just stating the facts: you didn't say whether the issue was addressed at all. It might have been fixed as a side-effect – but that's a bit too vague. Especially with a more than 4 months gap in communications, sorry.

Thanks nevertheless for the details and background!
