### ISSUE TITLE
How could I debug the linphone-desktop on windows?

### ISSUE THREAD

**Issue by LooJee** [BelledonneCommunications/linphone-desktop#143]
I wan't to learn the belle-sip and linphone coreapi, but I couldn't find the way to debug linphone-desktop ,anyone could help me?

**Comment by amit1576** [comment]
@LooJee 

Are you able to debug linphone-desktop on windows ?.

Please assist if possible.

**Comment by LooJee** [comment]
@amit1576 
Sorry, I give up.
