### ISSUE TITLE
Where are colors and styles set in code?

### ISSUE THREAD

**Issue by pdarcos** [BelledonneCommunications/linphone-desktop#144]
Hi,

I wanted to play around with the colors and style (not a big fan of orange).
Can someone point out where in the source code these are set?

Thanks

**Comment by pdarcos** [comment]
I see this file but it seems to me that it is setting all colors to black (#000000), so that can't be it, no?

https://github.com/BelledonneCommunications/linphone-desktop/blob/c579092e6559f6103b3060e712b6aa6ba490269c/ui/dev-modules/Colors/Colors.qml

**Comment by Wescoeur** [comment]
All colors are in this file: https://github.com/BelledonneCommunications/linphone-desktop/blob/master/src/components/other/colors/Colors.hpp

The `dev-modules` folder contains only mock files.
