### ISSUE TITLE
Linphone couldn't display Chinese messages as normal, until I restart linphone or change timeline entry. The platform is win10

### ISSUE THREAD

**Issue by LooJee** [BelledonneCommunications/linphone-desktop#146]
[You can get the screenshot from here](https://s20.postimg.org/e989878m5/image.png)

**Comment by Wescoeur** [comment]
What do you mean by "change timeline entry"? Your chat screen seems to display only one invalid message (the sending message). I think it exists a bad encoding in the UI.

**Comment by Wescoeur** [comment]
What is your Linphone version? You can see this info in About panel.

**Comment by LooJee** [comment]
1、Linphone version is 4.1.1. 
2、"change timeline entry" means change chatroom ,for example: I chat with A first, the message is invalid;then I change to chat with B, then I change back to chat with A, the message on the 'A chatroom' become valid. 
3、The invalid messages don't only exists at the sending time.[https://s20.postimg.org/ufrkrd9il/image.png](https://s20.postimg.org/ufrkrd9il/image.png)

 **My English isn't very well I hope you could understand what I said. XD**

**Comment by LooJee** [comment]
I think maybe the reason is the different between GBK and UTF8. But I don't know how to solve it.

**Comment by WPFilmmaker** [comment]
I think I had the same issue a few days ago, screenshot: https://s9.postimg.org/kfqx665of/linphone.png

I tried to reproduce it today but everything was fine..

In my test one of the client was Desktop 4.1.1 (Qt5.9.0) Core 3.12.0 on Xubuntu 17.10, the other one (in the screenshot) Desktop 4.0 (Qt5.9.0) Core 3.11.2-158-g4c291e2 on Lubuntu 16.04.3.

**Comment by LooJee** [comment]
I think I find a way to solve the problem: I write two functions to show the message directly, rather than changing codec by `::Utils::coreStringToAppString(_message->getText())`.The following are my definations:
```
 void ChatModel::insertMessageAtEnd_Own(const std::shared_ptr<linphone::ChatMessage> &message, const QString &content)
 {
 	int row = mEntries.count();

	  beginInsertRows(QModelIndex(), row, row);

	  QVariantMap map;
	  fillMessageEntry_Own(map, message, content);
	  mEntries << qMakePair(map, static_pointer_cast<void>(message));

	  endInsertRows();
 }
```

```
void ChatModel::fillMessageEntry_Own(QVariantMap &dest, const std::shared_ptr<linphone::ChatMessage> &message, const QString &str)
{
	dest["type"] = EntryType::MessageEntry;
	dest["timestamp"] = QDateTime::fromMSecsSinceEpoch(message->getTime() * 1000);
	dest["content"] =  str;
	dest["isOutgoing"] = message->isOutgoing() || message->getState() == linphone::ChatMessageStateIdle;
	dest["status"] = message->getState();

	shared_ptr<const linphone::Content> content = message->getFileTransferInformation();
	if (content) {
		dest["fileSize"] = quint64(content->getSize());
		dest["fileName"] = ::Utils::coreStringToAppString(content->getName());
		dest["wasDownloaded"] = ::fileWasDownloaded(message);

		::fillThumbnailProperty(dest, message);
	}
}
```

**Comment by Wescoeur** [comment]
Fixed on master.
