### ISSUE TITLE
I can't some functions' defination of belle-sip

### ISSUE THREAD

**Issue by LooJee** [BelledonneCommunications/linphone-desktop#147]
Hi. 
I want to figure out how does linphone send messages, so I read the source codes, but I couldn't find some functions' definations, such as 
`belle_sip_header_content_type_parse`
`belle_sip_header_content_length_create`
and so on.

Could you tell me where could I find them?The linphone version is 4.1.1 .
Thank you! :-D

**Comment by Wescoeur** [comment]
You can find `belle_sip_header_content_length_create` iimpl n `submodules/belle-sip/src/belle_sip_headers_impl.c`.

`belle_sip_header_content_type_parse` is a generated function by antlr3 and a macro like this: `BELLE_SIP_PARSE(header_content_type)`
