### ISSUE TITLE
latest commits broke ffmpeg compilation

### ISSUE THREAD

**Issue by pdarcos** [BelledonneCommunications/linphone-desktop#148]
I've been building on my Mac without problems.
Today after doing a fresh git pull I started getting errors with make:

License: LGPL version 2.1 or later
Creating config.mak and config.h...
[ 38%] Forcing build for 'EP_ffmpeg'
[ 38%] Performing build step for 'EP_ffmpeg'
ld: warning: directory not found for option '-Llibavdevice'
ld: warning: directory not found for option '-Llibavfilter'
ld: warning: directory not found for option '-Llibavformat'
ld: warning: directory not found for option '-Llibpostproc'
ld: warning: directory not found for option '-Llibavdevice'
ld: warning: directory not found for option '-Llibavfilter'
ld: warning: directory not found for option '-Llibavformat'
ld: warning: directory not found for option '-Llibpostproc'
ld: warning: directory not found for option '-Llibavdevice'
ld: warning: directory not found for option '-Llibavfilter'
ld: warning: directory not found for option '-Llibavformat'
ld: warning: directory not found for option '-Llibpostproc'
ld: warning: directory not found for option '-Llibavdevice'
ld: warning: directory not found for option '-Llibavfilter'
ld: warning: directory not found for option '-Llibavformat'
ld: warning: directory not found for option '-Llibpostproc'
[ 38%] Performing install step for 'EP_ffmpeg'
[ 39%] Performing post-installation for 'EP_ffmpeg'
[ 39%] Completed 'EP_ffmpeg'
[ 39%] Built target EP_ffmpeg
make[1]: *** [all] Error 2
make: *** [desktop-build] Error 2

Thought you'd like to know.

**Comment by pdarcos** [comment]
Actually latest commits seem to have broken things in many places:

Scanning dependencies of target mbedtls
[ 19%] Building C object CMakeFiles/opus.dir/silk/decode_core.c.o
[ 48%] Building C object corec/corec/CMakeFiles/corec-objects.dir/helpers/date/date_libc.c.o
[ 87%] Building C object library/CMakeFiles/mbedtls.dir/debug.c.o
[ 51%] Building C object corec/corec/CMakeFiles/corec-objects.dir/helpers/file/file_libc.c.o
[ 19%] Building C object CMakeFiles/opus.dir/silk/decode_frame.c.o
/Users/user/Documents/Development/linphone-desktop/submodules/bcmatroska2/corec/corec/helpers/file/file_libc.c:48:10: fatal error: 'sys/vfs.h' file not found
#include <sys/vfs.h>
         ^~~~~~~~~~~
[ 89%] Building C object library/CMakeFiles/mbedtls.dir/net_sockets.c.o
1 error generated.
make[6]: *** [corec/corec/CMakeFiles/corec-objects.dir/helpers/file/file_libc.c.o] Error 1
make[5]: *** [corec/corec/CMakeFiles/corec-objects.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/user/Documents/Development/linphone-desktop/WORK/desktop/Stamp/EP_matroska2/EP_matroska2-build] Error 2
make[2]: *** [CMakeFiles/EP_matroska2.dir/all] Error 2


[ 27%] Performing install step for 'EP_vpx'
[ 27%] Completed 'EP_vpx'
[ 27%] Built target EP_vpx
make[1]: *** [all] Error 2

**Comment by Wescoeur** [comment]
Fixed on master branch. It was a include order problem in bcmatroska2. :)

**Comment by pdarcos** [comment]
Thanks. Indeed it compiles fine now, but when I try to run it it crashes with error -67062.
Not sure what this error is about. Maybe it's the signing of the app? Where can we change the signing certificate used?


default	15:42:16.737013 +0000	analyticsd	[<private>] no observers; dropped.
default	15:42:20.913313 +0000	lsd	MacOS error: -67062
default	15:42:20.944631 +0000	lsd	MacOS error: -67062
default	15:42:20.946830 +0000	lsd	Parsed Info.plist for <private>
default	15:42:20.946874 +0000	lsd	Parsed MobileInstallation data for <private>
default	15:42:20.948818 +0000	lsd	UNIX error exception: 8
default	15:42:20.965545 +0000	taskgated	MacOS error: -67062
default	15:42:20.972925 +0000	lsd	UNIX error exception: 8
