### ISSUE TITLE
Not able to register to SIP Server from Windows Desktop - But Working fine in Android, Linphone Web

### ISSUE THREAD

**Issue by subu1979** [BelledonneCommunications/linphone-desktop#15]
We are not able to register to SIP Server through windows desktop (3.10.2) but working fine in android and linphone web.

message: 2017-02-17 19:07:22:827 nict_on_timer_E: sending retransmission
message: 2017-02-17 19:07:22:827 channel [052D7B70]: message sent to [UDP://sip-162412.accounts.vocalocity.com:5060], size: [617] bytes
REGISTER sip:sip-162412.accounts.vocalocity.com SIP/2.0

Via: SIP/2.0/UDP 192.168.137.173:5060;branch=z9hG4bK.NdxFswHqf;rport

From: <sip:vh1581105@sip-162412.accounts.vocalocity.com>;tag=L5G8CxAAv

To: sip:vh1581105@sip-162412.accounts.vocalocity.com

CSeq: 21 REGISTER

Call-ID: Pp2PNLV1x2

Max-Forwards: 70

Supported: replaces, outbound

Accept: application/sdp

Accept: text/plain

Accept: application/vnd.gsma.rcs-ft-http+xml

Contact: <sip:vh1581105@192.168.137.173;transport=udp>;+sip.instance="<urn:uuid:1d9814c4-c469-4ff4-bd41-5c747c133a38>"

Expires: 3600

User-Agent: Linphone/3.10.2 (belle-sip/1.5.0)

message: 2017-02-17 19:07:23:295 A timeout related to this channel occured and no message received during last 60 seconds. This channel is suspect, moving to error state
message: 2017-02-17 19:07:23:295 channel 052D7B70: state ERROR
warning: 2017-02-17 19:07:23:295 Transaction [01201418] reporting timeout, reporting to channel.
message: 2017-02-17 19:07:23:327 transaction [01201418] channel state changed to [ERROR]
message: 2017-02-17 19:07:23:327 Refresher: scheduling next timer in 60000 ms
message: 2017-02-17 19:07:23:327 Register refresher [503] reason [io error] for proxy [<sip:sip-162412.accounts.vocalocity.com;transport=udp>]
message: 2017-02-17 19:07:23:327 Refresher: scheduling next timer in 2000 ms
message: 2017-02-17 19:07:23:327 Register refresher [408] reason [timeout] for proxy [<sip:sip-162412.accounts.vocalocity.com;transport=udp>]
message: 2017-02-17 19:07:23:327 Changing [client] [REGISTER] transaction [01201418], from state [TRYING] to [TERMINATED]
message: 2017-02-17 19:07:23:327 Client internal REGISTER transaction [01201418] terminated
message: 2017-02-17 19:07:25:352 Channel [052D7B70] destroyed
message: 2017-02-17 19:07:25:352 Transaction [01201418] deleted
message: 2017-02-17 19:07:25:352 belle_sip_client_transaction_send_request(): waiting channel to be ready
message: 2017-02-17 19:07:25:352 channel [052D7B70]: starting resolution of sip-162412.accounts.vocalocity.com
message: 2017-02-17 19:07:25:352 channel 052D7B70: state RES_IN_PROGRESS
message: 2017-02-17 19:07:25:352 transaction [01201778] channel state changed to [RES_IN_PROGRESS]
message: 2017-02-17 19:07:25:368 Resolver is using DNS server(s):
message: 2017-02-17 19:07:25:368 	192.168.137.3
message: 2017-02-17 19:07:25:368 	8.8.8.8
message: 2017-02-17 19:07:25:368 resolver_process_data dns_res_check() in progress
message: 2017-02-17 19:07:25:368 DNS resolution awaiting response, queued to main loop
message: 2017-02-17 19:07:25:383 SRV _sip._udp.sip-162412.accounts.vocalocity.com resolved to [target:reg6app1.proxy.vocalocity.com. port:5060 prio:5 weight:10]
message: 2017-02-17 19:07:25:383 SRV _sip._udp.sip-162412.accounts.vocalocity.com resolved to [target:reg2app1.proxy.vocalocity.com. port:5060 prio:10 weight:10]
message: 2017-02-17 19:07:25:383 Starting A/AAAA query for srv result [reg6app1.proxy.vocalocity.com.]
message: 2017-02-17 19:07:25:399 Resolver is using DNS server(s):
message: 2017-02-17 19:07:25:399 	192.168.137.3
message: 2017-02-17 19:07:25:399 	8.8.8.8
message: 2017-02-17 19:07:25:399 resolver_process_data dns_res_check() in progress
message: 2017-02-17 19:07:25:399 DNS resolution awaiting response, queued to main loop
message: 2017-02-17 19:07:25:399 Starting A/AAAA query for srv result [reg2app1.proxy.vocalocity.com.]
message: 2017-02-17 19:07:25:415 Resolver is using DNS server(s):
message: 2017-02-17 19:07:25:415 	192.168.137.3
message: 2017-02-17 19:07:25:415 	8.8.8.8
message: 2017-02-17 19:07:25:415 resolver_process_data dns_res_check() in progress
message: 2017-02-17 19:07:25:415 DNS resolution awaiting response, queued to main loop
message: 2017-02-17 19:07:25:415 reg2app1.proxy.vocalocity.com. resolved to 107.23.9.200
message: 2017-02-17 19:07:25:415 A query finished for srv result [reg2app1.proxy.vocalocity.com.]
message: 2017-02-17 19:07:25:415 reg6app1.proxy.vocalocity.com. resolved to 54.213.138.55
message: 2017-02-17 19:07:25:415 A query finished for srv result [reg6app1.proxy.vocalocity.com.]
message: 2017-02-17 19:07:25:415 All A/AAAA results for combined resolution have arrived.
message: 2017-02-17 19:07:25:415 channel 052D7B70: state RES_DONE
message: 2017-02-17 19:07:25:415 transaction [01201778] channel state changed to [RES_DONE]
message: 2017-02-17 19:07:25:415 channel 052D7B70: state CONNECTING
message: 2017-02-17 19:07:25:415 transaction [01201778] channel state changed to [CONNECTING]
message: 2017-02-17 19:07:25:415 Trying to connect to [UDP://54.213.138.55:5060]
message: 2017-02-17 19:07:25:415 belle_sip_get_src_addr_for(): af_inet6=0
message: 2017-02-17 19:07:25:415 Channel has local address 192.168.137.173:5060
message: 2017-02-17 19:07:25:415 channel 052D7B70: state READY
message: 2017-02-17 19:07:25:415 transaction [01201778] channel state changed to [READY]
message: 2017-02-17 19:07:25:415 Changing [client] [REGISTER] transaction [01201778], from state [INIT] to [TRYING]
message: 2017-02-17 19:07:25:415 channel [052D7B70]: message sent to [UDP://sip-162412.accounts.vocalocity.com:5060], size: [617] bytes
REGISTER sip:sip-162412.accounts.vocalocity.com SIP/2.0

Via: SIP/2.0/UDP 192.168.137.173:5060;branch=z9hG4bK.xRTF29uW5;rport

From: <sip:vh1581105@sip-162412.accounts.vocalocity.com>;tag=L5G8CxAAv

To: sip:vh1581105@sip-162412.accounts.vocalocity.com

CSeq: 22 REGISTER

Call-ID: Pp2PNLV1x2

Max-Forwards: 70

Supported: replaces, outbound

Accept: application/sdp

Accept: text/plain

Accept: application/vnd.gsma.rcs-ft-http+xml

Contact: <sip:vh1581105@192.168.137.173;transport=udp>;+sip.instance="<urn:uuid:1d9814c4-c469-4ff4-bd41-5c747c133a38>"

Expires: 3600

User-Agent: Linphone/3.10.2 (belle-sip/1.5.0)

message: 2017-02-17 19:07:25:927 nict_on_timer_E: sending retransmission
message: 2017-02-17 19:07:25:927 channel [052D7B70]: message sent to [UDP://sip-162412.accounts.vocalocity.com:5060], size: [617] bytes
REGISTER sip:sip-162412.accounts.vocalocity.com SIP/2.0

Via: SIP/2.0/UDP 192.168.137.173:5060;branch=z9hG4bK.xRTF29uW5;rport

From: <sip:vh1581105@sip-162412.accounts.vocalocity.com>;tag=L5G8CxAAv

To: sip:vh1581105@sip-162412.accounts.vocalocity.com

CSeq: 22 REGISTER

Call-ID: Pp2PNLV1x2

Max-Forwards: 70

Supported: replaces, outbound

Accept: application/sdp

Accept: text/plain

Accept: application/vnd.gsma.rcs-ft-http+xml

Contact: <sip:vh1581105@192.168.137.173;transport=udp>;+sip.instance="<urn:uuid:1d9814c4-c469-4ff4-bd41-5c747c133a38>"

Expires: 3600

User-Agent: Linphone/3.10.2 (belle-sip/1.5.0)

**Comment by Wescoeur** [comment]
Have you got the same problem with the last app update?

**Comment by Wescoeur** [comment]
Must be fixed in the last version.
