### ISSUE TITLE
Trouble Compiling for Windows

### ISSUE THREAD

**Issue by adamcjohnson95** [BelledonneCommunications/linphone-desktop#151]
Hello,

When I try and issue the `python prepare.py -G "Visual Studio 14 2015"` command. I get the following errors:
![image](https://user-images.githubusercontent.com/37702785/37834294-ca9828ba-2e83-11e8-933f-2baff86bd478.png)

If I issue `python prepare.py -G "Visual Studio 12 2013"` The solution is created fine, but I'll get the following errors when I compile (Using Release and Win32 in visual studio 2013):

![image](https://user-images.githubusercontent.com/37702785/37836604-48c7e1d0-2e89-11e8-8e2d-07ba5a9e0cdd.png)

I have installed the most recent patches for the windows compiling issues. If anyone could give me some advice it would be much appreciated. I've tried from the regular command prompt and the Visual Studio command prompt. I have visual studio '13, '15, & '17 installed so if we can get it working on any of them I would be extremely grateful. If there is any other information you need, or if I missed a fix to these issues that already existed, please let me know.

Thanks,

**Update:**
This is for the desktop client

**Comment by adamcjohnson95** [comment]
This error also comes up when compiling in 2013

![image](https://user-images.githubusercontent.com/37702785/37846887-6ef09f52-2ea5-11e8-84d4-28219146ba6b.png)

**Comment by pdarcos** [comment]
Good luck getting help here. I haven't had much luck getting help with OSX and I don't use Windows so I cannot help you with that, except I seem to remember that the soci dependency was removed some time ago.
Are you sure your code is up to date with their git?

**Comment by adamcjohnson95** [comment]
I believe it is up to date. I'm really new to the GIT community (actually joined today to get help with this), and this is actually the first thing I've pulled from GIT.

I started with: `Git clone https://github.com/BelledonneCommunications/linphone-desktop.git`
Then I tried: `git checkout ce3707b8950117ee9a33b686ba368601875cbd19`

I also followed the git steps that would pop up in the command prompt on fails. I will run through all the steps again and put them on here.

**Comment by pdarcos** [comment]
Did you remember to do
`git submodule sync && git submodule update --init --recursive`

**Comment by adamcjohnson95** [comment]
Here is the process I went through:

1. `git clone https://github.com/BelledonneCommunications/linphone-desktop.git`
2. `git submodule sync && git submodule update --init --recursive`
3. `git checkout ce3707b8950117ee9a33b686ba368601875cbd19`
4. `python prepare.py -G "Visual Studio 14 2015"`
![image](https://user-images.githubusercontent.com/37702785/37849703-178a7486-2eaf-11e8-84ad-7e8a2436f42d.png)

5. `python prepare.py -c`
6. `python prepare.py -G "Visual Studio 12 2013"` (Building sln file is good)
7. Open the solution file in Visual Studio 2013
8. Set to Release and Win32
9. Run Local Windows Debugger

**Comment by pdarcos** [comment]
You need to follow the wiki completely.
I see from the configure error message you don't have CMake installed (or not in PATH) so it cannot compile

**Comment by pdarcos** [comment]
You need to do this part too:

Install some build tools: CMake, Python Java (build dependency for belle-sip) and Qt5 (5.9 or newer). C++11 support is required!

**Comment by adamcjohnson95** [comment]
I can check the PATH variable, but I know that CMake is installed, as are the rest of those build tools. I re-downloaded my visual studio 2015 as well. Quite confusing to me.

**Comment by adamcjohnson95** [comment]
**Update:**
I found a new download of visual studio 2015 and I got prepare.py to successfully create the project files. That cleared a lot of the errors that I was having in visual studio 2013, but there is still one more error that I cant seem to clear. 

![image](https://user-images.githubusercontent.com/37702785/37977187-4848d1d0-31b1-11e8-9969-ab417b2c77ca.png)

It looks like the compiler is having issues making the vpx project. I can't really find any information about the error `exited with code 2` in general.

**Comment by adamcjohnson95** [comment]
Here is the log for the error from building EP_vpx. 
**...**
2>10:18:26.677     1>
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 2.
2>                   Done executing task "CustomBuild" -- FAILED. (TaskId:63)
2>10:18:26.678     1>
2>Done building target "CustomBuild" in project "EP_vpx.vcxproj" -- FAILED.: (TargetId:113)
2>
2>Project Performance Summary:
2>        2 ms  C:\softphone\linphone-desktop\WORK\desktop\cmake\ZERO_CHECK.vcxproj   2 calls
2>                  1 ms  GetTargetPath                              1 calls
2>                  1 ms  GetNativeManifest                          1 calls
2>    231800 ms  C:\softphone\linphone-desktop\WORK\desktop\cmake\EP_vpx.vcxproj   1 calls
2>              231800 ms  Rebuild                                    1 calls
2>
2>Target Performance Summary:
2>        0 ms  BeforeResolveReferences                    1 calls
2>        0 ms  AfterResolveReferences                     1 calls
2>        0 ms  GetFrameworkPaths                          1 calls
2>        0 ms  CleanPublishFolder                         1 calls
2>        0 ms  Clean                                      1 calls
2>        0 ms  BeforeClean                                1 calls
2>        0 ms  BuildGenerateSourcesTraverse               1 calls
2>        0 ms  AfterCppClean                              1 calls
2>        0 ms  _RemoveNameMetadataFromProjectReferenceItems   1 calls
2>        0 ms  Desktop_PlatformPrepareForBuild            1 calls
2>        0 ms  ResolveReferences                          1 calls
2>        0 ms  GetInstalledSDKLocations                   1 calls
2>        0 ms  SelectCustomBuild                          1 calls
2>        0 ms  CppClean                                   1 calls
2>        0 ms  BeforeRebuild                              1 calls
2>        0 ms  ResolveSDKReferences                       1 calls
2>        0 ms  PreBuildEvent                              1 calls
2>        0 ms  AfterClean                                 1 calls
2>        0 ms  CleanReferencedProjects                    1 calls
2>        0 ms  ModifyUnitTestPlatformVersion              1 calls
2>        0 ms  BeforeBuildGenerateSources                 1 calls
2>        0 ms  _PrepareForReferenceResolution             1 calls
2>        0 ms  ExpandSDKReferences                        1 calls
2>        0 ms  _SelectedFiles                             1 calls
2>        0 ms  BeforeCppClean                             1 calls
2>        0 ms  PlatformPrepareForBuild                    1 calls
2>        0 ms  PGInstrumentedClean                        1 calls
2>        0 ms  _PrepareForRebuild                         1 calls
2>        1 ms  GetReferenceAssemblyPaths                  1 calls
2>        1 ms  ResolveAssemblyReferences                  1 calls
2>        1 ms  SetBuildDefaultEnvironmentVariables        1 calls
2>        1 ms  GetResolvedWinMD                           1 calls
2>        1 ms  GetTargetPath                              1 calls
2>        1 ms  CoreClean                                  1 calls
2>        1 ms  GetNativeManifest                          1 calls
2>        1 ms  _PrepareForClean                           1 calls
2>        1 ms  _PrepareForBuild                           1 calls
2>        2 ms  _CheckForInvalidConfigurationAndPlatform   1 calls
2>        3 ms  AssignProjectConfiguration                 1 calls
2>        3 ms  InitializeBuildStatus                      1 calls
2>        3 ms  PrepareForBuild                            1 calls
2>        5 ms  _SplitProjectReferencesByFileExistence     1 calls
2>        5 ms  SetCABuildNativeEnvironmentVariables       1 calls
2>       10 ms  CoreCppClean                               1 calls
2>       21 ms  ComputeCustomBuildOutput                   1 calls
2>       26 ms  ResolveProjectReferences                   1 calls
2>    231714 ms  CustomBuild                                1 calls
2>
2>Task Performance Summary:
2>        0 ms  RemoveDuplicates                           1 calls
2>        0 ms  SetEnvironmentVariable                     1 calls
2>        0 ms  FindUnderPath                              2 calls
2>        0 ms  ReadLinesFromFile                          2 calls
2>        1 ms  Message                                    2 calls
2>        1 ms  SetEnv                                     4 calls
2>        1 ms  Delete                                     4 calls
2>        1 ms  Touch                                      1 calls
2>        2 ms  AssignProjectConfiguration                 1 calls
2>        2 ms  WriteLinesToFile                           3 calls
2>        3 ms  MakeDir                                    5 calls
2>        5 ms  ResolveNonMSBuildProjectOutput             1 calls
2>        8 ms  CppClean                                   1 calls
2>       25 ms  MSBuild                                    2 calls
2>    231714 ms  CustomBuild                                1 calls
2>
2>Build FAILED.
2>
2>Time Elapsed 00:03:51.79
**========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========**

**Comment by ghismary** [comment]
Hi,
The real error will be located in the WORK/desktop/cmake/EP_vpx.log file. Take a look there.

**Comment by adamcjohnson95** [comment]
Before I checked that I got a clean clone from git and tried again. After a checkout of an older version of submodules/external, 2488cfd, I got a clean compile. Tomorrow I will put up a very detailed description of what all I did, and hopefully that can help some other people in the future. I will also close this then too.

**Comment by Wescoeur** [comment]
Sorry for the delay but do you still have this problem?

**Comment by adamcjohnson95** [comment]
I did eventually get this to compile for windows, however it seems that some of the buttons aren't showing up. It looks like any button that is `TextButtonA { }` or `Text ButtonB { }` isn't showing up in my compiled exe, however I can still click where the buttons are supposed to be and they work..

**Comment by Wescoeur** [comment]
Weird, It seems related to some rendering issues I've seen on windows with the app...

**Comment by adamcjohnson95** [comment]
An example would be Add Account and Erase Passwords button on the SipAccount Settings tab of the Setting Windows. I'm working on replacing all of these buttons with manually created ones.

**Comment by LAOMENGA** [comment]
I have encountered the same problem with you. Can I know how you solved it?
![image](https://user-images.githubusercontent.com/41133556/43064202-dadf09f6-8e90-11e8-9087-8521c1c86add.png)

**Comment by zahraesm** [comment]
@adamcjohnson95  hi im experiencing your issues with building the project.sln would you please look at my issue  [https://github.com/BelledonneCommunications/linphone-desktop/issues/204](url)

**Comment by adamcjohnson95** [comment]
Sorry for the no answer but I was out of country and then busy catching back up. We never found a reliable solution to get this working so we scrapped the project along with all of the code. Sorry I can't be more of a help, if this is even still a problem.
