### ISSUE TITLE
No UI for Missed Calls

### ISSUE THREAD

**Issue by Yousefjb** [BelledonneCommunications/linphone-desktop#152]
Desktop 4.1.1 - Qt5.9.0
Core 3.12.0
  
I can't find a way to view missed calls via the UI.
the only options I have are :
1.  open the sqlite database file to see if there was any missing calls while I was away
2. check every contact and see if I had new missed calls

**Comment by pdarcos** [comment]
I can confirm there is no indication at all for missed calls (at least on OSX and Linux builds).
This is obviously a pretty important feature to have. Is it in the works?

**Comment by Yousefjb** [comment]
I had only contacted with one person when I opened the issue, but after a while I started to see the contact call history on left sidebar and when I miss a call from someone they will be at the top of the list.

**Comment by anx-ckreuzberger** [comment]
+1

**Comment by nezhar** [comment]
+1

**Comment by anx-mwutte** [comment]
+1

**Comment by nezhar** [comment]
@Wescoeur They are not highlighted, I think causes most of the confusion. Usually you won't check the timeline to see if anybody called you.

**Comment by boospy** [comment]
Desktop 4.1.1-655-g95245907 - Qt5.12.0
Core 3.12.0-3170-g14ea64924

Same problem here. I see the missed calls, but only during i have this contact that me phoned open, and then i can see the missed call. The line is red. But if i click on a other history object, or an contact in the list and back, all missed entries are gone away. 

For test i configured my linphone from the scratch. But it still the same. 

System: Ubuntu 18.04 LTS, KDE NEON 18.04 LTS

**Comment by boospy** [comment]
Will this be fixed? In the office we have all the same issue. Or is there another way to work with linphone right?

**Comment by boospy** [comment]
You can see missed calls in history, only it you are on that contact, at the moment from the call.

![linphone-missed-call](https://user-images.githubusercontent.com/7432752/84008634-65f2d380-a972-11ea-8ae7-67de10c3547b.png)

**Comment by julonexus** [comment]
On what version? If it is from last snapshots, please explain on what you are doing.

**Comment by boospy** [comment]
> On what version? If it is from last snapshots, please explain on what you are doing.
> You should see them, even if the caller is not on your contact lists, and even after switch logs

```
Desktop 4.1.1-655-g95245907 - Qt5.14.2
Core 3.12.0-3170-g14ea64924
```
Sounds interesting. So i will rebuild the DEB packages. 

Thanks
