### ISSUE TITLE
Alert the user about a new version of Linphone (after X months)

### ISSUE THREAD

**Issue by WPFilmmaker** [BelledonneCommunications/linphone-desktop#154]
Right now if you want to know whether a new version of linphone is out or not you have to go to the website or github.

I know that checking for new version of a software (or even download them automatically) it is a burden both in terms of time and manpower required (plus servers) furthermore many don't like it due to privacy reasons.

So I think that  a popup would could suggesting the user that a new version might be available "on our website: https://www.linphone.org/technical-corner/linphone/downloads". Maybe once every 100 days? or 150? Twice or three times a year. 

It would be helpful to keep the users running the latest version.

**Comment by ghismary** [comment]
This is already implemented in the latest version (4.1.1). But no new release has been done since then. But when the next release will be out you will be notified by a popup allowing you to download the new version directly if you are running Linphone on Windows or Mac OS X.

**Comment by WPFilmmaker** [comment]
@ghismary Thanks a lot! What about Linux distros?Do we get a popup redirecting to the website or nothing at all?If the latter, it would be nice to have a popup for Linux too. Thanks!

**Comment by ghismary** [comment]
On Linux, the new version notification relies on the package manager you use to install the application.
