### ISSUE TITLE
I have successfully build linphone-desktop code in Visual studio 2015

### ISSUE THREAD

**Issue by kumar672** [BelledonneCommunications/linphone-desktop#156]
I have successfully build linphone-desktop code in Visual studio 2015 but while running project getting error  
"Unable to start program   ~\WORK\desktop\cmake\Release\ALL_BUILLD'.
The system cannot find the file specified"

**Comment by LooJee** [comment]
You could find the  executable file under linphone-desktop\OUTPUT\desktop\bin

**Comment by Wescoeur** [comment]
It's seems Ok. Please comment if not.
