### ISSUE TITLE
https connection on download page on linphone.org shown as not secure (FF 59.0.2)

### ISSUE THREAD

**Issue by WPFilmmaker** [BelledonneCommunications/linphone-desktop#158]
On FF56 no problem, but with FF 59.0.2 HTTPS does not seem to be working and it is shown as "connection is not secure" with the padlock crossed.

https://s31.postimg.org/tgs2hldjf/https.png

**Comment by Wescoeur** [comment]
Sorry for the answer but do you still have the problem?

**Comment by Wescoeur** [comment]
Thanks!
