### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by subu1979** [BelledonneCommunications/linphone-desktop#16]
![linphone_desktop_compilation_error](https://cloud.githubusercontent.com/assets/3286581/23118896/f6105e30-f77b-11e6-9131-0512d699edea.png)

**Comment by eirabie** [comment]
Mine gets interrupted too out of nowhere. I wonder if we're using the wrong version of cmake or something?

**Comment by tahirjilani** [comment]
@subu1979 were you able to fix your issue? I am hitting by same error.

Regards

**Comment by eirabie** [comment]
@tahirjilani I was able to get it working. The codec VPX is what causes this problem. Try disabling it by using -DENABLE_VPX=NO and try again
