### ISSUE TITLE
CMake Error at builders/vpx.cmake:78

### ISSUE THREAD

**Issue by nitish3197** [BelledonneCommunications/linphone-desktop#165]
While preparing the python file an error shows up saying :

 CMake Error at builders/vpx.cmake:78 (file):
 file failed to open for reading (No such file or directory):

CMake Error at builders/vpx.cmake:79 (file):
  file failed to open for reading (No such file or directory):.... and so on
The working repository is also created...how to deal with this error ??

i am using windows 10.

**Comment by nitish3197** [comment]
![1](https://user-images.githubusercontent.com/30616014/38542323-3956caa6-3cbf-11e8-99e8-0108cea2d769.png)
![2](https://user-images.githubusercontent.com/30616014/38542324-39a54e2e-3cbf-11e8-8e26-8f576ff8081f.png)
![3](https://user-images.githubusercontent.com/30616014/38542325-39f2cbfe-3cbf-11e8-8bc6-e6e504858245.png)
![4](https://user-images.githubusercontent.com/30616014/38542327-3a218854-3cbf-11e8-9bac-a749158f1a50.png)


Screenshots of the errors mentioned above

**Comment by Wescoeur** [comment]
Please use  `python prepare.py -G "Visual Studio 14 2015"` instead of ` python prepare.py -G "Visual Studio 15 2017"`. This version is not supported.

**Comment by nitish3197** [comment]
![1 1](https://user-images.githubusercontent.com/30616014/39852863-a26c1002-543c-11e8-8e51-184cd82f178d.png)
![1 2](https://user-images.githubusercontent.com/30616014/39852865-a4636874-543c-11e8-93bd-6fbb22a5c106.png)
![1 5](https://user-images.githubusercontent.com/30616014/39852867-ad4ebe02-543c-11e8-9bca-85e85901504a.png)

After Compiling the python file by python prepare.py -G "Visual Studio 12 2013" with no errors, not able to locate the solution file.

**Comment by GodStar88** [comment]
Hello, I have same problem in python prepare.py -G "Visual Studio 15 2017 Win64"
so i have to install vs2015 for using python prepare.py -G "Visual Studio 14 2015"
