### ISSUE TITLE
How to change executable name in osx?

### ISSUE THREAD

**Issue by pdarcos** [BelledonneCommunications/linphone-desktop#166]
Hi again,

I'm trying to change the OSX package to display the name myapp instead of Linphone.
I see that linphone seems to be hardcoded in a lot of different places so it's no easy task, although I think I'm almost there.

I've tried changing the CFBundleExecutable here from linphone to myapp https://github.com/BelledonneCommunications/linphone-desktop/blob/master/cmake_builder/linphone_package/Info.plist.in
And it seems to compile but it throws an error when trying to execute the app on High Sierra.
I believe this is where the compilation error happens (see bold)

Any ideas?

Thanks

Log: copy: "/Users/myuser/Documents/Qt/5.10.0/clang_64/qml/QtTest/libqmltestplugin_debug.dylib.dSYM/Contents/Resources/DWARF" "/Users/myuser/Documents/Development/linphone-desktop/WORK/desktop/Build/linphone_package/myapp.app/Contents/Resources/qml/QtTest/libqmltestplugin_debug.dylib.dSYM/Contents/Resources/DWARF"
Log:
Log: Deploying QML import "QtTest"
Log:
Log: Deploying QML import "testlogger.js"
Log:   Skip non-module import
Log:
Log: Deploying QML import ""
Log:   Skip import: name or path is empty
Log:
Log: Deploying QML import ""
Log:   Skip import: name or path is empty
Log:
Log: Deploying QML import ""
Log:   Skip import: name or path is empty
Log:
Log: Deploying QML import ""
Log:   Skip import: name or path is empty
Log:
Empty filename passed to function
**ERROR: Could not find bundle binary for "/Users/myuser/Documents/Development/linphone-desktop/WORK/desktop/Build/linphone_package/myapp.app"**
ERROR: "error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open file:  (No such file or directory)\n"
ERROR: ""
Changing RPATH of libavcodec.53.61.100.dylib from '/Users/myuser/Documents/Development/linphone-desktop/OUTPUT/desktop/lib' to '@executable_path/../Frameworks'
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RPATH load command with path: /Users/myuser/Documents/Development/linphone-desktop/OUTPUT/desktop/lib found in: /Users/myuser/Documents/Development/linphone-desktop/WORK/desktop/Build/linphone_package/myapp.app/Contents/Frameworks/libavcodec.53.61.100.dylib (for architecture x86_64), required for specified option "-rpath /Users/myuser/Documents/Development/linphone-desktop/OUTPUT/desktop/lib @executable_path/../Frameworks"

**Comment by pdarcos** [comment]
Hi,

Can someone from Belledonne please point me in the right direction?

Thanks

**Comment by WPFilmmaker** [comment]
@pdarcos maybe if you write to the mailnglist you will have more luck? Seems that the devs don't spend too much time here on the tickets section.

**Comment by pdarcos** [comment]
Thanks @WPFilmmaker 

Unfortunately the mailing list also doesn't seem to get much attention, so it's probably not worth the effort. Does anyone know of another open source desktop client I can experiment with? I'm thinking of trying out pjsip since they seem to have a lot more support than linphone.

**Comment by WPFilmmaker** [comment]
@pdarcos If I remember correctly they eventually fixed the crash you had on OSX right? So maybe trying the mailing list was worth, or just have patience since they seem to have a small team.

**Comment by pdarcos** [comment]
@WPFilmmaker , yes they fixed it after I had pinpointed the exact location of the code that was crashing the app. Until I'd done all that they were just ignoring the crash report even though it was a pretty serious crash in their code. Not complaining since I know this is OSS and there's no commercial support, but it does seem to indicate that this community isn't very active or responsive to bug reports like other OSS projects. I'll keep trying a little longer to grab their attention.

Hi Belledonne.

Can someone help out by pointing me in the right direction please?

Thanks

**Comment by WPFilmmaker** [comment]
@pdarcos My understanding is that (looking at their website) Linphone support is mostly oriented towards companies rather than individual users. If to that you add that the dev team is small and that most of the people prefer proprietary options you see why there isn't much community around the project. But I think Linphone is the best sip software around (as in opensource, cross-platform and actively developed)

**Comment by Wescoeur** [comment]
Yes, we are a small company. Personally in my free time, I spend a lot of time to check Github issues (problems, ideas...). I was unavailable since several weeks but generaly I try to give an answer when possible. I can't deal with all support questions on Github, it's not feasible.

So you can ask and wait for help but you can't hope for a real time answer.  I'm sorry, for the moment I'm the principal software developer of Linphone Desktop but I have no enough time to give a rebranding support here.

**Comment by pdarcos** [comment]
Hi @Wescoeur 
I understand perfectly and this a community driven open source project, so I'm not complaining. I know I'm not entitled to anything and am happy with any help I can get. Sorry if that came across wrong.

I understand you cannot help much with rebranding support. My goal here is to test out linphone and see how feasible it would be to rebrand. If it does work I plan to purchase a commercial license. But it seems to me your code was not designed with any rebranding in mind considering so many hardcoded strings spread all over the place. I don't ask to be spoonfed, but pointing out where in the code one should look to change the binary should not be a huge support question.

Thanks

**Comment by Wescoeur** [comment]
Good news, it's now easily to rename the app with the `application_info.cmake` file.
