### ISSUE TITLE
Why there is no server configure for another server , not Linphone.org

### ISSUE THREAD

**Issue by yankunsam** [BelledonneCommunications/linphone-desktop#173]
Is it possible for now? Thanks

**Comment by Wescoeur** [comment]
I don't understand your problem. You can use linphone-desktop with another SIP servers.

**Comment by ovari** [comment]
@yankunsam please close this issue if the following solves your situation. Thank you
https://australianphone.com.au/support/setup-guides/290-linphone
At the bottom, click on "Click here to view how to enable VoIP encryption on Linphone (optional)" for optional configuration.

**Comment by yankunsam** [comment]
okay. It works now. Thanks
