### ISSUE TITLE
Could not find MinGW

### ISSUE THREAD

**Issue by damasojm** [BelledonneCommunications/linphone-desktop#174]
fail when try run command: python prepare.py -G "Visual Studio 14 2015"

previously i set:
Qt5_DIR="C:\Qt\5.9\msvc2015\lib\cmake"
PATH="C:\Qt\5.9\msvc2015\bin;%PATH%"

but when try run command: python prepare.py -G "Visual Studio 14 2015"

show this error:
```
CMake Error at cmake/CheckBuildTools.cmake:40 (message):
  Could not find MinGW!
Call Stack (most recent call first):
  builders/CMakeLists.txt:67 (include)
  configs/config-desktop-common.cmake:92 (include)
  configs/config-desktop.cmake:55 (include)
  CMakeLists.txt:64 (include)
```

**Comment by Wescoeur** [comment]
Do you have installed MinGW?
