### ISSUE TITLE
Importing user account to linphone

### ISSUE THREAD

**Issue by Sharrisii** [BelledonneCommunications/linphone-desktop#176]
I read that there is a way on how to import contacts (using vcards, see https://wiki.linphone.org/xwiki/wiki/public/view/FAQ/As%20a%20user%2C%20how%20do%20I%20export%20or%20import%20Linphone%20contacts )

However, I'm looking for a way on how to import the user name and password for linphone (so a profile).
The reason why this is needed is because I would be using a livecd and don't want to type in the username and password with every boot. So the idea is to copy a file from a usb stick to the linux tmpfs using a script. I would need to know which file this would be though (which contains the username / password, ...) .

Is there any way to do this, and if not, can it be integrated (by which I mean:
integrate a profile export function
integrate a command to start linphone with a specific profile) ?

**Comment by Wescoeur** [comment]
Your profile data are available in this file: `~/.config/linphone/linphonerc`.
You can use this command to use a specific file: `linphone --config <file>`.
