### ISSUE TITLE
Expose LDAP settings

### ISSUE THREAD

**Issue by ari** [BelledonneCommunications/linphone-desktop#178]
There is LDAP code in this project. There is even a compile switch:

    ./prepare.py -DENABLE_LDAP=ON

However there is no UI for configuring LDAP. Either its there and very hidden, or it is missing.

**Comment by ari** [comment]
I've discovered a GTK ui here: https://github.com/BelledonneCommunications/linphone/blob/ff3ff7aec1e396390fa2ff27ec7974690ef61236/gtk/ldap.ui

But I can't see how that is exposed or what the relationship is between QT and GTK within the Linphone project.

**Comment by Wescoeur** [comment]
GTK was the old UI in Linphone Desktop 3. In this version Qt is used.

**Comment by ari** [comment]
Ah, so bits of the UI are in the core linphone project but ignored. So I'm guessing all the GTK stuff will be removed at some point in the future?

Anyhow, this means we still need a QT ui implementation. Unfortunately I don't have any skills with QT at all, so hopefully it might be on someone's radar. A very useful task for getting this project into any companies with a shared client address book.

**Comment by Wescoeur** [comment]
The GTK stuff was removed in the dev_groupchat branch. It will be merged soon.
For the moment LDAP settings are not in our plans. Sorry.

**Comment by ari** [comment]
OK, thanks for letting me know. I can't help with QT/C++ but if you ever need help with ways to query LDAP or doing reverse lookup of CID back to user, etc I've quite a few years building LDAP schemas, so happy to help.

Remember that if you decide to add LDAP settings back, this is also useful for people running Microsoft AD.

**Comment by ari** [comment]
Great! Feedback:

1. Links on news page are mixed up between Mac and Linux
2. Tooltips in the LDAP section have escaped \n
3. "Base object" is normally just called "search base". Using the common phrase will be easier. And the tooltip is wrong... no entries *above* will be found.
4. Please allow anonymous bind
5. It is not obvious that to edit an existing LDAP server you click on the orange bold text
6. Lots of tooltips talk about friends. Seems a bit out of place here.
7. If the returned record has more than one phone, eg "mobile" and "telephoneNumber" then I'd like to see two results listed in the search results so I can pick one.

Its not as snappy as I might expect. What is the debounce time set to?


Otherwise, brilliant! Thanks so much!

**Comment by julonexus** [comment]
Hi
Thanks for your feebacks. It certainly need more polishing.
From https://ldapwiki.com/wiki/BaseObject , it is "below" ;)

The time is set at 5s but the field to set it has been forget. We need to add it.
It can be set inside linphonerc with a "timeout" key.
Keys configurations are describe here : https://gitlab.linphone.org/BC/public/liblinphone/-/blob/34210034c1682ce84cf0cfaaf767736b0c116d23/src/ldap/ldap-config-keys.h#L36

**Comment by julonexus** [comment]
It should be easy to fix your other points but I need time to do them.
Maybe more time for your 7. as we have to manage a list of contact rather than having just one but it is not hardly to do in theory.

**Comment by ari** [comment]
Don't know who runs ldapwiki. Anyway here is the most popular LDAP implementation in the world and their ldap search tool:

https://www.openldap.org/software/man.cgi?query=ldapsearch&apropos=0&sektion=0&manpath=OpenLDAP+2.0-Release&format=html

searchbase is the word they use and that's pretty clear. I assume you always use subtree.


I reckon your debounce should be something like 0.5 seconds.

**Comment by julonexus** [comment]
Hi,
These points have been implemented. You will find them in the next snapshot versions (> alpha 96)aswell as a better normalization on URI (escape special characters like spaces in phone number etc.)
Regards

**Comment by HamburgerJungeJr** [comment]
I would like to give some feedback too.

In the new you wrote

> In addition, when an incoming call arrives, a LDAP search is automatically triggered to show the display name of the caller according to the LDAP directory.

I cant get this to work.

If I look at the LDAP-Request via Wireshark, linphone inserts the phonenumber into the filter-expression from the settings.
The phonenumber is not in the sn (or in my case displayName) field, no record is found. 

If I extend the filter to
`(|(displayName=*%s*)(telephoneNumber=%s)(mobile=%s))`
the following error occures
`021-07-22 12:45:04:879 [AppRun.wrapped/liblinphone] MESSAGE [LDAP] Found pending search 0x3939140 (for (|(displayName=*<myCallingPhoneNumber>*)(telephoneNumber=(|(displayName=*%s*)(telephoneNumber=%s)(mobile=%s)))(mobile=(null)))), launching...
2021-07-22 12:45:04:879 [AppRun.wrapped/liblinphone] ERROR [LDAP] Error ldap_search_ext returned -7 (Bad search filter)
`

It seems to be the problem with multiple placeholders for the search input (has likely something to do with printf)
