### ISSUE TITLE
error MSB6006: "cmd.exe" exited with code 1.

### ISSUE THREAD

**Issue by nitish3197** [BelledonneCommunications/linphone-desktop#180]
After building the project.sln file in visual studio 2013. Following  errors occured 

![screenshot 42](https://user-images.githubusercontent.com/30616014/40164769-0ea6fea8-59d8-11e8-97dd-68b95969ba98.png)

I am using PC with windows 10 64-bit on it..

**Comment by Wescoeur** [comment]
Please read the instructions in the README.md. Visual Studio 2015 is supported. Not the 2013 version.
