### ISSUE TITLE
Linphone Desktop Numpad

### ISSUE THREAD

**Issue by luciano-work** [BelledonneCommunications/linphone-desktop#181]
Hi Guys,
I would like know, why the desktop version don't have an number keyboard (numpad) like the mobile app and if this will be possible in the next release?

All the best ;)

**Comment by Wescoeur** [comment]
You have a button in the calls window to deal with DTMF. I don't know the usage of a numpad for other purposes on a Desktop version. Can you say me what is your goal? Thank you.

![capture d ecran_2018-05-21_10-11-21](https://user-images.githubusercontent.com/5610873/40297334-bda034c4-5cdf-11e8-9b18-49148e89d7e5.png)

**Comment by luciano-work** [comment]
@Wescoeur I would like to call for a number where it is not add in contact list. I dont no how to make this :(
For example in Xlite:
![image 2](https://user-images.githubusercontent.com/12519008/40304966-f6f4a982-5cce-11e8-9855-7bcfba3e14ff.png)

**Comment by deepak2503** [comment]
Hello Guys,

I guess May be its not the right issue to ask this question but I am really in Trouble Please Help me!!!!

I have compiled linphone-desktop for Mac OS High Sierra with below commands :

1. sudo git clone https://github.com/BelledonneCommunications/linphone-desktop.git
2. sudo chmod -R 777 linphone-desktop/
3. cd linphone-desktop/
4. sudo git submodule sync && git submodule update --init --recursive
5.  Qt5_DIR="/usr/local/Cellar/qt/5.11.0/lib/cmake"
6. PATH="/usr/local/Cellar/qt/5.11.0/bin/:$PATH"
7. ./prepare.py -G Xcode
8. make


All these command result successful but yet there is no xcode project file, so that I can open it in Xcode and use as per my needs.

These are the files generated after that. please help me 
![screen shot 2018-05-31 at 9 57 11 pm](https://user-images.githubusercontent.com/16147783/40794741-b3a5614c-651d-11e8-8fbb-a920669d5bee.png)

**Comment by oliver-graetz** [comment]
> I don't know the usage of a numpad for other purposes on a Desktop version.

- First of all, Linphone is a softphone. Users simply **expect** a numpad. You should implement one, and if only to keep people from searching for it for minutes on end only to realize it is missing.
- And then, in the X-Lite screenshot you can see the numpad being displayed including the vanity assignments. This should also be implemented, so people can enter new numbers for which they only remember the vanity number ("555-SHOE").

**Comment by dernalis** [comment]
> You have a button in the calls window to deal with DTMF. **I don't know the usage of a numpad for other purposes on a Desktop version**. Can you say me what is your goal? Thank you.
> 
> ![capture d ecran_2018-05-21_10-11-21](https://user-images.githubusercontent.com/5610873/40297334-bda034c4-5cdf-11e8-9b18-49148e89d7e5.png)

Jus few examples:
- Extension Call Pickup
- Conference Room
- Call Parking
- Voice Mailbox Menu

**Comment by sgarofalo808** [comment]
Honestly I have been searching the web, can't belive there is no way to use the keyboard numpad directly on linphone.
Clicking your ID, PIN and options using the mouse on that little popup is extremely cumbersome.
Could you please make some time to add this feature?

Thanks

**Comment by SLGShark6** [comment]
2021 and here to bump this issue

**Comment by Marx1st** [comment]
+1 have been looking for the numpad quit some time... this is supposed to be a (soft)phone, right?

**Comment by olku** [comment]
@Marx1st in-call there's a numpad (useful for IVR dtfm and such), but I'm assuming you mean a numpad instead of a search bar to dial out. That doesn't exist (yet?) in Linphone desktop. I'd love to have that too though.

**Comment by Marx1st** [comment]
> @Marx1st in-call there's a numpad (useful for IVR dtfm and such), but I'm assuming you mean a numpad instead of a search bar to dial out. That doesn't exist (yet?) in Linphone desktop. I'd love to have that too though.

Yes, exactly. Though it didn't even occure to me to use the search bar to dial... Thanks for the hint :)

**Comment by xfolder** [comment]
So no dialpad to make calls?

**Comment by Marx1st** [comment]
> So no dialpad to make calls?

Like I wrote. Use the "search field" to type the number and call it.

**Comment by julonexus** [comment]
Hi
Dialpad for the magic search bar will be available for 4.5. It will be available on the next nightly on master.
Regards

**Comment by tonymartino** [comment]
Slightly different problem... I have a need to send DTMF when I'm in a conference call and I believe this is not possible right now. Can this be addressed?

**Comment by lore-code** [comment]
> Slightly different problem... I have a need to send DTMF when I'm in a conference call and I believe this is not possible right now. Can this be addressed?

This is the issue I'm having as well....any updates on this? Finally figured out how to do a proper conference call but also need to dial numbers and that numpad disappears when on a conference call.

**Comment by lore-code** [comment]
> Slightly different problem... I have a need to send DTMF when I'm in a conference call and I believe this is not possible right now. Can this be addressed?

I updated to version 5.0 and now it has this fixed 😀
