### ISSUE TITLE
Customising linphone-desktop on mac

### ISSUE THREAD

**Issue by deepak2503** [BelledonneCommunications/linphone-desktop#184]
Should I have to run this
prepare.py . --Xcode
or
prepare.py --package
?

Actually I have Compiler linphone-desktop with success, but I want to customize it but there is no Xcode file so i can open project and make changes according to me.

Also please let me know if there is anything else by which i can customise linphone-desktop in mac.

**Comment by Wescoeur** [comment]
You can generate a Xcode project with: `prepare.py -G Xcode`, then make. And you can open the project.

**Comment by deepak2503** [comment]
I have again compile and make linphone-desktop using ./prepare.py -G Xcode and then make but still there is no Xcode project file..

These are the files after whole compilation....
![screen shot 2018-05-30 at 11 24 32 am](https://user-images.githubusercontent.com/16147783/40703653-77481d40-6403-11e8-91c4-e9a5cfe36e22.png)

Please Provide me any Solutions because i have already compiled for linphone-iPhone and linphone-Android already and they are working good.
In linphone-iPhone linphone.xcode project file get generated. See below :
![screen shot 2018-05-30 at 12 20 15 pm](https://user-images.githubusercontent.com/16147783/40703780-f1505012-6403-11e8-8a90-9463ac4c557e.png)

**Comment by privum** [comment]
Why has this issue been closed? It seems that prepare.py -G Xcode apparently doesn't generate xcode project file, or am I missing something?

**Comment by deepak2503** [comment]
I didn't Know Why?

I have recompiled the source code many times again and again. But after building it with ./prepare.py - G Xcode yet no Xcode project file is there to open the project.

**Comment by S0U1SB4N3** [comment]
@Wescoeur Please assist in this matter, I have also had this issue

**Comment by Omid-Mohajerani** [comment]
I use this method and is working for me: http://omid-mohajerani.blogspot.com/2020/05/compiling-linphone-desktop-in-mac-os.html

**Comment by jmvillaltas** [comment]
@deepak2503 did you manage to solve this?
