### ISSUE TITLE
Failed to add contacts with comma in the name

### ISSUE THREAD

**Issue by skuti-is** [BelledonneCommunications/linphone-desktop#186]
Unable to create contacts with comma ',' in the name.
Workaround create the contact with out the comma char, and editing the name to add the comma.

Using Linphone desktop 4.1.1 flatpak version on Ubuntu 18.04

**Comment by julonexus** [comment]
[Commit](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/f43f1d496f81d876fb35ad08d7f4d4819d20759a)
