### ISSUE TITLE
Freezes when running on remote Linux desktop (X2Go)

### ISSUE THREAD

**Issue by Hybrid512** [BelledonneCommunications/linphone-desktop#19]
Hi,

I'm running Linphone on a remote Linux desktop with X2Go (ThinClient setup).
Everything runs smooth and Linphone is great in this environment but, on some random occasions, the Linphone GUI freezes for a few seconds or even 2-3 minutes sometimes while Linphone still works normaly (sound ok, communication ok), only the GUI is frozen and thus, it is impossible to hangup or do anything.

This visibly only occur under X2Go and I see that kind of logs in .xsession-errors : 

------------------------------------------------------------------------------------------------------------------------------------

```
Avertissement du gestionnaire de fenêtres : Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x160004c (Linphone) 
Avertissement du gestionnaire de fenêtres : meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed. 
Avertissement du gestionnaire de fenêtres : Fenêtre WM_TRANSIENT_FOR 0x180004c non valide indiquée pour 0x184cb8e (Linphone).
```

------------------------------------------------------------------------------------------------------------------------------------

This didn't happen with Linphone 3.6.1 which is the version shipped with Ubuntu 16.04 (which this setup is based on) but I had more annoying problems with this version (truncated communications) so I installed Linphone Team PPA which provides Linphone 3.9.1.
From then, I get these "freezes" issues.
I built many different releases from then, even  the current 3.11.1 that I built myself.

Here are a few setup informations, please ask if you need more : 

OS : Ubuntu 16.04.2 LTS
Desktop : MATE Destop 1.12.1
X2Go Server : 4.1.0.0

Regards.

**Comment by Wescoeur** [comment]
The Linphone desktop app uses Qt5 now. This issue is invalid.
Thanks for your feedback and sorry for the delay of this answer.
