### ISSUE TITLE
Flatpak / linphone 4.1.1 / Ubuntu 18.04 / OpenGL Error

### ISSUE THREAD

**Issue by Bryan76** [BelledonneCommunications/linphone-desktop#190]
```
$ LIBGL_DEBUG=verbose flatpak --verbose run com.belledonnecommunications.linphone
F: Opening user flatpak installation at path /home/username/.local/share/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/username/.local/share/flatpak
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/username/.config/pulse/client.conf': Error opening file /home/username/.config/pulse/client.conf: No such file or directory
F: Running '/usr/lib/flatpak/flatpak-bwrap --args 21 /usr/lib/flatpak/flatpak-dbus-proxy --args=23'
F: Running '/usr/lib/flatpak/flatpak-bwrap --args 18 linphone'
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
libGL: screen 0 does not appear to be DRI2 capable
libGL: OpenDriver: trying /lib/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /lib/dri/swrast_dri.so
libGL: Can't open configuration file /home/username/.drirc: No such file or directory.
libGL: Can't open configuration file /home/username/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize GLX


$ flatpak --gl-drivers
nvidia-396-24-02
default
host

```

Nvidia Drivers: 396.24.02
GeForce 1080 Ti

glxinfo reports that direct rendering is available.

Any ideas?

**Comment by ocumo** [comment]
**Same problem here after upgrading to 18.04 (Kubuntu)**. Linphone was already installed and working OK, no issues before the upgrade. Differences with OP seem to be only because my environment is KDE, else I would say **identical problem**.
Running the standard OpenGL test program with:

`LIBGL_DEBUG=verbose glxgears`

...works and doesn't report anything wrong. Here follows the same tests @Bryan76 did:
```
$ LIBGL_DEBUG=verbose flatpak --verbose run com.belledonnecommunications.linphone
F: Opening user flatpak installation at path /home/username/.local/share/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/username/.local/share/flatpak
F: Cleaning up unused container id 716860737
F: Allocated instance id 460781433
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/username/.config/pulse/client.conf': Error opening file /home/username/.config/pulse/client.conf: No such file or directory
F: Running '/usr/lib/flatpak/flatpak-bwrap --args 21 /usr/lib/flatpak/flatpak-dbus-proxy --args=23'
F: Running '/usr/lib/flatpak/flatpak-bwrap --args 20 linphone'
libGL: screen 0 does not appear to be DRI2 capable
libGL: OpenDriver: trying /lib/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /lib/dri/swrast_dri.so
libGL: Can't open configuration file /home/username/.drirc: No such file or directory.
libGL: Can't open configuration file /home/username/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version

^C
$ flatpak --gl-drivers 
nvidia-390-48
default
host

$ glxinfo
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
....

```

**Comment by ocumo** [comment]
### **UPDATE: I believe I fixed it.**
I am not familiar with the flatpak platform, but reading man flatpak, two commands called my attention, although they are not well documented. So via "_try and see what happens_":   **Bottom line**:

1.   `$ flatpak repair com.belledonnecommunications.linphone`
2.    `$ flatpak update com.belledonnecommunications.linphone`

I am not sure if we really need the two commands for this fix (very poor documentation), but after this sequence, Linphone is back and running again.

Can any of the developers please comment on this and provide some more authoritative information? Could this be documented for future reference?

**Comment by Bryan76** [comment]
We were having separate issues.  Although I did try your fix, it didn't work.

For some reason mine appears to complain that my screen is not DRI2 capable.  It looks like it then tries to use a software renderer maybe?  swrast?  And then just fails.

**Comment by ocumo** [comment]
@Bryan76 : Sorry to hear that.  :-/

I actually have _yet another_ computer (also with Kubuntu 18.04, also upgraded, but this one with much more stuff installed, including Xfce, Cinnamon, Enlightenment and i3 !) with the exact same issue as in my first post, and I have just run five minutes ago the two above commands and then run Linphone like this, from command line:
`flatpak run com.belledonnecommunications.linphone`
It runs ok now.

(_tip: in your case: does running it from command line like that give you anything else different or worthy of mention?_)

Now, it still strikes me as (at least) "funny" (but I'm not laughing, believe me) that comparing line by line the error message you posted with mine, we have the same complaints about screen not being "DRI2 capable", failure to locate swrast_dri.so, and same libGL errors. The Gtk related GLX errors make the difference, but the whole thing still "smells" like bad symlinks or bad paths, which in my case one or both commands seem to have managed to resolve.

I still have one laptop (damn it, still KDE!) -also recently upgraded, but from 17.10- in which I have not tried Linphone. I suspect I will have the same issue, and of course I will try the same "solution".
I wonder what would happen with an installation from scratch? Perhaps uninstall Linphone and run the installation command again?  Stupid suggestion, I know! too much "_Windowsy_" for my taste, and if it fixes it, we will never know what on Earth was wrong; but hey, it depends on how much time you are willing to devote to do a proper troubleshooting... not that we are getting a lot of pointers here so far...

**Comment by esbroering** [comment]
@Bryan76,

You can run the follow command to solve this:
`$ flatpak --gl-drivers `
>  To get your nvidia driver. Example: nvidia-390-48

`$ flatpak --user install gnome org.freedesktop.Platform.GL.nvidia-XXX-YYY`
> Replace nvidia-XXX-YYY to result of the first command. Example: **flatpak --user install gnome org.freedesktop.Platform.GL.nvidia-390-48**

This works for me. I hope that works for you too.
