### ISSUE TITLE
How to use relative path for linux installation

### ISSUE THREAD

**Issue by frealgagu** [BelledonneCommunications/linphone-desktop#194]
I've tried to compile as follows:
git submodule sync
git submodule update --init --recursive
./prepare.py -c
./prepare.py --list-cmake-variables -DENABLE_RELATIVE_PREFIX=YES

compilation is successful, however the references to libraries are absolute to installation path. I want to move the package to another directory but is not possible because the references pointing to libraries in the original directory.

**Comment by ohquait** [comment]
the same problems here, 
i think it is one way to solve, create a project on ccmake or cmake-gui,
put all needed files such .h and .c into a project-dir and edit the cmake-list.txt
and also the pyprepare, e.g. add a DESTDIR= option for make install
i have not the time to learn it all,
cheers
