### ISSUE TITLE
Pass CMake argumments to each submodule in installation

### ISSUE THREAD

**Issue by frealgagu** [BelledonneCommunications/linphone-desktop#195]
I want to compile linphone and its submodules using the CMake argument ENABLE_STRICT=NO
however if I put the property to prepare.py, it only works for linphone-desktop and not for its submodules.

git submodule sync
git submodule update --init --recursive
./prepare.py --list-cmake-variables -DENABLE_STRICT=NO

How could I achieve this, I don't want to patch each CMakeLists each time I want to compile a new version.

Thanks a lot in advance.

**Comment by zahraesm** [comment]
@frealgagu  can you tell me what does -DENABLE_STRICT=NO mean?

**Comment by frealgagu** [comment]
Linphone treats some warnings as errors which cause that the compilation fails. Using -DENABLE_STRICT=NO causes that the warnings don't stop the compilation.

**Comment by Wescoeur** [comment]
For the moment this issue is blocked. We are working on a refactoring of our build system to deal with this issue and many other things.
