### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by shvchk** [BelledonneCommunications/linphone-desktop#197]
It has been almost a year since last release, are there any plans for a new one (maybe at least maintenance one)? My main concern are translations: there are 5 translations (French, German, Portuguese, Russian, Turkish) with 100% coverage or close to that, and 3 more (Japanese, Lithuanian, Swedish) with 75%+ coverage — but they can't be used as old release does not include them.

**Comment by baimafeima** [comment]
@Wescoeur Great to know that a new release is in the making. In addition to the source tarballs, could you also make a flatpak or snap package available? This would especially be helpful to install on operating systems where Linphone is not yet in the repositories. I also hope that the new release will have this issue resolved: https://github.com/BelledonneCommunications/linphone-desktop/issues/96

**Comment by Wescoeur** [comment]
#96 is normally done.
Of course, a flatpak will be available!

**Comment by baimafeima** [comment]
What are the current blockers for a new tarball release here on GitHub? As of now, inclusion into the repositories of operating systems are blocked because no regular release is available.

**Comment by Wescoeur** [comment]
A release is normally planned for this month. But sadly that doesn't depend on me.

**Comment by WPFilmmaker** [comment]
@Wescoeur news on this?

**Comment by Wescoeur** [comment]
Sorry but I don't have any idea. I resigned from my job many months ago because I don't share with this enterprise the same goals and opinions concerning IT, code management, Open Source... So all my apologies if can't help you. :confused:

**Comment by shvchk** [comment]
@fgrisez might have a clue, I hope.

**Comment by dyslesiq** [comment]
A new release is planned for the end of July.
It will be mainly focused on bug fixes and the integration of libraries update and new features that have already been released in Android/IOS apps.

**Comment by WPFilmmaker** [comment]
@dyslesiq thanks for the update! Will LIMEv2 for linux deskop be shipped with that release?

**Comment by dyslesiq** [comment]
Yes LIME v2 should be included in the release

**Comment by shvchk** [comment]
Looks like all new work is done in https://github.com/BelledonneCommunications/linphone repo. There is also 4.3.0 release there. Flatpak is still 4.1.1 though.

**Comment by julonexus** [comment]
Flatpack is not supported any more. You can find the appimage there https://www.linphone.org/snapshots/AppImages/

**Comment by cognifloyd** [comment]
@julonexus The flatpak had the python bindings for liblinphone. The AppImage does not have them. How can I get python bindings? In particular the flatpak had `/usr/lib/python2.7/site-packages/linphone/` which allowed a python2.7 script to do `from linphone import linphone` (in a flatpak built on top of the linphone flatpak).

If needed I can file a new issue. Since this would be distributed in the AppImage, would I file it against the linphone-desktop repo or a different repo?
