### ISSUE TITLE
linphone-desktop No Xcode project file appear after successful compilation. WHY?

### ISSUE THREAD

**Issue by deepak2503** [BelledonneCommunications/linphone-desktop#198]
I have compiled linphone-desktop Source code using these commands.
Every step got successful result but yet there is no Xcode project file to use.

These are the steps below:

1.sudo git clone https://github.com/BelledonneCommunications/linphone-desktop.git
2.sudo git submodule sync && git submodule update --init --recursive
3. Qt5_DIR="/usr/local/Cellar/qt/5.11.0/lib/cmake"
4. PATH="/usr/local/Cellar/qt/5.11.0/bin/:$PATH"
5. ./prepare.py -G Xcode
6. make

I have done all thing step by step but yet there is no Xcode projectfile. However ./prepare.py and make command yields a successful result.

Also I have raise this issue previously but yet there is no reply from concerned team for this. I want to know WHY?

Please let me know if i am doing anything wrong or any reason for why Xcode project file is not getting generated.

**Comment by anilStartele** [comment]
Hello Deepak! May I know how did you resolve this issue? I am trying to build it but getting error. Will you help me out from the issue?
