### ISSUE TITLE
By not providing "FindLinphone.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "Linphone", but CMake did not find one.

### ISSUE THREAD

**Issue by sshsu** [BelledonneCommunications/linphone-desktop#200]
27>  Creating directories for 'EP_linphoneqt'
27>  No download step for 'EP_linphoneqt'
27>  No update step for 'EP_linphoneqt'
27>  No patch step for 'EP_linphoneqt'
27>  Performing configure step for 'EP_linphoneqt'
27>  loading initial cache file D:/software/linphone/linphone-desktop/WORK/desktop//tmp/EP_linphoneqt/EP_linphoneqt-cache-Debug.cmake
27>  CMake Error at CMakeLists.txt:99 (find_package):
27>    By not providing "FindLinphone.cmake" in CMAKE_MODULE_PATH this project has
27>    asked CMake to find a package configuration file provided by "Linphone",
27>    but CMake did not find one.
27>
27>    Could not find a package configuration file provided by "Linphone" with any
27>    of the following names:
27>
27>      LinphoneConfig.cmake
27>      linphone-config.cmake
27>
27>    Add the installation prefix of "Linphone" to CMAKE_PREFIX_PATH or set
27>    "Linphone_DIR" to a directory containing one of the above files.  If
27>    "Linphone" provides a separate development package or SDK, be sure it has
27>    been installed.
27>
27>
27>  -- Configuring incomplete, errors occurred!
27>  See also "D:/software/linphone/linphone-desktop/WORK/desktop/Build/linphoneqt/CMakeFiles/CMakeOutput.log".
27>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe” exited，return code is  1。

**Comment by sshsu** [comment]
the output log tells me there is an error at CMakeLists.txt:99 , I am not sure where is the CMakeLists.txt，it seems that it is not the "linphone-desktop\submodules\linphone\CMakeLists.txt"，I cannot locate it ,can someone help?
and then I search for all files for "FindLinphone.cmake" but cannot find，is any problem with this?
and then I search for all files for "LinphoneConfig.cmake" and also cannot find a one, but just find a file named "LinphoneConfig.cmake.in" in the folder "\linphone-desktop\submodules\linphone\cmake"

**Comment by LAOMENGA** [comment]
so,please give him a solution!!please!!

**Comment by lepianoman** [comment]
Did the error message tell you to run:

git submodule sync && git submodule update --init --recursive

And if so, did you try that?

**Comment by LAOMENGA** [comment]
I had tried it ,but my files is same as git's;

**Comment by Wescoeur** [comment]
Could you paste the full log in a file please?
