### ISSUE TITLE
Sign git tags

### ISSUE THREAD

**Issue by Megver83** [BelledonneCommunications/linphone-desktop#202]
Please sign the tags you make for better security, so anyone can verify them when, e.g., a packager builds linphone-desktop for a distro. Idk if you create tags from GitHub or git CLI, but it's pretty easy:

    $ git tag -sa <tagname> -m "<tag message>" # Create and sign a tag
    $ git push origin <tagname> # Push it

**Comment by Wescoeur** [comment]
Than you for your interest. It's already planned for later.
