### ISSUE TITLE
python prepare.py error

### ISSUE THREAD

**Issue by zahraesm** [BelledonneCommunications/linphone-desktop#204]
i run python prepare.py -G  "Visual Studio 14 2015"
and i get the following error:
Error copying file "GCC_LIBRARY-NOTFOUND" to "C:/linphone-desktop/OUTPUT/desktop/lib/gcc.lib"
although the project.sln is built and when i build it i get:

> No download step for 'EP_bcunit'
> 5>  Creating directories for 'EP_xml2'
> 3>  Creating directories for 'EP_mbedtls'
> 6>  Creating directories for 'EP_bv16'
> 2>  No update step for 'EP_bcunit'
> 9>  Creating directories for 'EP_opus'
> 2>  No patch step for 'EP_bcunit'
> No download step for 'EP_srtp'
> 11>  No update step for 'EP_srtp'
> 7>  No update step for 'EP_gsm'
> 11>  No patch step for 'EP_srtp'
> 11>  Performing configure step for 'EP_srtp'
> 7>  No patch step for 'EP_gsm'

 the full loge is here:
[aug 6-linphone log.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/2262073/aug.6-linphone.log.txt)

**Comment by Wescoeur** [comment]
Your first problem is: 
```
3>x509.obj : error LNK2019: unresolved external symbol _mbedtls_snprintf referenced in function _mbedtls_x509_dn_gets [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]
```

What is your current commit?

**Comment by zahraesm** [comment]
@Wescoeur  thank you so much for responding. I made a fresh clone  and the curren commit is :f243c7c8e750e316a030bb1ded08ee54220dbc1a
