### ISSUE TITLE
Have an option to start linphone at startup on Linux

### ISSUE THREAD

**Issue by WPFilmmaker** [BelledonneCommunications/linphone-desktop#205]
I don't know about Windows, but on many Linux distros is quite hard to add a program to the startup (just google it, it requires copying/editing file strings etc., definitively not user-friendly). In my case on Lubuntu 16.04 I tried but it just won't work... It would be nice having an option in the preference to launch linphone automatically as the OS starts.

**Comment by Wescoeur** [comment]
It's now implemented in master branch.
