### ISSUE TITLE
v4l-utils is failing to compile

### ISSUE THREAD

**Issue by frealgagu** [BelledonneCommunications/linphone-desktop#208]
Currently there is an error trying to compile the complete package. The error message is as follows:

    /tmp/linphone-desktop/submodules/externals/v4l-utils/lib/libv4lconvert/control/libv4lcontrol.c: In function 'v4lcontrol_get_usb_info':
    /tmp/linphone-desktop/submodules/externals/v4l-utils/lib/libv4lconvert/control/libv4lcontrol.c:388:29: error: called object 'minor' is not a function or function pointer
           c == '\n' && minor == minor(st.st_rdev))
                                 ^~~~~
    /tmp/linphone-desktop/submodules/externals/v4l-utils/lib/libv4lconvert/control/libv4lcontrol.c:361:9: note: declared here
      int i, minor;
             ^~~~~
    make[7]: *** [Makefile:796: libv4lconvert_la-libv4lcontrol.lo] Error 1

**Comment by zahraesm** [comment]
are you working in visual studio?

**Comment by frealgagu** [comment]
No, I'm using linux bash (over Archlinux to be more exact). That package was compiling, but I don't know if one of its dependencies changed and started failing. I see that v4l-utils is in version 1.0.0 and it haven't been changed, however trying to compile with ./prepare.py && make stops with this error. I don't know where minor() should be supposed to point to but I guess it was removed recently.

**Comment by Wescoeur** [comment]
Thanks, related to #213. It's fixed now.

**Comment by frealgagu** [comment]
The new v4l-utils reference points to undefined commit.

error: Server does not allow request for unadvertised object 10d5c745bde031f21b36f8d016b5790150f70eea
Fetched in submodule path 'submodules/externals/v4l-utils', but it did not contain 10d5c745bde031f21b36f8d016b5790150f70eea. Direct fetching of that commit failed.
