### ISSUE TITLE
Limit number of concurrent calls

### ISSUE THREAD

**Issue by Hybrid512** [BelledonneCommunications/linphone-desktop#21]
Hi,

In some situations, this is not desirable to have multiple calls at a time, neither it is possible to limit those calls at the server side.

Beeing able to handle multiple calls with Linphone is great but it would be even greater to be able to limit the number of simultaneous calls on the Linphone side with an option in the preferences (or at least, in the ini file).
Something like "max_concurrent_calls=n" would be great.
Calls coming over the limit would then receive a BUSY state.

Regards.

**Comment by ghismary** [comment]
This is configurable in the linphonerc file with the max_calls parameter of the [misc] section.
