### ISSUE TITLE
dbus error

### ISSUE THREAD

**Issue by MrQuanLiang** [BelledonneCommunications/linphone-desktop#210]
Qt5.9.6/5.9.6/gcc_64/lib/libQt5DBus.so.5.9.6: undefined reference to `dbus_message_copy@LIBDBUS_1_3'

**Comment by MrQuanLiang** [comment]
Use Qt5.9.0 is ok

**Comment by Wescoeur** [comment]
Do you have other problem with dbus or it's ok now?

**Comment by MrQuanLiang** [comment]
It is ok now! Thank you!



lnpdit_lq@126.com
 
From: Ronan Abhamon
Date: 2018-08-23 19:53
To: BelledonneCommunications/linphone-desktop
CC: MrQuanLiang; Author
Subject: Re: [BelledonneCommunications/linphone-desktop] dbus error (#210)
Do you have other problem with dbus or it's ok now?

**Comment by Wescoeur** [comment]
Thanks.
