### ISSUE TITLE
Add linphone-python in a flatpak package

### ISSUE THREAD

**Issue by cognifloyd** [BelledonneCommunications/linphone-desktop#211]
As the official install of linphone now relies on flatpak, please also include the linphone-python module in the flatpak. Then I can run something like (where `my-linphone-based-script.py` imports the `linphone` module)
```
flatpak run --filesystem=~/my-linphone-based-script.py --command=~/my-linphone-based-script.py com.belledonnecommunications.linphone
```

**Comment by Wescoeur** [comment]
`linphone-python` is independent of linphone-desktop. In this case a specific flatpak package must be written. I add your issue as an idea.

**Comment by cognifloyd** [comment]
[AppImage replaces Flatpak](https://github.com/BelledonneCommunications/linphone-desktop/issues/197#issuecomment-615951911) so I'm closing this in favor of #346.
