### ISSUE TITLE
CMAKE_MAKE_PROGRAM is not set.

### ISSUE THREAD

**Issue by MrQuanLiang** [BelledonneCommunications/linphone-desktop#212]
-- Including builder belcard
-- Including builder minizip
CMake Error: CMake was unable to find a build program corresponding to "MinGW Ma
kefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a differe
nt build tool.
CMake Error: CMake was unable to find a build program corresponding to "MinGW Ma
kefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a differe
nt build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
CMake Error at cmake/CMakeLists.txt:205 (include):
  include could not find load file:

**Comment by MrQuanLiang** [comment]
The MinGW environment is poorly configured!

**Comment by WPFilmmaker** [comment]
@MrQuanLiang I am not a developer, but given your issue is technical and the tickets here are checked only by one person in the dev team probably, the mailing list is a better option https://linphone.org/contact.html

**Comment by MrQuanLiang** [comment]
@WPFilmmaker Thank you! I have solved it because the MinGW environment is not configured.
