### ISSUE TITLE
Compilation fail with glibc >= 2.25

### ISSUE THREAD

**Issue by kt-315** [BelledonneCommunications/linphone-desktop#213]
> * The inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated.  This
>   means that in a future release, the macros “major”, “minor”, and “makedev”
>   will only be available from <sys/sysmacros.h>.

In "submodules/externals/v4l-utils/lib/libv4lconvert/control/libv4lcontrol.c" and "submodules/externals/v4l-utils/utils/libmedia_dev/get_media_devices.c" need add include:
`#include <sys/sysmacros.h>`

**Comment by Wescoeur** [comment]
Thank you for your report. Fixed on master.
