### ISSUE TITLE
The new v4l-utils reference points to undefined commit

### ISSUE THREAD

**Issue by frealgagu** [BelledonneCommunications/linphone-desktop#215]
The new v4l-utils reference points to undefined commit.

    error: Server does not allow request for unadvertised object 10d5c745bde031f21b36f8d016b5790150f70eea
    Fetched in submodule path 'submodules/externals/v4l-utils', but it did not contain 10d5c745bde031f21b36f8d016b5790150f70eea. Direct fetching of that commit failed.

**Comment by Wescoeur** [comment]
Fixed.
