### ISSUE TITLE
Error compiling the whole package

### ISSUE THREAD

**Issue by frealgagu** [BelledonneCommunications/linphone-desktop#218]
The following is happening trying to compile in linux (archlinux):

./prepare.py --all-codecs
  make
...
...

[100%] Linking CXX executable bzrtpTest
/usr/bin/ld: /Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/OUTPUT/desktop/lib/libsqlite3.so: undefined reference to `dlopen'
/usr/bin/ld: /Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/OUTPUT/desktop/lib/libsqlite3.so: undefined reference to `dlclose'
/usr/bin/ld: /Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/OUTPUT/desktop/lib/libsqlite3.so: undefined reference to `dlerror'
/usr/bin/ld: /Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/OUTPUT/desktop/lib/libsqlite3.so: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
make[6]: *** [test/CMakeFiles/bzrtpTest.dir/build.make:164: test/bzrtpTest] Error 1
make[6]: Leaving directory '/Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/Build/bzrtp'
make[5]: *** [CMakeFiles/Makefile2:164: test/CMakeFiles/bzrtpTest.dir/all] Error 2
make[5]: Leaving directory '/Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/Build/bzrtp'
make[4]: *** [Makefile:163: all] Error 2
make[4]: Leaving directory '/Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/Build/bzrtp'
make[3]: *** [CMakeFiles/EP_bzrtp.dir/build.make:117: /Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/Stamp/EP_bzrtp/EP_bzrtp-build] Error 2
make[3]: Leaving directory '/Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/cmake'
make[2]: *** [CMakeFiles/Makefile2:898: CMakeFiles/EP_bzrtp.dir/all] Error 2
make[2]: Leaving directory '/Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/cmake'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Leaving directory '/Multimedia/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/cmake'
make: *** [Makefile:14: desktop-build] Error 2

**Comment by simwin** [comment]
Yes. Have these errors too. Ubuntu

**Comment by elangarika** [comment]
Me too..

**Comment by frealgagu** [comment]
Thanks, that works for me.
