### ISSUE TITLE
build fail linphone-desktop on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by bertonlu** [BelledonneCommunications/linphone-desktop#219]
Hi everyone,

I follow [the linephone guide](https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Linphone%20and%20Raspberry%20Pi/#HCompilinglinphoneontherasberrypi), but it produces a fail. Can you tell me what to do?

OS：RASPBIAN STRETCH LITE (Release date: 2018-06-27)

<pre><code>
.........................
Unable to invoke compiler: /usr/bin/cc   -m32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.
CMakeFiles/EP_vpx.dir/build.make:106: recipe for target '/home/pi/linphone-desktop/WORK/no-ui/Stamp/EP_vpx/EP_vpx-configure' failed
make[3]: *** [/home/pi/linphone-desktop/WORK/no-ui/Stamp/EP_vpx/EP_vpx-configure] Error 1
make[3]: Leaving directory '/home/pi/linphone-desktop/WORK/no-ui/cmake'
CMakeFiles/Makefile2:299: recipe for target 'CMakeFiles/EP_vpx.dir/all' failed
make[2]: *** [CMakeFiles/EP_vpx.dir/all] Error 2
make[2]: Leaving directory '/home/pi/linphone-desktop/WORK/no-ui/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/linphone-desktop/WORK/no-ui/cmake'
Makefile:14: recipe for target 'no-ui-build' failed
make: *** [no-ui-build] Error 2
.........................
</code></pre>

![fail01](https://user-images.githubusercontent.com/29419176/45610766-b257fa80-ba8f-11e8-8a29-ab334c3e3058.JPG)
![fail02](https://user-images.githubusercontent.com/29419176/45610923-3c07c800-ba90-11e8-8e64-a183f6d697cc.JPG)

**Comment by Hurleyking** [comment]
i have same error

**Comment by Fips11** [comment]
https://wiki.linphone.org/xwiki/wiki/public/viewrev/Linphone/Linphone%20and%20Raspberry%20Pi/WebHome?rev=1.14

**Comment by FrancescoTalotta** [comment]
Me too. Getting the same error on the Zero W. Any idea on how to fix it?
