### ISSUE TITLE
linphone-desktop compile issue

### ISSUE THREAD

**Issue by fruscil** [BelledonneCommunications/linphone-desktop#22]
After downloading the latest desktop source and following the instructions above; I was able to run the python prepare which generated the Visual Studio project.sln.

I then opened the project.sln in VS 2015 and tried a REBUILD ALL and received an error;

Code C2220
Project: EP_linphone
File: info.c
Description: warning treated as error - no 'object' file generated linphone.vcxproj

Did I miss something? 

Thank you,

**Comment by Wescoeur** [comment]
The Linphone desktop project has been updated in 4.0. (New app code.)
This compilation error is obsolete now.

**Comment by chowdarynamala** [comment]
I still face same error in linphone desktop 4.1  in modules linphone and belle-sip. Can any one please help in resolving these?
