### ISSUE TITLE
Qt5 not working when installing linphone remotely (using xrdp)

### ISSUE THREAD

**Issue by elangarika** [BelledonneCommunications/linphone-desktop#223]
Hi,
I want to install linphone-desktop on a remote ubuntu 16.04 Virtual Machine.
I have tried to build linphone-desktop from the sources. README says install Qt5 first... I tried but it´s interactive so I had to install xrdp. 
The error I am getting is QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server

**Comment by Wescoeur** [comment]
Sorry but it's not related to linphone-desktop. When does this error occur?

**Comment by elangarika** [comment]
Qt5 is a pre-reqiurement to build linphone-desktop as indicated in the README... and it requires a graphical environment
The error occurs when I try to bulid linphone-desktop and since it is in a virtual machine I had to use Remote Desktop. 
I managed to start QtControl by using VNC but the keyboard is sitll very weird on Qt application while it´s ok in the rest of the ubuntu applications.
