### ISSUE TITLE
Linphone Thunderbird Plugin

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-desktop#226]
Would you please create a "Linphone Thunderbird Plugin" add-on and make it available at ATN?
https://addons.thunderbird.net/

FYI there is a "Zoiper Thunderbird Plugin" add-on.
https://addons.thunderbird.net/thunderbird/addon/zoiper-thunderbird-plugin/

Thank you

**Comment by calllib** [comment]
Yes, this would be cool! Why should I copy my contacts over to Linphone?

**Comment by julonexus** [comment]
Linphone Desktop supports URI handlers (sip,sips,callto,tel). You can use a module that do the redirection for you, (like [that](https://addons.thunderbird.net/fr/thunderbird/addon/tbdialout/). I didn't try it, this is just an example)
