### ISSUE TITLE
install target

### ISSUE THREAD

**Issue by llemtt** [BelledonneCommunications/linphone-desktop#227]
Hi,

sudo make install

returns

make: *** No rule to make target 'install'.  Stop.

How do I install after compiling "no-ui" target?

**Comment by rexy712** [comment]
You have to manually copy the files over to your system. I've messed up my system by installing it to '/usr/local' before, so I always go with an alternate directory. I would suggest putting the contents of 'OUTPUT/desktop' in '/opt/linphone' to ensure you dont overwrite any system files. Especially if you ran prepare.sh without the -sys option. Setting it up in /opt does have some complications though.

This installs it to /opt and sets permissions:
```
sudo rsync -rzavh OUTPUT/desktop/ /opt/linphone/
sudo chown -R root:root /opt/linphone
```

Then I add a wrapper for each of the executables I want (linphone, linphonec, and linphonecsh) which specifies where the linphone libraries are:

Save this to /usr/local/bin/linphone, replacing the name with the desired target's name.
```
#!/bin/sh

#replace /opt/linphone/bin/linphone with whichever executable you want
LD_LIBRARY_PATH=/opt/linphone/lib64 /opt/linphone/bin/linphone
```

Now you can just run `linphone` from the terminal to launch it (as long as /usr/local/bin in in your PATH). Repeat for any other desired linphone executables.

**Comment by llemtt** [comment]
Many thanks!

The wrappers were my missing step...
