### ISSUE TITLE
Toolchain is unable to link executables in mac 

### ISSUE THREAD

**Issue by deepak2503** [BelledonneCommunications/linphone-desktop#228]
I was compiling Linphone-desktop in mac using ./prepare.py -DENABLE_DOC=OFF which is successfull but when i do make it  i am getting this "Toolchain is unable to link executables in mac " when it comes to EP_VPX.
![screen shot 2018-10-11 at 10 43 44 am](https://user-images.githubusercontent.com/16147783/46782183-ddf29b80-cd42-11e8-8f66-89d0f56ffa79.png)

Do anyone know how can i overcome from this?? 
Plesae!!!!

**Comment by sky1987a** [comment]
Same problem

**Comment by sky1987a** [comment]
I solved with -DENABLE_VPX=NO

**Comment by deepak2503** [comment]
Thanks, It worked. But after i do make an it succeeded, there is no Xcode project file which i can open and run the code. Can you tell if i am missing anything.

**Comment by arjun011** [comment]
Same problem. 
Can you please guide how to resolve ?
