### ISSUE TITLE
Compile issue after last commit

### ISSUE THREAD

**Issue by TomasAndersen** [BelledonneCommunications/linphone-desktop#23]
In submodules/linphone/coreapi/lpconfig.c:524:2: error: ‘bctbx_level’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  bctbx_logv(BCTBX_LOG_DOMAIN, bctbx_level,fmt,list);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Does anyone know how to fix this?

**Comment by TomasAndersen** [comment]
I just added a default statement to the switch statement.. but should be fixed in master.

**Comment by Viish** [comment]
It has been fixed in linphone master branch, thanks.
