### ISSUE TITLE
Error in vo-amrwbenc trying to compile from sources

### ISSUE THREAD

**Issue by frealgagu** [BelledonneCommunications/linphone-desktop#233]
The following is happenning to me trying to compile in archlinux using 

  ./prepare.py -c
  ./prepare.py --all-codecs
  make

[ 72%] Building C object CMakeFiles/vo-amrwbenc.dir/amrwbenc/src/q_pulse.c.o
/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/linphone-sdk/external/vo-amrwbenc/amrwbenc/src/q_pulse.c: In function ‘quant_4p_4N’:
/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/linphone-sdk/external/vo-amrwbenc/amrwbenc/src/q_pulse.c:191:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__unused’
  Word16 nb_pos, mask __unused, n_1, tmp;
                      ^~~~~~~~
/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/linphone-sdk/external/vo-amrwbenc/amrwbenc/src/q_pulse.c:195:2: error: ‘n_1’ undeclared (first use in this function)
  n_1 = (Word16) (N - 1);
  ^~~
/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/linphone-sdk/external/vo-amrwbenc/amrwbenc/src/q_pulse.c:195:2: note: each undeclared identifier is reported only once for each function it appears in
/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/linphone-sdk/external/vo-amrwbenc/amrwbenc/src/q_pulse.c:197:2: error: ‘mask’ undeclared (first use in this function)
  mask = vo_sub((1 << N), 1);              /* mask = ((1<<N)-1); */
  ^~~~
/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/linphone-sdk/external/vo-amrwbenc/amrwbenc/src/q_pulse.c:215:4: error: ‘tmp’ undeclared (first use in this function)
    tmp = vo_sub((N << 2), 3);           /* index = 1 << ((4*N)-3); */
    ^~~
make[6]: *** [CMakeFiles/vo-amrwbenc.dir/build.make:518: CMakeFiles/vo-amrwbenc.dir/amrwbenc/src/q_pulse.c.o] Error 1
make[6]: Leaving directory '/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/Build/voamrwbenc'
make[5]: *** [CMakeFiles/Makefile2:73: CMakeFiles/vo-amrwbenc.dir/all] Error 2
make[5]: Leaving directory '/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/Build/voamrwbenc'
make[4]: *** [Makefile:130: all] Error 2
make[4]: Leaving directory '/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/Build/voamrwbenc'
make[3]: *** [CMakeFiles/EP_voamrwbenc.dir/build.make:114: /ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/Stamp/EP_voamrwbenc/EP_voamrwbenc-build] Error 2
make[3]: Leaving directory '/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/cmake'
make[2]: *** [CMakeFiles/Makefile2:447: CMakeFiles/EP_voamrwbenc.dir/all] Error 2
make[2]: Leaving directory '/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/cmake'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Leaving directory '/ArchLinux/linphone-desktop-all-git/src/linphone-desktop/WORK/desktop/cmake'
make: *** [Makefile:14: desktop-build] Error 2

Thanks in advance.

**Comment by rexy712** [comment]
A workaround is to run this sed command from the base directory of the repo:
`sed -e 's/__unused//' -i linphone-sdk/external/vo-amrwbenc/amrwbenc/src/q_pulse.c`
