### ISSUE TITLE
Flatpack definition files

### ISSUE THREAD

**Issue by arthurlogilab** [BelledonneCommunications/linphone-desktop#238]
While investigating a network problem with a flatpack installation of linphone we can across a report from a VLC user that pointed to the configuration of VLC for flatpack https://github.com/endlessm/vlc-flatpak/blob/master/org.videolan.VLC.json

We were wondering where is the equivalent file for linphone-desktop ? Should it be in this repo ?

**Comment by arthurlogilab** [comment]
@julonexus thanks for taking a look at this, is the issue closed as in "wontfix" or it's been fixed ?

**Comment by julonexus** [comment]
I'm sorry but it is closed as won't fix. We doesn't support Flatpak anymore
