### ISSUE TITLE
Creating an Installer.

### ISSUE THREAD

**Issue by amitiyer** [BelledonneCommunications/linphone-desktop#239]
Hello All.

I have successfully built the code now i want to create an Installer of the package, Can anyone let me know how can i do it ?

**Comment by Wescoeur** [comment]
If you want to generate a package, it's necessary to use the -p flag with the prepare.py command.

**Comment by amitiyer** [comment]
I have used the -p flag in the prepare.py command to generate the installer package but when i build, i receive a lot of errors and the build fails.
