### ISSUE TITLE
libbctoolbox.so.1: undefined reference to `bctbx_clean'

### ISSUE THREAD

**Issue by HamletGhost** [BelledonneCommunications/linphone-desktop#240]
I am in a configuration where neither `POLARSSL` nor `MBEDTSL` are "FOUND". I have little idea of what that means, but since CMake let me get away with it, I suppose it's a supported configuration.

In these conditions, `linphone-sdk/bctoolbox/src/CMakeLists.txt` does not include `crypto/crypto.c` in the compilation of `bctoolbox` library. Unfortunately, the same `CMakeLists.txt` also unconditionally includes `crypto/ecc.cc`, which requires `bctbx_clean()` from the aforementioned `crypto/crypto.c`. Hence the linker error in the subject.
I have no idea which the correct solution is (not to compile `ecc.cc`? push `crypto.c` unconditionally in? require either `POLARSSL` or `MBEDTSL`?).

Environment: Gentoo Linux, GCC 8.2.0; HEAD: `780516e`

**Comment by Wescoeur** [comment]
Thank you for your report. You must install polarssl or mbedtls on your system to compile linphone-desktop.
But there is a real problem with the CMakeLists.txt, the library should compile with or without crypto library.

**Comment by Wescoeur** [comment]
Fixed.
