### ISSUE TITLE
Error executing linphonec

### ISSUE THREAD

**Issue by frealgagu** [BelledonneCommunications/linphone-desktop#241]
Hi, the following is happening to me trying to execute linphonec:

    2018-11-18 19:03:16:987 belr-error-Could not load grammar vcard_grammar because the file could not be located.
    2018-11-18 19:03:16:988 bctbx-fatal-Unable to load VCARD grammar.
    Aborted (core dumped)

Compilation and installation were succesfull, but I don't know why this is happening.

**Comment by Wescoeur** [comment]
What is your OS? And what's your commit?

**Comment by anders9ustafsson** [comment]
@Wescoeur This is a problem when installing the latest Linphone Desktop from snapshots, 4.1.1-663-g4a43f00, and trying to run *linphonec* from the command line for example.

**Comment by kpatil001** [comment]
Hi, I am facing same problem too, is there any sort of solution for this?

**Comment by neutrino38** [comment]
> Hi, I am facing same problem too, is there any sort of solution for this?

Make sure you bundle the three following files with your app:

- grammars\cpim_grammar
- grammars\vcard_grammar
- grammars\identity_grammar

And beware of the working directory when you initialize the stack.

**Comment by RussellGee** [comment]
> > Hi, I am facing same problem too, is there any sort of solution for this?
> 
> Make sure you bundle the three following files with your app:
> 
>     * grammars\cpim_grammar
> 
>     * grammars\vcard_grammar
> 
>     * grammars\identity_grammar
> 
> 
> And beware of the working directory when you initialize the stack.

Hi，I have the same problem，could you descripe detail your slution？Thank you in advance

**Comment by jfalexvijay** [comment]
Any solution for this issue?

**Comment by greless** [comment]
I can't solve it

**Comment by raphael4550** [comment]
I have the same problem.
```
BELR_GRAMMAR_PATH: /home/buspas/VOIP/SDK/linphone-sdk/desktop/share/belr/grammars
2024-06-27 11:14:21:022 belr-error- Could not load grammar vcard_grammar because the file could not be located.
2024-06-27 11:14:21:022 bctbx-fatal- Unable to load VCARD grammar.
Aborted (core dumped)
```

```
$ ls /home/buspas/VOIP/SDK/linphone-sdk/desktop/share/belr/grammars
belr-grammar-example.blr  cpim_grammar  ics_grammar  identity_grammar  mwi_grammar  sdp_grammar  vcard_grammar
```
