### ISSUE TITLE
Make a Call from CLI didn't work anymore since Upgrade to linphone4

### ISSUE THREAD

**Issue by boospy** [BelledonneCommunications/linphone-desktop#246]
Hello and nice evening :) 

we compiled actual version from Linphone4 and build an DEB Packages for Ubuntu 18.04. Works really fine! But one importend feature we are missing now. We use linphone in the office on the computers, notebooks to make calls directly from KDE's Kontact. We used this execusion with linphone 3.6. Since 4.x this didn't work anymore. Here are the command:

`linphone -c "$(echo '0%N' | sed 's/ //')"`

So is there someting new to get this work again? 
Thanks a lot and best Regards here all from us. 

If anyone is interested, here is our DEB package ... Dependencies have not yet been tested and installed. Run on KDE Neon 18.04.

https://apt.iteas.at/
`apt install linphone4`

**Comment by Wescoeur** [comment]
The syntax is different now. You can initiate a call with: ```linphone "call sip-address=test@sip.linphone.org"```.

**Comment by boospy** [comment]
Thanks a lot, it is working fine!!! Here are the entry for KDE's Kontact: 
`linphone "call sip-address=$(echo '0%N' | sed 's/ //')" `

**Comment by boospy** [comment]
Hello, last day I've updated my deb packages with information from hiere: https://github.com/BelledonneCommunications/linphone-desktop/issues/227#issuecomment-437405007 

So now i get this error's if i would like to make a call via cli:

```
[11:02:40:145][0x5618451aad50][Info]"Starting Linphone (bin: linphone)"
[11:02:40:145][0x5618451aad50][Info]"Use locale: de_DE"
[11:02:40:147][0x5618451aad50][Info]"Destroying app..."
```
What i'am doing wrong?

**Comment by Wescoeur** [comment]
It's not an error. You have executed a second linphone desktop instance and your command has been sent to the first.

For example:

``` 
# Second shell:
> linphone "call sip-address=sip:test@sip.linphone.org"
[16:16:24:493][0x602000000390][Info]app/App.cpp:210: "Starting Linphone (bin: linphone)"
[16:16:24:493][0x602000000390][Info]app/App.cpp:211: "Use locale: en_US"
[16:16:24:532][0x602000000390][Info]app/App.cpp:215: "Destroying app..."
```
```
# First shell:
[16:16:24:526][0x602000000390][Info]app/App.cpp:270: "Received command from other application: `call sip-address=sip:test@sip.linphone.org`."
[16:16:24:527][0x602000000390][Info]app/cli/Cli.cpp:360: "Detecting cli command: `call sip-address=sip:test@sip.linphone.org`..."
[16:16:24:528][0x602000000390][Info]app/cli/Cli.cpp:280: "Execute command:" QHash(("sip-address", "sip:test@sip.linphone.org"))
```

**Comment by boospy** [comment]
Found the solution: 

`export LD_LIBRARY_PATH=/opt/linphone/lib && /opt/linphone/bin/linphone "call sip-address=$(echo '0%N' | sed 's/ //')"`

**Comment by sw-Oldeu** [comment]
Hi @boospy ,

I had a little script for twinkle handling callto and tel links from Thunderbird plugin CardBook and Firefox. Thanks to your help I adjustet it for your Ubuntu package. Here is what I got.

First create a script in /usr/local/bin/mycallto:

```bash
#!/bin/sh
#
# Firefox will call mycallto like this:  mycallto callto:+41812528006
# CardBook uses tel links mycallto tel:+41812528006
# https://github.com/BelledonneCommunications/linphone-desktop/issues/246
export LD_LIBRARY_PATH=/opt/linphone/lib
number=`echo "$1" | sed 's/callto:\|tel://'`
exec /opt/linphone/bin/linphone "call sip-address=$number"
```
Configure Firefox to open callto links with your script. Same in  Cardbook.

I'm not an expert but I hope that this is helpful. Wouldn' t mind me if you have some extra tips :smiley:

Regards

**Comment by lipunis** [comment]
/usr/bin/flatpak run --branch=4.1.1 --arch=x86_64 --command=linphone --file-forwarding com.belledonnecommunications.linphone @@u %u @@   это в моем меню KDE NEON. Перепробовал все варианты, как должно быть у меня?
Заранее благодарен
