### ISSUE TITLE
ffmpeg Module Error can't build

### ISSUE THREAD

**Issue by DanishOmerSuri** [BelledonneCommunications/linphone-desktop#247]
Hello everyone,

While I am running command "python prepare.py -DENABLE_FFMPEG=NO" linphone source build is succeeded but while running application video is not working, when I click on video button my application has crashed and quit.

And If I run command "python prepare.py -DENABLE_FFMPEG=YES" so build failed and giving cmd.exe error on ffmpeg module and other modules.

Help in this context will be appreciated. Thanks in Advance

Regards
Danish Omer Suri

**Comment by Wescoeur** [comment]
What is your platform?

**Comment by DanishOmerSuri** [comment]
Hi Wescoeur,

Thank you for your consideration I am making build on windows 10 using visual studio 2015 and having Qt 5.9.0 and also all dependencies are on 32-bit architecture. I will be very thankful to you.

Regards
Danish Omer Suri

**Comment by Wescoeur** [comment]
I have no issues with the last commit on the master branch (Windows 10/Visual Studio 2015). What is your commit? And could you give me your full log? Thank you.

**Comment by DanishOmerSuri** [comment]
I cloned the latest commit it doing 30 succeeded and 6 failed. The logs has provided in the text file. The errors are in the end of the file. Thank You

Regards
Danish Omer Suri

[logs with latest commet-473f893.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/2674924/logs.with.latest.commet-473f893.txt)

**Comment by DanishOmerSuri** [comment]
> 
> 
> I have no issues with the last commit on the master branch (Windows 10/Visual Studio 2015). What is your commit? And could you give me your full log? Thank you.

hi @Wescoeur 

can you tell me the versions of the following which you used for compilation: 
MinGW
NSIS
CMake
Qt
Python

Regards
Danish Omer Suri

**Comment by Wescoeur** [comment]
Sorry, concerning the logs could you send me the `prepare.py` output? Clean with the `-c` option before. Thank you.

For your questions:
- C compiler GNU 6.3.0
- CXX compiler GNU 6.3.0
- cmake 3.13.0-rc2
- Qt 5.9, 5.10 and 5.11
- Python 3.7
- NSIS 3.03

**Comment by DanishOmerSuri** [comment]
Thank You for your concern the logs of prepare.py are provided in the text file attached.

[logs prepare.py.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/2689830/logs.prepare.py.txt)

**Comment by pangqystq** [comment]
hi, DanishOmerSuri 

    Has the issue been solved ? how ? could you shared whith me .

    thx!

**Comment by julonexus** [comment]
You need ffmpeg to get video working. It should not be an issue to build it with the current master version of the project. If it is still the case, please open a new Issue
