### ISSUE TITLE
mp3 ringtone are ignored, mkv ringtone exits the app

### ISSUE THREAD

**Issue by Incubatio** [BelledonneCommunications/linphone-desktop#248]
In Preferences > Audio > when changing ringtone:

- mp3 format is not played when previewing, I'm not sure if this is a bug or not.
If it's not supported, it should probably not appear in the file browser.

- the mkv format of the default ringtones is a bit misleading as mkv is well known video standard format.
I actually tried to put an actual mkv file, preview ended up with application crashing:
_(org.linphone.linphone.5044[5483]): Service exited with abnormal code: 139_
After opening the source file of your ringtone sample, I saw the libopus codec was used
I tried to use opus-tools ```opusenc marimba2.wav marimba2.mkv```, trying the mkv in the app crashed again, same error.
I'm not sure how you bake those.

- I finally tried with a wav file, and it worked fine.

**Comment by dominic-p** [comment]
I just ran into this problem myself. I tried a lot of different wav encodings, and nothing worked. After some time I took a look at the included ringtone files with `ffprobe` and found the following:

```
Input #0, wav, from 'oldphone.wav':
  Metadata:
    date            : 2003-08-29
    encoder         : Kwave-0.6.7 pour KDE 3.1.2
  Duration: 00:00:01.77, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
```

I encoded my file as a wav using ffmpeg in PCM signed 16bit little endian (pcm_s16le) and it seems to be working now.

**Comment by julonexus** [comment]
Linphone only supports WAV and MATROSKA format for ringtones.
opusenc gives a ogg container, not a matroska. It's why you cannot use it as a ringtone.
The app should gives this kind of error `Cannot open /run/media/LinuxSeagate/Belledonne/sounds/BASSSolo_InDEAD_Tuning.mp3. Unknown format` but it sould not crash.
