### ISSUE TITLE
Issues While Creating Setup.exe

### ISSUE THREAD

**Issue by amitiyer** [BelledonneCommunications/linphone-desktop#249]
hello i am trying to create a Setup Package, I have used "python prepare.py -G "Visual Studio 14 2015" --package" but the setup.exe does not generate, I have also used "cmake --build WORK\desktop\cmake --config Release" but still the installation package does not get generated, Can anyone please let me know what i am doing wrong here ? Also please do not close this issue like the previous one. I am using Windows 8 Desktop. I am receiving the below error after i use"cmake --build WORK\desktop\cmake --config Release".

> "E:\linphone-desktop_work\WORK\desktop\cmake\ALL_BUILD.vcxproj" (default target
) (1) ->
"E:\linphone-desktop_work\WORK\desktop\cmake\EP_linphone.vcxproj" (default targ
et) (19) ->
"E:\linphone-desktop_work\WORK\desktop\cmake\EP_ms2plugins.vcxproj" (default ta
rget) (28) ->
"E:\linphone-desktop_work\WORK\desktop\cmake\EP_msamr.vcxproj" (default target)
 (29) ->
"E:\linphone-desktop_work\WORK\desktop\cmake\EP_voamrwbenc.vcxproj" (default ta
rget) (31) ->
(CustomBuild target) ->
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(191): error C2146: syntax error: missing ';' before identifier '__unused'
[E:\linphone-desktop_work\WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E
:\linphone-desktop_work\WORK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(191): error C2065: '__unused': undeclared identifier [E:\linphone-desktop_
work\WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_wo
rk\WORK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(191): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(191): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(195): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(196): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(215): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(216): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(218): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(222): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(222): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(223): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(223): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(225): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(228): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(228): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(229): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(229): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(231): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(235): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(236): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(239): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(245): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(246): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(191): error C2146: syntax error: missing ';' before identifier '__unused'
[E:\linphone-desktop_work\WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E
:\linphone-desktop_work\WORK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(191): error C2065: '__unused': undeclared identifier [E:\linphone-desktop_
work\WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_wo
rk\WORK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(191): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(191): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(195): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(196): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(215): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(216): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(218): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(222): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(222): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(223): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(223): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(225): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(228): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(228): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(229): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(229): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(231): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(235): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(236): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(239): error C2065: 'n_1': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(245): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]
  E:\linphone-desktop_work\linphone-sdk\external\vo-amrwbenc\amrwbenc\src\q_pul
se.c(246): error C2065: 'tmp': undeclared identifier [E:\linphone-desktop_work\
WORK\desktop\Build\voamrwbenc\vo-amrwbenc.vcxproj] [E:\linphone-desktop_work\WO
RK\desktop\cmake\EP_voamrwbenc.vcxproj]

    276 Warning(s)
    48 Error(s)

Thanks in advance.

**Comment by DanishOmerSuri** [comment]
Hello @amitiyer 

Have you run 'python prepare.py -G "Visual Studio 14 2015' without using --package and still getting this error? And have you also install NSIS and set the path in environment variable? And can you build the project using Visual Studio 2015 Community Edition not by running cmake command and then send the logs and Error List of Visual Studio. And please make sure the all the dependencies path should be set in windows environment variable. Thank You 

Regards
Danish Omer Suri
