### ISSUE TITLE
EP_linphoneqt : No targets specified and no makefile found.

### ISSUE THREAD

**Issue by ghost** [BelledonneCommunications/linphone-desktop#251]
i build linphone-desktop as one rpm,
in specfile:
git clone https://github.com/BelledonneCommunications/linphone-desktop.git --recursive

%build
cd %{_builddir}/%{name}

./prepare.py -c && ./prepare.py -L desktop -DENABLE_GPL_THIRD_PARTIES=ON -DENABLE_VCARD=ON -DENABLE_NON_FREE_CODECS=ON -DENABLE_G729=ON -DENABLE_NLS=ON -DENABLE_LIME=ON -DENABLE_GSM=ON	-DENABLE_ILBC=ON -DENABLE_SILK=ON -DENABLE_SPEEX=ON -DENABLE_MKV=ON -DENABLE_OPUS=ON -DENABLE_AMRNB=OFF -DENABLE_AMRWB=OFF -DENABLE_H263=ON -DENABLE_MPEG4=ON -DENABLE_OPENH264=ON -DENABLE_VPX=ON -DENABLE_TOOLS=ON -DENABLE_SRTP=ON -DENABLE_ZRTP=ON -DENABLE_VIDEO=ON -DENABLE_WEBRTC_AEC=ON -DENABLE_JPEG=ON -DENABLE_MBEDTLS=ON -DENABLE_FFMPEG=ON

%{expand:%(%cmake . -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=%{install_prefix} -DCMAKE_PREFIX_PATH:PATH=%{install_prefix} -DMAKE_SKIP_INSTALL_RPATH=1 -DENABLE_SHARED=1 -DENABLE_STATIC=0 -DENABLE_UPDATE_CHECK=0 -DENABLE_AMRNB=0 -DENABLE_AMRWB=0 -DENABLE_BV16=1 -DENABLE_CODEC2=0 -DENABLE_CSHARP_WRAPPER=0 -DENABLE_CXX_WRAPPER=1 -DENABLE_DEBUG_LOGS=0 -DENABLE_DOC=0 -DENABLE_FFMPEG=1 -DENABLE_G726=0 -DENABLE_G729=1 -DENABLE_G729B_CNG=0 -DENABLE_GPL_THIRD_PARTIES=1 -DENABLE_GSM=1 -DENABLE_GTK_UI=0 -DENABLE_H263=1 -DENABLE_H263P=0 -DENABLE_ILBC=1 -DENABLE_ISAC=0 -DENABLE_JAVA_WRAPPER=0 -DENABLE_JPEG=1 -DENABLE_LIME=1 -DENABLE_LIME_X3DH=0 -DENABLE_MBEDTLS=1 -DENABLE_MDNS=0 -DENABLE_MKV=1 -DENABLE_MPEG4=1 -DENABLE_NLS=0 -DENABLE_NON_FREE_CODECS=1 -DENABLE_OPENH264=1 -DENABLE_OPUS=1 -DENABLE_PACKAGING=0 -DENABLE_PCAP=0 -DENABLE_POLARSSL=1 -DENABLE_QRCODE=0 -DENABLE_RELATIVE_PREFIX=0 -DENABLE_RTP_MAP_ALWAYS_IN_SDP=0 -DENABLE_SHARED=1 -DENABLE_SILK=1 -DENABLE_SOCI=1 -DENABLE_SOURCE_PACKAGING=0 -DENABLE_SPEEX=1 -DENABLE_SRTP=1 -DENABLE_STATIC_ONLY=0 -DENABLE_STRICT=0 -DENABLE_TESTS=1 -DENABLE_TESTS_COMPONENT=0 -DENABLE_THEORA=0 -DENABLE_TOOLS=1 -DENABLE_TUNNEL=0 -DENABLE_UNIT_TESTS=1 -DENABLE_UNMAINTAINED=0 -DENABLE_UPDATE_CHECK=0 -DENABLE_VCARD=1 -DENABLE_VIDEO=1 -DENABLE_VPX=1 -DENABLE_WEBRTC_AEC=1 -DENABLE_WEBRTC_AECM=0 -DENABLE_WEBRTC_VAD=0 -DENABLE_ZRTP=1)}

%make

%install
.....
--output by build on terminal:
-- Set runtime path of "/repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/lib64/liblinphone++.so.9" to "/repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/lib64:/repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/lib"
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/lib64/liblinphone++.so
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/object.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/event.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/presence_activity.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/tunnel.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/enums.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/nat_policy.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/video_activation_policy.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/account_creator_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/call_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/presence_note.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/call.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/event_log.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/auth_info.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/chat_message.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/search_result.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/error_info.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/core.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/event_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/linphone.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/friend_list_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/call_params.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/chat_message_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/config.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/payload_type.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/xml_rpc_request_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/xml_rpc_request.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/call_log.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/player.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/account_creator.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/presence_person.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/range.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/participant.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/participant_imdn_state.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/chat_room_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/presence_service.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/proxy_config.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/tunnel_config.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/presence_model.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/headers.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/factory.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/magic_search.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/logging_service_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/conference.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/call_stats.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/video_definition.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/player_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/participant_device.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/dial_plan.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/transports.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/xml_rpc_session.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/address.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/buffer.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/core_listener.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/chat_room.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/info_message.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/conference_params.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/content.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/friend_list.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/logging_service.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/friend.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/im_notif_policy.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/include/linphone++/vcard.hh
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/share/LinphoneCxx/cmake/LinphoneCxxTargets.cmake
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/share/LinphoneCxx/cmake/LinphoneCxxTargets-release.cmake
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/share/LinphoneCxx/cmake/LinphoneCxxConfig.cmake
-- Installing: /repm/src/rpm/BUILD/linphone-desktop/OUTPUT/desktop/share/LinphoneCxx/cmake/LinphoneCxxVersion.cmake
make[4]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/Build/linphone'
make[3]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
[ 97%] Completed 'EP_linphone'
make[3]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[2]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
[ 97%] Built target EP_linphone
make[2]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[3]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
Scanning dependencies of target EP_linphoneqt
make[3]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[3]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
[ 98%] Creating directories for 'EP_linphoneqt'
make[3]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[3]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
[ 98%] No download step for 'EP_linphoneqt'
make[3]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[3]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
[ 99%] No patch step for 'EP_linphoneqt'
make[3]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[3]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
[ 99%] No update step for 'EP_linphoneqt'
make[3]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[3]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
[ 99%] Performing configure step for 'EP_linphoneqt'
loading initial cache file /repm/src/rpm/BUILD/linphone-desktop/WORK/desktop//tmp/EP_linphoneqt/EP_linphoneqt-cache-Release.cmake
-- Found Git: /usr/bin/git (found version "2.20.0") 
Optional package TextToSpeech not found.
-- Found Git: /usr/bin/git (found suitable version "2.20.0", minimum required is "1.7.1") 
-- Package file name is linphone-4.1.1-644
-- Configuring done
-- Generating done
-- Build files have been written to: /repm/src/rpm/BUILD/linphone-desktop
make[3]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[3]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
[100%] Forcing build for 'EP_linphoneqt'
make[3]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[3]: Entering directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
[100%] Performing build step for 'EP_linphoneqt'
make[3]: Leaving directory '/repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/cmake'
make[4]: *** No targets specified and no makefile found.  Stop.
make[3]: *** [CMakeFiles/EP_linphoneqt.dir/build.make:116: /repm/src/rpm/BUILD/linphone-desktop/WORK/desktop/Stamp/EP_linphoneqt/EP_linphoneqt-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:1007: CMakeFiles/EP_linphoneqt.dir/all] Error 2
make[1]: *** [Makefile:84: all] Error 2
make: *** [Makefile:14: desktop-build] Error 2
error: Bad exit status from /home/quait/src/tmp/rpm-tmp.CHEprY (%build)

RPM build errors:
    Bad exit status from /home/quait/src/tmp/rpm-tmp.CHEprY (%build)
.....
What's my fault?

**Comment by ohquait** [comment]
if i do:
git clone -b release/4.2 https://github.com/BelledonneCommunications/linphone-desktop.git --recursive

the issue is out

**Comment by ohquait** [comment]
To make it simple to packaging, can we have options to splitt in:
1. **make build** TARGET_PATH=/opt/linphone-desktop # this should also set the rpath to /opt/linphone-desktop in configs and/or cmakes, so all linked binarys/libraries and xxxxxx.pc's have the targeted install-path   
2. **make install** DESTDIR=%{buildroot} # so on rpmbuild 

Please  if i am the fault , excuse me !
