### ISSUE TITLE
Select and copy text in "about" doesn't work

### ISSUE THREAD

**Issue by WPFilmmaker** [BelledonneCommunications/linphone-desktop#253]
**How to reproduce:**
Open "about", try to select text and right click on it or use ctrl+c
**Expected results:**
The whole text (desktop and core is selectable and I can copy and paste it to provide info on the software)
**What happens:**
Selecting text only works one line per time, so you either have "selected desktop" or "core"). Right clicking on it doesn't work and one has to use ctrl+c...not super friendly and I would like to being able to right click..but better than nothing I guess:)
**Version and OS:**
Lubuntu 16.04.3 Linphone 4.1.1 - qt5.9.0 Core 3.12.0

**Comment by julonexus** [comment]
Done
