### ISSUE TITLE
Noticeable echo during videocalls

### ISSUE THREAD

**Issue by WPFilmmaker** [BelledonneCommunications/linphone-desktop#254]
**How to reproduce:**
Just make a videocall with echo cancellation enabled
**Expected results:**
Echo doesn't affect the videocall
**What happens:**
There is a noticeable echo in the voice on both sides. #48 was closed but I still experienced it
**Version and OS:**
One caller on Lubuntu 16.04.3 Linphone 4.1.1 - qt5.9.0 Core 3.12.0 the other on Lubuntu 18.04 Linphone 4.1.1 - qt5.9.0 Core 3.12.0.

**Comment by dyslesiq** [comment]
A fix has been made (https://github.com/BelledonneCommunications/mediastreamer2/commit/3f4531f8b7c08f53536d7641ae93ea9ebbdb330f). It should be available in desktop application soon.
