### ISSUE TITLE
linphone-desktop compile issue

### ISSUE THREAD

**Issue by vinodmn** [BelledonneCommunications/linphone-desktop#26]
I am getting these errors. After the latest update.. Is there any configuration need to be done in the visual-studio, I am using visual-studio-2012.
 
**Error MSB6006 "cmd.exe" exited with code 2. EP_ffmpeg C:\ProgramFiles(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets 172
	
Error MSB6006 "cmd.exe" exited with code 1. EP_bctoolbox	 C:\ProgramFiles(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets 172	

Error MSB6006 "cmd.exe" exited with code 1.	EP_belr	  C:\ProgramFiles(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets 172	

Error MSB6006 "cmd.exe" exited with code 1.	EP_bzrtp
C:\Program Files(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets 172	

Error MSB6006 "cmd.exe" exited with code 1.	EP_ortp	
C:\Program Files(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets 172	

Error MSB6006 "cmd.exe" exited with code 1.	EP_bellesip
C:\Program Files(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets 172	
	
Error MSB6006 "cmd.exe" exited with code 1.	EP_belcard	
C:\Program Files(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets 172	
	
Error MSB6006 "cmd.exe" exited with code 1.	EP_ms2	
C:\Program Files(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets 172	

Error MSB6006 "cmd.exe" exited with code 1.	EP_linphone	
C:\Program Files(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets 172

**Comment by Wescoeur** [comment]
The Linphone desktop project has been updated in 4.0. (New app code.)
This compilation error is obsolete now.
