### ISSUE TITLE
The application does not detect that a new audio device has been connected / disconnected

### ISSUE THREAD

**Issue by daniel-ImpacTech** [BelledonneCommunications/linphone-desktop#267]
# Bug: The application does not detect that a new audio device has been connected / disconnected
When a new audio device is connected, it does not appear in the audio section of the settings unless I restart the application. And when a audio device is disconnected, it still appears in the audio section of the settings unless I restart the application again.
Please fix this

**Comment by julonexus** [comment]
Resolved in current snapshot version
