### ISSUE TITLE
I don't find G729 codec on version 4.1.1

### ISSUE THREAD

**Issue by thiagopeixoto16** [BelledonneCommunications/linphone-desktop#270]
This is my version:
![image](https://user-images.githubusercontent.com/4227271/52664417-1b815400-2ef0-11e9-88ac-5441eb1b81a5.png)

There is no G.729:
![image](https://user-images.githubusercontent.com/4227271/52664459-3d7ad680-2ef0-11e9-845f-22ecd5f96fea.png)

**Comment by dletruong** [comment]
I have this same issue. Using the same version, no G729 option.

**Comment by julonexus** [comment]
[Commit](https://gitlab.linphone.org/BC/public/linphone-cmake-builder/commit/b8b5a3cd82fa42c0bf0127222007fc0e52611f45)
You have to use the last version in snapshots or wait till the next release.
