### ISSUE TITLE
Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”exited with code 1

### ISSUE THREAD

**Issue by zakruby** [BelledonneCommunications/linphone-desktop#273]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”exited with code 1. [F:\LinP
hone\linphone-desktop\WORK\desktop\cmake\EP_linphone.vcxproj]

**Comment by Sina-KH** [comment]
I have the same problem; as you closed this issue, any idea how to fix it?
