### ISSUE TITLE
Cannot prepare project in windows 10

### ISSUE THREAD

**Issue by sonyraj** [BelledonneCommunications/linphone-desktop#275]
I am not able to run prepare.py in windows 10. Installed all dependencies and this is the output

cmake E:\LinphoneSource\linphone-desktop\linphone-sdk\cmake-builder -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=E:/LinphoneSource/linphone-desktop/OUTPUT/desktop -DCMAKE_INSTALL_PREFIX=E:/LinphoneSource/linphone-desktop/OUTPUT/desktop -DCMAKE_NO_SYSTEM_FROM_IMPORTED=YES -DLINPHONE_BUILDER_WORK_DIR=E:\LinphoneSource\linphone-desktop/WORK/desktop -DCMAKE_INSTALL_MESSAGE=LAZY -DLINPHONE_BUILDER_CONFIG_FILE=configs/config-desktop.cmake -DLINPHONE_BUILDER_EXTERNAL_SOURCE_PATH=E:/LinphoneSource/linphone-desktop/linphone-sdk -DLINPHONE_BUILDER_ALTERNATE_EXTERNAL_SOURCE_PATH=E:/LinphoneSource/linphone-desktop/submodules -DLINPHONE_BUILDER_EXTERNAL_BUILDERS_PATH=E:\LinphoneSource\linphone-desktop\cmake_builder -DLINPHONE_BUILDER_TARGET=linphoneqt -DENABLE_DOC=OFF
-- The C compiler identification is MSVC 19.16.27030.1
-- The CXX compiler identification is MSVC 19.16.27030.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using configuration file 'E:/LinphoneSource/linphone-desktop/linphone-sdk/cmake-builder/configs/config-desktop.cmake'
-- Including external builders from E:/LinphoneSource/linphone-desktop/cmake_builder
-- Found PythonInterp: C:/Users/Quiits/AppData/Local/Programs/Python/Python37-32/python.exe (found version "3.7.3")
-- Installing windows tools
-- Up-to-date: E:/LinphoneSource/linphone-desktop/OUTPUT/desktop/include/MSVC/inttypes.h
-- Up-to-date: E:/LinphoneSource/linphone-desktop/OUTPUT/desktop/include/MSVC/stdint.h
-- Including builder linphoneqt
-- Including builder linphone
-- Including builder bctoolbox
-- Including builder mbedtls
-- Including builder bcunit
-- Including builder bellesip
-- Including builder zlib
-- Including builder ortp
-- Including builder ms2
-- Including builder gsm
-- Including builder opus
-- Including builder speex
-- Including builder bv16
-- Including builder turbo-jpeg
-- Including builder ffmpeg
-- Including builder vpx
CMake Error at builders/vpx.cmake:79 (file):
  file failed to open for reading (No such file or directory):

    E:/LinphoneSource/linphone-desktop/WORK/desktop/cmake/windowsenv_path.txt
Call Stack (most recent call first):
  cmake/CMakeLists.txt:257 (include)
  cmake/CMakeLists.txt:272 (linphone_builder_include_builder)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:226 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:232 (lcb_declare_target)
  builders/CMakeLists.txt:71 (lcb_declare_targets)
  configs/config-desktop-common.cmake:91 (include)
  configs/config-desktop.cmake:29 (include)
  CMakeLists.txt:65 (include)

CMake Error at builders/vpx.cmake:89 (file):
  file failed to open for reading (No such file or directory):

    E:/LinphoneSource/linphone-desktop/WORK/desktop/cmake/windowsenv_include.txt
Call Stack (most recent call first):
  cmake/CMakeLists.txt:257 (include)
  cmake/CMakeLists.txt:272 (linphone_builder_include_builder)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:226 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:232 (lcb_declare_target)
  builders/CMakeLists.txt:71 (lcb_declare_targets)
  configs/config-desktop-common.cmake:91 (include)
  configs/config-desktop.cmake:29 (include)
  CMakeLists.txt:65 (include)

CMake Error at builders/vpx.cmake:90 (file):
  file failed to open for reading (No such file or directory):

    E:/LinphoneSource/linphone-desktop/WORK/desktop/cmake/windowsenv_lib.txt
Call Stack (most recent call first):
  cmake/CMakeLists.txt:257 (include)
  cmake/CMakeLists.txt:272 (linphone_builder_include_builder)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:226 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:232 (lcb_declare_target)
  builders/CMakeLists.txt:71 (lcb_declare_targets)
  configs/config-desktop-common.cmake:91 (include)
  configs/config-desktop.cmake:29 (include)
  CMakeLists.txt:65 (include)

CMake Error at builders/vpx.cmake:91 (file):
  file failed to open for reading (No such file or directory):

    E:/LinphoneSource/linphone-desktop/WORK/desktop/cmake/windowsenv_libpath.txt
Call Stack (most recent call first):
  cmake/CMakeLists.txt:257 (include)
  cmake/CMakeLists.txt:272 (linphone_builder_include_builder)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:317 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:226 (linphone_builder_add_builder_to_target)
  cmake/CMakeLists.txt:232 (lcb_declare_target)
  builders/CMakeLists.txt:71 (lcb_declare_targets)
  configs/config-desktop-common.cmake:91 (include)
  configs/config-desktop.cmake:29 (include)
  CMakeLists.txt:65 (include)

-- Including builder matroska2
-- Including builder srtp
-- Including builder bzrtp
-- Including builder xml2
-- Including builder sqlite3
-- Including builder ms2plugins
-- Including builder mswebrtc
-- Including builder mswasapi
-- Including builder belr
-- Including builder libxsd
-- Including builder xerces
-- Including builder soci
-- Including builder belcard
-- Including builder minizip
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: C:/Strawberry/c/bin/gcc.exe
-- Check for working C compiler: C:/Strawberry/c/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Strawberry/c/bin/g++.exe
-- Check for working CXX compiler: C:/Strawberry/c/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: E:/LinphoneSource/linphone-desktop/WORK/desktop/cmake/Autotools
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

-- Enabled features:
 * Unit tests, Enable unit tests support with BCUnit library.
 * CXX wrapper, Build the C++ wrapper for Liblinphone.
 * VCARD, Enable vCard 4 support in Linphone and Liblinphone.
 * Mbedtls, Crypto stack implementation based on mbeddtls.
 * GPL third parties, Usage of GPL third-party code (FFmpeg and x264).
 * SRTP, SRTP media encryption support.
 * ZRTP, ZRTP media encryption support.
 * WebRTC AEC, WebRTC echo canceller support.
 * WASAPI, Windows Audio Session API (WASAPI) sound card support.
 * GSM, GSM audio encoding/decoding support.
 * OPUS, OPUS audio encoding/decoding support.
 * Speex, Speex audio encoding/decoding support.
 * BV16, BroadVoice 16 audio encoding/decoding support.
 * Video, Ability to capture and display video.
 * jpeg, JPEG support with libjpeg-turbo.
 * FFmpeg, Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
 * MKV, MKV playing and recording support.
 * VPX, VPX (VP8) video encoding/decoding support.

-- Disabled features:
 * Theora, Theora video encoding/decoding support.
 * Static only, Enable compilation of libraries in static mode.
 * Packaging, Enable packaging
 * Source packaging, Enable source packaging
 * Debug logs, Enable debug level logs in libinphone and mediastreamer2.
 * Doc, Enable documentation generation with Doxygen and Sphinx
 * SOCI, Enable SOCI support.
 * Tools, Enable tools binary compilation.
 * unmaintained, Allow inclusion of unmaintained code in the build.
 * GTK UI, Enable the GTK user interface of Linphone.
 * CSharp wrapper, Build the C# wrapper from Liblinphone.
 * Java wrapper, Build the Java wrapper from Liblinphone.
 * LIME, Enable Linphone IM Encryption support in  Liblinphone.
 * LIME X3DH, Enable Linphone IM Encryption version 2 support in  Liblinphone.
 * NLS, Enable internationalization of Linphone and Liblinphone.
 * Update Check, Enable update check.
 * Polarssl, Crypto stack implementation based on polarssl.
 * Tunnel, Secure tunnel for SIP/RTP (require license).
 * RTP Map always in SDP, Always include rtpmap in SDP.
 * mDNS, Multicast DNS support
 * Non free codecs, Allow inclusion of non-free codecs in the build.
 * WebRTC AECM, WebRTC echo canceller for mobile support.
 * AMRNB, AMR narrow-band audio encoding/decoding support (require license).
 * AMRWB, AMR wide-band audio encoding/decoding support (require license).
 * Codec2, Codec2 audio encoding/decoding support.
 * G729, G.729 audio encoding/decoding support.
 * G729B CNG, G.729 annex B confort noise generation.
 * G726, G.726 audio encoding/decoding support.
 * iLBC, iLBC audio encoding/decoding support.
 * ISAC, ISAC audio encoding/decoding support.
 * Silk, Silk audio encoding/decoding support.
 * WebRTC VAD, WebRTC voice activation detector support.
 * qrcode, QRCode support with zxing.
 * H263, H263 video encoding/decoding support (require license).
 * H263p, H263+ video encoding/decoding support (require license).
 * MPEG4, MPEG4 video encoding/decoding support (require license).
 * OpenH264, H.264 video encoding/decoding support with the openh264 library (require license).
 * X264, H.264 video encoding support with the x264 library (require license).
 * PCAP, PCAP support.

-- Configuring incomplete, errors occurred!
See also "E:/LinphoneSource/linphone-desktop/WORK/desktop/cmake/CMakeFiles/CMakeOutput.log".

**Comment by milon19** [comment]
I got same issue. Any solution?

**Comment by joseph60** [comment]
i created the blank files with the required names.now i got a new error:
CMake Error at builders/vpx.cmake:89 (string):
string sub-command SUBSTRING require four arguments.

**Comment by FGIR13840** [comment]
Hi, I got the same issue on windows 7 / VisualStudio 2019.
Please, where can I find a solution ?

**Comment by julonexus** [comment]
@joseph60 it's because your files are blank. You can remove the lines about VPX_ENV_PATH and VPX_ENV_PATH_LIST. In fact, your PATH should be already set so these steps are useless.

**Comment by FGIR13840** [comment]
Thanks a lot !
In builders/vpx.cmake file, I comment lines 79 to 97 and build starts now

**Comment by FGIR13840** [comment]
...but build stops with these errors :

    Génération du projet "D:\projets\AGS\RetD\Telephonie\linphone\linphone-desktop\build\WORK\desktop\EP_vpx.vcxproj" terminée (cibles par défaut) -- ÉCHEC.
    Génération du projet "D:\projets\AGS\RetD\Telephonie\linphone\linphone-desktop\build\WORK\desktop\EP_ms2.vcxproj" terminée (cibles par défaut) -- ÉCHEC.
...
    Génération du projet "D:\projets\AGS\RetD\Telephonie\linphone\linphone-desktop\build\WORK\desktop\EP_openh264.vcxproj" terminée (cibles par défaut).
    Génération du projet "D:\projets\AGS\RetD\Telephonie\linphone\linphone-desktop\build\WORK\desktop\EP_msopenh264.vcxproj" terminée (cibles par défaut) -- ÉCHEC.
    Génération du projet "D:\projets\AGS\RetD\Telephonie\linphone\linphone-desktop\build\WORK\desktop\EP_ms2plugins.vcxproj" terminée (cibles par défaut) -- ÉCHEC.
    Génération du projet "D:\projets\AGS\RetD\Telephonie\linphone\linphone-desktop\build\WORK\desktop\EP_linphone.vcxproj" terminée (cibles par défaut) -- ÉCHEC.
    Génération du projet "D:\projets\AGS\RetD\Telephonie\linphone\linphone-desktop\build\WORK\desktop\ALL_BUILD.vcxproj" terminée (cibles par défaut) -- ÉCHEC.

It seems EP_openh264 compilation is OK and all other mentionned failed.
Please, can you help me ?
Or do I open another issue ?
