### ISSUE TITLE
cannot compil for raspberry ?

### ISSUE THREAD

**Issue by todely** [BelledonneCommunications/linphone-desktop#276]
Hello,

Please does someone can tell my exactly how i can compil linphone-desktop (version 4) on raspberry (raspbian) ?

Thanks ! Thanks ! Thanks !

**Comment by dyslesiq** [comment]
See this wiki page for building and running raspberry : https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Linphone%20and%20Raspberry%20Pi/
