### ISSUE TITLE
Despite disabling ICE linphone keeps sending ice candidates in sdp

### ISSUE THREAD

**Issue by babakyakhchali** [BelledonneCommunications/linphone-desktop#277]
Hi
I'm using linphone desktop on win 10 with freeswitch as my server. Even if I disable ice in preferences->network linphone keeps enabling it as I see in sdp:

o=FreeSWITCH 1554764956 1554764957 IN IP4 192.168.2.213
s=FreeSWITCH
c=IN IP4 192.168.2.213
t=0 0
a=msid-semantic: WMS S1z5rzTybVdS22xD5ArWayVrQ9xI7VQP
m=audio 29118 RTP/AVP 96 101
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:101 telephone-event/48000
a=fmtp:101 0-16
a=ptime:20
a=sendrecv
a=ice-ufrag:eS7ehSwXRTwPFcui
a=ice-pwd:i5dOqxmvTCu8hVjlEgqLYMzG
a=candidate:3019278166 1 udp 659136 192.168.2.213 29118 typ host generation 0
a=candidate:3019278166 2 udp 659135 192.168.2.213 29119 typ host generation 0
a=end-of-candidates
a=ssrc:1085216818 cname:NgK4GutHfwq8pOBk
a=ssrc:1085216818 msid:S1z5rzTybVdS22xD5ArWayVrQ9xI7VQP a0
a=ssrc:1085216818 mslabel:S1z5rzTybVdS22xD5ArWayVrQ9xI7VQP
a=ssrc:1085216818 label:S1z5rzTybVdS22xD5ArWayVrQ9xI7VQPa0
m=video 21998 RTP/AVP 96
b=AS:1024
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42801F
a=sendrecv
a=rtcp:21999 IN IP4 192.168.2.213
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 ccm tmmbr
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=ssrc:307841077 cname:NgK4GutHfwq8pOBk
a=ssrc:307841077 msid:S1z5rzTybVdS22xD5ArWayVrQ9xI7VQP v0
a=ssrc:307841077 mslabel:S1z5rzTybVdS22xD5ArWayVrQ9xI7VQP
a=ssrc:307841077 label:S1z5rzTybVdS22xD5ArWayVrQ9xI7VQPv0
a=ice-ufrag:DKzGtCqt6Yl09YAs
a=ice-pwd:5EFXwHFlH717UAinaIUuaaO6
a=candidate:9011948855 1 udp 659136 192.168.2.213 21998 typ host generation 0
a=candidate:9011948855 2 udp 659135 192.168.2.213 21999 typ host generation 0
a=end-of-candidates

Am I doing something wrong?
thanks

**Comment by systemcrash** [comment]
See closed issue: 
https://github.com/BelledonneCommunications/linphone-desktop/issues/82

**Comment by tangm421** [comment]
#82  works for me.
my linphone config file located at `C:\Users\Administrator\AppData\Local\linphone\linphonerc` on win10.
