### ISSUE TITLE
Windows7 - Not able to compile linphone-desktop

### ISSUE THREAD

**Issue by FriedrichMax** [BelledonneCommunications/linphone-desktop#278]
Hello,

I'm facing an issue compiling linphone desktop 4.11 on Windows 7.
I tried to compile linphone with Visual Studio 2015, but the following errors occured:

MSB6006	"cmd.exe" wurde mit dem Code 2 beendet.	EP_ffmpeg	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	

MSB6006	"cmd.exe" wurde mit dem Code 1 beendet.	EP_ms2	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171

MSB6006	"cmd.exe" wurde mit dem Code 1 beendet.	EP_mswasapi	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	

MSB6006	"cmd.exe" wurde mit dem Code 1 beendet.	EP_linphone	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	

MSB6006	"cmd.exe" wurde mit dem Code 1 beendet.	EP_mswebrtc	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	

MSB6006	"cmd.exe" wurde mit dem Code 1 beendet.	EP_msopenh264	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	

MSB6006	"cmd.exe" wurde mit dem Code 1 beendet.	EP_linphoneqt	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	

I think the first error with **EP_ffmpeg** is the one to be fixed, and all others occured because of this error.

I used prepare.py with the following command:
python prepare.py -G "Visual Studio 14 2015" -DENABLE_DOC=OFF -DENABLE_DEBUG_LOGS=ON -DENABLE_NON_FREE_CODECS=ON -DENABLE_OPENH264=ON

I used the following versions to compile linphone:
C compiler GNU 6.3.0
CXX compiler GNU 6.3.0
cmake 3.14.2
Qt 5.11
Python 3.7.3

Any help to make it work is appriciated!
Best regards

Max

**Comment by surfrock66** [comment]
I have followed the readme and have not successfully been able to compile linphone-desktop yet.  I wish someone would lay out EXACTLY what they've installed to get this to compile on windows.  It compiles fine on linux, but our call center uses windows and I'm testing adding some functionality they require.

**Comment by calanor** [comment]
The same happens to me. After hours of testing and more testing I can't compile linphone on windows:

prepare.py return an error:
-- Configuring incomplete, errors occurred!
See also "C:/Users/my-user/linphone-desktop/WORK/no-ui/cmake/CMakeFiles/CMakeOutput.log".

but CMakeOutput.log  not explain the reason for the error

**Comment by alsrbaa13** [comment]
i fix prepare.py error but I still have same error. What is the problem?

**Comment by julonexus** [comment]
The build configuration has changed. there is no more python scripts.
