### ISSUE TITLE
Linphone concatenates numbers when calling long numbers

### ISSUE THREAD

**Issue by perparim-m** [BelledonneCommunications/linphone-desktop#28]
Hi,

Linphone concatenates numbers when calling long numbers:

Example from linphonec (version 3.11.1)

linphonec> call +47580013000503
Establishing call id to sip:+4713000503@ourdomian.sip.no, assigned id 1
Contacting sip:+4713000503@ourdomian.sip.no
linphonec> Call 1 to sip:+4713000503@ourdomian.sip.no in progress.
linphonec> Not Found
linphonec> Call 1 with sip:+4713000503@ourdomian.sip.no error.

We can observe the same in the SIP invite sent from the client:
2017/06/01 12:52:14.727244 10.11.12.119:5060 -> XX.XXX.XX.XXX:5060
INVITE sip:+4713000503@ourdomian.sip.no SIP/2.0
Via: SIP/2.0/UDP 10.11.12.119:5060;branch=z9hG4bK.GjlM4qTQm;rport
From: <sip:+47580013000504@ourdomian.sip.no>;tag=dFSZuYvJo
To: sip:+4713000503@ourdomian.sip.no
CSeq: 20 INVITE
Call-ID: qemDEfmtLX
Max-Forwards: 70
Supported: replaces, outbound
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
Content-Type: application/sdp
Content-Length: 622
Contact: <sip:+47580013000504@194.69.215.22:32145;transport=udp>;+sip.instance="<urn:uuid:6188349d-dc77-4460-8db1-09986cab15c9>"
User-Agent: Linphonec/3.11.1 (belle-sip/1.6.1)

v=0
o=+47580013000504 3150 2190 IN IP4 10.11.12.119
s=Talk
c=IN IP4 10.11.12.119
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 7078 RTP/AVP 96 97 0 8 18 101 98
a=rtpmap:96 speex/16000
a=fmtp:96 vbr=on
a=rtpmap:97 speex/8000
a=fmtp:97 vbr=on
a=fmtp:18 annexb=yes
a=rtpmap:101 telephone-event/16000
a=rtpmap:98 telephone-event/8000
a=rtcp-fb:* trr-int 5000
a=rtcp-fb:* ccm tmmbr
m=video 9078 RTP/AVP 96
a=rtpmap:96 VP8/90000
a=rtcp-fb:* trr-int 5000
a=rtcp-fb:* ccm tmmbr
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 nack sli
a=rtcp-fb:96 ack rpsi
a=rtcp-fb:96 ccm fir

Best Regards,
Perparim

**Comment by Wescoeur** [comment]
Have you got the same problem with the last app update?

**Comment by perparim-m** [comment]
I will try it and let you know.

Regards

**Comment by perparim-m** [comment]
Hi,

I've been trying the latest version of the linphone but I've encountered
these difficulties:



Linphone flatpak version is successfully installed on Debian9 (HW:
MinnowBoardTurbot) but I cannot register in the SIP server with my user. If
you choose the next option to add a new SIP account, it is not allowed to
sew the changes that the button is hibernated inactive.



I also tried to compile the linphone-desktop from source and after many
dependency problems with QT5 I managed to compile it in the end. I'm new
with QT and I do not know what to do next with this problem. But now, after
launching the linphone, an error occurs please see the log:



sudo apt-get install extra-cmake-modules qtdeclarative5-dev
qtquickcontrols2-5-dev libqt5svg5-dev qttools5-dev-tools
qml-module-qtquick-dialogs qml-module-qtquick-controls


export Qt5_DIR=/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/cmake


export PATH=/usr/lib/x86_64-linux-gnu/qt5/bin/:$PATH


------------------------------------------------------


velferd@velferd:~/linphone-desktop/OUTPUT/desktop/bin$ ./linphone

[16:10:11:576][0x55d957437980][Info]"Use system locale: en_US"

[16:10:11:891][0x55d957437980][Info]"Running app..."

[16:10:11:893][0x55d9578fb300][Info]"Launch async linphone core creation."

[16:10:12:071][0x55d957437980][Info]"Activated selectors:" ("custom",
"en_US", "unix", "linux", "debian")

[16:10:12:078][0x55d957437980][Info]"Registering types..."

[16:10:12:079][0x55d957437980][Info]"Registering shared types..."

[16:10:12:080][0x55d957437980][Info]"Registering tool types..."

[16:10:12:614][0x55d957437980][Warning]"Errors found in `Notification`
component 2:"
(qrc:/ui/modules/Linphone/Notifications/NotificationReceivedCall.qml:68:13:
Type ActionButton unavailable,
qrc:///ui/modules/Common/Form/ActionButton.qml:2:1: module
"QtQuick.Controls" version 2.1 is not installed)

[PROCESS ABNORMALLY TERMINATED]: 6

If you have used valgrind, please remove your ~/.ICEauthority file and
rerun.

[16:10:12:696][0x55d9578fb300][Info]"Set `Friends` path:
`/home/velferd/.local/share/linphone/friends.db`"

[16:10:12:728][0x55d9578fb300][Info]"Set `CallLogs` path:
`/home/velferd/.local/share/linphone/call-history.db`"

[16:10:12:734][0x55d9578fb300][Info]"Set `Chat` path:
`/home/velferd/.local/share/linphone/message-history.db`"

Entity: line 1: parser error : Start tag expected, '<' not found

SQLite format 3

^


Regards

Perparim

**Comment by Wescoeur** [comment]
Thanks for your report.

> Linphone flatpak version is successfully installed on Debian9 (HW: MinnowBoardTurbot) but I cannot register in the SIP server with my user. If you choose the next option to add a new SIP account, it is not allowed to sew the changes that the button is hibernated inactive.

Strange bug. I'll open an issue for that. Thx.

> (qrc:/ui/modules/Linphone/Notifications/NotificationReceivedCall.qml:68:13: Type ActionButton unavailable, qrc:///ui/modules/Common/Form/ActionButton.qml:2:1: module "QtQuick.Controls" version 2.1 is not installed)

For your compilation problem, you are on Debian and the QtQuick Controls 2.1 module is not provided by this distribution.
You can download the latest version of Qt here to get this module: https://info.qt.io/download-qt-for-application-development
(Do not forget to update your `Qt5_DIR` and `PATH` after installation.)

**Comment by ricardofunke** [comment]
Same for me Linphone for Linux 3.11.1

**Comment by Wescoeur** [comment]
Please use the Linphone 4 version. The 3.x branch is no longer supported. ;)
