### ISSUE TITLE
Mic input broken (linphone doesn't ask for mic permission on macOS - snapshot 663)

### ISSUE THREAD

**Issue by systemcrash** [BelledonneCommunications/linphone-desktop#285]
https://www.linphone.org/snapshots/macosx/Linphone-4.1.1-662-gd8f1eea6-mac.dmg
copy to Apps. Run. Call, then app asks me permission to use my mic - mic works. Call works. 2 way audio. 

https://www.linphone.org/snapshots/macosx/Linphone-4.1.1-663-g4a43f00e-mac.dmg
copy to Apps. Run. Call. App doesn't ask permission to use my mic - silence. Callee cannot hear linphone. 

Checked packet capture - linphone streams audio bidirectionally.

**Comment by systemcrash** [comment]
Actually, even build 662 is silent now. All builds should ask for permission to use mic/cam ( ideally before first use, but ok on first use )

**Comment by ari** [comment]
I can confirm this on OX 10.14.6 and 4.1.1-663. But build 662 works fine for me.

**Comment by David-Matz** [comment]
The problem persists still in most recent snapshot 775. Any chance to fix this in a timely manner?

**Comment by julonexus** [comment]
This is fixed in the current version
