### ISSUE TITLE
How to do touch tone ("enter your PIN and hit #)

### ISSUE THREAD

**Issue by wgordon17** [BelledonneCommunications/linphone-desktop#289]
On a call, if I'm prompted to enter a PIN number or DOB, or any number of prompts...how can I send this through the Linphone interface?

**Comment by jehandelalune** [comment]
![capture](https://user-images.githubusercontent.com/903472/61388737-4b29f300-a8b8-11e9-9f90-1e58b8707d0f.jpeg)

**Comment by wgordon17** [comment]
HA, sorry...my UI is different from what you're showing 
![image](https://user-images.githubusercontent.com/22222756/61406017-0b0f4400-a8a9-11e9-8c2a-68b46bcb1625.png)

But after you gave me the hint, I found the `Show keypad` option. Thanks for the quick reply! 👍
