### ISSUE TITLE
Presence is not working.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-desktop#292]
Dear Team,

I am using Free switch as sip server and facing issue in **Presence**.  
My problem are :

1) Presence status only showing in contact list, not in Time Line.
2) Only Available and Offline status updated in contact, no Busy and DND status.

Please find attached .png file for same.

![Linphonedesktop_Presence_issue](https://user-images.githubusercontent.com/5437700/63514907-54d1f680-c507-11e9-9631-8c43d3dc2a1a.png)

**Comment by amit1576** [comment]
@Viish ,


Any suggestions.

**Comment by amit1576** [comment]
Hi @jehandelalune , @Viish ,

Any suggestion on above problem.

**Comment by julonexus** [comment]
It should be fixed in the current snapshot
