### ISSUE TITLE
Video Conference is not working with VP8 Codecs.

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-desktop#293]
Dear @Viish .

I am using **"Free-switch"** as sip server and try to dial my number in multi party conference. My video is not going to Conference means no one is able to see my video on **VP8** codecs whereas it is working fine with **H264** codecs.

Logs are attached.

[VP8_FreeSwitchVideo_Conference.log](https://github.com/BelledonneCommunications/linphone-desktop/files/3539895/VP8_FreeSwitchVideo_Conference.log)

[H264_FreeSwitchVideo_Conference.log](https://github.com/BelledonneCommunications/linphone-desktop/files/3539896/H264_FreeSwitchVideo_Conference.log)

**Comment by Viish** [comment]
You should check your Free-switch logs.
From the linphone logs, video is correctly sent.
