### ISSUE TITLE
About Linphone SDK 4.2 related issue

### ISSUE THREAD

**Issue by tjramoliya** [BelledonneCommunications/linphone-desktop#296]
Hello Linphone Support,

I am Calling From device A to B
I have once issue in callee device(B) side Invite packet. In which i am not getting Contact Header in that packet. 
So Please update me about this issue i need this contact header in that package i have also added screenshot and .pcap file.

<img width="1369" alt="Screenshot 2019-09-24 at 12 36 07 PM" src="https://user-images.githubusercontent.com/20963757/65757987-d71c8e80-e135-11e9-83c3-0e9689aed935.png">

**Comment by julonexus** [comment]
Linphone SDK issue should be reported in the github sdk :  https://github.com/BelledonneCommunications/linphone-sdk

**Comment by julonexus** [comment]
Issues about SDK should be reported in the SDK github : https://github.com/BelledonneCommunications/linphone-sdk/
