### ISSUE TITLE
Build linphone-desktop on Ubuntu Could not find a support sound driver API

### ISSUE THREAD

**Issue by Seejun** [BelledonneCommunications/linphone-desktop#305]
I use 'cmake .. -DENABLE_SOUND=NO',and rebuild,the same issue is there:

[ 64%] Performing install step for 'EP_matroska2'
[ 64%] Built target corec-objects
[ 89%] Built target ebml2-objects
[100%] Built target bcmatroska2-static
Install the project...
-- Install configuration: "RelWithDebInfo"
[ 65%] Completed 'EP_matroska2'
[ 67%] Built target EP_matroska2
[ 67%] Performing configure step for 'EP_ms2'
loading initial cache file /home/fei/linphone-sdk/build/WORK/desktop//tmp/EP_ms2/EP_ms2-cache-RelWithDebInfo.cmake
CMake Error at CMakeLists.txt:327 (message):
  Could not find a support sound driver API.  Use -DENABLE_SOUND=NO if you
  don't care about having sound.

-- Configuring incomplete, errors occurred!
See also "/home/fei/linphone-sdk/build/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
make[5]: *** [/home/fei/linphone-sdk/build/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure] error 1
make[4]: *** [CMakeFiles/EP_ms2.dir/all] error 2
make[3]: *** [all] error 2
make[2]: *** [sdk-prefix/src/sdk-stamp/sdk-build] error 2
make[1]: *** [CMakeFiles/sdk.dir/all] error 2
make: *** [all] error 2
root@fei-VirtualBox:/home/fei/linphone-sdk/build#

**Comment by Vringe** [comment]
Try installing libpulse-dev, pulseaudio and apulse as suggested in https://github.com/BelledonneCommunications/linphone-desktop/issues/129 This also worked for me

**Comment by Seejun** [comment]
@Vringe thinks.
