### ISSUE TITLE
No soundcard in Windows with Linphonec 4.1.1

### ISSUE THREAD

**Issue by calanor** [BelledonneCommunications/linphone-desktop#306]
linphonec 4.1.1 Windows desktop version don't show any soundcard with "shoundcard list" command, and "soundcard show" command shows "(null)" values.

Linphone 3.x  in Windows and  Linphone 4.1.1 in Linux shows the available sound cards correctly.

The Linphone 4.1.1 Windows version is downloaded from official page,  not self compiled.

**Comment by simon273** [comment]
Thank you! It was very usefully info , linphonec in Windows works in ver 3.x!

**Comment by julonexus** [comment]
"soundcard list" on linphonec.exe from [Alpha-63](https://www.linphone.org/snapshots/windows/app/Linphone-4.2.0-alpha.63+59c4cc19-win32.exe)  should print the list.
