### ISSUE TITLE
Undefined Symbols for architecture x86_64

### ISSUE THREAD

**Issue by iJasonWade** [BelledonneCommunications/linphone-desktop#31]
Building on Mac OS 10.12.5

`Undefined symbols for architecture x86_64:
  "_allocb", referenced from:
      _dec_process in amrnb.c.o
      _enc_process in amrnb.c.o
      _enc_process in amrwb.c.o
      _dec_process in amrwb.c.o
  "_fmtp_get_value", referenced from:
      _amr_match in msamr.c.o
      _enc_add_fmtp in amrnb.c.o
      _enc_add_fmtp in amrwb.c.o
  "_freemsg", referenced from:
      _dec_process in amrnb.c.o
      _enc_process in amrnb.c.o
      _enc_process in amrwb.c.o
      _dec_process in amrwb.c.o
  "_getq", referenced from:
      _dec_process in amrnb.c.o
      _enc_process in amrnb.c.o
      _enc_process in amrwb.c.o
      _dec_process in amrwb.c.o
  "_mblk_meta_copy", referenced from:
      _dec_process in amrnb.c.o
      _dec_process in amrwb.c.o
  "_msgdsize", referenced from:
      _dec_process in amrnb.c.o
      _dec_process in amrwb.c.o
  "_ortp_free", referenced from:
      _enc_uninit in amrnb.c.o
      _enc_uninit in amrwb.c.o
      _dec_uninit in amrwb.c.o
  "_ortp_logv", referenced from:
      _ortp_message in msamr.c.o
      _ortp_warning in amrnb.c.o
      _ortp_message in amrnb.c.o
      _ortp_error in amrnb.c.o
      _ortp_warning in amrwb.c.o
      _ortp_message in amrwb.c.o
      _ortp_error in amrwb.c.o
      ...
  "_ortp_malloc", referenced from:
      _enc_init in amrwb.c.o
      _dec_init in amrwb.c.o
  "_ortp_malloc0", referenced from:
      _enc_init in amrnb.c.o
  "_payload_type_clone", referenced from:
      _amr_match in msamr.c.o
  "_putq", referenced from:
      _dec_process in amrnb.c.o
      _enc_process in amrnb.c.o
      _enc_process in amrwb.c.o
      _dec_process in amrwb.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [src/libmsamr.so] Error 1
make[5]: *** [src/CMakeFiles/msamr.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/jash/Developer/linphone-desktop/WORK/desktop/Stamp/EP_msamr/EP_msamr-build] Error 2
make[2]: *** [CMakeFiles/EP_msamr.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [desktop-build] Error 2`

**Comment by Wescoeur** [comment]
Have you got the same error with the last app version?

**Comment by iJasonWade** [comment]
No! I just pulled in the changes and rebuilt, everything works great!
