### ISSUE TITLE
Include PulseAudio media role in .desktop file

### ISSUE THREAD

**Issue by philipflohr** [BelledonneCommunications/linphone-desktop#313]
PulseAudio supports automatic switching between A2DP and HFP profiles for bluetooth headsets, if it knows the media role of an application.

This is documented here: https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/ApplicationProperties/

and the implementation seems to be easy:
Adding 

>  X-PulseAudio-Properties=media.role=phone

to the .desktop file should be sufficient.

**Comment by julonexus** [comment]
Thanks for pointing that. It will be [available](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/06dc5ad96a2a1b59e61113c22800a63a8ce78783) for the next release
