### ISSUE TITLE
Video Conference In Desktop Phone

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-desktop#315]
Hi @Viish ,

Do we have Video conference in linphone desktop. ? 
Please let me know any possibility even if it is in any **paid version**.

Thanks.

**Comment by Viish** [comment]
Hi,
No currently our SDK doesn't include video conferencing.
However if you want it we can develop it. Send us a mail at sales@belledonne-communications.com and we'll send you a quotation.
Cheers,
