### ISSUE TITLE
Attended Transfer

### ISSUE THREAD

**Issue by strajk-** [BelledonneCommunications/linphone-desktop#316]
Hi,

was wondering if linphone already can do this, can't find it:
In Bria 5 there is the possibility during a Call to perform an Attended Transfer, as in, putting the caller on hold, and talk to the other Transfer Destination first before issuing a transfer.

Here is how it would play out:
     **1.** Select Attended Transfer to XYZ
     **2.** Caller gets put automatically on hold, XYZ is dialed and picks up (get a chance to talk to him)
     **3.** Click on Transfer again to connect the Caller to XYZ or bring the caller back to me

So far I've managed this by "Pausing" the call, and start a second call, if the second call is agreeing with the Transfer I hang up the second call and I Transfer the paused call to him.

This question might be a duplicate of [this](https://github.com/BelledonneCommunications/linphone-desktop/issues/192), but decided to create another post anyways to explicitly address this feature.

Any plans of perhaps adding this in the near future?

**Comment by julonexus** [comment]
There is no plan to do that.
XYZ can transfert the call back to you but you don't keep the call before.

**Comment by julonexus** [comment]
Linphone perform the "Attended Transfert" : You can dial the destination that lead to put the current call in hold. Then, you can transfert the Hold to the destination.

At the end, XYZ can transfert the call back to you but you don't keep the call before : You cannot keep the call after transfert So there is no plan to do that. .
Note that you don't have to put in pause. You can dial XYZ and make the transfert, or just transfert to XYZ in one time (it doesn't depend if you have an active call or not)

**Comment by attermann** [comment]
FYI, I recently submitted pull request #511 which adds support for attended transfer.
