### ISSUE TITLE
No ring tone playback

### ISSUE THREAD

**Issue by cajus** [BelledonneCommunications/linphone-desktop#319]
I've build from source, everything works fine so far (phone works), but I cannot get the ring-tones working:

```
[16:21:16:575][0x1f20210][Warning]components/sound-player/SoundPlayer.cpp:102: "Unable to open: `/home/cajus/Projekte/linphone-desktop/build-desktop/OUTPUT/share/sounds/linphone/rings/four_hands_together.mkv`"
```
The file is there and plays fine with `vlc`:

```
.rw-r--r-- 670k cajus 16 Mär 13:48 /home/cajus/Projekte/linphone-desktop/build-desktop/OUTPUT/share/sounds/linphone/rings/four_hands_together.mkv
```

Any ideas?

**Comment by julonexus** [comment]
The mkv is encoded with Opus. But on Linux and at the time of your issue, this codec didn't work as expected. It should work now.

**Comment by cajus** [comment]
Works for me, thanks.
