### ISSUE TITLE
Raspberry Pi build process and documentation is a mess

### ISSUE THREAD

**Issue by ganzgustav22** [BelledonneCommunications/linphone-desktop#324]
I'm trying to follow this guide:
https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Linphone%20and%20Raspberry%20Pi/

When doing:
`git clone git://git.linphone.org/linphone-desktop.git --recursive`

This happens:
```
Cloning into 'linphone-desktop'...
remote: Counting objects: 30270, done.
remote: Total 30270 (delta 14209), reused 30118 (delta 14209)
Receiving objects: 100% (30270/30270), 10.12 MiB | 585.00 KiB/s, done.
Resolving deltas: 100% (14209/14209), done.
Submodule 'linphone-sdk' (git://public/linphone-sdk.git) registered for path 'linphone-sdk'
Submodule 'submodules/externals/minizip' (git://public/external/minizip.git) registered for path 'submodules/externals/minizip'
Cloning into '/mnt/linphone-desktop/linphone-sdk'...
fatal: unable to look up public (port 9418) (Name or service not known)
fatal: clone of 'git://public/linphone-sdk.git' into submodule path '/mnt/linphone-desktop/linphone-sdk' failed
Failed to clone 'linphone-sdk'. Retry scheduled
Cloning into '/mnt/linphone-desktop/submodules/externals/minizip'...
fatal: unable to look up public (port 9418) (Name or service not known)
fatal: clone of 'git://public/external/minizip.git' into submodule path '/mnt/linphone-desktop/submodules/externals/minizip' failed
Failed to clone 'submodules/externals/minizip'. Retry scheduled
Cloning into '/mnt/linphone-desktop/linphone-sdk'...
fatal: unable to look up public (port 9418) (Name or service not known)
fatal: clone of 'git://public/linphone-sdk.git' into submodule path '/mnt/linphone-desktop/linphone-sdk' failed
Failed to clone 'linphone-sdk' a second time, aborting
Cloning into '/mnt/linphone-desktop/submodules/externals/minizip'...
fatal: unable to look up public (port 9418) (Name or service not known)
fatal: clone of 'git://public/external/minizip.git' into submodule path '/mnt/linphone-desktop/submodules/externals/minizip' failed
Failed to clone 'submodules/externals/minizip' a second time, aborting
```
Looks like references to non-existing domains (?), maybe accidently used some internal domains?

So I figured I try the Github repo, but similar thing:

```
 git clone https://github.com/BelledonneCommunications/linphone-desktop.git  --recursive
Cloning into 'linphone-desktop'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 30270 (delta 11), reused 23 (delta 6), pack-reused 30242
Receiving objects: 100% (30270/30270), 9.85 MiB | 554.00 KiB/s, done.
Resolving deltas: 100% (17215/17215), done.
Submodule 'linphone-sdk' (https://github.com/public/linphone-sdk.git) registered for path 'linphone-sdk'
Submodule 'submodules/externals/minizip' (https://github.com/public/external/minizip.git) registered for path 'submodules/externals/minizip'
Cloning into '/mnt/linphone-desktop/linphone-sdk'...
Username for 'https://github.com': ganzgustav22
Password for 'https://ganzgustav22@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/public/linphone-sdk.git/' not found
fatal: clone of 'https://github.com/public/linphone-sdk.git' into submodule path '/mnt/linphone-desktop/linphone-sdk' failed
Failed to clone 'linphone-sdk'. Retry scheduled
Cloning into '/mnt/linphone-desktop/submodules/externals/minizip'...
remote: Not Found
fatal: repository 'https://github.com/public/external/minizip.git/' not found
fatal: clone of 'https://github.com/public/external/minizip.git' into submodule path '/mnt/linphone-desktop/submodules/externals/minizip' failed
Failed to clone 'submodules/externals/minizip'. Retry scheduled
Cloning into '/mnt/linphone-desktop/submodules/externals/minizip'...
remote: Not Found
fatal: repository 'https://github.com/public/external/minizip.git/' not found
fatal: clone of 'https://github.com/public/external/minizip.git' into submodule path '/mnt/linphone-desktop/submodules/externals/minizip' failed
Failed to clone 'submodules/externals/minizip' a second time, aborting
```

I'm not sure what's going on there, for some reason, the dependences cannot be cloned?
Could anybody please give a hint on how to compile it from source?

**Comment by ganzgustav22** [comment]
Okay, I figured out that the repository mentioned here: https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/Linphone%20and%20Raspberry%20Pi/ seems outdated, the one that is listed under the linphone.org download page seems to work though, it has downloaded 1.8GB.

Now, according to the docs I try to run:
 `./prepare.py no-ui -DENABLE_OPENH264=ON -DENABLE_WEBRTC_AEC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_MKV=OFF -DENABLE_FFMPEG=ON -DENABLE_CXX_WRAPPER=OFF -DENABLE_NON_FREE_CODECS=OFF -DENABLE_VCARD=OFF -DENABLE_BV16=OFF -DENABLE_V4L=OFF`

But I get this error message:
> ERROR: Missing some git submodules. Did you run:
>         git submodule update --init --recursive

running the above command doesn't give any output. Then re-running the prepary.py tool still gives the same error.

Searching for the error message it seems to stem from "linphone-desktop/linphone-sdk/cmake-builder/prepare.py". 

Going into that subdirectory and then running git submodule update --init --recursive also doesn't change anything.

**Comment by ganzgustav22** [comment]
A colleague of mine figured it out. For some strange reason, some checks in the the prepare.py file don't work (or fail?), which make the script just exit.

Rewriting the prepare.py file so that the  preparator.run() run call comes before the `if preparator.check_environment() != 0:` line makes it work:

```
def main():
    preparator = DesktopPreparator()
    preparator.parse_args()
    preparator.show_environment_errors()
    preparator.run()
    if preparator.check_environment() != 0:
        preparator.show_environment_errors()
        return 1
    return preparator.run()

if __name__ == "__main__":
    sys.exit(main())
```

All this time invested just because you guys released a linphone release that segfaults when typig "answer", the debian guys never bothered fixing it. Raspbian being based on Debian thus also never received the fix. And here we go, several years later people still have to invest a day to figure out how to compile it from source because.


In case anybody faces the same problem on the Raspberry, here's how to compile it:

- `sudo apt-get install cmake automake autoconf libtool intltool yasm libasound2-dev libpulse-dev libv4l-dev nasm git libglew-dev`
- `sudo apt-get install python-six python-pystache`
- sudo apt-get install whatever I might have forgotten now
- `git clone https://gitlab.linphone.org/BC/public/linphone-desktop.git --recursive`
- Edit prepare.py so that it looks like above
- `./prepare.py no-ui -DENABLE_OPENH264=ON -DENABLE_WEBRTC_AEC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_MKV=OFF -DENABLE_FFMPEG=ON -DENABLE_CXX_WRAPPER=OFF -DENABLE_NON_FREE_CODECS=ON -DENABLE_VCARD=OFF -DENABLE_BV16=OFF -DENABLE_V4L=OFF`
- `make -j4`

**Comment by julonexus** [comment]
Hi, the wiki on Raspberry was edited at 2019/07/19 and was based on a 2017 version.
So, you should clone a commit around this date (try with the tag 4.1.1)
The current build configuration doesn't support prepare.py anymore and wasn't tested for Raspberry

**Comment by udvnl** [comment]
Hi!
Some time ago I made a small solution on Raspberry Pi and Linphonec: https://geeks-world.github.io/articles/464309/index.html
Now I just can’t repeat it. Raspberry Pi 3B, Raspbian (Debian 10).
) Installation from apt (apt-get install linphone-nogtk) is fine.
But when answering a call, Linphonec (picking up the handset by the command and in the auto answer mode) drops:
> ------- auto answering to call -------
> Segmentation fault

An outgoing call from the program works correctly. The call and talk state is set correctly, both from Linphonec and from Linphonecsh.
2) I can not make the current version:
 ` root @ raspberrypi: / home / pi / 3 / linphone-desktop / build # cmake .. -DCMAKE_BUILD_TYPE = RelWithDebInfo
`
-
>  User-Setting Platform to
> CMake Error at /usr/share/cmake-3.13/Modules/ExternalProject.cmake:2530 (message):
>   No download info given for 'sdk' and its source directory:
>    / home / pi / 3 / linphone-desktop / linphone-sdk

3) Installation from saved old source codes with the help of prepare.ru runs fine. The Linphonec client works correctly for both incoming and outgoing calls, but daemon linphonecsh does not start (on Debian 10 Buster).

**Comment by julonexus** [comment]
linphone from packages are 3 years old and are not really supported. H264 can be build if you set the build configuration but if you have not it, the codec will be downloaded from the desktop application.
' sudo ./prepare.py' is no more. You have to follow the Readme for building steps (a new version of the readme is currently on MR state but the master should be enough)
Do no forget to clone with recursive mode : I guess that 'no download info' means that you have nothing in your linphone-sdk folder
