### ISSUE TITLE
fatal: remote error: access denied or repository not exported: /linphone

### ISSUE THREAD

**Issue by dplamp** [BelledonneCommunications/linphone-desktop#325]
Hi,
I type :
```
$ git clone git://git.linphone.org/linphone-desktop.git
$ cd linphone-desktop
$ git checkout 4.1.x
$ ./prepare.py
```
Now I get an error and a message telling me to run :
`$ git submodule sync && git submodule update --init --recursive`

Among other messages, I get a warning : _"remote: warning: unable to access 'info/attributes': Permission denied"_
And finally, after cloning a whole lot of submodules, the cloning process stops with an error : _"fatal: remote error: access denied or repository not exported: /linphone"_

**Comment by julonexus** [comment]
The build configuration has changed. But it is still :
git clone https://gitlab.linphone.org/BC/public/linphone-desktop.git --recursive
git submodule update --init --recursive
