### ISSUE TITLE
[Q] Is there a way to build using only system dependencies?

### ISSUE THREAD

**Issue by Megver83** [BelledonneCommunications/linphone-desktop#326]
I'm trying to build the project in Arch Linux, without anything from the AUR (only python-pystache), and to build it I must update the submodules, which are built alongside linphone-desktop.

However, mediastreamer2 has been giving a big PITA, and although it is available in the pkg repos and installed, the submodule is built anyways. Is there a way to tell linphone-desktop to do not build it and directly use the one installed in the system?

**Comment by julonexus** [comment]
Mediastreamer is a part of the SDK. So it is more like a SDK option to set.
It is find by using find_package(Mediastreamer2 CONFIG REQUIRED)
So my guess is that setting Mediastreamer2_DIR to the path of your system should be good.

**Comment by julonexus** [comment]
To build the SDK with the system libraries, your have to set LINPHONE_BUILDER_USE_SYSTEM_DEPENDENCIES=ON
