### ISSUE TITLE
i3 Window Manager Call-Popup and settings window not working

### ISSUE THREAD

**Issue by velrest** [BelledonneCommunications/linphone-desktop#327]
The popup for an incoming call as well as the settings window are only displayed as a very small white rectangle in the top-left screen.
![image](https://user-images.githubusercontent.com/15276514/77147553-cf5af880-6a8d-11ea-8d37-ed1b03987a4a.png)

[i3](https://i3wm.org/)

For the settings window:
The mouse is captured and the window can be closed with `Esc`. everything other on the Desktop is unresponsive. When pressing `Enter` twice, the actual settings window opens.

For the call popup:
The mouse is not captured and the desktop is fully responsive. The hack with pressing `Enter` twice does not work. I think the window is never focused. So calls cannot be answered.

Tested in i3 modes tabbed, windowed and stacked. Always the same results.

Versions:
* Linux version 5.4.24-1-lts (linux-lts@archlinux) (gcc version 9.2.1 20200130 (Arc
h Linux 9.2.1+20200130-2)) #1 SMP Thu, 05 Mar 2020 20:29:59 +0000
* i3-wm 4.18-1
* xorg-server 1.20.7-1

```
➜  ~ flatpak info com.belledonnecommunications.linphone 
          ID: com.belledonnecommunications.linphone
         Ref: app/com.belledonnecommunications.linphone/x86_64/4.1.1
        Arch: x86_64
      Branch: 4.1.1
      Origin: linphone-origin
Installation: user
   Installed: 315.4 MB
     Runtime: org.freedesktop.Platform/x86_64/1.6
         Sdk: org.freedesktop.Sdk/x86_64/1.6

      Commit: bae79f29ce390b6b28254cba0ae63f1bbb8d9a30f50acce422ce5ef1f1839441
     Subject: build of com.belledonnecommunications.linphone, Fri Jul 21 15:09:01 CEST 2017
        Date: 2017-07-21 16:14:30 +0000
```

**Comment by julonexus** [comment]
Hi, the Flatpack package is not supported anymore : https://www.linphone.org/news/linphone-desktop-42-public-beta
You should test it and see if your issue is still there. There was a bug about HDPI that screw up the GUI.

**Comment by velrest** [comment]
I will test it thanks!

**Comment by velrest** [comment]
I am now on `Desktop 4.2.0-alpha-14-g0d3c37b - Qt5.12.5` and the issue is fixed. Thanks a lot!

**Comment by julonexus** [comment]
Nice! You should use alpha32 as it fixe some configurations issues 
https://www.linphone.org/snapshots/AppImages/Linphone-4.2.0-alpha.32+f2b054c.AppImage
