### ISSUE TITLE
KCrash on debian buster "module "QtQuick.Controls" version 2.7 is not installed"

### ISSUE THREAD

**Issue by Jackfritt** [BelledonneCommunications/linphone-desktop#329]
Build was fine. As you can see
...
[19:26:53:371][Warning]Core:linphone: QT: app/translator/DefaultTranslator.cpp:68: "Unable to find a translation. (context=MainWindow, label=newConferenceButton)"
[19:26:53:478][0x55ff9d1747f0][Info]app/App.cpp:772: "Open Linphone app."
[19:26:53:478][0x55ff9d1747f0][Info]app/App.cpp:223: "Creating subwindow: `qrc:/ui/views/App/Calls/CallsWindow.qml`."
[19:26:53:523][0x55ff9d1747f0][Info]app/App.cpp:230: "Subwindow status: `1`."
[19:26:53:532][0x55ff9d1747f0][Info]app/App.cpp:223: "Creating subwindow: `qrc:/ui/views/App/Settings/SettingsWindow.qml`."
[19:26:53:549][0x55ff9d1747f0][Warning]app/App.cpp:227: (qrc:/ui/views/App/Settings/SettingsWindow.qml:139:7: Type SettingsAudio unavailable, qrc:/ui/views/App/Settings/SettingsAudio.qml:2:1: module "QtQuick.Controls" version 2.7 is not installed)
[19:26:53:549][Warning]Core:linphone: QT: app/App.cpp:227: (qrc:/ui/views/App/Settings/SettingsWindow.qml:139:7: Type SettingsAudio unavailable, qrc:/ui/views/App/Settings/SettingsAudio.qml:2:1: module "QtQuick.Controls" version 2.7 is not installed)
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = linphone path = /home/kvm/src/linphone-desktop/build-desktop/OUTPUT/bin pid = 17735
KCrash: Arguments: /home/kvm/src/linphone-desktop/build-desktop/OUTPUT/bin/linphone --verbose 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0

Am I missing packages?

i   qml-module-qtquick-controls2                   - Qt 5 Qt Quick Controls 2 QML module
i A qml-module-org-kde-kquickcontrols              - provides integration of QML and KDE frameworks - kquickc
p   qml-module-org-kde-kquickcontrols:i386         - provides integration of QML and KDE frameworks - kquickc
i A qml-module-org-kde-kquickcontrolsaddons        - provides integration of QML and KDE Frameworks - kquickc
p   qml-module-org-kde-kquickcontrolsaddons:i386   - provides integration of QML and KDE Frameworks - kquickc
i A qml-module-qtquick-controls                    - Qt 5 Quick Controls QML module                          
p   qml-module-qtquick-controls:i386               - Qt 5 Quick Controls QML module                          
i A qml-module-qtquick-controls-styles-breeze      - QtQuick style for Qt and KDE Software                   
p   qml-module-qtquick-controls-styles-breeze:i386 - QtQuick style for Qt and KDE Software                   
i   qml-module-qtquick-controls2                   - Qt 5 Qt Quick Controls 2 QML module                     
p   qml-module-qtquick-controls2:i386              - Qt 5 Qt Quick Controls 2 QML module                     
i A qml-module-qtquick-dialogs                     - Qt 5 Dialogs QML module                                 
p   qml-module-qtquick-dialogs:i386                - Qt 5 Dialogs QML module                                 
p   qml-module-qtquick-extras                      - Qt 5 Quick Extras QML module                            
p   qml-module-qtquick-extras:i386                 - Qt 5 Quick Extras QML module                            
i A qml-module-qtquick-layouts                     - Qt 5 Quick Layouts QML module                           
p   qml-module-qtquick-layouts:i386                - Qt 5 Quick Layouts QML module                           
p   qml-module-qtquick-localstorage                - Qt 5 localstorage QML module                            
p   qml-module-qtquick-localstorage:i386           - Qt 5 localstorage QML module                            
p   qml-module-qtquick-particles2                  - Qt 5 particles 2 QML module                             
p   qml-module-qtquick-particles2:i386             - Qt 5 particles 2 QML module                             
i A qml-module-qtquick-privatewidgets              - Qt 5 Private Widgets QML module                         
p   qml-module-qtquick-privatewidgets:i386         - Qt 5 Private Widgets QML module                         
p   qml-module-qtquick-scene2d                     - Qt 5 Quick Scene 2D QML module                          
p   qml-module-qtquick-scene2d:i386                - Qt 5 Quick Scene 2D QML module                          
p   qml-module-qtquick-scene3d                     - Qt 5 Quick Scene 3D QML module                          
p   qml-module-qtquick-scene3d:i386                - Qt 5 Quick Scene 3D QML module                          
p   qml-module-qtquick-shapes                      - Qt 5 Qt Quick Shapes QML module                         
p   qml-module-qtquick-shapes:i386                 - Qt 5 Qt Quick Shapes QML module                         
i A qml-module-qtquick-templates2                  - Qt 5 Qt Quick Templates 2 QML module                    
p   qml-module-qtquick-templates2:i386             - Qt 5 Qt Quick Templates 2 QML module                    
i A qml-module-qtquick-virtualkeyboard             - Qt virtual keyboard - QML module                        
p   qml-module-qtquick-virtualkeyboard:i386        - Qt virtual keyboard - QML module                        
i A qml-module-qtquick-window2                     - Qt 5 window 2 QML module                                
p   qml-module-qtquick-window2:i386                - Qt 5 window 2 QML module                                
p   qml-module-qtquick-xmllistmodel                - Qt 5 xmllistmodel QML module                            
p   qml-module-qtquick-xmllistmodel:i386           - Qt 5 xmllistmodel QML module                            
i A qml-module-qtquick2                            - Qt 5 Qt Quick 2 QML module                              
p   qml-module-qtquick2:i386                       - Qt 5 Qt Quick 2 QML module                              
i   qtquickcontrols2-5-dev                         - Qt 5 Quick Controls 2 development files                 
p   qtquickcontrols2-5-dev:i386                    - Qt 5 Quick Controls 2 development files                 
i A qtquickcontrols2-5-doc                         - Qt 5 Quick Controls 2 documentation                     
p   qtquickcontrols2-5-doc-html                    - Qt 5 Quick Controls 2 HTML documentation                
p   qtquickcontrols2-5-examples                    - Qt 5 Qt Quick Templates 2 examples                      
p   qtquickcontrols2-5-examples:i386               - Qt 5 Qt Quick Templates 2 examples                      
i A qtquickcontrols5-doc                           - Qt 5 Quick Controls documentation                       
p   qtquickcontrols5-doc-html                      - Qt 5 Quick Controls HTML documentation                  
p   qtquickcontrols5-examples                      - Qt 5 Quick Controls examples                            
p   qtquickcontrols5-examples:i386                 - Qt 5 Quick Controls examples

Any suggestions? or need more Info?

Thx

**Comment by julonexus** [comment]
Maybe it is the qt.conf that is not configured correctly. Try to remove the [Paths] section.
