### ISSUE TITLE
Linphone calls are (sometimes?) extremely quiet

### ISSUE THREAD

**Issue by wtok** [BelledonneCommunications/linphone-desktop#33]
Hi, I just tried Linphone 4.0 out with a friend and we found that the call was extremely quiet. The actual Linphone program had the right volume -- the ringtone was fine, but we could barely hear eachother in the call without turning the system volume up drastically, which makes every other sound (including the Linphone ringtones) deafeningly loud.

There don't appear to be any volume options in the settings, either, so we had to switch back to Mumble to be able to talk.

I was using the Linux Flatpak, and my friend was using the Windows version on Windows 7.

Please ask if you need any more info.

**Comment by Wescoeur** [comment]
Solution: Wait for the audio assistant in a future release. I have no other solution for the moment.

**Comment by rdiez** [comment]
7 years later, I am having the same problem. Linphone 5.2.6 on Linux is too quiet, compared to other sound and videoconference software on the same system (Ubuntu 22.04.5).

There is no "audio assistant" yet, or is there?

Linphone 5.2.5 on Android is much louder.
