### ISSUE TITLE
belle-sip should add an Accept header to SUBSCRIBE messages

### ISSUE THREAD

**Issue by JohnHughesAtlantech** [BelledonneCommunications/linphone-desktop#334]
I'm working with an Asterisk PABX and it rejects belle-sip's SUBSCRIBE messages because bell-sip does not include an Accept header specifying that it wants application/pidf+xml.

If the Accept header is added to the SUBSCRIBE request Asterisk will send valid NOTIFY responses.

This issue is present in the current beta.

**Comment by julonexus** [comment]
If you think this is a bug from the SDK, please post the issue in the right project (https://github.com/BelledonneCommunications/linphone-sdk)

**Comment by JohnHughesAtlantech** [comment]
Closing and making new issue on linphone-sdk.  Isn't there supposed to be some way to transfer issues?  I can't find the option.  Oh well
