### ISSUE TITLE
Settings Button does not Work

### ISSUE THREAD

**Issue by rlarranaga** [BelledonneCommunications/linphone-desktop#336]
OS Version: WIndows 10 1909
Linphone Version: Desktop 4.2.0-alpha-14-g0d3c37bd - Qt5.12.5

When Clicking on the account tab (Top left Pane, above the "Home"
A window with all accounts opens up. Each Account shows a button with a gear on the righ side. This button does not work.

On the "Preferences" Section (Top right button), there is no way to configure an account either. That makes the account assistant the only way to configure a new account, and it can only be configured by creating it from scratch

**Comment by julonexus** [comment]
The gear do nothing yet. It will be better to remove it till the availability of the shortcut.
But, the account can be edited in the settings (proxy accounts). There is a pen button to edit it.

**Comment by rlarranaga** [comment]
The pen button does not allow you to edit the same settings. Password, for
example, is not there

**Comment by julonexus** [comment]
The assistant let you create an account, not update it. 
You cannot change the password inside the application. It is doable on the website.

**Comment by rlarranaga** [comment]
Hey Julian:
Thanks. The problem is when you use an account, change the password, and
need to update the password on the application. There is no way to do that,
and you need to re create the account from scratch.

At the same time, the "pen" button does not have the same fields to fill
than the assistant.

Regards

**Comment by julonexus** [comment]
The button "erase password" doesn't work?

**Comment by rlarranaga** [comment]
Hello:
Here is a page for the assistant button, when configuring a sip account:

![image](https://user-images.githubusercontent.com/7197023/79343470-cfbba780-7f04-11ea-8ccf-d9aa5aa68bac.png)

Now, here is a page when using the pen icon:

![image](https://user-images.githubusercontent.com/7197023/79343778-3a6ce300-7f05-11ea-8b30-b57026e5764c.png)

Maybe it is just a different way of entering the same information, but the the sip address in this page is of the form:
"Name: <sip:user@voiced_domain>
and the server, of the form
<sip:voice_domain:transport=>

I guess it is the same information in both pages, but it is a little bit more error prone to modify the information through the pen button.

I just used the "Erase passwords" Button. At first it was confusing, because i did not know where to put the password again. Then i realized that the software will request for a password on next login.

I think the way these features work are a little unconventional, but in the end they work. so this could be considered a closed ticket.

Thanks!

**Comment by julonexus** [comment]
It could be done better but it is not the priority. The main thing is to have things working for a 2 years old exhumation. And I agree, the password and account behaviour is weird.

**Comment by rlarranaga** [comment]
3 years old exhumation?. What do you mean by that?
Anyway, it was not my intention to be critical at all. Just trying to understand the operating parameters :)

**Comment by julonexus** [comment]
The last stable version of Linphone was back to 2017. There were many features, optimizations and more since then  ;)
