### ISSUE TITLE
Linphone 4.2 install will not install due to unknown component running

### ISSUE THREAD

**Issue by rlarranaga** [BelledonneCommunications/linphone-desktop#337]
Sometimes, when trying to install linphone 4.2 alpha, the following message appears:

"is running. Please close it First and restart the installation"

![image](https://user-images.githubusercontent.com/7197023/79271715-a7856780-7e76-11ea-8143-ed7fbb4a4a0a.png)

The message does not make clear what is running. In some computers this was resolved by restarting computer. In others, it did not.

Thanks.

**Comment by SirDMZ** [comment]
Yeah, also seeing this.
Windows 10 1909 18363.720
Nothing particularly interesting in the system configuration.

**Comment by julonexus** [comment]
This a missing typo, it's about Linphone and is fixed in the next version.
The application is still running (old version or new). You have to kill it, closing windows is not enough as it only close windows and not the application by default.

**Comment by rlarranaga** [comment]
Hello: i ran into this issue in systems that did not have linphone running.
I checked in the task manager before opening the ticket.

Thanks

**Comment by SirDMZ** [comment]
Yeah, this system does not have linphone installed. It "may" have previously, but has been restarted alot "IF" it did ever have it installed.

**Comment by julonexus** [comment]
Maybe it will be fixed in the next version tomorrow. The test is done by the NSIS installer but with an empty APPLICATION_NAME
```
Function .onInit
  FindWindow $0 "gdkWindowToplevel" "@APPLICATION_NAME@"
  FindWindow $1 "Qt5QWindowOwnDCIcon" "@APPLICATION_NAME@"
  StrCmp "$0$1" "00" notRunning
  MessageBox MB_OK|MB_ICONEXCLAMATION "@APPLICATION_NAME@ is running. Please close it first and restart the installation." /SD IDOK
  Abort

notRunning:
```

**Comment by rlarranaga** [comment]
Will try it tomorrow, and give you feedback.
Thanks!

**Comment by rlarranaga** [comment]
In the test that i did today, i did not have the same issue of the application not installing. I do not have any other machines to test than mine currently though.

**Comment by SirDMZ** [comment]
I tested it. Works here now!
