### ISSUE TITLE
Related To issue #337 - Unknown component prevents install

### ISSUE THREAD

**Issue by rlarranaga** [BelledonneCommunications/linphone-desktop#338]
Hello:
I saw that issue #337 was closed deemed as a typo.
I wan't to clarify that in the instances i encountered this error, linphone was not running.
I exited it before running the installer, and also went through the task manager looking for windows services before running the installer.

I can reproduce this in my current computer, where linphone is installed, but if i exit it and try to run the installer, the installer fails with the mentioned error.

Thanks

**Comment by julonexus** [comment]
Thanks but I already reopened it ;) this typo seems to be more important than expected
