### ISSUE TITLE
Linphone 4.2 Not Signed app Not signed

### ISSUE THREAD

**Issue by rlarranaga** [BelledonneCommunications/linphone-desktop#339]
Hello:
I noticed that linphone desktop 4.2 installer is not signed, unlike 4.1. I just want to confirm that it will be, once oficially deployed? Singing the app allows better deployment mass enviroments where security is a concern.

Thanks!

**Comment by julonexus** [comment]
Hi
At this time, only the Mac binary is signed. Others will follow later

**Comment by rlarranaga** [comment]
Does this mean the stable version will be released signed? Or are you
talking about takling this in another version?.

Thanks

**Comment by julonexus** [comment]
Binaries should be signed now.
