### ISSUE TITLE
Calls between someone with no encryption and someone with ZRTP will connect, but be silent

### ISSUE THREAD

**Issue by wtok** [BelledonneCommunications/linphone-desktop#34]
I encountered this when trying Linphone 4.0 just now. I had "ZRTP" set in the settings menu, but my friend had "None" set. Our calls would connect, but would be completely silent. 

There was no message about encryption incompatibilities that I could see. It appeared to be a perfectly functioning call, just we couldn't hear eachother.

**Comment by Wescoeur** [comment]
I have no problem to call a person which has no encryption.
Does the call end after 30 seconds? Does a call without encryption on both sides work?

**Comment by Wescoeur** [comment]
It seems not an issue.
