### ISSUE TITLE
Does Linphone Desktop work on MACOS Catalina ? Cant not Register

### ISSUE THREAD

**Issue by Omid-Mohajerani** [BelledonneCommunications/linphone-desktop#341]
Hi, 

Does Linphone Desktop works on MACOS Catalina? Im using my sip account or linphone account both cant register. Im using  Desktop 4.2.0-alpha-14-g0d3c37bd - Qt5.13.2.

Thanks

**Comment by julonexus** [comment]
Hi,
Linphone support Catalina. You should try the last version https://www.linphone.org/snapshots/macosx/app/Linphone-4.2.0-alpha.29+ce58ce03-mac.dmg
If you have still your issue, more logs will be needed ("./Linphone.app/Contents/MacOS/Linphone --verbose" or a link to your log file with the send log button)
