### ISSUE TITLE
Enable more strings to be translated

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-desktop#343]
Please add the following translations to be translated.

![kép](https://user-images.githubusercontent.com/17465872/79632783-cbadb500-81a4-11ea-9779-ce911a5fb05c.png)

![kép](https://user-images.githubusercontent.com/17465872/79632799-ed0ea100-81a4-11ea-93fe-be0f79b0e70f.png)

![kép](https://user-images.githubusercontent.com/17465872/79632815-03b4f800-81a5-11ea-8214-53802c7175db.png)

What do you think?

Thank you

Desktop 4.2.0-alpha-27-g9b156c0 - Qt5.12.5
Core 4.4.0-alpha-136-g1202151

Linux Mint 19.3 Cinnamon 64-bit

**Comment by julonexus** [comment]
For the country, I  think we can do something.

But other strings are dynamics and come from the SDK. The application cannot translate them without having a Machine Translator embedded. You should ask it to the SDK project https://github.com/BelledonneCommunications/linphone-sdk

The only strings that can be translated in the application are those that are in : https://www.transifex.com/belledonne-communications/linphone-desktop/languages/
And if you see that some are missing or erroneous, do not hesitate to propose a translation in Transifex ;)

**Comment by julonexus** [comment]
Countries have been added to the translation.

**Comment by ovari** [comment]
> Countries have been added to the translation.

1. Thank you for adding the translations.

2. The Hungarian translations have been provided. Can they please be available on the next developmental release?

3. For the en source strings, when there were multiple words in on string, the spaces were missing. Can the en source strings be fixed?

Thank you

**Comment by julonexus** [comment]
The english text is not translated. This is done by Qt

**Comment by ovari** [comment]
@julonexus could you please advise when the Hungarian translation of the `Country` strings will be available in Linphone development build so we can check that they show correctly. Thank you

Desktop 4.2.0-alpha-32-gf2b054c - Qt5.12.5
Core 4.4.0-alpha-136-g1202151
