### ISSUE TITLE
Where can I inform about bugs on Linphone AppImage?

### ISSUE THREAD

**Issue by alexandre1985** [BelledonneCommunications/linphone-desktop#344]
I want to be a tester of the new Linphone alpha version AppImage for Linux.
I already have a bug report.

Where can I submit such bug?

**Comment by julonexus** [comment]
You are in the place for submitting bugs. If you want to keep your privacy, you can use the `Send logs` button in the settings : it will upload your log file to allow you sending it by email. But you have to know that taking account issues is on free-time based as we don't offer free support.
