### ISSUE TITLE
Can't update my build, no access to the sourcecode of Linphone

### ISSUE THREAD

**Issue by boospy** [BelledonneCommunications/linphone-desktop#345]
Hello all, 

i following the instruction from the readme. But if i say
`git submodule sync && git submodule update --init --recursive`
i must enter my user and password for git, and after i get this error:

```
Fehler beim Klonen von 'msaaudio'. Weiterer Versuch geplant
Klone nach '/root/linphone-desktop/linphone-sdk/msandroidcamera2' ...
Username for 'https://github.com': boospy
Password for 'https://boospy@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/public/msandroidcamera2.git/' not found
fatal: Klonen von 'https://github.com/public/msandroidcamera2.git' in Submodul-Pfad '/root/linphone-desktop/linphone-sdk/msandroidcamera2' fehlgeschlagen
```
Do i something wrong?

Thanks and best Regards :)

**Comment by julonexus** [comment]
You have to use the gitlab repository https://gitlab.linphone.org/BC/public/linphone-desktop.git
or
git@gitlab.linphone.org:BC/public/linphone-desktop.git

The readme will be updated to avoid this kind a error

**Comment by boospy** [comment]
Ah ok. Thanks. It works now :)
