### ISSUE TITLE
No other realm than linphone.org possible

### ISSUE THREAD

**Issue by fbsi** [BelledonneCommunications/linphone-desktop#348]
In my .linphonerc under [proxy_0] i stumbled across these lines:
```
[proxy_0]
reg_proxy=sip:sip.1und1.de
reg_identity=sip:49xxxxxxxxx76@1und1.de
realm=sip.linphone.org
```
It seems like **linphone changes the realm back to linphone.org** even if i edit it manually in the config-file.
Just asking because i think i have an issue with ACK Messages and therefore drops of incoming calls. Wrong realm could maybe play a role?
I'm using Linphone Desktop 4.1.1-655-g95245907 on Ubuntu 18.04
I can rule out any NAT issues because i'm not behind one and with a linphone account everything works just fine.

**Comment by julonexus** [comment]
I couldn't reproduce your issue in the current snapshots.
