### ISSUE TITLE
Linphone app is always asking me password

### ISSUE THREAD

**Issue by icbrg** [BelledonneCommunications/linphone-desktop#35]
It's very annoying, when I open the app I have to insert the password again. Why does it not save?

If I have to make a call passed X time, it asks me for the password again.

**Comment by Wescoeur** [comment]
Could you give me some informations please?

Does your username contain special characters like `%` or `-`...?
Are you using the default `sip.linphone.org` domain?

**Comment by icbrg** [comment]
Hello ofc

Yes, it has a -

I'm using an external SIP server.

**Comment by Wescoeur** [comment]
Maybe a stupid question: Are you sure you entered the correct password? Can you call and send messages?

**Comment by icbrg** [comment]
Yes, without problems. 

What I can see is that Realm changes when asking me password again.

mpbx1.xxx.com
mpbx3.xxx.com

**Comment by Wescoeur** [comment]
I see your problem. A hash is computed with your username, password and realm for authentication. The hash become invalid when you receive a different realm. (See RFC: HTTP: Digest Access Authentication.)

If you have an access on this server, you can fix the realm. An other solution is to force the used sip server in the application settings, edit your proxy config and set the server address like this:

    <sip:mpbx1.xxx.com;transport=tls>

**Comment by icbrg** [comment]
As I don't have access to server config I cannot do it but now I think is fixed changing sip server with realm fixed!

**Comment by Wescoeur** [comment]
Nice! If you have any questions, do not hesistate. So, this issue is a problem server, it's not easy to deal with this is in the application. The RCF is not correctly respected.
