### ISSUE TITLE
Conversion of call strings (space prefix error)

### ISSUE THREAD

**Issue by mokkin** [BelledonneCommunications/linphone-desktop#350]
If I copy and paste a number from somewhere in the browser or the PC, the number appears in a rare format:

![grafik](https://user-images.githubusercontent.com/2938748/79975771-cbaaff00-849b-11ea-931b-e30a17fa748a.png)

Theoretically it should be converted from `+49 - 177 - 123 45 67` into `00491771234567`

**Comment by mokkin** [comment]
It seems like the problem is a space at the beginning of the string. If I delete the first space, the rest gets converted into a prettier format:
![grafik](https://user-images.githubusercontent.com/2938748/79976229-8cc97900-849c-11ea-8cc7-7a635faa796a.png)

**Comment by julonexus** [comment]
This is not a space, this is the character %0a. As you search contains special char, the ID is not considered as a number. So, characters are encoded.
