### ISSUE TITLE
ACK processing issue

### ISSUE THREAD

**Issue by FedorZarubin** [BelledonneCommunications/linphone-desktop#351]
Hi!
I'm a technical support engineer in а VoIP platform ITooLabs.
Our clients, using Linphone, start encounter a problem of bracking call after 30-40 sec duration.
In our logs we see, that your app give an "400 Bad request" response on our ACK. It problem take place in all platform versions of Linphone (has recently seen in: LinphoneAndroid/4.2.3 (COL-L29) LinphoneSDK/4.3.3 (tags/4.3.3^0); Linphone Desktop/4.1.1 (belle-sip/1.6.3); LinphoneiOS/4.2.2 (iPhone) LinphoneSDK/4.3.1). With using any other softphones or hardware SIP phones this issue not occurs.
Please, explore the log example (in attach) and let me know if you will find a reason of that issue.
Thanks!
[centrexlogs.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/4516253/centrexlogs.txt)

**Comment by JohnHughesAtlantech** [comment]
Doesn't this look like: https://lists.gnu.org/archive/html/linphone-users/2017-01/msg00023.html

I see no Max-Forwards in your ACK

**Comment by FedorZarubin** [comment]
Thanks a lot!
