### ISSUE TITLE
Call history is confusing and not very practical

### ISSUE THREAD

**Issue by JohnHughesAtlantech** [BelledonneCommunications/linphone-desktop#354]
The "previously" panel shows calls by remote identity, the actual call history for that remote is shown if the identity is clicked on.  I can find no way of seeing a simple list of all calls

Also, incoming calls don't get added to the previously panel, only outbound calls.

**Comment by bugybunny** [comment]
Linked to #352 with incoming calls not showing up in call history.

**Comment by julonexus** [comment]
Having only logs for the clicked entity is a feature to avoid having a full unreadable logs. I don't think it will be reimplemented.
For the incoming calls, it should work with alpha:  4.2.alpha55

**Comment by JohnHughesAtlantech** [comment]
On 19/05/2020 14:36, Julien Wadel wrote:
>
> Having only logs for the clicked entity is a feature to avoid having a 
> full unreadable logs. I don't think it will be reimplemented.
>
"full unreadable logs" means what?

I've never seen any telephone that doesn't allow a simple chronological 
log.  With the current linphone UI how can I see calls that are not from 
contacts?

> For the incoming calls, it should work with alpha: 4.2.alpha55
>
That's nice.

**Comment by julonexus** [comment]
The left panel shows you all the accounts that interacted with you. It doesn't depend if it is in your friends list or not.

**Comment by JohnHughesAtlantech** [comment]
On 19/05/2020 14:49, Julien Wadel wrote:
>
> The left panel shows you all the accounts that interacted with you. It 
> doesn't depend if it is in your friends list or not.
>
In the current session, yes?  No way of seeing people you called (or who 
called you) yesterday.

**Comment by JohnHughesAtlantech** [comment]
On 19/05/2020 14:49, Julien Wadel wrote:
>
> The left panel shows you all the accounts that interacted with you. It 
> doesn't depend if it is in your friends list or not.
>
Ignore my reply, I've obviously confused myself while switching between 
linphone-gtk and linphone-qt
