### ISSUE TITLE
linphone doesn't show caller-id info for incoming calls.

### ISSUE THREAD

**Issue by JohnHughesAtlantech** [BelledonneCommunications/linphone-desktop#355]
I get an incoming call that looks like this:

INVITE sip:mini@10.27.128.18;transport=udp SIP/2.0^M
Via: SIP/2.0/UDP 10.27.128.1:5060;branch=z9hG4bK67022708^M
Max-Forwards: 70^M
From: "John Hughes [CALVAEDI]" <sip:+336xxxxxxxx@10.27.128.1>;tag=as0211e0f5^M

And linphone shows me the phone number but ignores the text part of the "from"

(The old GTK Linphone used to show it).

**Comment by julonexus** [comment]
Hi, this should be fixed on [incoming notification ](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/5829d54f70826aa11a2105db45637c4b59d3f924)
