### ISSUE TITLE
Support for encrypted SIP telephony by German Telekom CloudPBX

### ISSUE THREAD

**Issue by lvogt** [BelledonneCommunications/linphone-desktop#362]
Hi everybody :)
I would like to use Linphone with my CloudPBX account from German provider Telekom. If you do not have an internet connection by Telekom, only the encrypted SIP endpoints are exposed and they seem to require some special "handling" as described [here (German; DeepL translation below)](https://cpbx-hilfe.deutschland-lan.de/de/ratgeber-zur-konfiguration/spezialkonfigurationen/mediasec)

They provide some basic information about what SIP/SDP header values should be send (see below). REGISTERing with server seems to work with a recent version, however everything else does not.

Is it possible to configure Linphone to behave like this?

```
   IP-PBX                                         P-CSCF
    |                                               | 
    |----(1) REGISTER------------------------------>| 
    |        Security-Client: sdes-srtp;mediasec    |
    |        Proxy-Require: mediasec                |
    |        Require: mediasec                      |
    |                                               | 
    |<---(2) 401------------------------------------|
    |        Security-Server: msrp-tls;mediasec     | 
    |        Security-Server: sdes-srtp;mediasec    | 
    |        Security-Server: dtls-srtp;mediasec    |
    |                                               | 
    |----(3) REGISTER(with Authorization Header)--->| 
    |        Security-Client: sdes-srtp;mediasec    |
    |        Proxy-Require: mediasec                |
    |        Require: mediasec                      |
    |        Security-Verify: msrp-tls;mediasec     | 
    |        Security-Verify: sdes-srtp;mediasec    | 
    |        Security-Verify: dtls-srtp;mediasec    |
    |                                               | 
    |<---(4) 200------------------------------------|
    |                                               | 
    |                                               | 
    |----(5) INVITE-------------------------------->| 
    |        Security-Verify: msrp-tls;mediasec     | 
    |        Security-Verify: sdes-srtp;mediasec    | 
    |        Security-Verify: dtls-srtp;mediasec    |
    |        Proxy-Require: mediasec                |
    |        Require: mediasec                      |
    |        a=3ge2ae:requested                     |
    |        a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:EpcgtOdT5qd...
    |                                               | 
    |<---(6) TRYING---------------------------------|
    |                                               | 
    |<---(7) RINGING--------------------------------|
    |                                               | 
    |<---(8) 200------------------------------------|
    |        a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:lnfakjh2sd1...
    |                                               | 
```

<details><summary>DeepL translation</summary>
<p>

Mediasec (manual configuration of encryption)

For the successful use of an encrypted VoIP connection, in addition to a TLS connection for SIP signaling and SRTP for voice encryption, other additional SIP headers and SDP attributes are required. During registration (SIP REGISTER) the additional SIP headers inform the platform about the use of the encryption type and during call setup (SIP INVITE) the encryption type and range of the encryption (edge to access-edge, encryption between PBX and registration server) must be included. The SIP headers are based on an IETF draft (https://tools.ietf.org/html/draft-dawes-sipcore-mediasec-parameter-10) but are to be seen as a static addition to the SIP signaling.

SIP REGISTER

1) The initial REGISTER without Authentication Challenge requires the SIP headers "Security-Client: sdes-srtp;mediasec", "Proxy-Require: mediasec" and "Require: mediasec".

2) The platform responds with 401 UNAUTHORIZED. This SIP response includes the SIP headers "Security-Server: msrp-tls;mediasec", "Security-Server: sdes-srtp;mediasec" and "Security-Server: dtls-srtp;mediasec", which reflect the possible encryption types.

3) For the subsequent REGISTER with Authentication Challenge, the SIP headers "Security-Client: sdes-srtp;mediasec", "Proxy-Require: mediasec" and "Require: mediasec", which were already sent originally, must now be supplemented by the SIP headers "Security-Verify: msrp-tls;mediasec", "Security-Verify: sdes-srtp;mediasec" and "Security-Verify: dtls-srtp;mediasec".

According to RFC 3261 the Security-Verify headers can also be combined and sent as "Security-Verify: msrp-tls;mediasec,sdes-srtp;mediasec,dtls-srtp;mediasec" in the REGISTER with Authenfication Challenge.

INVITE/UPDATE

1) The initial INVITE must again contain "Security-Verify" header as well as "Proxy-Require: mediasec" and "Require: mediasec". This communicates the use of the encryption and the encryption type. Additionally, the attribute "a=3ge2ae:requested" is required in the SDP. This defines the range of the encryption, in this case between IP-PBX and registration server.

2) If a RE-INVITE or UPDATE is initiated by the SIP client, the SIP headers and also the SDP attribute must be included again.

Translated with www.DeepL.com/Translator (free version)
</p>
</details>

**Comment by Omid-Mohajerani** [comment]
Its more practical to to setup a pbx in the middle and trunk to german telecom with encryption and then register your linphone desktop apps in your own pbx .
