### ISSUE TITLE
The linphone-desktop of windows version will crash if the sound card's name has Chinese characters

### ISSUE THREAD

**Issue by JimYang365** [BelledonneCommunications/linphone-desktop#363]
The linphone-desktop of windows version will crash when open preferences if the sound card's name has Chinese characters. I build it by the master codes, and [today's ci artifacts](https://gitlab.linphone.org/BC/public/linphone-desktop/-/jobs/238109/artifacts/download) will crash too. I try to fix it by calling `setlocale` before `wcstombs_s` in `add_or_update_card` .  And I think the `inputlen` variable was not calculated correctly. Hope you can fix it, thanks.

https://gitlab.linphone.org/BC/public/mswasapi/blob/master/mswasapi.cpp#L502

``` cpp
static void add_or_update_card(MSSndCardManager *m, bctbx_list_t **l, LPWSTR id, LPWSTR wname, EDataFlow data_flow) {
    MSSndCard *card;
    const bctbx_list_t *elem = *l;
    uint8_t capabilities = 0;
    char *idStr = NULL;
    char *nameStr = NULL;
    size_t inputlen;
    size_t returnlen;
    const char* locale = NULL;

    locale = setlocale(LC_ALL, "");
    if (locale) {
        setlocale(LC_ALL, locale);
    }

    inputlen = (wcslen(wname) + 1) * 2;
    nameStr = (char *)ms_malloc(inputlen);
    if (!nameStr || wcstombs_s(&returnlen, nameStr, inputlen, wname, inputlen) != 0) {
        ms_error("mswasapi: Cannot convert card name to multi-byte string.");
        goto error;
    }
    inputlen = (wcslen(id) + 1) * 2;
```

![image](https://user-images.githubusercontent.com/44395677/81380334-5139da80-913d-11ea-80fa-91f43b3b1d1d.png)

**Comment by JimYang365** [comment]
Can you help me see this, @julonexus , thanks.

**Comment by julonexus** [comment]
Hi, what do you think about replacing name conversion by :
`std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
	std::string narrow = converter.to_bytes(wname);
	inputlen = wcslen(wname) + 1;
	nameStr = (char *)ms_malloc(narrow.size() );
	strcpy(nameStr, narrow.c_str());`

**Comment by JimYang365** [comment]
Hi, @julonexus 
The `nameStr` was decoded in `UTF-8`, and in some place the linphone app use `qt local8bits string` to compare with `nameStr`. So, it can't work correctly.

**Comment by julonexus** [comment]
What about something like that?
```cpp
UINT currentCodePage = GetACP();
int size_needed = WideCharToMultiByte(currentCodePage, 0, wname, inputlen, NULL, 0, NULL, NULL);
std::string strTo( size_needed, 0 );
if(!WideCharToMultiByte(currentCodePage, 0, wname, inputlen, &strTo[0], size_needed, NULL, NULL)){
		nameStr = (char *)ms_malloc(strTo.length()+1 );
		strcpy(nameStr, strTo.c_str());
}else
		ms_error("mswasapi: Cannot convert card name to multi-byte string.");
		goto error;
}
```

**Comment by JimYang365** [comment]
Great, it works. Thank you. @julonexus

**Comment by julonexus** [comment]
[Commit](https://gitlab.linphone.org/BC/public/mswasapi/commit/56d0df44370e571e88b61347926038491ab1fae3)
