### ISSUE TITLE
How to created DMG file for linphone ? 

### ISSUE THREAD

**Issue by Omid-Mohajerani** [BelledonneCommunications/linphone-desktop#364]
Hi,

I have [downloaded and compiled linphone-desktop code in my mac. ](http://omid-mohajerani.blogspot.com/2020/05/compiling-linphone-desktop-in-mac-os.html). Now I want to create a DMG file from my new build.  Can u guide me how can I do it or what is the process?  Is there any script or generator for DMG for linphone?

**Comment by JimYang365** [comment]
Hi, @Omid-Mohajerani , please see here https://gitlab.linphone.org/BC/public/linphone-desktop/blob/master/.gitlab-ci-files/job-macosx-desktop.yml#L82 , you can make a DMG.

**Comment by Omid-Mohajerani** [comment]
@JimYang365 Great. Thank you for your help. It saved me a lot of time. Do you know where it reads the image and name of the APP?  Can the name be customized via make parameters as well? 

I already changed the icons in https://gitlab.linphone.org/BC/public/linphone-desktop/tree/master/linphone-app/assets/icons/hicolor and also linphone.svg but when I create DMG using your mentioned method it is still with linphone icon. 

<img width="540" alt="Screenshot 2020-05-15 at 11 28 51 AM" src="https://user-images.githubusercontent.com/5101364/82008825-4b457b80-96a0-11ea-9ec1-dd8ce48b3ae8.png">

**Comment by JimYang365** [comment]
Sorry, I do not know. I use the linphone default name and icon. @Omid-Mohajerani

**Comment by Omid-Mohajerani** [comment]
@JimYang365 ok. thanks for the help . I will update here when finding it.

**Comment by JimYang365** [comment]
Hi, @Omid-Mohajerani 
You can try to edit `linphone-desktop\linphone-app\application_info.cmake` to change the app name, I'm not sure whether it works.  
About the icon, please see here `linphone-desktop\linphone-app\assets\`.

**Comment by Omid-Mohajerani** [comment]
thanks, @JimYang365 for the icon path is  linphone-app/cmake_builder/linphone_package/macos/linphone.icns

**Comment by JimYang365** [comment]
😄

**Comment by Omid-Mohajerani** [comment]
but there is a problem with this kind of making DMG. It seems it is not included needed libraries to install. For example, I'm getting this error on the other systems 

When you are building using this method are u installing dependencies or libraries manually ? 

Dyld Error Message:
  Symbol not found: _libiconv_open
Expected in: /usr/lib/libiconv.2.dylib

**Comment by julonexus** [comment]
Linphone uses macdeployqt to embed libraries. I guess this is its work to get libiconv if needed.
But as you can create the DMG file, I'll close this issue.
Thanks @JimYang365  ;)
