### ISSUE TITLE
windows debug

### ISSUE THREAD

**Issue by Arvant** [BelledonneCommunications/linphone-desktop#365]
i compile linphne-desktop in windows with visual studio 2017
How i can debug it. i test with Debug config but visual studio can not open output and debuging project.

**Comment by julonexus** [comment]
You will get more help by asking on the mailing list or on stackoverflow-like.
Build in Debug config (CMAKE_BUILD_TYPE=Debug and --config Debug) and open the executable that is in the OUTPUT/bin folder. Visual are another debug message but I don't remember what is it (I'm using Qt Creator).
Logs will be in your log folder (all output are not redirect in Windows)
I'm closing this issue as it not one.
