### ISSUE TITLE
Linphone for desktop crashes when selecting preferances tab. 

### ISSUE THREAD

**Issue by CuriosityPentium** [BelledonneCommunications/linphone-desktop#369]
I have installed the free Linphone for desktop version 4.1.1 for Windows for use on my Windows 10 PC. The problem is the software crashes within the next few seconds after clicking the "preferences" tab. I have not yet installed any software components. Please Help.

**Comment by julonexus** [comment]
You should use the last version from https://www.linphone.org/snapshots/windows/app/

**Comment by CuriosityPentium** [comment]
Can you please tell me which last version of Linphone should I get. I downloaded Linphone for desktop Windows version on 25 May 2020.

**Comment by CuriosityPentium** [comment]
> 
> 
> You should use the last version from https://www.linphone.org/snapshots/windows/app/

Can you please tell me which last version of Linphone should I get. I downloaded Linphone for desktop Windows version on 25 May 2020.

**Comment by julonexus** [comment]
Last version is https://www.linphone.org/snapshots/windows/app/Linphone-4.2.0-alpha.59+eca8bd8a-win32.exe
But your issue should be fixed in the 25 May version

**Comment by CuriosityPentium** [comment]
Can you please conform wheter ypur suggested verson of Linphone is safe to install because I tested "Linphone-4.2.0-alpha.59+eca8bd8a-win32.exe" on virustotal.com and DrWeb is detecting it with "Tool.BtcMine.2285".  I have attached the image below. 
![Linphone virustotal test](https://user-images.githubusercontent.com/66019659/83328390-3cfe7e80-a2a0-11ea-8e91-2fac7825ebcd.png)
