### ISSUE TITLE
4.0 official release

### ISSUE THREAD

**Issue by bderembl** [BelledonneCommunications/linphone-desktop#37]
Have you made an official release of linphone 4.0?

I don't see it here
http://www.linphone.org/releases/sources/linphone/

**Comment by Wescoeur** [comment]
Yes, we have made an official release.

http://www.linphone.org/releases/sources/linphone/ => This link contains now the sources of the Linphone Core. (Not the Linphone Desktop 4.0.)

You can download a binary here: http://www.linphone.org/technical-corner/linphone/downloads
Or clone this repository if you want the sources.

**Comment by bderembl** [comment]
thanks.
do you plan to add linphone 4.0 here? http://www.linphone.org/releases/sources/linphone/

**Comment by Wescoeur** [comment]
Yes, it's planned for the next release in one month!
