### ISSUE TITLE
Login failure - no connection - FreeBSD12.1Stable

### ISSUE THREAD

**Issue by SteveBH** [BelledonneCommunications/linphone-desktop#380]
The application tries to confirm my credentialos and fails [red triangle].
This is now over  a week of inability to log in at all times of day and night.
Worked without issue until this bug.
Have checked my account on your site and can use browser to login and see my details so credentials fine there (Linphone.org sip). No changes to passphrase.
Tried reinstalling and couldn't then get my sip account to link and verify.
Have tried to get this to work on 3 freebsd os (2 ghostbsd and an old project-trident).
 *  I note when listing the pkg [see below] the licensing field is empty = **important**?
No changes to IPFW from old working system - ports are open as required:
00020 allow ip from any to any via lo0
01000 check-state :default
01050 allow tcp from any to any established
01100 allow udp from any to any established
02000 allow ip from any to any out keep-state :default
02050 allow ip6 from any to any out keep-state :default
02100 allow ipv6-icmp from any to any keep-state :default
02150 allow icmp from any to any keep-state :default
10000 allow tcp from any to any 5060 in keep-state :default
10001 allow udp from any to any 5060 in keep-state :default
10002 allow tcp from any to any 5061 in keep-state :default
10003 allow udp from any to any 5061 in keep-state :default
10004 allow udp from any to any 7078 in keep-state :default
10005 allow udp from any to any 9078 in keep-state :default
64000 deny log ip from any to any
65535 allow ip from any to any
This log from alternate system with same issue.
[linphone1.log](https://github.com/BelledonneCommunications/linphone-desktop/files/4733096/linphone1.log)
OS:
Operating system release:	FreeBSD 12.1-STABLE
OS architecture:		amd64
linphone-4.1.1_6,1
Name           : linphone
Version        : 4.1.1_6,1
Installed on   : Tue May  5 18:29:17 2020 AEST
Origin         : net/linphone
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : net
Licenses       : 
Maintainer     : ports@FreeBSD.org
WWW            : https://www.linphone.org/
Comment        : SIP client supporting voice/video calls and text messaging
Shared Libs required:
	libbctoolbox.so.1
	libQt5Gui.so.5
	libQt5QmlModels.so.5
	libQt5Core.so.5
	libQt5Concurrent.so.5
	libQt5Qml.so.5
	libQt5Widgets.so.5
	libQt5Network.so.5
	libQt5Quick.so.5
	libQt5Test.so.5
	liblinphone++.so.9
	liblinphone.so.9
	libQt5QuickControls2.so.5
	libbelcard.so.1
	libQt5TextToSpeech.so.5
	libQt5Svg.so.5
Annotations    :
	FreeBSD_version: 1201512
	icon           : http://www.pcbsd.org/appcafe/icons/net_linphone.png
	repo_type      : binary
	repository     : GhostBSD
Flat size      : 3.22MiB

Thanks,

Log file attached.

**Comment by nikolay-t** [comment]
This happens due to expiration of certificate
```
issuer name       : C=SE, O=AddTrust AB, OU=AddTrust External TTP Network, CN=AddTrust External CA Root
subject name      : C=SE, O=AddTrust AB, OU=AddTrust External TTP Network, CN=AddTrust External CA Root
issued  on        : 2000-05-30 10:48:38
expires on        : 2020-05-30 10:48:38
```
This is a good page about it: https://calnetweb.berkeley.edu/calnet-technologists/incommon-sectigo-certificate-service/addtrust-external-root-expiration-may-2020
It is not a code issue, but rather misconfiguration on server side. We should ask linphone service admin to remove expired certificate from server SSL chain.

As a temporary and insecure walk-around, it is possible to disable certificate verification by setting `verify_server_certs=0` in linphonerc.

**Comment by jehandelalune** [comment]
You may also manually replace file C:\Program Files (x86)\Linphone\share\linphone\rootca.pem by https://gitlab.linphone.org/BC/public/liblinphone/blob/master/share/rootca.pem

**Comment by SteveBH** [comment]
Thanks for  the assist - much appreciated.
New version due out next week [Desktop 4.2] with the fix [Peio Rigaux at BC].
