### ISSUE TITLE
compiling VPX error

### ISSUE THREAD

**Issue by linuxtmty** [BelledonneCommunications/linphone-desktop#382]
This error occurs when compiling VPX
<img width="720" alt="3" src="https://user-images.githubusercontent.com/8682294/83934873-68282700-a7e6-11ea-9978-e47f28073697.png">
What's the reason？

**Comment by jalowiczor** [comment]
I have the same problem while compiling on Windows 10.

**Comment by julonexus** [comment]
Having these errors doesn't seem to be an issue.
