### ISSUE TITLE
tel protocol?

### ISSUE THREAD

**Issue by Esantana0** [BelledonneCommunications/linphone-desktop#385]
I have seen that in the main page, it says that version 4.2 supports "click2dial", I understand by what it says that it will have web integration. I am testing the latest version of the alpha output today but the option to launch calls over the phone does not appear in any case, nor in the default applications. I do not know if this implementation is still in place or if I am misunderstanding it.

I understand that web integration is through the use of the tel protocol, and that the application will have to be configured so that it is taken by default by the operating system when mentioned on any website.

**Comment by julonexus** [comment]
Linphone can be called from URI handlers https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/URI%20Handlers%20%28Desktop%20only%29/?language=en
I think by "click2dial", it means to allow browsers to link the app the the URI
