### ISSUE TITLE
More call history

### ISSUE THREAD

**Issue by glebaccon** [BelledonneCommunications/linphone-desktop#386]
I think Linphone should display more call history.

The calls with status 'Aborted', 'EarlyAborted', 'AcceptedElsewhere' and 'DeclinedElsewhere' are not present from the "Previously" section.

I need them so I propose a small patch. Perhaps an option would be more appropriate in order to activate this behavior.
[linphone-desktop_more-history.zip](https://github.com/BelledonneCommunications/linphone-desktop/files/4765978/linphone-desktop_more-history.zip)

**Comment by julonexus** [comment]
Ha! It seems that a commit didn't pass on it...
Thanks for pointing that, I'll fix right away

**Comment by glebaccon** [comment]
Perhaps you can also customize the event message for all status in Chat/Event.qml

**Comment by julonexus** [comment]
Yes, later and if it is really needed ;)
The first release is soon™

**Comment by julonexus** [comment]
[commit](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/6278ebe966a9745154d075a7b8fb08e9566bea48)

**Comment by dsp76** [comment]
Linphone on MacOS is still missing missed calls in the history? Version 4.2.5
