### ISSUE TITLE
Merge hu (Hungarian - magyar) translations from Transifex

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-desktop#387]
Please merge hu (Hungarian - magyar) translations from Transifex. Thank you

**Comment by julonexus** [comment]
What are you talking about?
Updated date transifex for Hungarian was 18 May
Updated date on application was [19 May](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/8e1c7e83e5ece5a8cc7c5438e754717644e5e20a)

**Comment by ovari** [comment]
It is understood that the translations need to be manually merged as they are not automatically merged every week.

Not sure if we updated some of the translations since then.

Thank you
