### ISSUE TITLE
Automatically change http:// to https:// (force SSL)

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-desktop#388]
When `linphone.org` is typed into the address bar on the Firefox web browser, the `http://linphone.org/` website is shown and a lock warning ![image](https://user-images.githubusercontent.com/17465872/84652064-536a3280-af4e-11ea-92d6-8a6b33b065e5.png).

In the `.htaccess` file on the Linphone website, it is suggested to add:
````
# How to force SSL with .htaccess
# https://www.siteground.com/kb/how-to-force-ssl-with-htaccess/
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
````

What do you think?

Thank you

P.S. Sorry about listing this issue in `linphone-desktop` as `linphone-website` was not found or does not exist.

**Comment by Viish** [comment]
Hi,
We can't force the SSL as there are people around the world that aren't able to consult our website through SSL.
Cheers,
