### ISSUE TITLE
How to configure account to connect to multi-tenant pbx

### ISSUE THREAD

**Issue by strangerism** [BelledonneCommunications/linphone-desktop#39]
Hello

I am trying to use the desktop app with freeswitch pbx.

My freeswitch pbx support multi domain so I am trying to see if I can use the desktop version with the multi domain feature (or multi tenants).

I managed to configure the linphone desktop account using the following setup, assuming pbx ip is 192.168.1.82 and extension 0000002 (the pbx use 7 digits extension format) is under domain "mydomain".

SIP Address --> sip:0000002@mydomain
SIP Server Address --> <sip:192.168.1.82;transport=tcp>

the same setup was done on the linphone android app

username --> 0000002
domain --> mydomain
proxy --> <sip:192.168.1.82;transport=tcp>
outbound proxy --> Enabled

With this setup I managed to call successfully from app to desktop client (audio both directions), the problem I have is that I cannot call the extension registered on the app. 
The desktop client seems to ignore the proxy settings and the call does nothing (wireshark does not show any SIP flow) as it fails.

I wanted to investigate what prevents the desktop app to make the call, so I was trying to see if the client write any logs (I am using the mac version).

My question is, does the client write logs somewhere, and if yes where are they?

Apologies if this is not the right place to post this issue.

Thanks for your help

Massimo

**Comment by Wescoeur** [comment]
In the android app, you have enabled the `outbound proxy` option. On the desktop app, it's necessary to fill the `route` field. To do this, open the settings, edit your proxy account, and fill the field like this:

    <sip:192.168.1.82;transport=tcp>

For the logs, if you have compiled the sources, ensure you have the latest version:

    git pull --rebase
    git submodule update --init --recursive
    make

Then, go in the logs view (Settings Window), you can set logs path and enable this feature.
    
Otherwise, if you have downloaded the app, the logs are enabled by default in:

    ~/Library/Application Support/linphone/logs/

**Comment by strangerism** [comment]
Hi thank you for your quick answer, I appreciate a lot.

Indeed doing as you said it worked, I managed to do calls in both directions.

One last questions, using the routing/proxy feature against a multi-tenant pbx would in any way affect video streaming, as when I tried to enable video call all I got was a black screen.

I am going to see if I can find out the cause, but if you have an idea on top of your head that will be great.

Massimo

**Comment by strangerism** [comment]
I have change the title of the issue so other people might find this info easly in case they have the same question

**Comment by Wescoeur** [comment]
Thx. Normally the routing does not influence the video.
Have you tried with a low definition? Maybe the bandwidth is bad?

**Comment by Wescoeur** [comment]
@strangerism Can you give me an answer please?

**Comment by strangerism** [comment]
I am sorry, I haven't made much testing on this issue since then. I had to move on working on other things and then holiday. Feel free to close the issue. I will try investigate at some point again although I suspect the problem was with the pbx server configuration I was using.

**Comment by Wescoeur** [comment]
Okay, thx!
