### ISSUE TITLE
Contacts order/sorting

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-desktop#393]
The contacts are not sorted correctly as shown in the image below.

![image](https://user-images.githubusercontent.com/17465872/85933566-dbbbe080-b91b-11ea-87ca-0a30a34a8e63.png)

The incorrect order shown in the image is:
````
Obadiás
Relli
Zádor
Ócsa
Örkönd
Özséb
Ügyek Údó
Őzike
````

The correct order is:
````
Obadiás
Ócsa
Örkönd
Özséb
Őzike
Relli
Ügyek Údó
Zádor
````

If would be appreciated if you would please ensure the following characters (ó, ö, ő, ú, ü, ű) are sorted correctly.
````
#
*
0
⋮
9
a
⋮
n
o
ó
ö
ő
p
⋮
t
u
ú
ü
ű
v
⋮
z
````

![image](https://user-images.githubusercontent.com/17465872/85933656-f478c600-b91c-11ea-907f-7fde22e42c75.png)

There also seems to be a problem when lowercase and uppercase characters are used.
````
Özséb
Ügzek Údó
öz
````
While the display of the names can be a combination of uppercase and lowercase characters, the sorting should internally convert all strings to lowercase (or uppercase) before sorting. Would this solution work here?

Can this please be fixed as correct sort order of contacts is vital for usability.

What do you think?

Thank you 

Desktop 4.3.0-alpha-1-g439d1882 - Qt5.12.5
Core 4.4.0-2-g08f0afbe9
Linux Mint 19.3 Cinnamon 64-bit

This also occurs on Linphone 4.3 for Android. Does a separate issue need to be created for Android?

Does this issue need fixing on Windows, macOS, and iOS too?

Thank you once again

**Comment by julonexus** [comment]
Thanks for your feedback. Contacts are currently sorted on Unicode, so it is not fine for systems that are outside. The fix is simple : just add the local awarness of the Qt sort. I'll do that when I got time.

**Comment by ovari** [comment]
@julonexus will this be fixed for the Linphone 4.3 release? Thank you

**Comment by julonexus** [comment]
[commit](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/cbe85af852e1d876146da804e65b30bd5386e22b)

**Comment by ovari** [comment]
@julonexus does this fix also fix the Contacts sort order on the Linphone Android client? Thank you

**Comment by julonexus** [comment]
No, the fix is only on Linphone Desktop.

**Comment by julonexus** [comment]
`This also occurs on Linphone 4.3 for Android. Does a separate issue need to be created for Android?

Does this issue need fixing on Windows, macOS, and iOS too?`
Yes, you need to do that for Android (and iOS if it is the case)
