### ISSUE TITLE
Linphone window is incorrectly restored, should stay maximized

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-desktop#394]
1. Open Linphone
2. Maximize the Linphone window
3. Click ‘CONTACTS’
`bug` the Linphone window is no longer maximized.
4. Maximize the Linphone window
5. Click ‘HOME’
`bug` the Linphone window is no longer maximized.

When saving a contact, the Linphone windows restores, does not stay maximized.

Can you reproduce and please fix?

Thank you

Desktop 4.3.0-alpha-1-g439d1882 - Qt5.12.5
Core 4.4.0-2-g08f0afbe9
Linux Mint 19.3 Cinnamon 64-bit

**Comment by culebrasolida** [comment]
Same thing here
Desktop 4.2.0 - Qt5.12.5
Core 4.4.0-2-g08f0afbe9
Ubuntu 20.04 64 bits

**Comment by julonexus** [comment]
[Fixed](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/74f50933fd4eb3bdb29d9a766b249eb7c88c0bdd)

**Comment by ovari** [comment]
Thank you for fixing. Would [Linphone-4.3.0-alpha.4](https://www.linphone.org/snapshots/AppImages/) have the fix for testing when released? Thank you once again

**Comment by julonexus** [comment]
Yes, it will be available for the next nightly release

**Comment by ovari** [comment]
Isn't fixed with https://www.linphone.org/releases/linux/app/Linphone-4.2.2.AppImage

**Comment by julonexus** [comment]
The fix is only for master(so 4.3). Updates on 4.2 are mostly for critical fixes.
