### ISSUE TITLE
"(specify gateway IP)" Option missing in version 4.2.0 on macos

### ISSUE THREAD

**Issue by leuvataral** [BelledonneCommunications/linphone-desktop#395]
As shown in the image below, in version 3.9.1 of app, there was an option to specify the Gateway IP to use for outgoing calls:
![Screen Shot 2020-06-28 at 2 22 30 AM](https://user-images.githubusercontent.com/19230712/85939786-39353a80-b8e6-11ea-85ea-cb923866cb53.png)

This option is missing in the 4.x versions:
![Screen Shot 2020-06-28 at 2 23 02 AM](https://user-images.githubusercontent.com/19230712/85939796-4c480a80-b8e6-11ea-93d3-17f9b15b5ba7.png)

This is a very necessary option when we use Linphone from inside firewall or over VPN, otherwise there is no audio received because RTP packets are sent to an incorrect IP.

**Comment by julonexus** [comment]
This option is deprecated. Your VPN/firewall must be configured to forward correctly packets. So it is not a very necessary option when we use Linphone from inside firewall or over VPN. I'm sorry but we will not spend our limited time resources to maintain/implemented it unless it is requested from our sales department (sales@belledonne-communications.com)
