### ISSUE TITLE
compile is successful but app doesn't not launch

### ISSUE THREAD

**Issue by strangerism** [BelledonneCommunications/linphone-desktop#40]
Hello,

I have managed to compile the app but when I launch it from the build output folder

OUTPUT/desktop/build/linphone

a terminal windows opens up and I can see from the dock (I am on mac) that the app icon appears and disappears, like it would fail and close straight away.

I don't know where I would find logs of the app. The terminal windows stays open (see below)

```
Nicolas-MacBook-Air:~ massimo$ /Users/massimo/Linphone/linphone-desktop/OUTPUT/desktop/bin/linphone ; exit;
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Maybe I am not supposed to launch the app this way. How shall I launch it with logging enabled and where they will be located?

I followed the instructions in the README, the only difference is the QT installation, I have used a different compiler because QT 5.9 installation didn't have gcc_64 folder. 

This was the content of 5.9 folder

```
MacBook-Air:~ massimo$ ls Qt/5.9/
.DS_Store      android_armv7/ clang_64/      ios/ 
```

the environment variable were set as below 

```
Qt5_DIR="~/Qt/5.9/clang_64/lib/cmake"

export PATH="~/Qt/5.9/clang_64/bin/:$PATH"
```

Any help is appreciated

regards

Massimo

**Comment by strangerism** [comment]
[make.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/1114831/make.txt)

I am attaching a partial output produced from the make command.

**Comment by strangerism** [comment]
I have tried building an installation package (./prepare.py --package) just to see if this way I could validate the compilation and I get several rpath errors

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RP
ATH load command with path: /Users/massimo/Linphone/linphone-desktop/OUTPUT/desktop/lib found in: /Users/massimo/Linphone
/linphone-desktop/WORK/desktop/Build/linphone_package/Linphone.app/Contents/Frameworks/libswscale.2.dylib (for architectu
re x86_64), required for specified option "-rpath /Users/massimo/Linphone/linphone-desktop/OUTPUT/desktop/lib @executable
_path/../Frameworks"
Changing RPATH of libswscale.dylib from '/Users/massimo/Linphone/linphone-desktop/OUTPUT/desktop/lib' to '@executable_pat
h/../Frameworks'
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RP
ATH load command with path: /Users/massimo/Linphone/linphone-desktop/OUTPUT/desktop/lib found in: /Users/massimo/Linphone
/linphone-desktop/WORK/desktop/Build/linphone_package/Linphone.app/Contents/Frameworks/libswscale.dylib (for architecture
 x86_64), required for specified option "-rpath /Users/massimo/Linphone/linphone-desktop/OUTPUT/desktop/lib @executable_p
ath/../Frameworks"
-- Configuring incomplete, errors occurred!
See also "/Users/massimo/Linphone/linphone-desktop/WORK/desktop/Build/linphone_package/CMakeFiles/CMakeOutput.log".
make[3]: *** [/Users/massimo/Linphone/linphone-desktop/WORK/desktop/Stamp/TARGET_linphone_package/TARGET_linphone_package
-configure] Error 1
make[2]: *** [CMakeFiles/TARGET_linphone_package.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [desktop-build] Error 2
```

**Comment by strangerism** [comment]
I resolved all the compile issues by checking out tag 4.0 and working on that instead.

**Comment by strangerism** [comment]
I did troubleshoot furthermore this compiling issue on master branch.

I have noticed that having a preferences folder already created and populated with files (e.g. by running once the distributed app downloaded from your site) won't crash the newly compiled app.

Although if I delete anything in /Users/<username>/Library/Preferences/Linphone the compiled app will crash as if it fails to write in there. This doesn't happen if I compile from branch 4.0

**Note:** the compiled app as mentioned is just vanilla master branch, no files have been modified.

**Comment by ghismary** [comment]
This is fixed with this git revision:

commit 39cc76d46b2ca6e1d2b2ceef9693ddc430c35f91 (HEAD -> master, origin/master, origin/HEAD)
Author: Ghislain MARY <ghislain.mary@belledonne-communications.com>
Date:   Tue Jul 4 17:56:42 2017 +0200

    Fix crashes when starting the application if no linphonerc file exists yet.
