### ISSUE TITLE
question: Encryption in Linphone 4.2

### ISSUE THREAD

**Issue by WPFilmmaker** [BelledonneCommunications/linphone-desktop#401]
I remember seeing that Linphone for android/iphone has linphone's own encryption protocol (LIME), I saw 4.2 for desktop is out but in the release notes encryption was not mentioned. Is LIME included in linphone for desktop or are there plans to work on it? Thanks.

**Comment by julonexus** [comment]
Lime3 is not yet supported by Linphone Desktop and is not on the current plan.

**Comment by WPFilmmaker** [comment]
@julonexus I have a question so I am writing you here and not reopening the ticket.

If Lime is not supported, how can smartphone and pc versions send encrypted messages to each others? Or does smartphone use LIME with other smartphone and another protocol with pc?

Also on the website I can see for the pc version:
Secure communications:
• Benefit from secure user authentication with TLS certificates
• Make encrypted audio and video calls with SRTP, STRP-DTLS or ZRTP
• **Secure your messages with Linphone’s powerful end-to-end encryption protocol. Users can privately and asynchronously exchange messages, so that only you and your friend can decrypt the content that you have shared**

Does it refer to LIME or is it another protocol? If it is LIME does it mean plans changed since you sent your previous message?
Thanks

**Comment by julonexus** [comment]
I don't read that on https://www.linphone.org/technical-corner/linphone
Where did you get it?

**Comment by julonexus** [comment]
As Desktop doesn't support Lime, you will not get encrypted messages. It will not make sense to receive them ;)
So smartphone and pc versions cannot send encrypted messages to each others.

**Comment by WPFilmmaker** [comment]
> I don't read that on https://www.linphone.org/technical-corner/linphone
> Where did you get it?

https://www.linphone.org/features (click on desktop) so maybe a mistake on the site?

@julonexus (about your previous message) that's what I assumed :D

**Comment by julonexus** [comment]
I saw that after checking where you could get this information and we removed it some time later ;)
