### ISSUE TITLE
Contacts from CardDAV Server

### ISSUE THREAD

**Issue by lukasubo** [BelledonneCommunications/linphone-desktop#402]
Hello,

Since liblinphone supports reading contacts from CardDAV servers, could this be integrated with Linphone Desktop? This would allow syncing contacts from Android.

Thanks

https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Vcard4%20contacts/

**Comment by julonexus** [comment]
Duplicate of #349
