### ISSUE TITLE
[Feature Request] Provide Raspberry Pi build howto

### ISSUE THREAD

**Issue by StefanGies99** [BelledonneCommunications/linphone-desktop#404]
Hi folks, 

I'm currently busy with building linphone for Raspberry Pi 3. 
The process of buiding takes quite long and there's no updated information available about how to build with Cmake. 
Can you update the [setup guide](https://www.tal.org/tutorials/building-qt-512-raspberry-pi) for this? 
Also there's no release available of qt5.12 on the raspbian repo. How can I setup this without compiling the source of 5.12?
When compiling from source it would take about 6 hours of build time which is quite long.

**Comment by GieForce** [comment]
Any updates on this so far?
