### ISSUE TITLE
Linphone 4.2.1 Windows, crash when playing sounds

### ISSUE THREAD

**Issue by hrickes** [BelledonneCommunications/linphone-desktop#407]
The program crashes with "application error 1000" when playing the ringtone or when making audio calls.

Outgoing Video calls without activated audio codec are ok.

When I replace the opus.dll file with the version of Linphone-4.1.1-win32.exe everything is ok.

Name der fehlerhaften Anwendung: linphone.exe, Version: 0.0.0.0, Zeitstempel: 0x5eff3017
Name des fehlerhaften Moduls: opus.dll, Version: 0.0.0.0, Zeitstempel: 0x5eff2d17
Ausnahmecode: 0xc000001d
Fehleroffset: 0x0004874d
ID des fehlerhaften Prozesses: 0x3228
Startzeit der fehlerhaften Anwendung: 0x01d65c11eb53f6df
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Linphone\bin\linphone.exe
Pfad des fehlerhaften Moduls: C:\Program Files (x86)\Linphone\bin\opus.dll
Berichtskennung: bfdae031-e716-48d2-af0b-8e5422a9c00d
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by julonexus** [comment]
Hi, could you test this [windows app](https://www.linphone.org/snapshots/temp/Linphone-4.3.0-alpha.15+01ff927c-win32.exe) please?

**Comment by hrickes** [comment]
Hi, this Version crash with "application error 1000" when I going to Preference->Audio.

Name der fehlerhaften Anwendung: linphone.exe, Version: 0.0.0.0, Zeitstempel: 0x5f16e0f1
Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.19041.207, Zeitstempel: 0x1bdbc4b8
Ausnahmecode: 0xc0000374
Fehleroffset: 0x000e5af3
ID des fehlerhaften Prozesses: 0x1f14
Startzeit der fehlerhaften Anwendung: 0x01d65f6627f00104
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Linphone\bin\linphone.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\SYSTEM32\ntdll.dll
Berichtskennung: 28ee35c1-db6e-44af-9ded-e9a5efc6e00e
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

[linphone1.log](https://github.com/BelledonneCommunications/linphone-desktop/files/4953928/linphone1.log)

**Comment by julonexus** [comment]
The goos news is that it is not about opus anymore.

**Comment by hrickes** [comment]
if I use the opus.dll from Linphone-4.3.0-alpha.15+01ff927c-win32.exe in Linphone-4.2.1-win32.exe everything is ok.

**Comment by Chambana** [comment]
I had a similar issue with the Windows GUI on 4.2.1 and 4.3.0.  The audio was high pitched and unintelligible. I was testing over my LAN with the other endpoint running linphonec on Linux.  
Replacing the Windows Linphone client with a MicroSIP client delivered perfect audio quality, so I think the issue is with Windows Linphone.

**Comment by julonexus** [comment]
Could you test [this version](https://www.linphone.org/snapshots/temp/Linphone-4.2.2-pre.1+0e1f1f36-win32.exe) please?

**Comment by hrickes** [comment]
Hi, this version works very well. Incoming and outgoing calls with audio are now possible without any problems.

**Comment by julonexus** [comment]
[Fixed](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/bcfc99d2be5594d7a8496f3855f55a4602fc59db)
