### ISSUE TITLE
Invalid svg file

### ISSUE THREAD

**Issue by vishalrawat123** [BelledonneCommunications/linphone-desktop#408]
I've customized images although the format is SVG and dimension are the same but getting this. 

![Screenshot from 2020-07-17 21-30-26](https://user-images.githubusercontent.com/58972615/87806690-e6132f80-c874-11ea-8de2-2263847cb768.png)

**Comment by linuxtmty** [comment]
I also have this problem

**Comment by vishalrawat123** [comment]
@linuxtmty I got fixed it up it was due to the missing of XML in SVG image code.so just add it up now working fine. I am closing this issue for now
