### ISSUE TITLE
MacOS - Call notification is being displayed on all screens

### ISSUE THREAD

**Issue by oliverhr** [BelledonneCommunications/linphone-desktop#409]
If you have a setup with multiple displays (tested with two), the notification is displayed on each display, this is a bit annoying since on call the notification "get" focus so all the displays change to the main desktop screen on each display.

can you add an option to select if we want this behavior or the notification should be displayed only in the main display?

Additional info:

```
Desktop 4.2.1 - Qt5.14.2
Core 4.4.0-3-gcfaf00e3c

MacOS Catalina - 10.15.5
```

**Comment by julonexus** [comment]
>  so all the displays change to the main desktop screen on each display.
Could you clarify this sentence please?

**Comment by oliverhr** [comment]
yes, you can have multiple desktops or fullscreen apps, so when the call notification is displayed on all the screens the focus an all the screens change from the current fullscreen app you have currently active the displays to the desktop screen where the notification is shown.
