### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by robdyck** [BelledonneCommunications/linphone-desktop#414]
Linphone desktop 4.2.1 from appimage
Linphone crashes on incoming call. Libopus seems to be the culprit.

          PID: 585031 (AppRun.wrapped)
           UID: 1000 (rdyck)
           GID: 1000 (rdyck)
        Signal: 4 (ILL)
     Timestamp: Mon 2020-07-27 10:19:46 PDT (2h 11min ago)
  Command Line: /tmp/.mount_Linphotse5Zu/AppRun.wrapped
    Executable: /tmp/.mount_Linphotse5Zu/usr/bin/linphone
 Control Group: /user.slice/user-1000.slice/session-6.scope
          Unit: session-6.scope
         Slice: user-1000.slice
       Session: 6
     Owner UID: 1000 (rdyck)
       Boot ID: c33b6cb394074d9cb29f35906232ce0e
    Machine ID: 880918cfecb14877a508dfde3dbbf333
      Hostname: blacky.mylan
       Storage: /var/lib/systemd/coredump/core.AppRun\x2ewrapped.1000.c33b6cb394074d9cb29f35906232ce0e.585031.1595870386000000000000.lz4
       Message: Process 585031 (AppRun.wrapped) of user 1000 dumped core.
                
                Stack trace of thread 585056:
                #0  0x00007f2ac2d439d2 n/a (/tmp/.mount_Linphotse5Zu/usr/lib/libopus.so.0 + 0x39d2)

**Comment by julonexus** [comment]
[duplicate](https://github.com/BelledonneCommunications/linphone-desktop/issues/379)
