### ISSUE TITLE
OSX package error

### ISSUE THREAD

**Issue by tqcenglish** [BelledonneCommunications/linphone-desktop#42]
This error occurs when adding the `-package` parameter to compile
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RPATH load command with path ...
```

**Comment by ghismary** [comment]
The install_name_tool error you have here is normal and is not the real cause of the failed build. I have commited some fixes and the build with the --package parameter should now build correctly and any Mac OS X computer.

**Comment by strangerism** [comment]
Yes. I can confirm that now I am able to run package from master branch on Mac OS X, although the app still fails to launch.

**Comment by ghismary** [comment]
The crash on launch has also been fixed. Take a look at issue #40.
