### ISSUE TITLE
Noise removal too strong after 4.2 update, removes parts of voice (Linux AppImage)

### ISSUE THREAD

**Issue by UniqueActive** [BelledonneCommunications/linphone-desktop#420]
Hello,

After the 4.2 update, the noise removal seems to be a lot more aggressive (or I guess you could say effective?) in removing audio, to the point of removing audio of a speaking person.

I understand this may work well in some environments and with some microphones, but in environments with a lot of ambient noise, it fails to distinguish between voice and noise and removes significant parts of the voice, forcing me to switch to Linphone Android where I can hear the other person fine.

Since our brains are better at picking out a voice over some noise, I would prefer to hear a little more noise if that means that I can make out what the other person is saying. Would it be possible to provide options for tweaking the noise/echo removal aggressiveness?

Thanks in advance!

**Comment by julonexus** [comment]
Hi, there is an option that you can set in linphonerc under sound section: "ec_delay=x" (where x is the delay in ms). You can set it in a higher value or tweak it by yourself.
There is no GUI for that, but a future update will contain the echo cancellation calibration like in Android.
