### ISSUE TITLE
DSCP (DiffServ, QoS): not set

### ISSUE THREAD

**Issue by traud** [BelledonneCommunications/linphone-desktop#421]
In the user interface of Linphone, Preferences → Network → DSCP is enabled on default. However, when I trace SIP and RTP traffic, the field for DSCP is null in Wireshark. When I set/change the DSCP values including the one for video, DSCP is still not set on the network layer. Just reporting, had no chance to look into the source code, yet.

Tested:
- Linphone 4.2.2
- Ubuntu 20.04 LTS and Windows 10 Version 1809

**Comment by julonexus** [comment]
This is a kernel issue. DSCP doesn't fully work on dual-stack and there is issues on Mac too. Disable Ipv6 from the option if you really want this feature.
There is a high chance that it will be removed in future version of Linphone-Desktop, this is already the case for Linphone-Android.
