### ISSUE TITLE
Cannot build the project on Windows 10

### ISSUE THREAD

**Issue by singhravi1** [BelledonneCommunications/linphone-desktop#423]
Hi,

I've followed the README guidelines to build this project on windows and tried many iterations as well but its been few days and I'm still getting errors in build and it is not returning any output to run.

### I've installed,
- cmake v3.18.1 64 bit (tried 32 bit too)
- python v3.6
- yasm v1.3.0 32 bit (tried 64 too)
- nasm v2.14.02 64 bit (tried 32 bit too)
- doxygen v1.8.19
- perl (using Strawberry v5.30.2.1 64 bit (tried 32 bit too))
- Pystache installed via pip
- six installed via pip
- MinGW (installed from the installer downloaded from the given link, https://sourceforge.net/projects/mingw/)

### Ran following commands (can be seen in logs as well),
- `C:\Qt\5.12.9\msvc2017\bin\qtenv2.bat`
- `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"`
- `cmake .. -DCMAKE_BUILD_PARALLEL_LEVEL=10 -DCMAKE_BUILD_TYPE=RelWithDebInfo -A Win32`
- `cmake --build . --target ALL_BUILD --parallel 10 --config RelWithDebInfo`

## Logs
ALL the logs from setting env variables to build getting failed **can be found here**, https://pastebin.com/ubT2F1Uc

There were two shell popups while building, both have errors, see below
<img width="775" alt="Annotation 2020-08-18 042309" src="https://user-images.githubusercontent.com/20294674/90455846-c5a8f000-e114-11ea-9247-32d54cd21e79.png">
<img width="767" alt="Annotation 2020-08-18 043240" src="https://user-images.githubusercontent.com/20294674/90455854-c93c7700-e114-11ea-91a7-4e559701f091.png">

Please suggest.
**Please let me know if anything else is needed.**

**Comment by julonexus** [comment]
Hi
Your GCC that is used is not the good one. You must have "6.3.0" in your logs. Move your Mingw folder before perl and others in your PATH. 
Errors from other console are "normal"

**Comment by singhravi1** [comment]
Thanks a lot for the suggestion @julonexus !
I moved C:\MinGW\bin to the top in PATH variable.
And now you can find the gcc 6.3.0 in the log, https://pastebin.com/XeLweYiP
But there were still multiple sqlite related errors and EP_vpx build error.
Also, I checked OUTPUT folder and it does not have any file.
Can you please also confirm that after successfull build we'll get a .exe file in OUTPUT folder?

Please suggest. Thanks

**Comment by julonexus** [comment]
For VPX, remove these lines:
https://gitlab.linphone.org/BC/public/linphone-cmake-builder/blob/master/builders/vpx.cmake#L81-89

**Comment by singhravi1** [comment]
Hey @julonexus ,
I updated the lines as you suggested in file, linphone-desktop\linphone-sdk\cmake-builder\builders\vpx.cmake, and the error was not there anymore. thanks!
But the `OUTPUT` dir is still empty.
Can you please suggest what could be the reason?
You can find the build logs here,  https://controlc.com/49f7098f

**Comment by julonexus** [comment]
These issues aren't a problem for getting the build. So we are not going to actively spend time to resolve them. But you can do it if you want ;)
By the way, be advise that this is not a helping forum. You should ask on stack-overflow or on the mailing list if you want more help from people.

**Comment by singhravi1** [comment]
@julonexus Got it. I thought it was an actual problem with latest windows 10. Thanks a lot btw!
