### ISSUE TITLE
Error while running "successfully" created appimage

### ISSUE THREAD

**Issue by singhravi1** [BelledonneCommunications/linphone-desktop#425]
Hi,

I configured the project with -DENABLE_APP_PACKAGING=YES and created the build.
There was no error and build was successfull.
But when i run the created package, i get the following error,
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

[1]    3966 abort (core dumped)  ./Linphone-4.5.1.AppImage
```

Am i missing something? Please suggest.

**Comment by singhravi1** [comment]
Hey @julonexus ,
Can you please suggest anything for this?

**Comment by singhravi1** [comment]
Fixed it!
Qt5_DIR and PATH variables were not set.
Very silly, I know.

**Comment by ankurios10** [comment]
@singhravi1 - Please help me in compilation, I am also phasing same issue. I even set Qt5_DIR and PATH variables .
You can message me +91 8010022711.
