### ISSUE TITLE
Contacs with german Umlaute crashes linphone at start

### ISSUE THREAD

**Issue by Jogile1** [BelledonneCommunications/linphone-desktop#428]
If you add a contact in linphone for windows with an german Umlaut, e.g. Jürgen, then linphone will crash each time you try to start linphone.

**Comment by apollo40** [comment]
Have a similar issue. When the Windows User has a German Umlaut in his/her Name.

So i think there a general Problem with German Umlaute and crashes of the Client.

**Comment by bugybunny** [comment]
IIRC Linphone 4.1.1 did not allow umlauts and I just could not save the contact. With 4.2.2 if I save one it will be shown until I restart and then just does not pop up anymore in my contact list, but no crash when starting.

**Comment by Jogile1** [comment]
@bugybunny Thanks for the infos! With my version (4.2.2) I now can save a contact with german Umlaut, too. In my case, if I restart linphone, the contact name disappears and therefore the telephone number is shown. I don´t know, why linphone not crashes now. Maybe because I have more contacts in my contact list now?!

![Screenshot 2020-09-25 142048](https://user-images.githubusercontent.com/71124906/94266336-48a23f00-ff3a-11ea-9900-5dd1cb007324.png)

**Comment by julonexus** [comment]
Hi, the [4.2.3](https://www.linphone.org/releases/windows/app/Linphone-4.2.3-win32.exe) contains the fix about this Umlaute on Windows. I fixed the lost contact when using commas too.
Also, it will be available on the next nightly build.
