### ISSUE TITLE
Set linphone as default app for tel or callto protocol in windows 10

### ISSUE THREAD

**Issue by Jogile1** [BelledonneCommunications/linphone-desktop#429]
Unfortunately linphone for windows don´t add itself as default protocol handler in Windows 10.

So here is a workaround:

1. Add LinphoneCall.bat to "c:\Program Files (x86)\Linphone\bin\"
2. Add LinphoneCall.reg to your Windows 10 (by double click this file)
3. Reload your registry settings (by restart your PC or just by sign out and sign in)

Now you should be able to use LinphoneCall.bat as default handler for tel or callto links (e.g. in Browser or Thunderbird Contacts)

Notice: This will only work, if you install linphone for windows in the default directory (here it is c:\Program Files (x86)\Linphone\bin\). If you have a different install directory, you will have to modify both files LinphoneCall.bat and LinphoneCall.reg according to your needs.

[linphone.zip](https://github.com/BelledonneCommunications/linphone-desktop/files/5208051/linphone.zip)

**Comment by julonexus** [comment]
Thanks for your feedback. Windows, Linux and Mac now support tel and callto.
[commit](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/d54ebbcc598a834d4e6ea4c0fb05fba9a019cee6)

**Comment by countzero** [comment]
@Jogile1: Thank you for sharing. Works like a charm!

@julonexus: Is there a roadmap for Linphone to implement this configuration via the installer?

**Comment by Jogile1** [comment]
> 
> 
> @Jogile1: Thank you for sharing. Works like a charm!
> 
> @julonexus: Is there a roadmap for Linphone to implement this configuration via the installer?

As julonexus mentioned above, this issue should be solved already. Unfortunately, it is not - therefore I´m further using my workaround. I don´t know, if there is somebody who will implement my solution in future.

**Comment by angelaki** [comment]
Any news on this?

**Comment by canove** [comment]
> Thanks for your feedback. Windows, Linux and Mac now support tel and callto.
> [commit](https://gitlab.linphone.org/BC/public/linphone-desktop/commit/d54ebbcc598a834d4e6ea4c0fb05fba9a019cee6)

The version containing this feature is already released? 

I'm using @Jogile1 workaround, works like a charm!

**Comment by chrisandrewmann** [comment]
Also used @Jogile1 workground, thanks it's great. However I found a problem with links that contain spaces in them so made an adjustment to the batch file here so it handles those correctly.

```
@echo off

SETLOCAL ENABLEDELAYEDEXPANSION
set str=%1%
set "str=!str:%%20=!"
set str=%str:tel:=%
set str=%str:callto:=%

start /min "" "C:\Program Files (x86)\Linphone\bin\linphone.exe" "call sip-address=%str%"
```

**Comment by q00d0** [comment]
@julonexus 

This does not work in this version:
![image](https://user-images.githubusercontent.com/11162933/141661286-45e31eef-3823-49a2-a527-577d28494783.png)

**Comment by UkeFan** [comment]
@julonexus Could you name us ANY version in which Linphone can handle call-to-links in Mac Big Sur? I just can't find anything ); Thanks!

**Comment by angelaki** [comment]
Any plans on native support?

**Comment by ilmaisin** [comment]
On 4.3.2, tel links do not work. It opens Linphone, but does not offer to place a call to the number of the url. Sip links work fine, though.

**Comment by Jogile1** [comment]
> 

@ilmaisin Maybe this is the problem. You have to choose LinphoneCall.bat as default Handler for tel links, not linphone.exe!!!
The easiest way to do that, is to create a html File, e.g. callto.html with following content:
<a href="tel:phone number you want to call">Text for phone number you want to call</a>
If you open this callto.html file in your browser, just click on the link you´ve just created. Then you can choose LinphoneCall.bat as default Handler for tel Links.
![grafik](https://user-images.githubusercontent.com/71124906/158768315-529d8ef7-d7cd-49cd-b54e-e4fd3ddfe1e0.png)

**Comment by mooneydude** [comment]
@Jogile1 your workaround does the trick in Windows. do you know how we can implement your solution on macOS? maybe a shell script similar to your bat?

**Comment by viktoriasee** [comment]
I confirm the issue still exists in version 4.4.8 (current stable) for Windows. Please fix!

The workaround does not work for me. When I try to set the default protocol handlers in Windows 10 I can only choose apps from a list or from the Microsoft store. But no .bat file.

**Comment by Jogile1** [comment]
> I confirm the issue still exists in version 4.4.8 (current stable) for Windows. Please fix!
> 
> The workaround does not work for me. When I try to set the default protocol handlers in Windows 10 I can only choose apps from a list or from the Microsoft store. But no .bat file.

It´s important to execute the REG File within the linphone.ZIP File!!! Then you have to reboot your pc. When you then open your default apps per protocol, you´ll see, that the protocol "callto" is registered with LinphoneCall.bat.

![image](https://user-images.githubusercontent.com/71124906/199552035-e68fd3e1-2ad5-4caa-bd4d-023ef5bcb503.png)

By the way, the linphone version I use is Desktop 4.4.10-QT5.15.2

**Comment by ilmaisin** [comment]
The thing is that it should not need any esoteric workarounds, but it should work out of the box after installing Linphone.

**Comment by mooneydude** [comment]
@chrisandrewmann any reason your 'space fix' stopped working with the newest Windows Desktop v5.0.10?

**Comment by chrisandrewmann** [comment]
Sorry @mooneydude, not sure why. I've had to stick to using 4.3.2 because I had problems after a Windows 11 upgrade.

**Comment by mooneydude** [comment]
@chrisandrewmann the update installed under "c:\Program Files\Linphone\bin" and not "c:\Program Files (x86)\Linphone\bin". its always something

**Comment by julonexus** [comment]
The application has changed from win32 to x64 so path has changed.
As long as you are using HKEY_CURRENT_USER in your regs, you're overwriting the Linphone config that set handlers to HKEY_CLASSES_ROOT (which backport to HKEY_LOCAL_MACHINE). Linphone doesn't erase your custom reg as it is not part of the installation.

On fresh Windows installations, typing "callto:user@domain.com" in a browser (Edge) will open the installed application.
That was tested on Windows 10 and 11.
