### ISSUE TITLE
Linphone on windows7 starts and crahes immidiately

### ISSUE THREAD

**Issue by mabra** [BelledonneCommunications/linphone-desktop#430]
Hello!
I just this day downloaded linphone (Linphone-4.2.2-win32.exe) and installed it successfully.
Bit it does not start and issues the following error message:
---------------------------
linphone.exe - System Error
---------------------------
The program can't start because qwave.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

Any help would be great!

Thanks anyway.

**Comment by Jogile1** [comment]
I searched on my windows 10 for qwave.dll. It seams, that it is a System File from windows itself and should exist on your system.
Furthermore I think, that the blue marked it necessary for linphone.

![Screenshot 2020-09-14 122252](https://user-images.githubusercontent.com/71124906/93074830-3516ee80-f685-11ea-8b67-914425c6c275.png)

**Comment by mabra** [comment]
Thank you very much!
I dont came to that idea ;) 
And Indeed, I am using the server version ("Windows Server 2008 R" - I am on the
was to remove all my windows computers), which dont has this file, but
I was able to fix it!
