### ISSUE TITLE
Contact names with commas are lost upon program start

### ISSUE THREAD

**Issue by mbunkus** [BelledonneCommunications/linphone-desktop#435]
Placing a comma anywhere in a contact's name works fine as long as you don't restart the program. Upon restart the contact's name is replaced by its number.

For example, create a contact called `cow, moo` with a SIP number, e.g. `12345`. The result looks OK in the contact list; you can browse it just fine, searching for `w, m` yields that result.

Here's how the vcard content looks in `friends.db`:

```
[0 mosu@ketani ~/.local/share/linphone] echo "SELECT vcard FROM friends WHERE id = 2004;" | sqlite3 friends.db 
BEGIN:VCARD
VERSION:4.0
FN:cow, moo
IMPP:sip:12345@somewhere
END:VCARD
```

Now restart linphone & browse the contacts again. You'll notice that the contact shows up as `12345` and that its name `cow, moo` is nowhere to be found.

This is:
Desktop 4.3.0-alpha-23-g82b90a85 - Qt5.15.1
Core 4.5.0-alpha-155-g244b70154

**Comment by julonexus** [comment]
Hi, the [4.2.3](https://www.linphone.org/releases/linux/app/Linphone-4.2.3.AppImage) contains the fix. Also, it will be available on the next nightly build.
