### ISSUE TITLE
Custom notification size

### ISSUE THREAD

**Issue by glebaccon** [BelledonneCommunications/linphone-desktop#439]
Hello,

First of all, the last nightly for desktop is very cool. Thanks for the workaround to see previous calls.

I wanted to suggest you a last modification to improve user experience. Can you add the ability to customize the size of the desktop notification in a settings page, please ?

The best would be the width of the notification because in the most case (for us in particular) the caller name is long and it is truncated.

It can be a good idea to display 2 lines for the caller name also, but the first solution above would suffice.

Thank you for taking my request into account.

**Comment by julonexus** [comment]
Hi, The next notification implementation will use System notification. So there will be no new options about the current notification.
Also, it will not be available for a moment as it will be done on free-time.
