### ISSUE TITLE
Linphone MacOS  desktop app

### ISSUE THREAD

**Issue by apfalmeida** [BelledonneCommunications/linphone-desktop#442]
At least on Linphone Desktop App 4.2.3 and 4.2.2 the configuration generated does not honor all capital letters on some pathnames.
On MacOS this is not usually a problem, unless you have the filesystem formated in a "Case-sensitive" fashion. This is not the default but as any Unix system, the case is important.

Ex:
rootca.pem installation path:

/Applications/Linphone.app/Contents/Resources/share/Linphone/rootca.pem

related configuration line on linphonerc (~/Library/Preferences/linphone/linphonerc):

root_ca=/Applications/Linphone.app/Contents/Resources/share/linphone/rootca.pem

This can be be workarounded with a symbolic link but if possible, it should be corrected on the application.

Thanks in advance,

Pedro

**Comment by julonexus** [comment]
There is a fix about it and it is merge on master. It will be available in the next nightly build.
