### ISSUE TITLE
Unable to click on call notifications or to see incoming calls in call history

### ISSUE THREAD

**Issue by Qdion** [BelledonneCommunications/linphone-desktop#443]
Every time I have an incoming call (answered or not) it's never report in the call history list. 
And if i miss a call, i can't click on the notification icon so I have no way to know what call I missed.
When I look at the log file, i can confirm that the call is well received. 

I use the latest Windows Desktop app (4.2.3)

**Comment by julonexus** [comment]
Duplicate of #397
The fix is in the nightly build and will be available for 4.3
