### ISSUE TITLE
Feature Request: Disable Recording

### ISSUE THREAD

**Issue by wurschtsupp** [BelledonneCommunications/linphone-desktop#448]
We would like to use linphone in our authority. We only use linux desktops. The current linphone version in our distribution is 3.12.0. Our staff representatives have a problem with the recording function in linphone. It would be helpful if linphone had a configuration option that disables the recording functions.

**Comment by julonexus** [comment]
We don't support 3.12 anymore so you have to upgrade your distribution (or do pressure on mainteners :p)
There is an option to deactivate auto recording in the options in the current release 4.2.3

**Comment by wurschtsupp** [comment]
Thank you. Now i have instaled 4.2.3, but i can't find any option to deactivate recording.

**Comment by julonexus** [comment]
The option is in :
Settings => Calls and Chat => Automatically record calls

**Comment by wurschtsupp** [comment]
I found that. I thought, however, that there should be a possibility that the recording function can generally be deactivated. For data protection reasons.

**Comment by julonexus** [comment]
On the public version, the state depends of the configuration file. So Linphone could protect the reactivation by a password (for example). In this case the user must have permission to manually change the file and it should be enough.
But if it is really something that you need, you should ask it at our sales department in https://www.linphone.org/contact
