### ISSUE TITLE
Webcam is active as soon as Linphone starts

### ISSUE THREAD

**Issue by cweiske** [BelledonneCommunications/linphone-desktop#449]
When starting the Linphone desktop application on Ubuntu 18.04 (Linphone-4.3.0-alpha.43+d3594766.AppImage and Linphone-4.2.3.AppImage), the webcam is activated immediately.

The webcam should only be used when a video call is started and not earlier.

**Comment by julonexus** [comment]
Yes, I done a fix about that but it hasn't been merged yet. This is related of the preview that is set to enabled at the start (that could lead to crash if the camera is faulty) where it is only used when showing preview.
I'll come back when it's done.

**Comment by julonexus** [comment]
Merged

**Comment by cweiske** [comment]
(https://github.com/BelledonneCommunications/linphone-desktop/commit/89f9edbd1c18c3d649b18655cef1fef804b5adee)

**Comment by cweiske** [comment]
Thank you for solving the problem so fast!
