### ISSUE TITLE
menu window

### ISSUE THREAD

**Issue by bderembl** [BelledonneCommunications/linphone-desktop#45]
when trying to open the menu window, the window opens in random places. here is the warning I get
`Gdk-Message: Window 0x18b24d0 is a temporary window without parent, application will not be able to position it on screen.`

using 
Desktop 4.0-165-gde2fcd99 - Qt5.9.1

**Comment by Wescoeur** [comment]
What is your desktop environment? Have you tried with the Qt5.9.0 version?

**Comment by bderembl** [comment]
I am using gnome 3.24.2. I haven't trid qt5.9.0

**Comment by Wescoeur** [comment]
I tried with Qt5.9.1 and Gnome 3.24.2 on Archlinux. I can't reproduce...  Do you have a specific configuration (Wayland, a modified gnome config...)?

**Comment by bderembl** [comment]
yes, I am using wayland but it the standard gnome (I haven't changed anything)

**Comment by bderembl** [comment]
looks like an old bug in wayland
https://mail.gnome.org/archives/commits-list/2016-January/msg02035.html

**Comment by Wescoeur** [comment]
You are right. I can't correct this problem in the app for the moment. (It's difficult to apply a workaround on this menu...)
