### ISSUE TITLE
Volume setting for ring device

### ISSUE THREAD

**Issue by dan-it** [BelledonneCommunications/linphone-desktop#453]
It would be nice to have a volume control for the ring device in Preferences => Audio.

At the moment ring volume seems to be always at maximum and this isn't always appropriate.

**Comment by DBX12** [comment]
Yes, I second that.
I found a workaround on Linux (pulse audio) with the help of my colleagues:
- create a new combined sink with `pactl load-module module-combine-sink sink_name="LinphoneRinger" slaves=` and define your main sink as slave. (the sink which sends audio to your speakers)
-  set the ringer device to this combined sink
- reduce the volume of that combined sink as needed

**Comment by linuzer** [comment]
How can it be, that after 7 years (!!!) this is still an issue??? 😡
https://lists.gnu.org/archive/html/linphone-developers/2014-11/msg00048.html

**Comment by julonexus** [comment]
Unfortunately, there are no API on the SDK to manage the volume. So, this is not really an issue from the application.
You should contact the sales at https://www.linphone.org/contact to a get a quote or make a request at https://github.com/BelledonneCommunications/linphone-sdk for a community contribution.
Regards
