### ISSUE TITLE
[Feature] Switch account dialog: Show Label in front of sip user

### ISSUE THREAD

**Issue by sjjh** [BelledonneCommunications/linphone-desktop#455]
If I add another sip account, I can add a label in front of it, e.g. `"Bob" <sip:123@host.tdl>`, which is then also shown in the top left of the main window. If I there click there on the display to change the active account (or change the presence state) a dialog pops up where I can only see the account (e.g. `<sip:123@host.tdl>`) but the label `Bob` is not shown.
IMHO it would increase the usability to show the label in the dialog as well.

**Comment by julonexus** [comment]
This detail is on master and will be available for the next nightly builds (as soon as a build error will be fixed in SDK)

**Comment by sjjh** [comment]
FYI, I'm not familiar with your release cycle, so please forgive me if I'm stating the obvious. Just wanted to say, that I noted that the feature is still not visible on the latest release:
Ubuntu 20.04 Linphone 4.2.5 Appimage
