### ISSUE TITLE
~/linphone/captures folder created despite different configuration

### ISSUE THREAD

**Issue by dorsiflexion** [BelledonneCommunications/linphone-desktop#457]
Heya,
first and foremost a big thanks for all your work.

Even if you set every configurable path option different from `~/linphone/captures` this folder is still created by linphone on every start. It should not be created if it is not set.

What I have configured:
Saved screenshots folder: `~/.local/share/linphone/captures`
Saved calls folder: `~/.local/share/linphone/captures`
Downloads folder: `~/.local/share/Downloads`
Logs folder: `~/.cache/linphone/log`

Versions:
Linphone-desktop 4.2.4
Qt5.15.2
Core 4.4.13

**Comment by carstenknoch** [comment]
I see this on Windows (Desktop 5.0.11 - Qt5.15.12; Core 5.2.25).

I switched/renamed local user accounts. Made sure to install Linphone *after* renaming accounts. Yet Linphone picked up the location of my assumed user/Documents from some default location in the registry, and re-created the original hierarchy to this capture directory on every run. Delete the capture directory and Linphone crashes.

I eventually uninstalled Linphone and combed through the registry manually to eradicate any and all mentions of that old user/Documents path (which no longer exists). Then it installs fine and places its capture folder in the "correct" default Documents location. However, using the configuration dialog under Preferences/User Interface/Path still isn't respected by the app. It is effective a "dead" field.

**Comment by odoepner** [comment]
I also see this issue on Debian 11.7  stable ("bullseye"), using the Debian provided "linphone" package, and its automatically install dependencies. 

Version details (from burger menu - "About" dialog):
Desktop  - Qt5.15.2
Core 4.4.21

List of automatically installed dependencies:
  libantlr3c-3.4-0 libbctoolbox1 libbelcard1 libbellesip1 libbelr1 libbzrtp0 libglew2.1 liblinphone++10 liblinphone10 libmbedcrypto3
  libmbedtls12 libmbedx509-0 libmediastreamer11 libortp15 libqt5quickcontrols2-5 libqt5quicktemplates2-5 libsoci-core4.0
  libsoci-sqlite3-4.0 libturbojpeg0 linphone-common linphone-desktop qml-module-qt-labs-folderlistmodel 
  qml-module-qt-labs-platform qml-module-qt-labs-settings qml-module-qtgraphicaleffects qml-module-qtqml 
  qml-module-qtqml-models2 qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs 
  qml-module-qtquick-layouts qml-module-qtquick-privatewidgets qml-module-qtquick-templates2 qml-module-qtquick-window2

![linphone-ui-settings](https://github.com/BelledonneCommunications/linphone-desktop/assets/1536531/815a8341-7797-44ae-90d1-9e3f7d04e055)
