### ISSUE TITLE
App Crashed on Chat received

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-desktop#467]
@Viish ,

With latest sdk **4.5.0_Beta** android app got crashed on chat message received. Same is happening with Linphone Desktop with sdk Virsion **4.5.0-alpha-312-g15a9aecaf**.

Logs are attached.

[LinphoneCrashOnMessageReceived.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/5923572/LinphoneCrashOnMessageReceived.txt)

**Comment by Viish** [comment]
Duplicate of https://github.com/BelledonneCommunications/linphone-android/issues/1285
