### ISSUE TITLE
crush when Contact contain ";isfocus"

### ISSUE THREAD

**Issue by sergey-safarov** [BelledonneCommunications/linphone-desktop#475]
We use FreeSwitch as a conference server.
When FreeSwitch send "isfocus" in Contact header, then Linphone dies.

**Example**
```
Contact: <sip:3500@192.168.100.31:5060;transport=udp>;isfocus
```

`isfocus` usage defined [rfc4579](https://tools.ietf.org/html/rfc4579)

If you have FreeSwitch server, then you can reproduce the issue using this dialplan
```xml
<include>
  <context name="default">
    <extension name="conference">
      <condition field="destination_number" expression="^3500$">
        <action application="answer" data="is_conference"/>
        <action application="conference" data="3500@video-mcu-stereo"/>
      </condition>
    </extension>
  </context>
</include>
```

**Comment by Viish** [comment]
@julonexus Can you handle it please?

**Comment by sergey-safarov** [comment]
I can prepare `SIPp` script as a test case.

**Comment by julonexus** [comment]
Hi,
What is your version of appimage? Is it from releases or snapshots? Logs will be helpful thanks

**Comment by sergey-safarov** [comment]
I cannot reproduce the issue now.
I will reopen the ticket when I catch the issue again.
