### ISSUE TITLE
Echo/feedback in version 4.1.1

### ISSUE THREAD

**Issue by alexeymuranov** [BelledonneCommunications/linphone-desktop#48]
I tried to use the latest version 4.1.1 between a laptop with Ubuntu 17.04 and a laptop with Linux Mint 18.1, and the audio was almost unusable because of strong feedback/echo.  On both machines echo cancellation was enabled in Linphone preferences (i also tried to disable it on one machine, but it only made it worse, i believe).

I tried before the versions of Linphone provided by these two distributions (versions 3 -- something) and had no big issues with the audio (but there were problems with the video).

However, on one attempt of using version 4.1.1, for the first minute or so, the echo was almost absent.  So, i am not sure if there were any regression.

**Comment by Wescoeur** [comment]
Not reproductible with the next release.
