### ISSUE TITLE
No audio in Windows 10 build

### ISSUE THREAD

**Issue by attermann** [BelledonneCommunications/linphone-desktop#487]
Hi,

After MUCH trial, error and pain, I have finally able to get a build in Windows 10 using Visual Studio 2017 Community to complete.  However I am not finding the binaries in `\<build\>\OUTPUT` as expected.  I did find `linphone.exe` in `\<build\>\linphone-app` and after adding `\<build\>\linphone-sdk\desktop\bin` to my PATH I was able to get it to run and even register with my SIP service.  I am not getting audio in either direction though on test calls, and Preferences/Audio doesn't list any devices for either Playback or Capture.

My questions are:

- Does binaries missing from `\<build\>\OUTPUT` imply a build issue, or are my binary locations described above to be expected?
- Should `linphone.exe` run from the <build> directory be fully functional, or is there another step required?
- Any additional "best practices" for working with linphone-desktop in Windows (I haven't had nearly the issues building in MacOS)?

For reference, below is the version that I have built and run:

```
Desktop 4.3.0-alpha-76-g6f63b37c - Qt5.12.10
Core 4.5.0-alpha-314-gab5a94c1e
```

Log file is attached and shows failure to find audio devices.  I have the official 4.2.5 downloaded version running on the same machine and it has no problem finding audio devices so the issue definitely with my build.

Thanks!

[linphone1.log](https://github.com/BelledonneCommunications/linphone-desktop/files/6367820/linphone1.log)

**Comment by julonexus** [comment]
Hi
You didn't do all steps.
`cmake --build . --target install --parallel 10 --config RelWithDebInfo`

**Comment by attermann** [comment]
That was it!  Solved all of the problems.  Thank you so much.

I thought I was following the build instructions to a tee, but maybe I misunderstood.  Step 4 under `Specific instructions for the Windows platform` shows only the `cmake .. ` and `cmake --build . --target ALL_BUILD` commands.  The `cmake --install .` command is only included in Step 6 which implies it's only after updating the project, and I hadn't even reached that step yet.

**Comment by attermann** [comment]
Resolved by properly finishing build/install with `cmake --install .` command.
