### ISSUE TITLE
Fairly easy question 

### ISSUE THREAD

**Issue by cinnamoner** [BelledonneCommunications/linphone-desktop#49]
I have been contemplating Linphone-desktop for well over a year now. Can it be used as a replacement for Skype? That would be the question. I'm considering the possibility to use your software and recommend it to my friends as well. Much appreciated in advance.

**Comment by Wescoeur** [comment]
If your goal is to call your friends and send messages, it's possible. (And if you search security and privacy unlike Skype.)
But at this time group chat is not supported (wait for some months).

**Comment by cinnamoner** [comment]
@Wescoeur Thanks.
