### ISSUE TITLE
Advice for building version compatible with older OSX

### ISSUE THREAD

**Issue by attermann** [BelledonneCommunications/linphone-desktop#492]
Hi All,

I have built the app for MacOS on Catalina (10.15) running Xcode 12.3 and using Qt 5.15.2, and I can install and run this version on other Catalina machines. I tried installing on a very old El Capitan (10.11) machine though and it failed with the error "Requires OSX 10.15 or higher".  I don't necessarily need it to run in El Capitan, but I would like to support OSX versions below Catalina. Would appreciate advice on how to configure for such a backwards compatible build, and whether I also need an older Qt version or custom 5.15.2 build to support older OSX systems.

Thanks in advance!

**Comment by olku** [comment]
El Capitan is unsupported by Apple for years now. I'd advise against it.

**Comment by julonexus** [comment]
The SDK (and the app) support OSX till 10.9. When configuraing, you can set it with -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
