### ISSUE TITLE
Get logs with AppImage version ??

### ISSUE THREAD

**Issue by vincegre** [BelledonneCommunications/linphone-desktop#493]
Hi

Is there a way to run Linphone with verbose mode when you use the AppImage ? Suddenly from an day to an other it doesn't connect at 2/3 of my SIP lines and so need logs to check what's problem as I found no way in Linphone to get a description of problem or indication what's problem :(

Thanks

Vincèn

**Comment by julonexus** [comment]
Hi

You could try to do these steps: https://gitlab.linphone.org/BC/public/linphone-desktop#feedback-or-bug-reporting
Or to find the logs that you set in your settings panel of the application.

Regards

**Comment by vincegre** [comment]
> Or to find the logs that you set in your settings panel of the application.

Oups didn't notice it could be setup in settings panel of app, sorry for that ! Now that I have my log file have to understand it as it's pretty verbose and can't find anything related at my SIP connection problem that appeared "without" reason !

**Comment by julonexus** [comment]
Good luck ;)
