### ISSUE TITLE
Xcode project file does not exits in my project.

### ISSUE THREAD

**Issue by anilStartele** [BelledonneCommunications/linphone-desktop#494]
**Describe the bug**
I am not able to open linphone-desktop project into the Xcode 12.4
**To Reproduce**
    Step 1 git clone https://gitlab.linphone.org/BC/public/linphone-desktop.git --recursive
    Step 2 cd linphone-desktop
    Step 3 mkdir build
    Step 4 cd build
    Step 5 cmake .. -DCMAKE_BUILD_PARALLEL_LEVEL=10 -DCMAKE_BUILD_TYPE=RelWithDebInfo
    Step 6 cmake --build . --target install --parallel 10 --config RelWithDebInfo
![Screenshot 2021-04-30 at 2 26 09 PM](https://user-images.githubusercontent.com/62588690/116672603-048b8700-a9c0-11eb-8a72-a7aa95b15c3b.png)

**Expected behavior**
After following all these steps a xcode project file should be generated into project directory.

**Desktop (please complete the following information):**
 - OS: [ MacOs 10.15.7]
 - Xcode Version [12.4]
 - Qt Version[5.12.5]
New to this field. If I have done any mistake let me know.

**Comment by julonexus** [comment]
Hi, you not looking to the build folder but to the root project.

**Comment by anilStartele** [comment]
Thanks for pointing the issue.

**Comment by anilStartele** [comment]
Found the xcode file **linphoneqt.xcodeproj** after running the cmake .. -G Xcode. Now I am able to open it into the Xcode.
Facing different issue
`PhaseScriptExecution Generate\ WORK/stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/sdk-configure /Users/startelelogic/Documents/Ayrix/linphone-desktop/build/linphoneqt.build/Debug/sdk-build.build/Script-CCE156970FECEEA62CA42CEE.sh (in target 'sdk-build' from project 'linphoneqt')
    cd /Users/startelelogic/Documents/Ayrix/linphone-desktop
    /bin/sh -c /Users/startelelogic/Documents/Ayrix/linphone-desktop/build/linphoneqt.build/Debug/sdk-build.build/Script-CCE156970FECEEA62CA42CEE.sh

CMake Error: Error: generator : Xcode
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Command PhaseScriptExecution failed with a nonzero exit code
` 
at the time of compilation.
