### ISSUE TITLE
Cannot get working build

### ISSUE THREAD

**Issue by zackm0571** [BelledonneCommunications/linphone-desktop#5]
Good morning (evening in France), 

Is there a working build at SHA-1 = 9043c7f8aaba91fbe3bf196f90aa3b69f59d78bd of this repo? If not, what is a usable SHA of this repo that I can mimic submodules for a good mac build?

Thanks, 

Zack

**Comment by Viish** [comment]
Hi Zack,

If you build linphone-desktop from revision 95810e2889857fcd54d518dc6e063e8eda1170a2 you should have a very stable SDK/application.

Cheers.
