### ISSUE TITLE
Changing ring duration

### ISSUE THREAD

**Issue by Xenorio** [BelledonneCommunications/linphone-desktop#503]
I would like to change how long Linphone rings on an incoming call. More specifically, i would like it to ring as long as possible.

I have found the ~/.config/linphone/linphonerc file and have increased the inc_timeout variable to 300 seconds. Now Linphone keeps ringing after the default 30 seconds, but the notification-like window with the buttons for accepting or declining a call still disappears after 30 seconds. This means that all i can do is keep listening to my ringtone, and can't actually accept the call.

It seems like there is no other variable in the config which holds the timeout for that window. 

Using Linphone Desktop 4.2.5 (Core 4.4.19) on Ubuntu 20.10

**Comment by InterLinked1** [comment]
In addition to unlimited ring duration (the real ring duration can be set by the server, anyways), distinctive ringing using the standard Alert-Info SIP header would be very useful (e.g. audio files for up to 10 distinctive rings).

**Comment by DBX12** [comment]
Can confirm what Xenorio said, set `inc_timeout=300` and the window disappears after 30 seconds.
I believe the hardcoded timeout in [src/components/notifier/Notifier.cpp:86](https://github.com/BelledonneCommunications/linphone-desktop/blob/master/linphone-app/src/components/notifier/Notifier.cpp#L86) is to blame for that.

**Comment by julonexus** [comment]
There is another harcoded value (MaxTimeout).
I made a fix that use the inc_timeout for the call notification timeout.

https://gitlab.linphone.org/BC/public/linphone-desktop/-/commit/f15a68d3434bbd875e6a772ecd597d77be34293a
