### ISSUE TITLE
black squares instead of buttons 

### ISSUE THREAD

**Issue by drjors2** [BelledonneCommunications/linphone-desktop#514]
Good morning, 
The new Linphone interface display black squares instead of buttons.

This happened after I've upgraded to Ubuntu  21.04 .

![image](https://user-images.githubusercontent.com/1298596/123792106-421c6b80-d8ae-11eb-95b6-6a50eb69d4d7.png)

Thank you ,
Daniel

**Comment by JFroch** [comment]
Had the same issue on debian bookworm.
The console log showed:  `QSGTextureAtlas: texture atlas allocation failed, code=501`
Removing the package `libqt5quick5-gles` (which in turn installs `libqt5quick5`) fixed the issue for me.

**Comment by drjors2** [comment]
Thank you,  it worked !
Used `sudo aptitude remove libqt5quick5-gles` command , which offered to resolve the dependencies using `libqt5quick5`

**Comment by julonexus** [comment]
Thanks for your solution. Was it about a custom build?

**Comment by drjors2** [comment]
No.
