### ISSUE TITLE
No binary in path after flatpack install

### ISSUE THREAD

**Issue by etamme** [BelledonneCommunications/linphone-desktop#52]
I installed linphone via flatpack and afterwards there is no "linphone" binary in my path.  I have to run 

 flatpak run com.belledonnecommunications.linphone/x86_64/4.1.1

To start linphone, which is ... not good

**Comment by ghismary** [comment]
A good desktop environment should add a Linphone entry in your application menu. On some, you may need to close your session and open a new one for the entry to appear.

**Comment by etamme** [comment]
yeah .. it did add an application entry.  That's not what the issue was opened for.

**Comment by ghismary** [comment]
yeah... and that's how flatpak works.
