### ISSUE TITLE
keep calls windows in background feature not working

### ISSUE THREAD

**Issue by IbrahimBond** [BelledonneCommunications/linphone-desktop#522]
**Describe the bug**
the keep calls windows in background feature that is toggled from preferences --> calls and chat is not working. when i ever i make a call a pop of the call shows on top of the desktop. i have a use case where i dont want the call window to show when ever someone makes a call.

**Steps to reproduce the behavior:**
go to preferences --> calls and chat
toggle auto answer
toggle keep calls windows in background
make a call from another machine
Expected behavior
call should be answered without any pop up.

**Please complete the following information**

Device: computer
OS: ubuntu 18.04
Version of the App: Linphone-4.2.5.AppImage

**Comment by julonexus** [comment]
Duplicate #526

**Comment by IbrahimBond** [comment]
can you provide a link to this version?

**Comment by olku** [comment]
> can you provide a link to this version?

It used to be https://www.linphone.org/snapshots/ubuntu/ but it appears currently the entire linphone.org website is down.
