### ISSUE TITLE
Incorrect LDAP search UTF8 russian language name encoding 4.3 beta

### ISSUE THREAD

**Issue by Nikopol3000** [BelledonneCommunications/linphone-desktop#533]
In the new release 4.3 beta, the search for LDAP contacts in the UTF-8 encoding is displayed incorrectly.
![2021-08-31 093626](https://user-images.githubusercontent.com/41819899/131454051-a8d344c0-6b9f-4a5c-853b-558ddf465f26.png)

![2021-08-31 093359](https://user-images.githubusercontent.com/41819899/131453893-d2648381-860a-4afc-872f-2ce7c04244a5.png)

**Comment by julonexus** [comment]
Hi, this should have been fixed in the next beta version (after beta 9)
Regards
