### ISSUE TITLE
LDAP search sends too many requests

### ISSUE THREAD

**Issue by cweiske** [BelledonneCommunications/linphone-desktop#539]
**Describe the bug**
When typing into the main window's "Search contact" box and an LDAP server (#178) is enabled, a search request is sent for each single typed character. Linphone should wait some time until the request is sent to the ldap server (e.g. 300ms, or when "Enter" is pressed).

The UI flickers quite a bit while all the ldap results are shown, then the next results are shown etc.

**To Reproduce**
1. Enable an LDAP server
2. Go to main window, click into "Search contact" text field
3. Type "weiske"
4. The search result autocomplete will show the results for "w"
5. The search result autocomplete will show the results for "we"
6. The search result autocomplete will show the results for "wei"
7. The search result autocomplete will show the results for "weis"
8. The search result autocomplete will show the results for "weisk"
9. The search result autocomplete will show the results for "weiske"

**Expected behavior**
Linphone waits until I stopped typing before searching, or I press enter/return.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: 4.3.0-beta.38+ed52503e
 - Version of the SDK: Core 5.0.22-1-g8c5243994

**Comment by julonexus** [comment]
Requests are pushed to the search but there is a wait of 100ms between each search. So if you type quickly weiske, you will find a request for each letter, but 2 searches will only be done. On "w" and on "weiske"
