### ISSUE TITLE
I am unable to compile the macOS version 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-desktop#54]
![screen shot 2017-08-01 at 2 26 40 pm](https://user-images.githubusercontent.com/22788570/28843133-b5b42eec-76c5-11e7-81ac-bc178a657b9a.png)

I run the ./prepare.py desktop and make and I still only have the output folder with the 4 directories in it and now dmg or Xcode project files 

I've tried make -G Xcode and ./prepare.py -p desktop -G Xcode 

any ideas ?

**Comment by Wescoeur** [comment]
Dou you have the privilege to read/write in you project `Debug` folder?

**Comment by S0U1SB4N3** [comment]
yes and I corrected this error and it gives me another error, I will supply latest error in the next few hours, thank you for responding/

**Comment by S0U1SB4N3** [comment]
![screen shot 2017-08-05 at 12 59 15 am](https://user-images.githubusercontent.com/22788570/28993333-604ff448-7979-11e7-9834-0119486c4eba.png)

**Comment by S0U1SB4N3** [comment]
![screen shot 2017-08-05 at 2 09 11 am](https://user-images.githubusercontent.com/22788570/28993734-51bc012e-7983-11e7-9c93-ef1b6dd6493f.png)

**Comment by S0U1SB4N3** [comment]
this is the root account on my Mac. I should have full permissions 

ill chmod 777 -R /parent directory 

after the build and try again

**Comment by S0U1SB4N3** [comment]
this is the error log 
Performing C++ SOURCE FILE Test SUGGEST_OVERRIDE failed with the following output:
Change Dir: /Users/S0U1SB4N3/linphone-desktop/WORK/desktop/Build/linphoneqt/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_5db75/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_5db75.dir/build.make CMakeFiles/cmTC_5db75.dir/build
Building CXX object CMakeFiles/cmTC_5db75.dir/src.cxx.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -DSUGGEST_OVERRIDE -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12   -Wsuggest-override -o CMakeFiles/cmTC_5db75.dir/src.cxx.o -c /Users/S0U1SB4N3/linphone-desktop/WORK/desktop/Build/linphoneqt/CMakeFiles/CMakeTmp/src.cxx
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
Linking CXX executable cmTC_5db75
/usr/local/Cellar/cmake/3.8.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5db75.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DSUGGEST_OVERRIDE -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_5db75.dir/src.cxx.o  -o cmTC_5db75 

Source file was:
int main() { return 0; }

**Comment by S0U1SB4N3** [comment]
I got it to compile however there aren't any Xcode project files to visually code this project.. anything I'm doing wrong >

**Comment by Wescoeur** [comment]
Xcode files => Related to #62.
