### ISSUE TITLE
LDAP: Show autocomplete entry for each phone number of a contact

### ISSUE THREAD

**Issue by cweiske** [BelledonneCommunications/linphone-desktop#540]
**Describe the bug**
When an LDAP (#539) contact has multiple phone numbers, and the "SIP attributes" is a comma-separated list of multiple fields, then the autocomplete box of the "Contact search" field shows only the first telephone number.

This makes it impossible to call the contact on the second number.

**To Reproduce**
1. Configure the LDAP SIP attributes: `mobile,telephoneNumber,homePhone`
2. Create an LDAP address book entry with a mobile and a homePhone number.
3. Search for that name in the "Contact search" text field
4. The contact is shown with its mobile number, but not with its homePhone number.

**Expected behavior**
The contact with its mobile number, and the contact with its homePhone number is shown in the autocomplete box.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: 4.3.0-beta-38-ged52503e
 - Version of the SDK: Core 5.0.22-1-g8c5243994

**Comment by julonexus** [comment]
That's strange, it was something that has been fixed

**Comment by julonexus** [comment]
Is " "SIP attributes" is a comma-separated list of multiple fields" a mandatory?

**Comment by cweiske** [comment]
There are two possible cases:

1. A single ldap field is a "multi-valued" field, which means it can contain two or more values at the same time. In this case, a result entry must be shown for each of the values
2. The ldap result has values in two or more of the "SIP attributes" fields. A result entry for each of the values must be shown, too.

Maybe you fixed number 1, but not number 2 which I described here in this bug.

**Comment by julonexus** [comment]
This case is not really a bug but more like a bad behavior. The SIP attributes field is in a priority order and not a "all findings".
For one contact, you will get first all its mobiles. If they doesn't exist, it will be telephoneNumber and if not, the homePhone.

"This makes it impossible to call the contact on the second number." : So, no, it doesn't. You can still add another LDAP entry with a different fields. For you case, you will get 3 providers with a single SIP attribute field each.
It's only a workaround. Having multiple requests is not really right and optimized.

I'll check if we can change that.

**Comment by julonexus** [comment]
It will be available in the next beta build (after 41)
Regards

**Comment by cweiske** [comment]
Thank you!

Commit: https://gitlab.linphone.org/BC/public/liblinphone/-/commit/3249a4813ca0a56f5d4f2e9ec8260e1ebd5ae464

**Comment by JoelLinn** [comment]
Please reopen this issue as again only one entry is shown (using the mobile number) even though multiple numbers in other attributes are returned by the ldap search. Using version 6.1.2
