### ISSUE TITLE
Disabling LDAP debugging has no effect until restart

### ISSUE THREAD

**Issue by cweiske** [BelledonneCommunications/linphone-desktop#541]
**Describe the bug**
When enabling LDAP debugging in the preferences, searching for contacts shows ldap debug messages.
After disabling debugging, searching for contacts still shows ldap debug messages.

When I quit linphone and start it again, no ldap debug messages are logged anymore.

**To Reproduce**
1. Open Preferences, Advanced
2. Click on ldap server name
3. Scroll down to 'Misc'
4. Enable "Debug"
5. Confirm LDAP settings and OK setting changes
6. Search for contacts in main window "Search contact" text field
7. See ldap debug messages in terminal
8. Disable LDAP debugging in preferences
9. Search for contacts
10. Still see ldap debug messages in terminal

**Expected behavior**
When disabling LDAP debugging, no ldap debugging log lines should be visible in terminal anymore.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: Desktop 4.3.0-beta-38-ged52503e - Qt5.12.5
 - Version of the SDK: Core 5.0.22-1-g8c5243994

**Comment by julonexus** [comment]
Hi, the debug mode wasn't reset. The fix will be available in the next beta build (after 41)
Regards

**Comment by cweiske** [comment]
Thank you!

Commit: https://gitlab.linphone.org/BC/public/liblinphone/-/commit/3249a4813ca0a56f5d4f2e9ec8260e1ebd5ae464
