### ISSUE TITLE
Request: please keep the alpha versioning system in beta. Format (4.3.0-beta.4-g123abcdef)

### ISSUE THREAD

**Issue by leukimi** [BelledonneCommunications/linphone-desktop#545]
The versioning system has changed.
Previously versions would be spelled something like 4.3.0-**alpha.98**-g123abcde with a dot.
Now it has changed to 4.3.0-**beta-1234**-g123abcde with a dash instead.
I don't understand why the need of this change.

Reason: Scripts grab the different parts of `git decribe`when there is a dot instead of a dash.

Please change the new versioning system back to the old style alpha-versioning-system:
New versioning system:
```sh
$ git describe
4.3.0-beta-4-g39e41a60a
```

Old versioning system would output beta.4 instead of beta-4:
4.3.0-beta.4-g39e41a60

```sh
$ git describe
4.3.0-beta.4-g39e41a60a
```

**Comment by julonexus** [comment]
Hi
The versioning system didn't change : There is no way that 'git describe' gives '4.3.0-beta.4-g39e41a60a' : This is not in its specification.
The package version is based on bc_compute_full_version that compute from 'git describe' and use a dot. But if your build cannot compute it, you get only the git versioning (with a dash)
You need to clarify what exactly are you comparing.

**Comment by leukimi** [comment]
Understand. 

By packaging... bctoobox functionality must become static (rather than dynamic) and not depend on git data. The `.git` folder is sometimes very large.

A suggestion to a more portable code would be to have a separate text file (or init file) that holds the data that otherwise git describe or bctoolbox would get via git if it was present, so that the code can be compiled independently on git.

A textfile in the root could specify:

```sh
APP_VERSION=4.4.0-beta.43 (not sure from where this is taken, but suspect git describe is the source somehow)
CORE_VERSION=5.0.49 (taken from liblinphone/CMakeListst.txt which says version 5.0.0 instead of 5.0.49)
VARIABLE_ONE=something (like the data you get via: git rev-parse HEAD)
```

and instruct bctoolbox to read that data needed from the text file instead, if git cannot give any data because it is not shipped within a package. As it is now, the compilation bails out when git data is not there and things need to be adjusted manually to cater for the version numbers.

It would also be nice to have a top level flag that turns off all debug generation at compilation time.

**Comment by julonexus** [comment]
Hi
The issue was not about git describe, but a mix between semver and git.
bctoolbox compute versions by following the semver rules (dot) while the application use git describe (minus)
It will be fixed for next release.
Regards
