### ISSUE TITLE
4.3.0-beta-49: warm and cold call transfer stopped working 

### ISSUE THREAD

**Issue by bronsgeest** [BelledonneCommunications/linphone-desktop#548]
Hi, 

In beta build 4.3.0-beta-49-g08a7f3b4 (29 september) the transfer button stopped working, it worked in earlier beta builds. I start a call then I click the "transfer" option in the context menu. I get the dialog to select a device/number. When selected, I click on the button with the arrow, then nothing happens. No error and no action either (as if the button in the GUI is not associated with anything at all). Warm transfer fails in a similar way.

I have attached the Linphone  [linphone1.log](https://github.com/BelledonneCommunications/linphone-desktop/files/7250954/linphone1.log).  User "user_id_UA" starts the call to 205 and "user_id_UA" attempts to do the transfer to "201".  "user_id_UA" terminates (BYE) 

the call after nothing happens. 

Just let me know if there are any checks you want me to do. 

Regards, 

Max

**Comment by julonexus** [comment]
Hi, I confirm,  the arrow doesn't work, I'll fix that.
But transfer still work by clicking on the bar and not on the arrow.

**Comment by bronsgeest** [comment]
ah new feature ;) 
confirmed in that way both cold and warm transfer works. Will close case.
