### ISSUE TITLE
caller id name

### ISSUE THREAD

**Issue by BesSystem** [BelledonneCommunications/linphone-desktop#55]
I set caller id name in Asterisk
example caller id name: [test-112233]

linphone-android incoming call  show as "test-112233" 

But linphone-desktop incoming call show as "112233"

What should I do to show both clients as "test-112233"?

**Comment by Wescoeur** [comment]
Must be fixed now. :)

**Comment by z3ntu** [comment]
@Wescoeur I tested today with a version from flatpak, the about menu says 'Desktop 4.1.1 - Qt5.9.0' 'Core 3.12.0' and the caller id does not get displayed. I was wondering probably half an hour why the caller id wasn't display and then finally realized it was a bug in the new version of linphone (have used the 3.x version before)

**Comment by Wescoeur** [comment]
The bug is on 4.1.1,  It's normally fixed on master and on the next 4.2 release.

**Comment by z3ntu** [comment]
Any way to get a version with the fix with flatpak?

**Comment by Wescoeur** [comment]
Easy solution => Wait for the next 4.2 flatpak release. :)
Or you can build from sources. (Okay, you must deal with dependencies in this case!)

**Comment by z3ntu** [comment]
Any time estimate when that will happen? So like another 6 months or a couple of weeks? 

Also how do the flatpaks get built? Is the flatpak manifest available somewhere (then I could probably build it from the newest sources)?
