### ISSUE TITLE
UX not Accessible - contrast too low

### ISSUE THREAD

**Issue by Robotic-Brain** [BelledonneCommunications/linphone-desktop#557]
The desktop userinterface is too low in contrast.

Is there a way to change the color palette?
Which files do I have to change?

If not please make sure to adhere to the accessibility guidelines for color contrast!
grey on light-gray on white is absoluteley unreadable....

**Comment by julonexus** [comment]
Questions have to be asked on the mailing list. Colors can be changed in linphonerc.
There will be a new design on chats but it will not be for today.
