### ISSUE TITLE
No call log in 4.3.0 UI?

### ISSUE THREAD

**Issue by cinterloper** [BelledonneCommunications/linphone-desktop#560]
In 4.2.5, the left hand bar had a 'Previously' entry, where if you clicked, you could view missed calls, your outbound call log, etc.

In 4.3.0, this has disappeared, I do not know how to view missed calls
![redacted_linphone 4 3 0](https://user-images.githubusercontent.com/1668926/138348158-103e247c-6b11-48f6-bf95-eccb11459fce.jpg)
![redacted_linphone 4 2 5](https://user-images.githubusercontent.com/1668926/138348159-a2971dbb-8bfe-4ff1-8775-e22eb382bcc2.jpg)

**Comment by mniehren** [comment]
I also missed this history feature too, there should be a Button on the main page.

Running Linphone under Linux.

**Comment by javitron100** [comment]
Wonderful, i can see it yet.
Thanks a lot for all of you.
