### ISSUE TITLE
search bar on the top handles german umlauts incorrectly

### ISSUE THREAD

**Issue by AlBundy33** [BelledonneCommunications/linphone-desktop#569]
Linphone 4.3.0 on Windows 10

steps to reproduce
create a contact: Müller Test with number XXX

Now search in the top bar for Müller
Result: new contact is not displayed
![image](https://user-images.githubusercontent.com/6294586/140372675-94f65902-ca49-4024-bd9c-ad8603d3099e.png)

Now Search in the top bar for test
Result: new contact is displayed
![image](https://user-images.githubusercontent.com/6294586/140373282-a92197c1-2d86-40c3-89ac-b1b6d5cf1534.png)

now switch to your contacts and search in the "lower search bar" for Müller
Result: contact is displayed
![image](https://user-images.githubusercontent.com/6294586/140373509-4eafc035-e0e7-4d8f-b605-c1c4ea7131b1.png)

expected behavior: contact is also found when using the top search bar

**Comment by julonexus** [comment]
Search should be fixed on 4.3.2

**Comment by AlBundy33** [comment]
works 👍
