### ISSUE TITLE
Missing button to open list of missed calls

### ISSUE THREAD

**Issue by AlBundy33** [BelledonneCommunications/linphone-desktop#570]
Linphone 4.3.0 on Windows 10

There is currently no way to open the list missed calls.

If I have a missed call there is a small icon right hand side of my user name.
If I click on this icon I see the the missed call (an i think all other outgoing and incoming calls).

But if I have no missed call, I don't see the icon ander therefore I have no chance to open this list.

**Comment by aGrimRepoMan** [comment]
See #560

**Comment by AlBundy33** [comment]
Thank you @aGrimRepoMan - downloaded 4.3.1-pre.30 and now have a button to access the call log.

![image](https://user-images.githubusercontent.com/6294586/140393570-c2ff5c2f-6a46-441f-ac30-059694da8164.png)

**Comment by aGrimRepoMan** [comment]
@AlBundy33:  No worries.   

If you didn't build that version yourself, could you let me know where to find 4.3.1-pre.30?  Thanks.

**Comment by AlBundy33** [comment]
it's on the same location as the release ;-)
https://www.linphone.org/releases/windows/app/

maybe its also in the daily builds https://new.linphone.org/technical-corner/linphone?qt-technical_corner=2#qt-technical_corner
