### ISSUE TITLE
Enter key at numblock does not start a call

### ISSUE THREAD

**Issue by q00d0** [BelledonneCommunications/linphone-desktop#576]
**Describe the bug**
If you dial a number (entering the number in the searchbar) and hit the enter button at the numblock nothing happens. If you hit the enter button located at the letters the call gets started.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
1. Open the software Linphone
2. Enter a number to the searchbar as seen in the screenshot
3. Hit the enter button at the numblock - nothing will happen
4. Hit the enter button located near the letters - the call will start

**Expected behavior**
The call should start in both ways (with both enter buttons). It doesn't make sense for me. Usually you dial phone numbers with the numblock and then the nearest enter button should (or both).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 4.3.0
 - Version of the SDK: 5.0.39

**Screenshots**
![image](https://user-images.githubusercontent.com/11162933/141660797-c1425655-31b8-4506-a34c-845c983eed5e.png)

**Comment by julonexus** [comment]
Thanks for the report. Thois has been fexed on master : https://gitlab.linphone.org/BC/public/linphone-desktop/-/commit/be4398247b5ccaf39844e176f08f733e3e7ddabc
