### ISSUE TITLE
Integration of language dependent speech synthesis

### ISSUE THREAD

**Issue by leukimi** [BelledonneCommunications/linphone-desktop#579]
How is the language speech synthesis configured?
By accident I discovered that espeak-ng speech synthesis works with Linphone v4.4.0-alpha.43 but there is no way to configure the correct language per chat, nor is it described how to use festival or other speech synthesis with Linphone-Desktop.

How is it all configured?
How does the speech synthesis guess the correct language used?

**Comment by julonexus** [comment]
There are no implemented options.
The tool behind the Speech is the QTextToSpeech from Qt : https://doc.qt.io/qt-5/qtexttospeech.html
The default is the system locale.

If you are willing to code something about that, that is at https://gitlab.linphone.org/BC/public/linphone-desktop/-/blob/master/linphone-app/src/components/other/text-to-speech/TextToSpeech.cpp

**Comment by leukimi** [comment]
The guess is that each conversation could be in a different language. Either the user can set the language self per chat, or some simple privacy concerned analysis has to guess the language used. Then espeak-ng voice synthesis or festival can read out the message in a way that can actually be understood.

The analysis of which language is used could be based on characters used (quite obsolete, since many drop the apostrophes) or specific characteristic words for that language. Not sure how translators guess the language.

It seems that the simplest way would be to add the choice of language in the chat, which then speech engine uses to pronounce more corectly. espeak-ng is probably the best way to go for Linux currently, since it supports more languages.

Where the language selection should be put in the chat window is maybe something the project could/should decide first before the code is adapted to use special form of the speech synthesis.

How does one become a resource on the project, since it is a company, economics and such? Do you employ virtually or how does it work?
