### ISSUE TITLE
Linphone closes after starting Mac OS 10.15

### ISSUE THREAD

**Issue by it555** [BelledonneCommunications/linphone-desktop#586]
When I start the program, a window opens for 1 second and closes.
versions: 4.3 and 4.4 (beta)

**Comment by julonexus** [comment]
The crash is known and is under fix. It is about OpenGL 4 that is not yet supported.

**Comment by it555** [comment]
Thanks for the answer!
What do you recommend?

**Comment by julonexus** [comment]
I found a workaround by setting an earlier version with QSurfaceFormat in main.cpp
For example:
```
QSurfaceFormat format;
format.setVersion(2,1);
QSurfaceFormat::setDefaultFormat(format);
```

**Comment by it555** [comment]
What version of the program did you install?
And where to find the file main.cpp?
Thanks.

**Comment by it555** [comment]
> The crash is known and is under fix. It is about OpenGL 4 that is not yet supported.

Is there any information on when to wait for the next version of linзрone with bug fixes?

**Comment by julonexus** [comment]
The last version have the fix. If it still crashes on your side, you need to open another issue with more data like requested by github template.
Regards
