### ISSUE TITLE
Call Log / History - Missing button to view

### ISSUE THREAD

**Issue by chriswatt** [BelledonneCommunications/linphone-desktop#587]
Using Linphone Desktop Linux 4.3.2

After an inbound missed call, an indicator shows at the top left corner next to my display name, clicking it then shows the call history. After you click the indicator it disappears, offering no other way to get back to call history.

![image](https://user-images.githubusercontent.com/488912/144863774-51647294-f5b2-48d6-921d-24668d82598c.png)

**Comment by chriswatt** [comment]
Related issue #560 - 

> Hi, A new icon has been added in the filter bar in order to view all calls. It will be available on 4.3.1 in next days. Regards

Not seeing the new icon in 4.3.2, also missing from 4.4.0-alpha-75

**Comment by kiorky** [comment]
confirmed

**Comment by julonexus** [comment]
The bar is hide when there are no chat rooms. Missing call is not a chat room.
As a workaround, you can open a new chat room by sending a message to someone.
