### ISSUE TITLE
Current [2021-12-15] Version: What's that?

### ISSUE THREAD

**Issue by jayjupdhig** [BelledonneCommunications/linphone-desktop#589]
### Context

Only see that gui after connecting with fake account data to test that linphone is able for multiple accounts or not.

### General information

- Device: Lenovo Workstation
- OS: Windows 10 Pro x64
- Version of the App: Most current
- Version of the SDK: ?

### Expected behaviour

All, but not a start screen like that!!

### To Reproduce

As described above

### Additional context

Screenshot:

![linphone](https://user-images.githubusercontent.com/42765391/146193729-c6437e93-f964-4fb0-b4b2-09ff398fa200.jpg)

**Comment by jayjupdhig** [comment]
???

**Comment by jayjupdhig** [comment]
Problem still persists...

**Comment by julonexus** [comment]
This issue is coming from Qt and OpenGL. You could try to deactivate/activate mipmap settings in "User interface" panel.

**Comment by jayjupdhig** [comment]
ok thx, will look on it!!
