### ISSUE TITLE
ms2  can't compile success(win7+vs2015), anyone can help?

### ISSUE THREAD

**Issue by Charist** [BelledonneCommunications/linphone-desktop#59]
**_I compile all the other projects but ms2, and the linphone\linphoneqt which depends on it.
the VS console print:_** 
 -- Found Speex: D:/workspace/projects/Others/linphone-source/linphone-desktop/OUTPUT/desktop/include
  -- Found SpeexDsp: D:/workspace/projects/Others/linphone-source/linphone-desktop/OUTPUT/desktop/include
  -- Could NOT find PulseAudio (missing:  PULSEAUDIO_INCLUDE_DIRS PULSEAUDIO_LIBRARIES HAVE_PULSE_PULSEAUDIO_H HAVE_PA_MAINLOOP_NEW)
  -- Looking for pthread.h
  -- Looking for pthread.h - not found
 `  CMake Error at D:/Program Files/cmake-3.7.0-rc2-win64-x64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
    Could NOT find FFMpeg (missing: FFMPEG_INCLUDE_DIRS FFMPEG_LIBRARIES
    LIBAVCODEC_INCLUDE_DIRS LIBAVUTIL_INCLUDE_DIRS LIBSWSCALE_INCLUDE_DIRS
    LIBAVCODEC_LIBRARIES LIBAVUTIL_LIBRARIES LIBSWSCALE_LIBRARIES)
  Call Stack (most recent call first):
    D:/Program Files/cmake-3.7.0-rc2-win64-x64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    cmake/FindFFMpeg.cmake:108 (find_package_handle_standard_args)
    CMakeLists.txt:236 (find_package)

  -- Configuring incomplete, errors occurred!
  See also "D:/workspace/projects/Others/linphone-source/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
  See also "D:/workspace/projects/Others/linphone-source/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeError.log".
`

**_the ms2/CMakeFiles/CMakeError.log print:_**

 `cl /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_4daee.dir\Debug\\" /Fd"cmTC_4daee.dir\Debug\vc140.pdb" /Gd /TC /analyze- /errorReport:queue "D:\workspace\projects\Others\linphone-source\linphone-desktop\WORK\desktop\Build\ms2\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  CheckIncludeFile.c

D:\workspace\projects\Others\linphone-source\linphone-desktop\WORK\desktop\Build\ms2\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件:##  **“sys/shm.h”: No such file or directory** [D:\workspace\projects\Others\linphone-source\linphone-desktop\WORK\desktop\Build\ms2\CMakeFiles\CMakeTmp\cmTC_4daee.vcxproj]
`
`  LINK : fatal error LNK1104: ## 无法打开文件“dl.lib” [D:\workspace\projects\Others\linphone-source\linphone-desktop\WORK\desktop\Build\ms2\CMakeFiles\CMakeTmp\cmTC_744bd.vcxproj]
`
`
  D:\workspace\projects\Others\linphone-source\linphone-desktop\WORK\desktop\Build\ms2\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: **“alloca.h”: No such file or directory** [D:\workspace\projects\Others\linphone-source\linphone-desktop\WORK\desktop\Build\ms2\CMakeFiles\CMakeTmp\cmTC_43b68.vcxproj]
`
`D:\workspace\projects\Others\linphone-source\linphone-desktop\WORK\desktop\Build\ms2\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件:  **“pthread.h”: No such file or directory** [D:\workspace\projects\Others\linphone-source\linphone-desktop\WORK\desktop\Build\ms2\CMakeFiles\CMakeTmp\cmTC_76cbf.vcxproj]
`

**_I found phread.h exist in the C:\MinGW\include. Did I miss something? Can any one help?_**

**Comment by Wescoeur** [comment]
FFmpeg was not found in your system. Can I see your build commands? (prepare.py, cmake...)

**Comment by Charist** [comment]
I have fix it, It has some error while compile FFmpeg. Thank you all the same

**Comment by qq529668986** [comment]
I have the same as issues of you. I want to know, how did you solve it?

**Comment by qq529668986** [comment]
> I have fix it, It has some error while compile FFmpeg. Thank you all the same

I have the same as issues of you. I want to know, how did you solve it?

**Comment by hcq11** [comment]
> I have fix it, It has some error while compile FFmpeg. Thank you all the same

Could you tell me how to rolve it?I hava the same as issues of you

**Comment by hcq11** [comment]
> > I have fix it, It has some error while compile FFmpeg. Thank you all the same
> 
> I have the same as issues of you. I want to know, how did you solve it?

did you solve it ?
