### ISSUE TITLE
[Bug]: Proxy SIP account missing in preferences when ui.show_local_sip_account=0

### ISSUE THREAD

**Issue by cweiske** [BelledonneCommunications/linphone-desktop#590]
### Context

I use Linphone to start and receive telephone calls for numbers registered on my router.

### General information

- Device: Desktop PC
- OS: Ubuntu 20.04
- Version of the App: Linphone-4.3.2.AppImage
- Version of the SDK: Desktop 4.3.2 - Qt5.12.12, Core 5.0.49

### Expected behaviour

I want to hide the automatically created local SIP account by using the setting

    [ui]
    show_local_sip_account=0

With that I still want to be able to edit all the proxy sip accounts in the preferences.

The bug: When the setting is enabled, the first SIP proxy account is not shown anymore in the preferences

### To Reproduce

1. Make sure that the local SIP account is visible by opening the presence status popup from the main window. "sip@myipaddress" must be visible.
2. Create a SIP proxy account
3. Open preferences. The new account is visible in "SIP accounts" > "Proxy accounts"
4. Quit Linphone
5. Edit the configuration file and add
```
[ui]
show_local_sip_account=0
```
6. Start linphone
7. Open the presence status popup. "sip@myipaddress" is not visible anymore (which is correct)
8. Open preferences. The proxy account is not visible anymore in  "SIP accounts" > "Proxy accounts" 

Note: Only the first proxy account is not visible. If you have two proxy accounts, the second one is there.

**Comment by olku** [comment]
I was about to report this very same problem, on macOS Monterey 12.0.1

**Comment by julonexus** [comment]
Thanks for the report.
Fix: https://gitlab.linphone.org/BC/public/linphone-desktop/-/commit/9bd60217821d027a20073676313440555a9d7a77
