### ISSUE TITLE
Please offer option of compact interface when calling

### ISSUE THREAD

**Issue by morciej** [BelledonneCommunications/linphone-desktop#596]
I am using Linphone from Appimage (Desktop 4.3.1 - Qt5.12.12 Core 5.0.47 on Linux Mint Ulyssa/Focal.) The two windows that show up during call are taking up more than half of the screen. I know I can ignore them, or minimize them, but I need that keypad...

Would it be possible to offer a minimal version of call window, and not show the main window at all during call, as an option? All a caller really needs is contact list when idle, and DTMF keypad when in call. Chat options are nice, but not while talking on the phone.

For example, something like this:

![Proposed](https://user-images.githubusercontent.com/17895139/148462583-0608b88f-9933-4217-b980-78aa69fcfd90.png)

Thanks for considering.

![Linphone screen real estate](https://user-images.githubusercontent.com/17895139/148449071-0c3408ff-de5e-4515-ad16-857f8cdbd294.png)

**Comment by GrimAnEye** [comment]
up!

**Comment by morciej** [comment]
Very nice!

**Comment by GrimAnEye** [comment]
@morciej Hello, have you looked into this issue? If you can implement a compact interface - that would be fantastic!

**Comment by morciej** [comment]
I am not a developer, just a retiree who needs a good softphone with SMS capability that works with voip.ms.

**Comment by GrimAnEye** [comment]
up

**Comment by Polve** [comment]
That would make linphone finally usable!
