### ISSUE TITLE
[Bug]: H264 codec fails to download

### ISSUE THREAD

**Issue by InterLinked1** [BelledonneCommunications/linphone-desktop#603]
### Context

I downloaded Linphone to try to do some testing with H264 and Asterisk. However, I never got that far, as H264 is not built in and doesn't download when asked to.

### General information

- Device: Dell OptiPlex 980
- OS: Windows 7 Enterprise
- Version of the App: 4.3.2 (latest)

### Expected behaviour

Toggling on and then downloading would add the codec.

### To Reproduce

1. Go to "Video" tab
2.  Try to toggle H264 on.
3. Click "CONFIRM" to download from Cisco.
4. It ends at 276B/276B, but says "Failed to install H264!" after just a second.

Since H264 isn't included, and it won't download, H264 support is broken at the moment.

**Comment by julonexus** [comment]
Duplicate : https://github.com/BelledonneCommunications/linphone-desktop/issues/595
