### ISSUE TITLE
[Bug]: Call recording fails in Windows due to invalid character in file name.

### ISSUE THREAD

**Issue by IamGimli** [BelledonneCommunications/linphone-desktop#605]
### Context

When recording a phone call in Windows, the recording will fail without an error message if the file name generated includes a character that is invalid for a Windows file name, such as "*". This can happen if the phone number dialed includes such a character, such as calls to * shorthands (for example, my VOIP provider uses *97 to access an account's voice mail).

The Linphone User Interface fails to notify the user that the recording couldn't be started and, instead, shows indicators that the recording is actually taking place, even though that is not the case.

### General information

- Device: Home desktop computer
- OS: Windows 10 Pro x64
- Version of the App: 4.3.2
- Version of the SDK: N/A

Excerpt from the log file when opening the recording file fails:
```
2022-02-05 11:08:50:192 [/mediastreamer] MESSAGE MKVRecorder: opening file C:/Temp/Linphone\2022-02-05_11-08-48_121834_soft_*97.mkv in create mode
2022-02-05 11:08:50:192 [/mediastreamer] ERROR MKVRecorder: fail to open C:/Temp/Linphone\2022-02-05_11-08-48_121834_soft_*97.mkv

```

### Expected behaviour

The file names generated on Windows should be compliant with Windows file naming standards by replacing invalid characters with valid characters automatically or omitting the invalid characters altogether.

Moreover, if the recording can't be triggered due to a failure to create the recording file, the UI should show an error message instead of acting as if the recording is under way.

### To Reproduce

Call a number which contains a character which is invalid in Windows file names, such as *97.

Trigger a recording of the call. Linphone will show the call as being recorded. After the call ends, Linphone will issue a notification to the OS with a path to the recorded call. Clicking the notification takes the user to an empty directory as the file could not be created.

**Comment by julonexus** [comment]
Hi, Thanks for your report. A fix has been done and it will be available for the next release of 4.4.
Regards
