### ISSUE TITLE
No WebView plug-in found!

### ISSUE THREAD

**Issue by Annirudh-sh** [BelledonneCommunications/linphone-desktop#609]
The following error occurred after I finished building Linphone-desktop on Ubuntu.
Whenever I click on " Create Linphone Account" or "Use A Linphone Account", this error pops up.

[0x55ec6f98ca70][Warning]No WebView plug-in found!

**Comment by julonexus** [comment]
linuxdeploy doesn't deploy correctly the webview. You can check this workaround : https://gitlab.linphone.org/BC/public/linphone-desktop/-/commit/4ed608f01798c1a1d57426d98c0f22e7e2476a9e

**Comment by julonexus** [comment]
plugin has been removed.
