### ISSUE TITLE
Provide a way to disable subscribe to rls@sip.linphone.org

### ISSUE THREAD

**Issue by systemcrash** [BelledonneCommunications/linphone-desktop#61]
Why does this client send messages like the following which contain an XML list of my personal contacts for an account which is on an entirely different domain? I have not even manually subscribed to this sip:rls@sip.linphone.org resource, nor given permission to. This surreptitious data-gathering is to be considered as a violation of privacy and breach of trust. :(

SUBSCRIBE sip:rls@sip.linphone.org SIP/2.0
Via: SIP/2.0/UDP redacted:5060;branch=z9hG4bK.redacted;rport
From: <sip:redacted>;tag=redacted
To: sips:rls@sip.linphone.org
CSeq: 29 SUBSCRIBE
Call-ID: redacted
Max-Forwards: 70
Supported: eventlist
Event: presence
Expires: 3600
Content-Type: application/resource-lists+xml
Content-Length: redacted
Content-Encoding: deflate
Contact: <redacted@redacted;transport=udp>;+sip.instance="<urn:uuid:redacted>"
Require: recipient-list-subscribe
Accept: multipart/related
Accept: application/pidf+xml
Accept: application/rlmi+xml
Content-Disposition: recipient-list
Accept-Encoding: deflate
User-Agent: Linphone Desktop/4.1.1 (belle-sip/1.6.3)
<?xml version="1.0" encoding="UTF-8"?>
<resource-lists xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:ietf:params:xml:ns:resource-lists">
 <list>
  <entry uri="redacted"/>
  ...
 </list>
</resource-lists>

**Comment by Wescoeur** [comment]
Don't worry, it's not a violation of privacy. This message is handled by [flexisip](https://github.com/BelledonneCommunications/flexisip) and it's used to show in the app what contact is connected. This data is not saved by flexisip (you can check the source code if you want.)

If you don't want to send this data, you can disable the presence in your sip address config.

**Comment by systemcrash** [comment]
Thank you for the answer.

Publishing of presence info is done to the proxy to which you REGISTER, not to an arbitrary proxy sip:rls@sip.linphone.org. There are methods subscribe and notify to endpoints in your address book. Why would my @corp.com account *ever* need to send this info to linphone.org?

The response that the arbitrary proxy sends is 404 anyway, meaning sending the data is supposedly pointless, but I have no idea what happens to the data beyond that proxy. 

This 'data' is a violation of privacy. And should not happen, irrespective of 'presence'.

**Comment by Wescoeur** [comment]
Okay. I see the problem in your case, I will make an option to disable this feature globally.

**Comment by Wescoeur** [comment]
Fixed in this commit: 5cd97cb5c644984a7ab7b729566365712faef236
You can disable the RLS URI in the Settings (See the `Presence` part in `Network` tab.)

**Comment by systemcrash** [comment]
Okay, I tried an August 24th nightly and disabled the "Use RLS URI" setting to NEVER. That seemed to do the trick. 

The setting could do with being renamed to something far more meaningful than "RLS URI" (what is that?)

I propose: "Send unsolicited Publish of contacts to Linphone (to find friends)"

**Comment by Wescoeur** [comment]
https://tools.ietf.org/html/rfc4662#section-2 => `RLS:  Resource List Server.`
https://tools.ietf.org/html/rfc4662#section-3 => `This resource list is represented by a SIP URI.`

So `RLS URI` appeared to be a good name. Or `Send solicited Publish of contacts to Linphone to find connected friends`.

**Comment by systemcrash** [comment]
Ah, thank you. I wasn't aware it was standards backed. How about:

Send unsolicited SIP SUBSCRIBE of contacts to Linphone Resource List Server (RLS) to find connected friends.

I urge that it default to disabled/never, since this is a SUBSCRIBE being sent to a domain to which the user is not (yet) REGISTERed, or probably even cognizant of.  The standard you mention references a single federated domain and refers to sub-domains, e.g. Stockholm, Vancouver etc. (and not inter-domain). At least make this disabled for those installs that do not have accounts "@linphone" out of the box.

https://tools.ietf.org/html/rfc5039
https://tools.ietf.org/html/rfc3265

Because SUBSCRIBE events create dialogues, where there is no prior REGISTER, it is thus unsolicited - from UAC or UAS perspective not important here. (The user does not yet know that their client is sending their contact list somewhere)  An annoying sales phone call in the evening you weren't expecting? Solicited or unsolicited? Did you sign up to be called at a specific time? Solicited or unsolicited?

There was a time when users were once impressed by things happening transparently and contacts being found - but now security and privacy are of great concern and debate, as reflected by the advent of TLS and SRTP etc. Private contacts (zipped) sent over an unencrypted connection without user consent is alarming to any privacy advocate. Users should be aware of what is happening to their data.

**Comment by systemcrash** [comment]
Additionally, I think the un/solicited will be implied when the user has en/disabled the setting, understanding what it does.

**Comment by pdarcos** [comment]
What's the latest status of this feature?

Is it already possible to disable presence completely and by default for all accounts?
Do we just place rls_uri_enabled=0 in linphone_factory to diable presence globally?

I see under the [ui] section other parameters. What does rc_version do and what happens if force_assistant_at_startup=1? Does this mean the Assistant is run every single time Linphone starts or just on first run until an account is active?

 [ui]
rc_version=1
force_assistant_at_startup=0
logs_enabled=1

Thanks

**Comment by systemcrash** [comment]
It's committed, exists in nightlies.

**Comment by pdarcos** [comment]
So if I set rls_uri_enabled=0 in linphone_factory it will be globally disabled?
