### ISSUE TITLE
[Bug]: Cannot download submodule from gitlab.linphone.org -  SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by Shkiperon** [BelledonneCommunications/linphone-desktop#610]
### Context

I'm trying to use one of these commands:

git clone https://github.com/BelledonneCommunications/linphone-desktop --recursive
git clone https://gitlab.linphone.org/BC/public/linphone-desktop.git --recursive

### General information

- Device:
- OS:
- Version of the App:
- Version of the SDK:

### Expected behaviour

I just want to download the project, but you are forget about certificate expiration date.

### To Reproduce

Just try run one of the two commands from "Context" block

**Comment by Shkiperon** [comment]
Error changed:
fatal: «http://gitlab.linphone.org/BC/public/linphone-desktop.git/» unavailable: SSL certificate problem: unable to get local issuer certificate

**Comment by julonexus** [comment]
The webserver was misconfigured.
