### ISSUE TITLE
Caution sign with new SIP accounts

### ISSUE THREAD

**Issue by Annirudh-sh** [BelledonneCommunications/linphone-desktop#612]
![logx2](https://user-images.githubusercontent.com/61970861/154469569-8a002f62-4449-45e6-bb91-0d1c5409ad88.png)

A caution sign appears after every new SIP account is created.

**Comment by julonexus** [comment]
You are not connected.

**Comment by Annirudh-sh** [comment]
connected where?
I was connected to a local server.
