### ISSUE TITLE
QT project files missing for visual editing the UI 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-desktop#62]
the qml files are present but no qt project file is found in your build, I can edit the qml files through command line vim but can not see the result unless I compile the whole build. also this does not load in Xcode work space either. any assistance on gui editing for visual UI edits ? I downloaded QT Creator for Mac as well and it states there are no project files just allows me to textually edit the qml

**Comment by Wescoeur** [comment]
- There is no Qt project inside `linphone-desktop`. It uses only `cmake`.
- The Xcode support is chaotic for the moment. (Bad source tree in the editor, I must fix this in `CMakeLists.txt`).
- The edition of `qml` files with direct preview is only available for some files. (Why? The big part of qml files in the project uses QML components defined in the C++ source code. => Result visible at runtime.)

**Comment by S0U1SB4N3** [comment]
Thank you for explanation

**Comment by Simoon-F** [comment]
> * linphone-desktop

Does it mean that linphone-desktop does not support custom UI?
