### ISSUE TITLE
[Bug]: Incoming call shown in wrong account

### ISSUE THREAD

**Issue by cweiske** [BelledonneCommunications/linphone-desktop#620]
### Context

I use Linphone on my Ubuntu Linux desktop to start and receive calls for my work and my personal telephone number.
For that I have setup two SIP accounts in Linphone that both go to my router which provides the SIP accounts.

The problem:
When an call is incoming, it gets logged to the account that is currently selected in the UI, and not to the account that is is actually for.

Example:
In the Linphone desktop UI, I select my home account to be the active one. Now a call to my work number is incoming, and it is shown in the call log of my home account. When switching to my work account, the call is not visible.

### General information

- OS: Ubuntu 20.04
- Version of the App: Desktop 4.3.2 - Qt5.12.12
- Version of the SDK: Core 5.0.49

### Expected behaviour

When a call for my work SIP account is incoming, it should be added to the work account's call log, no matter if the home accounts is currently active or not.

### To Reproduce

1. Have 2 SIP accounts setup in Linphone, "home" and "work".
2. Click on the account name on the top left
3. Select "work" to be the active account in the popup window
4. Call your "home" phone number and cancel the call
5. The call log (left side of the main window) will show the call <-- this is the problem
6. Click the account name on the top left and switch to the "home" account
7. The call log does not show the call <-- this is also the problem

### Additional context

![2022-03-02 linphone](https://user-images.githubusercontent.com/59036/156383710-ba7bd90e-60e6-40e7-a0c7-7684892f250f.png)

**Comment by julonexus** [comment]
Hi, could you test it with the last [beta](https://download.linphone.org/snapshots/AppImages/Linphone-4.4.0-beta.39+cf5f918d.AppImage) ? 
I don't reproduce it with it.

**Comment by cweiske** [comment]
Yes, it happens here with Desktop 4.4.0-beta-39-gcf5f918d - Qt5.12.12, Core 5.1.10

**Comment by julonexus** [comment]
Just to confirm : You hide the computed default proxy? And then "For that I have setup two SIP accounts", the first one (cweiske-mojic@...) was manually set?
Do you have a log? I guess your are not calling from "cweiske-home" on another device.

**Comment by cweiske** [comment]
I tried calling from my mobile phone to my home account twice, once when the work account is active, and once when my home account is active in linphone.

I'm sending the logs by mail to you because I don't want all those log data appear publicly in this bug report.

**Comment by cweiske** [comment]
An update to router firmware 6.87 did not change the From: behavior

**Comment by julonexus** [comment]
I made a fix on chat room creations when receiving a call : https://download.linphone.org/snapshots/temp/Linphone-4.4.0-beta.42+db55480e.AppImage

**Comment by cweiske** [comment]
I get a crash. 
[linphone.crash.log](https://github.com/BelledonneCommunications/linphone-desktop/files/8262542/linphone.crash.log)

```
[14:31:20:940][0xda7770][Info]ChatRoom creation of  ""  at  0  security and with  (QVariant(QString, "sip:mymobilephonenumber@fritz.box"))
[New Thread 0x7fff9657f700 (LWP 140375)]
[14:31:21:108][0xda7770][Info]"Add call:" "sip:cweiske-mogic@192.168.3.4" "\"Christian Weiske\" <sip:mymobilephonenumber@fritz.box>"

Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.
linphone_chat_room_get_current_params (cr=<optimized out>)
    at ../../../../../../../linphone-sdk/liblinphone/src/c-wrapper/api/c-chat-room.cpp:88
88	../../../../../../../linphone-sdk/liblinphone/src/c-wrapper/api/c-chat-room.cpp: Datei oder Verzeichnis nicht gefunden.
```

**Comment by julonexus** [comment]
What about this one? https://download.linphone.org/snapshots/temp/Linphone-4.4.0-beta.42+6fc1b1ce.AppImage

**Comment by cweiske** [comment]
- No crash
- No chat room entry in the left list was created, neither in the correct nor in the other account. Was this what you wanted to do?
- A question: The call log (the small phone icon with the clock below "contacts") does not change when switching active account. Is that planned that way? I don't see which of both accounts the call was for.

**Comment by julonexus** [comment]
Thanks. You should get a chat room for the other account., not having it is not wanted.
- yes, the buttons show the whole call history. It was implemented only for convenience so features are limited. I'm taking account about showing local account. But it will be done for the 4.5.

**Comment by julonexus** [comment]
Did you unchecked the option "Hide empty chat rooms" in "Call and Chat"? Because if you don't have any messages (not call log) in the room, it is considered as empty.

**Comment by cweiske** [comment]
No, I did not enable that option.

**Comment by cweiske** [comment]
(Not sure if I should open a new bug, but that 4.4.0-beta.42+6fc1b1ce constantly takes 11% CPU, even when it should be idling and I'm not using it)

**Comment by julonexus** [comment]
> (Not sure if I should open a new bug, but that 4.4.0-beta.42+6fc1b1ce constantly takes 11% CPU, even when it should be idling and I'm not using it)

Hidding the timeline may improve the CPU consumption.

**Comment by cweiske** [comment]
I've sent you the logs by e-mail.

And yes, when the window is closed and only the tray icon is left, the CPU utilization of linphone drops from 11-12% to 0.7%.

**Comment by julonexus** [comment]
I'm sorry but there are nothing obvious in your logs. Your chat room is created and there are no errors about it.

So the only solution is that you must set hide_empty_chat_rooms=0 in the misc section.
But as long as you wrote that you already done that by not enabling this option, I don't see why you don't have this chat room :/

**Comment by cweiske** [comment]
I removed `~/.config/linphone/linphonerc` and `~/.local/share/linphone` and setup linphone freshly with only my work account.
The problem is still there: The call appears in the call log list, but no chat room is visible on the left side.

(Linphone-4.4.0-beta.42+f2ec342c, even though "about" shows "Desktop 4.4.0-beta-42-gf2ec342c")

**Comment by cweiske** [comment]
Also happens with Desktop 4.4.0-beta-46-g49eb29fe - Qt5.12.12

**Comment by cweiske** [comment]
Linphone Desktop 4.4.0-beta-53-g1667b78b still does not create new chatrooms for incoming calls.

**Comment by cweiske** [comment]
When doing an outgoing call, a chatroom is created.
It has some strange behavior though. Maybe it is related to the chatroom-not-appearing-problem:

1. Make outgoing call and hang up before the other side answers. Chatroom is created.
2. Click on the chatroom so the call history is shown (which the recent call is not listed in! It only gets listed when the other side picks up)
3. Click the waste basked icon to clear the history
4. Confirm the clearing
5. The chatroom is not visible in the left list anymore
6. Click the account selector
7. The deleted chatroom re-appears (this is the bug)
8. Delete the chatroom again
9. Quit Linphone
10. Start Linphone
11. The deleted chatroom is there again (this is the bug again)
12. Delete the chatroom
13. Open account selector
14. The deleted chatroom does not re-appear.

(all with Desktop 4.4.0-beta-53-g1667b78b - Qt5.12.12 Core 5.1.15-3-g591f8fe7e)

**Comment by cweiske** [comment]
The original issue has been fixed (Call shown in wrong account).
I've opened #660 for the new problem (no chatlog for incoming call).
