### ISSUE TITLE
High CPU usage when idling

### ISSUE THREAD

**Issue by julonexus** [BelledonneCommunications/linphone-desktop#624]
(Not sure if I should open a new bug, but that 4.4.0-beta.42+6fc1b1ce constantly takes 11% CPU, even when it should be idling and I'm not using it)

_Originally posted by @cweiske in https://github.com/BelledonneCommunications/linphone-desktop/issues/620#issuecomment-1069384508_

**Comment by julonexus** [comment]
Should be r"esolved with https://download.linphone.org/snapshots/AppImages/Linphone-4.4.0-beta.49+592ca087.AppImage

**Comment by cweiske** [comment]
I confirm it's fixed with Desktop 4.4.0-beta-50-g5bb35ff5
