### ISSUE TITLE
Some problems about linphone desktop

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-desktop#636]
Hi,
I just downloaded liphone-desktop code. I'd like to ask you some questions:
1， After compiling linphone desktop, how can I demonstrate the effect？
2，What is the relationship between linphone app and linphone SDK? How do they call each other?
3，Which file is it to process H264 video and which file is it to process audio?
4，I have downloaded Qt5.12.9, how to call linphone-desktop?

First contact with linphone-desktop, please give me more advice,。thank you！
Best Regards!

**Comment by soroshsabz** [comment]
Did you can build it? related to #647 #652
