### ISSUE TITLE
Can't open menu button - compiled with Qt 5.9.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by nbubis** [BelledonneCommunications/linphone-desktop#64]
In Linphone 4.0, there's a menu button on the top right (the three horizontal lines), which when clicked, does not open any additional dialogues / menus. This happens with a clean download of the Qt 5.9.1 installer. No terminal logs appear when clicking the menu button.

**Comment by bderembl** [comment]
Is this related to #45 ?

**Comment by Wescoeur** [comment]
Not the same problem. On Ubuntu you have one main desktop bar and the options of the button on the top right are only available in this place.

This component is used: https://doc.qt.io/qt-5/qml-qt-labs-platform-menubar.html
At this moment, it's not (easily) possible to create the options in the main ubuntu bar and in a popup menu. It's a little bug.

**Comment by Jona-lee** [comment]
I have also encountered the same problem, but if run as root it can pop a angly menu
sudo ./linphone

why this bug's severity is low?

**Comment by Jona-lee** [comment]
It's obviously a big bug.

**Comment by Jona-lee** [comment]
Linux version 4.10.0-42-generic (buildd@lgw01-amd64-007) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) ) #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017

OUTPUT/desktop/bin$ ./linphone-tester
QML debugging is enabled. Only use this in a safe environment.
[13:16:23:974][0x230f710][Info]app/App.cpp:111: "Use locale: en_US"
[13:16:24:246][0x230f710][Info]app/App.cpp:178: "Library paths:" ("/home/jwli/Qt5.9.1/5.9.1/gcc_64/plugins", "/home/jwli/worksp/tools_software/ubuntu_ware/linphone-desktop/OUTPUT/desktop/bin")
[13:16:24:246][0x28e8430][Info]components/core/CoreManager.cpp:211: "Launch async linphone core creation."
[13:16:24:257][0x230f710][Info]app/App.cpp:202: "Activated selectors:" ("custom", "en_US", "unix", "linux", "ubuntu")
[13:16:24:258][0x230f710][Info]app/App.cpp:384: "Registering types..."
[13:16:24:258][0x230f710][Info]app/App.cpp:418: "Registering shared types..."
[13:16:24:258][0x230f710][Info]app/App.cpp:430: "Registering tool types..."
[13:16:24:258][0x230f710][Info]app/App.cpp:438: "Registering shared tool types..."
[13:16:24:325][0x230f710][Info]app/App.cpp:139: "Open splash screen..."
[13:16:24:353][0x230f710][Info]app/App.cpp:234: "Loading main view..."
********* Start testing of SelfTest *********
Config: Using QtTest library 5.9.1, Qt 5.9.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20160406 (Red Hat 5.3.1-6))
PASS   : SelfTest::initTestCase()
QINFO  : SelfTest::checkAppStartup() "Set `Friends` path: `/home/jwli/.local/share/linphone/friends.db`"
QINFO  : SelfTest::checkAppStartup() "Set `CallLogs` path: `/home/jwli/.local/share/linphone/call-history.db`"
QINFO  : SelfTest::checkAppStartup() "Set `Chat` path: `/home/jwli/.local/share/linphone/message-history.db`"
QINFO  : SelfTest::checkAppStartup() "Core created. Enable iterate."
QINFO  : SelfTest::checkAppStartup() "Core started."
QINFO  : SelfTest::checkAppStartup() "Notify unread messages count: 0."
QINFO  : SelfTest::checkAppStartup() "Add sip address: `sip:1@192.168.132.135`."
QINFO  : SelfTest::checkAppStartup() "Add sip address: `sip:1@192.168.132.153:5062`."
QINFO  : SelfTest::checkAppStartup() "Open linphone app."
QINFO  : SelfTest::checkAppStartup() "Notify unread messages count: 0."
PASS   : SelfTest::checkAppStartup()
PASS   : SelfTest::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 384ms
********* Finished testing of SelfTest *********
********* Start testing of MainViewTest *********
Config: Using QtTest library 5.9.1, Qt 5.9.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20160406 (Red Hat 5.3.1-6))
PASS   : MainViewTest::initTestCase()
PASS   : MainViewTest::showAboutPopup()
PASS   : MainViewTest::showManageAccountsPopup()
QINFO  : MainViewTest::showSettingsWindow() "Update nat policy."
PASS   : MainViewTest::showSettingsWindow()
PASS   : MainViewTest::testMainMenuEntries(home view 1)
PASS   : MainViewTest::testMainMenuEntries(contacts view 1)
PASS   : MainViewTest::testMainMenuEntries(home view 2)
PASS   : MainViewTest::testMainMenuEntries(contacts view 2)
PASS   : MainViewTest::cleanupTestCase()
Totals: 9 passed, 0 failed, 0 skipped, 0 blacklisted, 1321ms
********* Finished testing of MainViewTest *********
********* Start testing of AssistantViewTest *********
Config: Using QtTest library 5.9.1, Qt 5.9.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20160406 (Red Hat 5.3.1-6))
PASS   : AssistantViewTest::initTestCase()
PASS   : AssistantViewTest::showAssistantView()
PASS   : AssistantViewTest::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 151ms
********* Finished testing of AssistantViewTest *********
[13:16:26:292][0x230f710][Info]tests/main.cpp:100: "Tests seems OK. :)"
[13:16:26:292][0x230f710][Info]app/App.cpp:115: "Destroying app..."

**Comment by Jona-lee** [comment]
sometimes the linphone-tester will return failure

QML debugging is enabled. Only use this in a safe environment.
[13:19:15:004][0x1eff710][Info]app/App.cpp:111: "Use locale: en_US"
[13:19:15:033][0x1eff710][Info]app/App.cpp:178: "Library paths:" ("/home/jwli/Qt5.9.1/5.9.1/gcc_64/plugins", "/home/jwli/worksp/tools_software/ubuntu_ware/linphone-desktop/OUTPUT/desktop/bin")
[13:19:15:033][0x248a790][Info]components/core/CoreManager.cpp:211: "Launch async linphone core creation."
[13:19:15:035][0x1eff710][Info]app/App.cpp:202: "Activated selectors:" ("custom", "en_US", "unix", "linux", "ubuntu")
[13:19:15:035][0x1eff710][Info]app/App.cpp:384: "Registering types..."
[13:19:15:035][0x1eff710][Info]app/App.cpp:418: "Registering shared types..."
[13:19:15:035][0x1eff710][Info]app/App.cpp:430: "Registering tool types..."
[13:19:15:035][0x1eff710][Info]app/App.cpp:438: "Registering shared tool types..."
[13:19:15:102][0x1eff710][Info]app/App.cpp:139: "Open splash screen..."
[13:19:15:132][0x1eff710][Info]app/App.cpp:234: "Loading main view..."
********* Start testing of SelfTest *********
Config: Using QtTest library 5.9.1, Qt 5.9.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20160406 (Red Hat 5.3.1-6))
PASS   : SelfTest::initTestCase()
QINFO  : SelfTest::checkAppStartup() "Set `Friends` path: `/home/jwli/.local/share/linphone/friends.db`"
QINFO  : SelfTest::checkAppStartup() "Set `CallLogs` path: `/home/jwli/.local/share/linphone/call-history.db`"
QINFO  : SelfTest::checkAppStartup() "Set `Chat` path: `/home/jwli/.local/share/linphone/message-history.db`"
QINFO  : SelfTest::checkAppStartup() "Core created. Enable iterate."
QINFO  : SelfTest::checkAppStartup() "Core started."
QINFO  : SelfTest::checkAppStartup() "Notify unread messages count: 0."
QINFO  : SelfTest::checkAppStartup() "Add sip address: `sip:1@192.168.132.135`."
QINFO  : SelfTest::checkAppStartup() "Add sip address: `sip:1@192.168.132.153:5062`."
QINFO  : SelfTest::checkAppStartup() "Open linphone app."
QINFO  : SelfTest::checkAppStartup() "Notify unread messages count: 0."
PASS   : SelfTest::checkAppStartup()
PASS   : SelfTest::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 353ms
********* Finished testing of SelfTest *********
********* Start testing of MainViewTest *********
Config: Using QtTest library 5.9.1, Qt 5.9.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20160406 (Red Hat 5.3.1-6))
PASS   : MainViewTest::initTestCase()
PASS   : MainViewTest::showAboutPopup()
PASS   : MainViewTest::showManageAccountsPopup()
QINFO  : MainViewTest::showSettingsWindow() "Update nat policy."
PASS   : MainViewTest::showSettingsWindow()
PASS   : MainViewTest::testMainMenuEntries(home view 1)
PASS   : MainViewTest::testMainMenuEntries(contacts view 1)
PASS   : MainViewTest::testMainMenuEntries(home view 2)
PASS   : MainViewTest::testMainMenuEntries(contacts view 2)
PASS   : MainViewTest::cleanupTestCase()
Totals: 9 passed, 0 failed, 0 skipped, 0 blacklisted, 1264ms
********* Finished testing of MainViewTest *********
********* Start testing of AssistantViewTest *********
Config: Using QtTest library 5.9.1, Qt 5.9.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.3.1 20160406 (Red Hat 5.3.1-6))
PASS   : AssistantViewTest::initTestCase()
FAIL!  : AssistantViewTest::showAssistantView() 'spyLoaderReady.count() == 1' returned FALSE. ()
   Loc: [/home/jwli/worksp/tools_software/ubuntu_ware/linphone-desktop/src/tests/assistant-view/AssistantViewTest.cpp(46)]
PASS   : AssistantViewTest::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 114ms
********* Finished testing of AssistantViewTest *********
[13:19:16:950][0x1eff710][Warning]tests/main.cpp:98: "One or many tests are failed. :("
[13:19:16:950][0x1eff710][Info]app/App.cpp:115: "Destroying app..."

**Comment by Wescoeur** [comment]
> It's obviously a big bug.

No. On Ubuntu the menu options are available in the main desktop Ubuntu bar.
So the options are not invisible to the user.

**Comment by Wescoeur** [comment]
Fixed on master. But due to a Qt 5.10 limitation, the Ubuntu menu bar is not used now.
