### ISSUE TITLE
Could not find a support sound driver API

### ISSUE THREAD

**Issue by fengqz627** [BelledonneCommunications/linphone-desktop#640]
Hi,

cmake version 3.23.1
Python 3.8.10
pip 20.0.2
QT 5.12.9
ubuntu 20.04
The linphone-desktop I downloaded yesterday encountered Compilation error,
But I executed the following three commands, and the problem still exists. Please help :

sudo apt-get install libpulse-dev
sudo apt-get install pulseaudio
sudo apt-get install apulse

CMake Error at CMakeLists.txt:369 (message):
Could not find a support sound driver API. Use -DENABLE_SOUND=NO if you
don't care about having sound.

-- Configuring incomplete, errors occurred!
See also "/home/fqz/linphoneD/linphone-desktop/build/WORK/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
See also "/home/fqz/linphoneD/linphone-desktop/build/WORK/WORK/desktop/Build/ms2/CMakeFiles/CMakeError.log".
make[8]: *** [CMakeFiles/EP_ms2.dir/build.make:108: /home/fqz/linphoneD/linphone-desktop/build/WORK/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[7]: *** [CMakeFiles/Makefile2:953: CMakeFiles/EP_ms2.dir/all] Error 2

thanks.
Best Regards.

**Comment by seraphv3** [comment]
@fengqz627 Have you solved this problem? Please help, I encounter the same problem.

**Comment by Simran211103** [comment]
Hi sir, I am also getting the same issue, I request you to please guide me through it. I am using Ubuntu 22.04 and using the following listed commands:-
sudo apt-get remove --purge alsa-base
sudo apt-get remove --purge pulseaudio
sudo apt-get install alsa-base
sudo apt-get install pulseaudio
sudo alsa force-reload

It would be a great help for me. 
Thanks and Regards,
Simran Chetiwal
