### ISSUE TITLE
Accent menu having trouble on macOS

### ISSUE THREAD

**Issue by ddobrev** [BelledonneCommunications/linphone-desktop#65]
Note: a friend and I created SIP accounts today and started testing. This is the first one of the numerous issues we've found so far. We hope they can be fixed in a timely manner so that we can get rid of Skype once and for all.

As you know, macOS has an accent menu when typing text, anywhere. It is invoked by holding down a key at which no characters appear but rather the menu does. The problem in Linphone is that a few copies, 4 or 5, of the character appear before the menu shows up.

**Comment by Wescoeur** [comment]
> We hope they can be fixed in a timely manner so that we can get rid of Skype once and for all.

We are a small company, an we can't fix rapidly this problem. It's your choice if you want to use Skype.
But thank you for all your bug reports!

I can reproduce this issue, I add this to our list.

**Comment by ddobrev** [comment]
@Wescoeur please accept my apology if I have sounded too harsh on demanding. I rather meant that we have an extremely high desire to get rid of Skype and Linphone is one of our best hopes.

**Comment by Wescoeur** [comment]
No problem. ;)

Concerning this issue, it cannot be solved easily at this moment. 

Related: https://bugreports.qt.io/browse/QTBUG-50006
You can see the last comment too.

**Comment by ddobrev** [comment]
@Wescoeur I understand. Please allow me to offer a piece of advice: add your own comment to the issue. This way it serves as a vote which sometimes works to make authors fix their work. I think they would pay special attention if you called it a regression what it is. You could even add a new bug report since this regression is not the actual bug reported. The latter is the inability of Qt to switch to key repetition which does not concern Linphone.

**Comment by Wescoeur** [comment]
Always present... See: https://bugreports.qt.io/browse/QTBUG-68764

**Comment by julonexus** [comment]
Feature have been implemented by removing autorepeating keys in chat. It will be available in the next nightly build
