### ISSUE TITLE
[Bug]: CallerID is taken from last calls Information, not the current one

### ISSUE THREAD

**Issue by basti1508** [BelledonneCommunications/linphone-desktop#657]
### Context

I use the linphone-desktop on ubuntu against an Asterisk PBX.

### General information

- OS: Ubuntu
- Version of the App: 4.4.3

### Expected behaviour

The Caller ID shown in the ringing Call PopUp should be taken from the SIP-Header.

### To Reproduce

Send Invite with CallerID Name "abc" and extension 111
-> Call shows CallerID "abc"

Send Invite with CallerID Name "def" and extension 111
-> Call shows CallerID "abc"

Send Invite with CallerID Name "ghi" and extension 111
-> Call shows CallerID "def"

and so on. It seems the stored information gets overwritten AFTER the call. If you want to keep this behaviour, updating before showing the Incoming Call dialog would be better.

This is very annoying if you use CallerID Name for specific additional Information. Before 4.3.x this was not the case. This issue keeps us from updating to a current version.

**Comment by julonexus** [comment]
It should be fixed for next nightly (alpha 132)

**Comment by basti1508** [comment]
If I'm not wrong, this fix should be included in 4.4.6 release. I've just tested this release an it is not working (Same behavior as before)

**Comment by basti1508** [comment]
This issue is still not fixed in the 4.4.7 release @julonexus Can you reopen this pleases....

**Comment by julonexus** [comment]
What is read first (if you don't have a contact in your friends list) is the full address of the caller to get the display name (your "CallerID"), there is no other parsing before. If the display name is not found, then the search is done on call logs.

Please provide a log file of a call (till the end) where your popup doesn't show the right display name.

**Comment by basti1508** [comment]
@julonexus sure

This is the log: [linphone_bug2.log](https://github.com/BelledonneCommunications/linphone-desktop/files/9069037/linphone_bug2.log)

And this is what I see:
![linphone_bug_popup](https://user-images.githubusercontent.com/2934508/177921070-a055ac7f-3eb7-4de7-8876-6b83c4d76240.png)

**Comment by julonexus** [comment]
What about the 4.4.8?

**Comment by basti1508** [comment]
@julonexus Thank you very much. It seems to working in 4.4.8!
