### ISSUE TITLE
[Bug]: 4.5.0-alpha.128 app crashes if caller not logged in at linphone.org account

### ISSUE THREAD

**Issue by leukimi** [BelledonneCommunications/linphone-desktop#666]
4.5.0-alpha.128 app crashes if caller not logged in at linphone.org account.
This used to be possible to do before (to call without account).
If caller is logged in, the app does not crash.

- Device: Linux Desktop
- OS: Manjaro 21
- Version of the App: 4.5.0-alpha.128
- Version of the SDK: 5.2

### Expected behaviour

I wanted to do a simple call with the Linux client calling the Android phone. However, the desktop app crashed.

### To Reproduce

1. Delete account information in Preferences.
2. Place a call.
3. App crashes
4. Restart app
5. Place a call.
6. App crashes.

### Additional context

56:49:571[Info]"Notify event count: 0."
57:06:850[Warning]<Unknown File>: QML StateGroup: Can't apply a state change as part of a state definition.
segmentation fault (core dumped)    linphone

**Comment by julonexus** [comment]
4.5.0-alpha.128 app crashes if caller not logged  to an account (not related to linphone)
Fix: https://gitlab.linphone.org/BC/public/linphone-desktop/-/commit/f0c6c2e079ec9e55bc5f28093846e0fcc49d6529
