### ISSUE TITLE
History date is one day behind

### ISSUE THREAD

**Issue by robdyck** [BelledonneCommunications/linphone-desktop#670]
**Describe the bug**

History date is one day behind.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**
1. Place a call
2. End call
3. observe that the history is one day behind

**Expected behavior**

Should see the actual date when call occurred.

**Please complete the following information**
 - Device: PC
 - OS: Fedora 36
 - Desktop 4.4.6 - Qt5.12.12
 - Core 5.1.42

**SDK logs**
Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go to About page, click on "Send logs" and copy/paste the link here.

**Adb logcat logs**
In case of a crash of the app, please also provide the stack trace of the crash using adb logcat.

**Screenshots**

**Additional context**
4.4.5 was the same.
My laptop, same problem.

**Comment by Viish** [comment]
And attach logs as asked in template please.

**Comment by robdyck** [comment]
Attaching log of a call made on Monday June 20. In the screen shot it says the call was made on Sunday June 19.

[call.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/8941590/call.txt)

![Screenshot_20220620_073035](https://user-images.githubusercontent.com/58280584/174627183-b06361c2-d071-4df2-b29a-17b4fdd7c543.png)

**Comment by robdyck** [comment]
Attached is a log of a call and a screen shot of the same call. Notice that the call was made Monday June 20 and the screen shot says it was made Sunday June 19.

[call.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/8941605/call.txt)
![Screenshot_20220620_073035](https://user-images.githubusercontent.com/58280584/174628400-1ed4d084-b662-4292-b646-f11a16278fdc.png)

**Comment by robdyck** [comment]
The browser crashed and I didn't think it suceeded on the first attempt to add attachments.

**Comment by julonexus** [comment]
Hi,
It was a bug from the creation date of events in the SDK. It has been fixed into the SDK 5.2 and then, it will be also fixed for the upcoming version of the Desktop application (Desktop 5.0).
Regards

**Comment by mooneydude** [comment]
Hi @julonexus Is this still a bug? I'm still showing a day behind on my history using desktop app for mac v5.0.3 and beta 5.1.

**Comment by ctsconsultoria** [comment]
Hi.  Is this still a bug? I'm still showing a day behind on my history using desktop app for Windows v5.0.18

**Comment by ctsconsultoria** [comment]
Hi!  Is this still a bug? I'm still showing a day behind on my history using desktop app for Windows v5.0.18
