### ISSUE TITLE
VCRUNTIME140_1.dll is missing in Windows 11 - Requires Microsoft Visual C++ Redistributable 2022

### ISSUE THREAD

**Issue by essereio** [BelledonneCommunications/linphone-desktop#683]
### Context

I use Linphone for personal use.

### General information

- Device: Desktop
- OS: Windows 11
- Version of the App: Desktop 4.4.8 - Qt5.15.2
- Version of the SDK: Core 5.1.46-1-gb853a6bad

### Expected behaviour

I opened Linphone on WIndows 11 and received an error indicating that VCRUNTIME140_1.dll is missing. I had to download and install Microsoft Visual C++ Redistributable 2015-2022 separately for Linphone to open on Windows 11.

https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

### To Reproduce

Install Linphone on Windows 11 and missing VCRUNTIME140_1.dll dialog box should show up.

**Comment by julonexus** [comment]
This is due to a cmake bug whie building the project: https://gitlab.kitware.com/cmake/cmake/-/issues/19829
The CI are using 3.14.0, it will be updated.

**Comment by julonexus** [comment]
The 4.4.9 has been rebuild.
