### ISSUE TITLE
Publish Polish translation

### ISSUE THREAD

**Issue by Debeet** [BelledonneCommunications/linphone-desktop#687]
Hello,

Could you please put Polish translation in Linphone Desktop? It seems it's 100% complete on Transifex:
https://explore.transifex.com/belledonne-communications/linphone-desktop/

**Comment by julonexus** [comment]
Hi,

We no longer use transifex for the translation process, instead we have deployed our own instance of [Weblate](https://weblate.linphone.org/).
If you want you can contribute at: https://weblate.linphone.org/projects/linphone-desktop/

Regards
