### ISSUE TITLE
Linhphone on macOS does not mark unread messages

### ISSUE THREAD

**Issue by ddobrev** [BelledonneCommunications/linphone-desktop#69]
Skype, for example, marks unread messages.

**Comment by Wescoeur** [comment]
Are you sure? In this example, you can see one unread message (grey icon) and one read message (blue icon):

![read_and_unread](https://user-images.githubusercontent.com/5610873/29606196-d7562d82-87ed-11e7-9b3d-ac94610ed512.png)

**Comment by ddobrev** [comment]
@Wescoeur I am sorry, it's my fault for not making it clear. What I mean is the red circle with a number within which appears on top of the app icon in the dock.

**Comment by ddobrev** [comment]
We have been able to discover some additional information which might help you. The red circle with a number does appear in some cases. If the user selects "HOME" or "CONTACTS" and then removes Linphone from view, for example by clicking 'x' or switching to another app, any received messages cause the red circle to appear. However, if the user has selected the very contact he's talking instead, then no circle. The circle must always appear when the app is not visible.
In addition, the circle, being red, is a little difficult to see on the orange background of the Linphone image. I understand you wouldn't change the colour of your years-old design because of this single feature but you could make the macOS image circular or oval so that the red circle is visible at the top right corner.

**Comment by Wescoeur** [comment]
Okay, I see the problem. Thanks for your report.
