### ISSUE TITLE
Unspecified session_description parser error

### ISSUE THREAD

**Issue by phatjmo** [BelledonneCommunications/linphone-desktop#7]
I'm having an issue when interacting with FreeSWITCH, where linphone core fails to parse the SDP on a reply to re-INVITE that is initiating the pause state. I already resolved one issue with line endings in FS, so the latest 1.7 unstable branch has that fix, but I'm getting this out of Linphone core:

2016-07-12 10:53:58.424 PUC[35781:17085859] 3.9.1-962-g40778ef E session_description parser error for [v=0
o=FreeSWITCH 1468325773 1468325775 IN IP4 104.197.230.189
s=FreeSWITCH
c=IN IP4 104.197.230.189
t=0 0
m=audio 11366 RTP/AVP 9 101
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=recvonly
a=rtcp:11367
m=video 11406 RTP/AVP 102
a=rtpmap:102 H264/90000
a=fmtp:102 profile-level-id=42801F;packetization-mode=1
b=AS:1024
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 ccm tmmbr
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=recvonly
a=rtcp:11407
]
2016-07-12 10:53:58.425 PUC[35781:17085859] 3.9.1-962-g40778ef E Failed to parse SDP message.
2016-07-12 10:53:58.425 PUC[35781:17085859] ****** callupdate

I've scanned through belle_sdp.g with this SDP and I can't see anything obvious, and suspect it's failing to set one of the parameters. Unfortunately, I can't tell which. I'm also attaching a PCAP with the SIP dialog that created the issue. There is a second call that comes in, and we attempt a "pause and answer". The pause state fails due to the issue parsing the SDP on the reply, and, in this case, crashes the client (VTCSecure PUC for Windows). This also impacts "pause" in general when engaged in dialogue with FreeSWITCH. This does not occur outside of FreeSWITCH, so there is some incompatible parameter that FS is sending and it would be great if someone from Belladonne can help spot the problem in the SDP so that I can address it.
[ACD-352 - StillCrashingAfterSDPFix.pcapng.zip](https://github.com/BelledonneCommunications/linphone-desktop/files/366613/ACD-352.-.StillCrashingAfterSDPFix.pcapng.zip)

**Comment by jehandelalune** [comment]
Hi,
Issue is b=AS1024
From rfc 4566:
_media-descriptions =  *( media-field
                         information-field
                         *connection-field
                         bandwidth-fields
                         key-field
                         attribute-fields )_

b field cannot be before a fields.

Does it clarify ?

Jehan

**Comment by jehandelalune** [comment]
Hi,

My bad, b field cannot be **after** a fields.

Regards

**Comment by phatjmo** [comment]
Yes, that helps, I'll follow that path and let you know.

**Comment by phatjmo** [comment]
FreeSWITCH resolved this issue in https://freeswitch.org/jira/browse/FS-9365
