### ISSUE TITLE
Can't place calls but can receive them

### ISSUE THREAD

**Issue by GuillaumeSorel** [BelledonneCommunications/linphone-desktop#702]
### Context

I use Linphone Desktop on MacOS 12.6
I can't place calls anywhere when it was previously working but I can receive them. 
I've checked the settings of the account but as long as I can receive calls I'm supposed to be able to place them.

### General information

- Device: Mac Mini 2018
- OS: iOS 12.6
- Version of the App: Linphone Desktop 4.4.10 - Qt5.15.2 
- Version of the SDK: Core 5.1.62

### Expected behaviour

I can't place calls any more when it was previously working but I can receive them. 

### To Reproduce

Try to place a call and nothing happens.
Trying to receive a phone call and it works.

**Comment by julonexus** [comment]
Hi
I'm sorry but there is nothing to do without any logs.
Regards

**Comment by allinappli** [comment]
How can you close? It's a bug!

**Comment by julonexus** [comment]
I closed it because the OP didn"t respect the "Get Started"
