### ISSUE TITLE
Enable Logs but Keep them Locally (no uploads to Linphone's servers)

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-desktop#708]
Desktop 4.4.10 - Qt5.12.12
Core 5.1.61-1-g5cc4f4675

I have logs enabled and I can see that Linphone Desktop connects to:
```
message sent to [TLS://lime.linphone.org:443], size: [3969] bytes
```
It looks like as soon as one enables logs, it also uploads them to the address configured by default (`https://www.linphone.org:444/lft.php`).

Can one enable logs and NOT upload them automatically but keep them only locally?

**Comment by julonexus** [comment]
"NOT upload them automatically "
No, it doesn't. Uploading logs are only done when clsiking on the Send button.
