### ISSUE TITLE
Pressing 'x' in Linphone for macOS minimises rather than closes the main window

### ISSUE THREAD

**Issue by ddobrev** [BelledonneCommunications/linphone-desktop#71]
The standard behaviour when 'x' is pressed in a macOS app is that all windows of the app entirely disappear but the app remains alive and can be restored to view by pressing it in the dock. Linphone minimises the app instead (sends it to the bottom area right of the dock).

**Comment by julonexus** [comment]
Done for the next nightlies (> alpha 312)
