### ISSUE TITLE
Use Port 5061 for TLS

### ISSUE THREAD

**Issue by stef204** [BelledonneCommunications/linphone-desktop#712]
My SIP Provider tells me, that, in order to use `SIP/TLS`, the account needs to be configured by adding `:5061` to the end of the user name. (using the `Account Assistant` for example.)

````
Configuring your Linphone with Encryption
In the SIP Domain field, append port 5061 to the end of the server address (i.e.: sip.someprovider.com:5061)
````

This is how the user name looks:

`"JOE ABCD" <sip:user12345@sip.tsomeprovider.com:5061>`

Does that make sense, i.e. is it necessary even if one chooses `TLS` as the transport protocol?

Using `linphone-desktop-appimage-4.4.11`.

**Comment by Viish** [comment]
Hi @stef204,

First of all, please open issues for desktop in this repository and not in linphone-android...

Regarding the port, for 5061 you don't have to specify it if you use TLS transport protocol as it is the default one.
If you really want to specify it, don't put it in the domain field but in the SIP server address & route fields, for example: `<sip:sip.linphone.org:5061;transport=tls>`
