### ISSUE TITLE
[Bug]: Activate only specific sip account

### ISSUE THREAD

**Issue by edimondi** [BelledonneCommunications/linphone-desktop#726]
### Context

i have my own asterisk server

### General information

- Device: micorosft
- OS: windows 11
- Version of the App:
- Version of the SDK:

### Expected behaviour

i have multiple sip account but i only want to activate only one account 

### To Reproduce

click and acticate speciifc account

**Comment by julonexus** [comment]
Don't register it in account settings.

**Comment by vmrfriz** [comment]
I have 4 users working shifts at different computers. It is inconvenient to delete/add accounts every day and will certainly cause problems for inexperienced users. Is there another solution to use only one account out of all the added ones?
