### ISSUE TITLE
Can't enable H264 codec on linphone.AppImage

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/linphone-desktop#729]
https://i.imgur.com/GOOqZ2e.png

Reproduce:
1.open linphone.AppImage
2. Go to Settings, video tab
3. Turn H264 status on and confirm downloading from Cisco.
4.  H264 status still off.

Archlinux 6.0.15-1-MANJARO
linphone.AppImage Desktop 4.4.6 - Qt5.12.12
Core 5.1.42

Logs:(./linphone.AppImage --appimage-extract ; cd squashfs-root ; ./AppRun)
[23:22:12:823][0xe922b0][Info]"Download of http://ciscobinary.openh264.org/libopenh264-2.1.0-linux64.5.so.bz2 finished to /home/user/.local/share/linphone/codecs/libopenh264-2.1.0-linux64.5.so.bz2"
[23:22:13:554][0xe922b0][Info]"Loading `libopenh264.so` symbols..."

cd ~/.local/share/linphone/codecs
ls -a
  ..  H264.txt  libopenh264.so

**Comment by basncy** [comment]
BTW, openh264 can be installed into /usr/lib folder, is it possible of loading from the system library? 


ls /usr/lib/libopenh264.s* -a
/usr/lib/libopenh264.so  /usr/lib/libopenh264.so.2.3.1  /usr/lib/libopenh264.so.7

**Comment by basncy** [comment]
Auto fixed with Linphone-5.0.4.AppImage which download openh264 2.2.0 version.
and this openh264 version works with 4.4.6 too.

logs:
[0x2cdaee0][Info]"Download of http://ciscobinary.openh264.org/libopenh264-2.2.0-linux64.6.so.bz2 finished to /home/user/.local/share/linphone/codecs/libopenh264-2.2.0-linux64.6.so.bz2"
[0x2cdaee0][Info]"Loading `libopenh264.so` symbols..."

**Comment by basncy** [comment]
To prevent libopenh264.so downgrade by old stable linphone-desktop version:
sudo chattr +i ~/.local/share/linphone/codecs/libopenh264.so

**Comment by julien-celya** [comment]
Hi.

I'm reproducing the same issue with [version 5.2.6](https://download.linphone.org/releases/linux/app/Linphone-5.2.6.AppImage)

I fixed it by replacing ~/.local/share/linphone/codecs/libopenh264.so with http://ciscobinary.openh264.org/libopenh264-2.2.0-linux64.6.so.bz2

**Comment by Ledjlale** [comment]
Thanks for your report. I confirm that a bug has been introdduced into 5.2.6 for Linux where it download the wrong version (2.4.1). It will be fixed for 5.2.7.
Regards

**Comment by rdiez** [comment]
It has been over 6 months from the last message confirming the bug in the current Linux release.

I would release a fixed version sooner rather than later, now that many people like me are looking for an alternative to Skype, which will be discontinued soon. Such a silly error doesn't give a good impression to newcomers.
