### ISSUE TITLE
[Bug]: Invalid SSL certificate for download.linphone.org

### ISSUE THREAD

**Issue by pschichtel** [BelledonneCommunications/linphone-desktop#742]
### Context

I'm trying to download the appimage built of linphone desktop from https://download.linphone.org, but it fails due to an invalid certificate:

![image](https://user-images.githubusercontent.com/526104/217495463-5267ddac-6a38-4141-8d1d-f5ba8893bdb4.png)

The certificate seems to be missing the appropriate subject alternative name.

### General information

Irrelevant

### Expected behaviour

TLS certificate is valid.

### To Reproduce

Go to https://download.linphone.org with any browser or HTTP client with certificate validation.

**Comment by julonexus** [comment]
Hi,
download.linphone.org was not available the previous week. It should be ok now
