### ISSUE TITLE
[Bug]: cannot add or edit contacts

### ISSUE THREAD

**Issue by rkoe** [BelledonneCommunications/linphone-desktop#746]
### Context

Contacts cannot be added and most contact-fields cannot be edited:

- add: After clicking on the "add contact" button, I can only edit the name and "ADDRESS" field of a contact; the "SIP ACCOUNT(S)", "COMPANIES", "E-MAIL(S)", "WEBSEITE(S)" field cannot be selected; instead a warning is shown on the console:
  ```[Warning]qrc:/ui/modules/Common/Form/ListForm.js:70: TypeError: Value is undefined and could not be converted to an object```.
  The "SAVE"-button is also disabled (probably because "SIP ACCOUNT(S)" is empty and cannot be edited.

- edit: A similar problem exits when trying to edit a contact: "COMPANIES", "E-MAIL(S)", "WEBSEITE(S)" cannot be selected/edited and the same message as above occurs.

### General information

- Device: PC
- OS: Linux (NixOS 22.11)
- Version of the App: Desktop 4.4.10 - Qt5.15.7
- Version of the SDK: Core 5.1.0

### Expected behaviour

When adding/editing a contact, all fields should be editable.

### To Reproduce

1. Click on "ADD CONTACT"
2. Try to enter a sip account.

**Comment by julonexus** [comment]
4.4 is no more supported.
