### ISSUE TITLE
Document if instant messages are encrypted

### ISSUE THREAD

**Issue by ddobrev** [BelledonneCommunications/linphone-desktop#75]
http://www.linphone.org/technical-corner/linphone/features does not specifically clarify if instant messages are encrypted as well or only audio and video are.

**Comment by ddobrev** [comment]
Could you please just clarify if instant messages are encrypted? This is really important to us and we might be forced to forgo Linphone if it doesn't encrypt text.

**Comment by Viish** [comment]
Hi,
As you can see on our wiki we do have a way to encrypt instant messages: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/LIME/
Cheers,

**Comment by ddobrev** [comment]
@Viish thank you very much for your reply. I am afraid, however, that I am unable to fully understand it. What do you mean by "we do have a way"? Is this encryption a feature of Linphone or Liblinphone? Is it turned on by default in Linphone? If not, can it be set?
