### ISSUE TITLE
Format link  tel:+XXXXXXX not working

### ISSUE THREAD

**Issue by evol87** [BelledonneCommunications/linphone-desktop#753]
### Context

When you click on a link in the format tel:**+**31XXXXXXX nothing happens from the browser.  When manually typing in the program, through + everything is fine. No problem with links of body formats tel:XXXXX

### General information

- OS Windows 11
-  Desktop 5.0.14 - Qt5.15.2

### Expected behaviour

When you click on the link tel:+XXXXX
call will be made

### To Reproduce

1. Go to browser and open link tel:+3100000000000

**Comment by hansbaas** [comment]
I have this same problem, on the Windows client, in all versions I've worked in. As a workaround you can substitute + by 00. So for this dutch number, instead of dialing +31... you dial 0031...

**Comment by julonexus** [comment]
Hi
You can add the domain and you will get what you want

**Comment by evol87** [comment]
example https://nicelocal.com/new-york-city/medical/queens_medical_wellness_center_qiao_guo_md_minyi_tan_md/
![image](https://user-images.githubusercontent.com/62426911/227647265-a4f65f98-fd6f-4335-853e-769cc15feefc.png)
when you click on the phone, the linphone opens and that's it
![image](https://user-images.githubusercontent.com/62426911/227647482-d1398c33-5946-49e5-b08f-855a9da3cb8c.png)
if you remove the "+" then the program opens and the call goes

**Comment by julonexus** [comment]
It should be fixed for next releases (5.0.15/master)
