### ISSUE TITLE
[Bug]: No lost call reminder in newer versions of linphone

### ISSUE THREAD

**Issue by javierckr** [BelledonneCommunications/linphone-desktop#757]
### Context

I use linphone desktop with sip.linphone.org and with another sip service (Asterisk)

### General information

- OS: Ubuntu
- Version of the App: Above 5.0

### Expected behaviour

When you miss a call, after version 5.0 you don't have any notification of the lost call.

### To Reproduce

Open linphone, receive a call and don't take it.

**Comment by julonexus** [comment]
Nothing to do without logs.
