### ISSUE TITLE
Linux flatpak no audio device available

### ISSUE THREAD

**Issue by broken-trigger** [BelledonneCommunications/linphone-desktop#76]
- debian Stretch amd64
- installed via flatpak
- playback device, capture device and ringer device are empty
- aplay -l, cat /proc/asound/devices no problems e.g. jitsi and twinkle are running fine
- sip accounts, calling in and out and so on are working fine but without sound :)

**Comment by broken-trigger** [comment]
trying to compile from git repository ends with

`CMake Error at CMakeLists.txt:321 (message):
  Could not find a support sound driver API.  Use -DENABLE_SOUND=NO if you
  don't care about having sound.`

https://github.com/BelledonneCommunications/mediastreamer2/blob/master/CMakeLists.txt 320-322

Solution from [https://askubuntu.com/questions/770298/how-can-a-current-version-of-linphone-be-installed/874044](url) -> libasound2-dev no help :)

Maybe -DENABLE_SOUND=NO has been used for flatpak build =)?

**Comment by mlichvar** [comment]
It seems the mediastreamer library included in the flatpak was compiled without alsa support. It supports pulseaudio only.

**Comment by Wescoeur** [comment]
The linphone flatpak version supports only PulseAudio. :) You cannot use it with alsa, sorry.
