### ISSUE TITLE
Linphone replaces first 00 digits of a number with "+"

### ISSUE THREAD

**Issue by ricardofunke** [BelledonneCommunications/linphone-desktop#77]
Linphone Desktop for Linux (3.11.1-2 arch linux) suffers from the same issue discovered in Linphone iPhone:

https://github.com/BelledonneCommunications/linphone-iphone/issues/191

**Comment by Wescoeur** [comment]
The Linphone (3.x) version is no longer supported now. Please check with the last 4.1 version if you have really a problem.
