### ISSUE TITLE
[Bug]: Linphone on Windows crashes on incoming call when the configured audio device is no longer available

### ISSUE THREAD

**Issue by ColinFinck** [BelledonneCommunications/linphone-desktop#778]
### Context

I use Linphone on Windows on a laptop and with a pair of USB headphones. The USB headphones appear as WASAPI input and output devices.
Depending on my location, I sometimes need to switch to another pair of USB headphones. Windows auto-detects them and always configures the current USB headphones as the new WASAPI default device.
However, I can't configure Linphone to use the WASAPI default device. Instead, I always need to select the current pair of USB headphones. If I change the headphones and get a call, Linphone crashes. The Linphone log confirms this:

```
[/liblinphone] MESSAGE Starting local ringtone...
[/bctbx] ERROR mswasapi: Could not activate the rendering device
```

These lines are obviously related to https://gitlab.linphone.org/BC/public/mswasapi/-/commit/2bf105ef544f8f132e85e647c4bdef141f5c5659, which hasn't landed in a Linphone release yet.
However, the application also crashes when I disable logging.

### General information

- OS: Windows 10
- Version of the App: 5.0.18

### Expected behaviour

Linphone should automatically switch to the new default audio device when it notices that the previously selected audio device is no longer available.
Alternatively, it would also be sufficient for me if I could configure Linphone to use the "Default" device for audio input and output. But currently, I always have to select the current headphones, and Linphone obviously can't find them anymore when I switch headphones.

### To Reproduce

1. Set up Linphone on Windows and select USB headphones as the input and output device.
2. Unplug the USB headphones.
3. Receive a call --> Crash

**Comment by julonexus** [comment]
Hi
Default device from Windows will be available on Linphone Desktop 5.2.
It is a new feature so it will no be available on SDK 5.2.
Regards
