### ISSUE TITLE
Add a Linux desktop target

### ISSUE THREAD

**Issue by probonopd** [BelledonneCommunications/linphone-desktop#78]
`./prepare.py --package` for Linux could generate an [AppImage](http://appimage.org/) which would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

[`linuxdeployqt`](https://github.com/probonopd/linuxdeployqt) is a tool specifically made to make packaging Qt-based (and other) applications as an AppImage easy.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment]
Another way would be to simply repackage https://www.linphone.org/snapshots/debian/wheezy/ as an AppImage.

**Comment by vphantom** [comment]
An AppImage would definitely be a _lot_ simpler than relying on users installing the FlatPak daemon. I ended up sticking with Debian's old Linphone 3.6 despite its UI shortcomings (forgets window position/size, no contact grouping) because of this dependency with 4.x.

**Comment by probonopd** [comment]
Seems it has happened :+1: 
https://www.linphone.org/technical-corner/linphone
