### ISSUE TITLE
Feature request: Option to disable Message Composition Indication (RFC 3994)

### ISSUE THREAD

**Issue by sysfu** [BelledonneCommunications/linphone-desktop#785]
While troubleshooting a problem sending outbound SIP text messages via Linphone 5.1.2 and the voip.ms service I discovered the cause. Linphone is sending XML 'isComposing' typing indicator SIP messages which are triggering SIP/2.0 415 Unsupported Media Type error messages from voip.ms servers. This causes any subsequently typed text messages to fail.

I discovered this while trying to get Zoiper 5 Pro working with the service. Zoiper software has an option to disable typing notifications on a per SIP account basis. Once I did that, and the typing indicator SIP messages stopped being sent, that resolved the issue for me. I was finally able to both send and receive text messages with the Zoiper 5 Pro app for my voip.ms SMS-enabled DID.

It would be great if Linphone could also be configured to work the same way. I think this can be accomplished by disabling the typing indicator messages.

Please consider adding this feature, allowing end users to disable [Message Composition Indication (RFC 3994)](https://www.pjsip.org/pjsip/docs/html/group__PJSIP__ISCOMPOSING.htm)

Also of note: there was an [inquiry about disabling typing indicators](https://www.mail-archive.com/linphone-users@nongnu.org/msg06725.html) on the linphone-users mailing list from 2015 that went unanswered. Apparently it was causing this persons contacts to receive confusing and unwanted messages on their end of the conversation.

**Comment by julonexus** [comment]
in linphonerc file:
[sip]
im_notif_policy=0

**Comment by sysfu** [comment]
> in linphonerc file: [sip] im_notif_policy=none
> 
> This will deactivate compose/imdn events.

Thank you for the config file setting.

Can you please re-open this issue with the clarification that this is a request to add a GUI toggle switch under Preferences => SIP accounts => Account Settings?
