### ISSUE TITLE
Linphone 4.1.1 compilation error debian

### ISSUE THREAD

**Issue by perparim-m** [BelledonneCommunications/linphone-desktop#79]
Hi,

I'm having trouble while compiling the linphone on Debian Strech. I appreciate if anyone can give me any advice :)

root@debian:~$ uname -a
Linux udoo 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

root@debian:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch
velferd@udoo:~$

-- Configuring incomplete, errors occurred!
See also "/home/velferd/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeOutput.log".
See also "/home/velferd/linphone-desktop/WORK/desktop/Build/ms2/CMakeFiles/CMakeError.log".
CMakeFiles/EP_ms2.dir/build.make:120: recipe for target '/home/velferd/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure' failed
make[3]: *** [/home/velferd/linphone-desktop/WORK/desktop/Stamp/EP_ms2/EP_ms2-configure] Error 1
make[3]: Leaving directory '/home/velferd/linphone-desktop/WORK/desktop/cmake'
CMakeFiles/Makefile2:380: recipe for target 'CMakeFiles/EP_ms2.dir/all' failed
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[2]: Leaving directory '/home/velferd/linphone-desktop/WORK/desktop/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/velferd/linphone-desktop/WORK/desktop/cmake'
Makefile:14: recipe for target 'desktop-build' failed
make: *** [desktop-build] Error 2
velferd@udoo:~/linphone-desktop$ 

[CMakeError1.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/1260101/CMakeError1.txt)
[CMakeOutput1.txt](https://github.com/BelledonneCommunications/linphone-desktop/files/1260102/CMakeOutput1.txt)

Regards,
Perparim

**Comment by markd89** [comment]
Did you get your issue resolved?

I am also trying on Stretch but think I am missing dependencies. If yours is working, I'm curious on what you installed to get a successful build.

Thanks,
Mark

**Comment by Wescoeur** [comment]
It's necessary to have a recent version of Qt (5.9 minimum) to build (see README.md).
