### ISSUE TITLE
[Bug]: Linphone native and appimage refuse to work with tel links on linux

### ISSUE THREAD

**Issue by Haui1112** [BelledonneCommunications/linphone-desktop#790]
### Context

I use the newest appimage (after using the apt install version) and both dont open tel links. Ubuntu 23.04 asks me what application to use, I select linphone (now the appimage) and nothing happens. I would like the link to just call the person I selected.

The link syntax is `tel:12345-45` for example.

### General information

- Device: Desktop PC
- OS: Ubuntu 23.04
- Version of the App: Desktop 5.1.2 - Qt5.15.2 - Core 5.2.97
- Version of the SDK:

### Expected behaviour

I would like the app to just start calling when I click the tel: link (and select the correct app for handling the link). Instead, it does nothing.

### To Reproduce

1. Open any html document
2. Put in an href link "tel:123456"
3. Click on it
4. (Optional:) Select linphone as handler for the link
5. See nothing happen

### SDK logs URL

https://www.linphone.org:444//tmp/652e4c2e278cf_f140ab8dd3887887ed6a.gz

**Comment by vKnmnn** [comment]
the syntax ist `tel://sipnumber`
to immediately call a number do this: `tel://+1234567?method=call`

you can also use sip:// instead of tel://

query the distros defaults with this:

```
xdg-mime query default tel://
xdg-settings get default-url-scheme-handler tel
xdg-settings get default-url-scheme-handler sip
xdg-mime query default sip://
```

to set this to linphone per default, do this:

```
# linphone-desktop must be the application name in the corresponding .desktop-file
xdg-settings set default-url-scheme-handler linphone-desktop
```

**Comment by julonexus** [comment]
Thanks for reporting. I think it has been fixed and will be available for 5.2.1.
Related to #809

**Comment by gilgongo** [comment]
I'm running Linphone-5.2.1.AppImage on Ubuntu 23.10 (symlinked to `/usr/local/bin/linphone`) with the following in `/usr/share/applications/linphone.desktop`:

```
[Desktop Entry]
Name=Linphone
Comment=A libre SIP client
Terminal=false
Exec=/usr/local/bin/linphone --iconified %F
Type=Application
Icon=/home/gilgongo/.customicons/linphone.svg
Categories=Network;Telephony;
MimeType=x-scheme-handler/sip-linphone;x-scheme-handler/sip;x-scheme-handler/sips-linphone;x-scheme-handler/sips;x-scheme-handler/tel;x-scheme-handler/callto;
X-KDE-Protocols=tel;callto;
StartupNotify=true
```
I've run:

`xdg-mime default linphone.desktop "x-scheme-handler/tel"`

But when I click on a `tel:` link, the applicaiton starts but does not dial.

**Comment by vKnmnn** [comment]
@gilgongo does your tel: - link have the method parameter attached? See my first comment.

**Comment by gilgongo** [comment]
> does your tel: - link have the method parameter attached? See my first comment.

Not in the HTML - that's just `<a href="tel:0345 xxx xxx">Call Now</a>` But that's a third party site so not something I can control.

**Comment by lipunis** [comment]
There is someone here who can help me. Thanks a lot. I've tried everything that's written here. The result is zero. I use Plasma 5.7.11, Kubuntu 24.04 does not work, although on KDE NEON 6.04 it worked immediately as Linphone indicated in the settings.

**Comment by lipunis** [comment]
/roman@roman-virtual-kubuntu:~$ xdg-mime default gearlever_linphone_c73484.desktop x-scheme-handler/tel
roman@roman-virtual-kubuntu:~$ xdg-mime query default tel://
roman@roman-virtual-kubuntu:~$

**Comment by Haui1112** [comment]
Hi folks, sorry for the late reply and thanks for your replies. I followed the steps and it didnt work. I checked journalctl (debian) and it showed the following:

```
Jul 26 10:05:59 TowerPC plasmashell[9682]: dlopen(): error loading libfuse.so.2
Jul 26 10:05:59 TowerPC plasmashell[9682]: AppImages require FUSE to run.
Jul 26 10:05:59 TowerPC plasmashell[9682]: You might still be able to extract the contents of this AppImage
Jul 26 10:05:59 TowerPC plasmashell[9682]: if you run it with the --appimage-extract option.
Jul 26 10:05:59 TowerPC plasmashell[9682]: See https://github.com/AppImage/AppImageKit/wiki/FUSE
Jul 26 10:05:59 TowerPC plasmashell[9682]: for more information
```

From what I read online this has to do with firefox running inside a flatpak and linphone being an appimage. Flatpak isnt allowed to use FUSE because it could break the sandbox which would be a security problem.

Any ideas how to solve this? I assume this is very relevant since flatpak is very common these days and linphone aims at a (semi?) professional market which will absolutely run flatpaks here and there for simplicity.
