### ISSUE TITLE
[Bug]: Unable to dial a phone number

### ISSUE THREAD

**Issue by nicolas-75** [BelledonneCommunications/linphone-desktop#791]
### Context

I've just installed Linphone on my computer and set up a SIP account. I can receive and make calls to a landline, but only by double-clicking on the call history.

### General information

- Device: ASUS ZenBook 13 UX331UAL
- OS: Manjaro
- Version of the App: 5.1.2
- Version of the SDK: I don't know where to find the information

### Expected behaviour

I wanted to do a simple call with the Linux client calling a landline. Unfortunately, I can’t dial at all a new number. When I enter the desired number in the “find a contact, call or send a message” bar, only the “Add this contact” action appears. Impossible to call it! When I press Enter the seach disappear. Even if I add the code +33 before the number, it’s impossible to call.

Doesn't the application allow you to call landlines other than through the call history?

### To Reproduce

1. Click on the  “find a contact, call or send a message” bar
2. Enter a phone number
3. Press Enter
4. Note that the number has disappeared and nothing is happening

**Comment by tsifert** [comment]
I am having the exact same issue with the Windows desktop client. Latest version (just installed today).

**Comment by MarkDreyband** [comment]
I have the same issue. Can someone confirm if this is a bug, or known limitation of product? I beleive this behavior should be changed

**Comment by MarkDreyband** [comment]
Please let us know if this accepted as bug, or  this is expected behavior (aka "known feature"). I'd like to implement Linphone as main SIP client instead of MicroSIP.
MicroSIP can just make a call to phone number, you don't have to add SIP server suffix.

Thank you in advance!

**Comment by MarkDreyband** [comment]
@julonexus Thank you for your response, it was very helpful!
I've found an old feature request ( [stop automatically creating default identity and modify how default and proxy addresses are handled](https://github.com/BelledonneCommunications/linphone-desktop/issues/376) ), and once I've modified config file with **show_local_sip_account=0** it fixed my request. On the other hand my colleague told that this key works inconsistently, but I haven't verified yet.

**Comment by DodgeDeBoulet** [comment]
Direct dialing a phone number from the "search contact" field or keypad worked before, but it's not working now. I fail to see how this is not a bug? I could paste any valid number into the search field or punch it in on the keypad and Linphone would dial it through my default VoIP provider. It has stopped doing that with the most recent versions.

**Comment by nicolas-75** [comment]
I install the 4.4.10 version and now I can call a phone number with the the bar “find a contact, call or send a message”. Thanks for the tip!

Maybe someone could explain how to do the same thing with the last version, because I don't understand what to do :'(
