### ISSUE TITLE
Feature-Request: Set path of file "friends.db" for shared usage (dual-boot)

### ISSUE THREAD

**Issue by Symbiont123** [BelledonneCommunications/linphone-desktop#796]
Hello Devs,
I'm missing a GUI option to set the path of file "friends.db". This would be very helpful when switching OS in a dual-boot system (e.g. Linux & Windows). Otherwise I need to implement a script with conditional file copy at system start.
Cheers
Symbiont123

**Comment by Ledjlale** [comment]
friends.db is deprecated and doesn't exist anymore
