### ISSUE TITLE
Can we have an option to remove + and 00 on prefix?

### ISSUE THREAD

**Issue by UnNew90** [BelledonneCommunications/linphone-desktop#799]
Hi Dev team and all.

As per title above, can you make it on next update? 

Because my provider already configured to make call, just press 9 and following by number for both local and international call.

These doesn't not require to enter 00 or + before or after 9.

![SCR-20231215-jvky](https://github.com/BelledonneCommunications/linphone-desktop/assets/38325821/1d993fbb-0477-4d4a-a9a2-fa60609d0b36)
![SCR-20231215-jvhr](https://github.com/BelledonneCommunications/linphone-desktop/assets/38325821/9a2f0653-2e18-462a-9e0c-20c97289d28a)

Thanks.

**Comment by julonexus** [comment]
Hi,
The option couldn't be change from the Ui. This will be fixed for 5.2.5.
Meanwhile, you have to deactivate it in your linphonerc in your proxy configuration with:
[proxy_n] (where n is the number of your accounts)
use_dial_prefix_for_calls_and_chats=0

Regards
