### ISSUE TITLE
[Bug]: tel: link not working

### ISSUE THREAD

**Issue by P0zitiff4ik** [BelledonneCommunications/linphone-desktop#809]
### Context

The same problem as [#753](https://github.com/BelledonneCommunications/linphone-desktop/issues/753), but now it isn't work with all formats.
When you click on a link in the format tel:**+**31XXXXXXX nothing happens from the browser. When manually typing in the program, through + everything is fine. Same problem with links of body formats tel:XXXXX

### General information

- Device: PC
- OS: Windows 11
- Version of the App: Desktop 5.2.0 - Qt5.15.2
- Version of the SDK :Core 5.3.1

### Expected behaviour

When you click on the link tel:+XXXXX call will be made

### To Reproduce

1. Go to browser and open link tel:+3100000000000
OR
Open the [link](https://nicelocal.com/new-york-city/medical/queens_medical_wellness_center_qiao_guo_md_minyi_tan_md/) and click on the phone
2. When you click on the phone, the linphone opens and that's it.

### SDK logs URL

https://www.linphone.org:444//tmp/65a6919ca0a19_62b49cfda728f9500f18.gz

**Comment by julonexus** [comment]
Thanks for reporting. It has been fixed and will be available for 5.2.1.
