### ISSUE TITLE
[Bug]: Version text is editable in "About" Text Box  

### ISSUE THREAD

**Issue by xenotropic** [BelledonneCommunications/linphone-desktop#817]
### Context

If one chooses "About", then selects the version text and starts typing, it is editable. Not *the* highest priority bug, but clearly a bug. 

![image](https://github.com/BelledonneCommunications/linphone-desktop/assets/4050617/f4a31371-bb0f-48db-8998-d6dda9d2e8e1)

### General information

- Device: Lenovo Thinkpad Carbon X1 v3
- OS: Ubuntu 23.10
- Version of the App:  Desktop 5.2.0 - Qt5.15.10 Core 5.3.1
- Version of the SDK:

### Expected behaviour

Should not be an editable text box

### To Reproduce

Click app indicator
Click "About"
Click on version text
Start typing

**Comment by JonathanBartet** [comment]
Hi @xenotropic,

Thank you for this bug report.
We will fix it ! 

Regards,
