### ISSUE TITLE
Linphone for macOS Renaming the app 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-desktop#83]
how would I go about renaming the app, I looked in info.plist and cmakelists.txt to change the name of the packaged file to HappyPhone but it keeps breaking. How can I change this?
Info.plist.in
        <key>CFBundleName</key>
	<string>Happy Phone</string>
	<key>CFBundleDisplayName</key>
	<string>Happy Phone</string>
	<key>CFBundleExecutable</key>
	<string>happyphone</string>
CMakeLists.txt
set(CPACK_PACKAGE_NAME "Happy Phone")
set(CPACK_PACKAGE_VENDOR "Belledonne communications")
set(CPACK_PACKAGE_VERSION_MAJOR ${LINPHONE_MAJOR_VERSION})
set(CPACK_PACKAGE_VERSION_MINOR ${LINPHONE_MINOR_VERSION})
if(LINPHONE_MICRO_VERSION)
	set(CPACK_PACKAGE_VERSION_PATCH ${LINPHONE_MICRO_VERSION})
endif()
set(CPACK_PACKAGE_EXECUTABLES "happyphone;Happy Phone")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Linphone")
set(CPACK_RESOURCE_FILE_LICENSE "${LINPHONE_SOURCE_DIR}/COPYING")

**Comment by Wescoeur** [comment]
I have no easy procedure to do this:
- You can rename `APPLICATION_NAME` in `src/app/AppController.cpp`
- It's necessary to change some things in many cmake files in project dir and cmake_builder (executable name, ...)
- ...
