### ISSUE TITLE
How to call a number without adding to contacts

### ISSUE THREAD

**Issue by ITMaximago** [BelledonneCommunications/linphone-desktop#838]
Hi, I'm pretty sure this is a Layer 8 problem, but I'm not able to call a phone number. 

What I use:
Operating system: Win 11 23H2
Linphone version: Desktop 5.2.4 - Qt5.15.2 Core 5.3.41

I installed Linphone using the .exe from the supposedly official site (https://www.linphone.org/technical-corner/linphone)

I can answer calls, but it is not possible to simply call a number. As far as I understand it, you enter the desired number in the search bar at the top and confirm with Enter? I only get the dropdown to create a new contact. 

I don't think there are any helpful log files, unless you are actually supposed to start the call with enter.
I hope I have provided all the necessary information.

I'm pretty sure I'm the problem, can anyone enlighten me? 

![example](https://github.com/BelledonneCommunications/linphone-desktop/assets/152481253/da55f525-35ec-49be-9e26-c94551802b1f)

**Comment by grummbeer** [comment]
> As far as I understand it, you enter the desired number in the search bar at the top and confirm with Enter? 

I think you understand it right. I am sure, this behaviour is new. 

I use the Linux AppImage, currently 5.2.4. Tried to run versions 5.2.3, 5.2.2, 5.2.1 but they behave the same. Strange … I'm sure it worked not too long ago.

This also means that the "tel:+49..." links (at least for unknown phone numbers) do not work properly anymore.

**Comment by julonexus** [comment]
Your are not using a configured account, else you would have a domain completion in the search

**Comment by grummbeer** [comment]
Hi, thanks for you answer. What do you mean with "a configured account"? Is something broken in my local settings?

**Comment by julonexus** [comment]
In fact, I answered to the OP ;)
I don't know what your settings are, but if you get nothing else that what you entered in your search bar (and at some point, if you get the disabled icons to the top right), then you are more like using the default account and not the a configured one.

The default account have an IP in its address and is not usable.
Configured Account ==  Created from Assistant, directly in the account settings or in [proxy_n] into linphonerc

**Comment by grummbeer** [comment]
> In fact, I answered to the OP ;)

:-) Anyway, thanks for the explanation.

**Comment by ITMaximago** [comment]
I have not actually adjusted the settings, i.e. left them as default. 
I used the wizard to use a “SIP account”. Our provider (Sipgate) offers a documentation for linphone, which we followed. 
I can provide this if required.

If I would use a linphone account I can understand that, but with a SIP account?

**Comment by julonexus** [comment]
It is not needed.
If you have a configured account, I think that you didn't select the correct account at the top left of the application.

**Comment by ITMaximago** [comment]
Yes, that was the problem.
Thanks for the advice!

Like I said, layer 8 problem. xD
Sorry for wasting your time.

**Comment by grummbeer** [comment]
@julonexus Forgotten to say: Thank you for this nice software!

Im my case, i was wondering why the default account was selected. But I also wondered why my call list does not show all entries (depends on the account, i know).

I figured out, that there were different addresses in `sip_address` for the same (main) account. After changing all different `conference_call.from_sip_address_id` and `conference_call.to_sip_address_id` to only one `sip_address.id`, it looks much better now. Especially the call list looks now complete. Thank you for the nudge and have a nice day.

**Comment by samuk10** [comment]
Hi I use sip, but I want to call `*8` this is to push a call from a group and `*2` to forward a call.
is it possible?
I also tried: "`tel:*8`" doesnt work
