### ISSUE TITLE
No UI option to enable presence for contacts

### ISSUE THREAD

**Issue by anatoli26** [BelledonneCommunications/linphone-desktop#84]
In Linphone 3 there was an option to subscribe to presence notifications for each contact. In Linphone 4 there's no such option in the UI, though the functionality is there. I can activate it by removing the linphone.org entries in the linphonerc file and changing the sqlite contacts DB to enable subscribe, but this is clearly not the adequate way of enabling presence for a contact.

**Comment by Wescoeur** [comment]
The presence system of Linphone 4 is not the same. A presence server is used now.
It works if you add a contact in the interface and if your contact add you in his app.

**Comment by anatoli26** [comment]
What do you mean by "presence server"? AFAIC the standard SIP presence is managed via SIP SIMPLE with core RFCs 6665 (SUBSCRIBE and NOTIFY), 3856 (defines how to make use of SUBSCRIBE/NOTIFY for presence) and 3903 (PUBLISH). Then there are several more for the presence body coding.

Do you mean that Linphone4 no longer supports SIP SIMPLE and the presence is managed by linphone.org hosted service?

**Comment by Wescoeur** [comment]
See: https://tools.ietf.org/html/rfc4662 (`Resource List Server`)
It exists a lot of manners to deal with presence. With this choice the network traffic is optimized.
I mean: Linphone 4 uses by default `linphone.org` and it can be use with other `RLS URI`. The linphone lib supports basic presence, not the application.

**Comment by anatoli26** [comment]
Thanks, I see it now. But the old functionality (SIP SIMPLE) is still there and it can be activated manually (by disabling the resource list server in the rc file and enabling in the DB for each contact the subscribe option). Why not to leave it more accessible? If not in the UI, at least in the rc file (something like sip_simple=on/off).

The problem is that FreeSWITCH doesn't support RFC 4662 at this time so this change breaks presence at all FS deployments with L4.

**Comment by Betriebsrat** [comment]
i seem to run into the same problem... while 3.6.1 works flawlessly with presence i can't manage to get it to work with 4.1.1. Is there a simple way to activate the old behaivor here?

**Comment by LucasfoliveiraSe** [comment]
I am expericing same problem. My team developed a solution integrating linphone and asterisk directly . I couldn´s make the contact presence in linphone to work out with asteriks, , it worked with microsip. Does anybody could help me out where i am missing? I have tried already to change directly in the friends.db the send_subscribe from 0 to 1 , and i disabled rls as well in the ui of linphone. I would apretiated any kind of help.

**Comment by anonymous-explorer** [comment]
I am experiencing exactly the same issue with asterisk 18 as LucasfoliveiraSe. Since version 13 Asterisk supports RLS in its pjsip channel, though I haven't tested it yet.

**Comment by PBXForums** [comment]
Does anyone know how to restore the old behaviour? I too am using Freeswitch and would like to use Linphone but need the old simple SUBSCRIBE/NOTIFY

**Comment by johan-smits** [comment]
@Wescoeur where can you find information on how to change this RLS server? Because asterisk has support for it https://wiki.asterisk.org/wiki/pages/viewpage.action?pageId=30278158 but there are some missing document parts on how to make this work.

@PBXForums Disable RLS auto and edit your friends.db (.local/share/linphone/friends.db) to set the presence option to 1 for each contact makes it work.
