### ISSUE TITLE
Unnecessary git submodule?

### ISSUE THREAD

**Issue by daniel7558** [BelledonneCommunications/linphone-desktop#840]
Hi all, 

I noticed that one of the top-level submodules (`plugins/contacts/contacts-api`) seems to require credentials  to clone. When initializing the submodules, git will ignore submodules that it cannot access, i.e. this one does not get cloned when running `git submodule update --init --recursive` and its folder remains empty. 

Should this module be removed or is there a special purpose for it?  (It builds fine without the submodule)

```
[submodule "plugins/contacts/contacts-api"]
        path = plugins/contacts/contacts-api
        url =  https://gitlab.linphone.org/BC/public/linphone-desktop-plugins/contacts/contacts-api.git
```

Cheers

**Comment by Ledjlale** [comment]
Hi, thanks for your report. This repo is not private. It just doesn't exist.
I updated the .modules file in master
Regards
