### ISSUE TITLE
[Bug]: No suitable soundcard on Windows .Net8/WPF Application

### ISSUE THREAD

**Issue by Gorden998** [BelledonneCommunications/linphone-desktop#847]
### Context

use Linphone-sdk Windows version for my company, custom sip server.

### General information

- Device: Dell Vostro 3020
- OS: Windows 11 Pro, 23H2
- Version of the App:
- Version of the SDK: Linphone-sdk-win64-5.2.114 

### Expected behaviour

Environment: Linphone-sdk-win64-5.2.114, .Net8/WPF Application
I wanted to do a simple call with the Windows client calling mobile devices. Incoming/outcoming dial calls normally, but no audio output for both sides ( it certainly is Windows client side issue, because the mobile apps already can call each other).

- Already tested on 2 PC, 1 apple airpods, and 2 wired headset, all audio perform normally in other programs.
- Already grant system permission for input/output, can see the debug program in the system volume mixer.

### To Reproduce

SIP registered, and incoming or outcoming calls.

### Additional context

Logs maybe related:
Linphone-[Message](mediastreamer)Registering all soundcard handlers
Linphone-[Message](mediastreamer)Loading ms plugins from [.]
Linphone-[Message](mediastreamer)no plugin (*.dll) found in [.\libms*.dll] [2].
Linphone-[Error](liblinphone)Could not find a suitable soundcard with capabilities : 2
Linphone-[Error](liblinphone)Could not find a suitable soundcard with capabilities : 2
Linphone-[Error](liblinphone)Could not find a suitable soundcard with capabilities : 1
Linphone-[Error](liblinphone)Could not find a suitable soundcard with capabilities : 2

v=0
o=F 1718842163 1718842164 IN IP4 xx.xx.xx.xx
s=F
c=IN IP4 xx.xx.xx.xx
t=0 0
m=audio 29638 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=silenceSupp:off - - - -
a=ptime:20

Linphone-[Error](ortp)QOSAddSocketToFlow failed to add a flow with error 87
Linphone-[Message](liblinphone)Created stream of type audio at index 0: stream#0 [audio] in state [Stopped]
Linphone-[Warning](liblinphone)Failed to find audio device matching default output sound card [0000000000000000]
Linphone-[Warning](liblinphone)Failed to find audio device matching default input sound card [0000000000000000]
Linphone-[Error](liblinphone)Unable to retrieve contact address from proxy confguration for call session 0000022529C3E940

v=0
o=msp%xx%xx 3119 4065 IN IP4 xx.xx.xx.xx
s=Talk
c=IN IP4 xx.xx.xx.xx
t=0 0
m=audio 55831 RTP/AVP 0 101
a=rtpmap:101 telephone-event/8000

Linphone-[Message](liblinphone)Unable to find audio video conference with conference ID ConferenceId
Linphone-[Message](liblinphone)stream#0 [audio] in state [Stopped] is not part of any bundle
Linphone-[Message](liblinphone)Audio bandwidth for StreamsGroup [000001E48AF6F4D0] is 80
Linphone-[Message](liblinphone)stream#0 [audio] in state [Stopped] is not part of any bundle
Linphone-[Message](liblinphone)ICE state is IceStateNotActivated for stream#0 [audio] in state [Stopped]
Linphone-[Message](mediastreamer)Setting audio encoder network bitrate to [80000] on stream [000001E483E42010]
Linphone-[Message](liblinphone)AudioStream[000001E483E42010]: mic is [enabled].
Linphone-[Message](liblinphone)Unable to find audio video conference with conference ID ConferenceId

Linphone-[Message](mediastreamer)MSAudioMixer [000002252A23B6D0] is entering bypass mode.
Linphone-[Message](ortp)First estimation
Linphone-[Message](liblinphone)Bandwidth usage for CallSession [0000022529C3E940]:
	Stream #0 (audio) | cpu: 2.71% | RTP : [d=68.36,u=73.88] RTCP: [d=0.00,u=1.08]  (kbits/sec)
Linphone-[Message](mediastreamer)MSAudio_stream_iterate[000001E483E42010], local statistics available:
	Local current jitter buffer size:  45.5ms
Linphone-[Message](mediastreamer)Stun packet of length 20 sent on rtcp for session [0000022529BE72D0] 
Linphone-[Message](liblinphone)Bandwidth usage for CallSession [0000022529C3E940]:
	Stream #0 (audio) | cpu: 0.92% | RTP : [d=77.91,u=79.89] RTCP: [d=0.00,u=2.52]  (kbits/sec)
    Linphone-[Message](mediastreamer)Stun packet of length 20 sent on rtcp for session [0000022529BE72D0] 
Linphone-[Message](mediastreamer)Stun packet of length 20 sent on rtcp for session [0000022529BE72D0] 
Linphone-[Message](liblinphone)Bandwidth usage for CallSession [0000022529C3E940]:
	Stream #0 (audio) | cpu: 2.71% | RTP : [d=69.65,u=80.03] RTCP: [d=0.00,u=0.77]  (kbits/sec)

Linphone-[Message](mediastreamer)=================================================================================
Linphone-[Message](mediastreamer)                         FILTER USAGE STATISTICS                                 
Linphone-[Message](mediastreamer)Name                          Count           Time/tick (ms)            CPU Usage
Linphone-[Message](mediastreamer)                                        min     mean    max     sd               
Linphone-[Message](mediastreamer)---------------------------------------------------------------------------------
Linphone-[Message](mediastreamer)MSRtpSend                     1868      0.00    0.04    3.00    0.26         81.3
Linphone-[Message](mediastreamer)MSRtpRecv                     1868      0.00    0.01    3.00    0.12         15.1
Linphone-[Message](mediastreamer)MSAudioMixer                  3736      0.00    0.00    2.00    0.04          1.7
Linphone-[Message](mediastreamer)MSUlawEnc                     1868      0.00    0.00    1.00    0.02          1.2
Linphone-[Message](mediastreamer)MSResample                    2864      0.00    0.00    1.00    0.02          0.8
Linphone-[Message](mediastreamer)MSAudioFlowControl            921       0.00    0.00    0.00    0.00          0.0
Linphone-[Message](mediastreamer)MSGenericPLC                  1868      0.00    0.00    0.00    0.00          0.0
Linphone-[Message](mediastreamer)MSEqualizer                   2789      0.00    0.00    0.00    0.00          0.0
Linphone-[Message](mediastreamer)MSVolume                      2789      0.00    0.00    0.00    0.00          0.0
Linphone-[Message](mediastreamer)MSUlawDec                     893       0.00    0.00    0.00    0.00          0.0
Linphone-[Message](mediastreamer)MSFileRec                     996       0.00    0.00    0.00    0.00          0.0
Linphone-[Message](mediastreamer)MSFilePlayer                  3736      0.00    0.00    0.00    0.00          0.0
Linphone-[Message](mediastreamer)MSDtmfGen                     1868      0.00    0.00    0.00    0.00          0.0
Linphone-[Message](mediastreamer)MSSpeexEC                     0         0.00    0.00    0.00    0.00          0.0
Linphone-[Message](mediastreamer)=================================================================================

**Comment by Gorden998** [comment]
Please help. And i open issue on both linphone-desktop and linphone-sdk, not sure which is the better place.

**Comment by Ledjlale** [comment]
Hi
Wrong place here ;)
