### ISSUE TITLE
Enable AMR-WB codec on LinPhone

### ISSUE THREAD

**Issue by gbernaldo82** [BelledonneCommunications/linphone-desktop#848]
Hi, good morning!

I'm using linphone (free version for Linux) and I need to add support to the codec AMR-WB which it seems to be supported (at least ti's shown in the Advanced Features, here: https://new.linphone.org/technical-corner/linphone?qt-technical_corner=2#qt-technical_corner) 

The thing is I don't see the option in the window Preferences -> Audio -> Audio Codecs. 

So my question is about the support of this codec. Is it supported? Do I have to do something more (maybe install some package or whatever)?

Thank you so much in advance!

**Comment by Ledjlale** [comment]
Hi
The license for this codec is not free. So it is not embedded into the application. You have to buy it from them, build/get the library and put the file into your plugin folder.
Regards

**Comment by AkibHossainOmi** [comment]
Hi,
I was using the linphone-sdk for my android application.

I have build the sdk using docker with ,

```
cmake --preset=android-sdk -B build-android -DLINPHONESDK_ANDROID_ARCHS=arm64 \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DENABLE_NON_FREE_FEATURES=ON \
  -DENABLE_AMRNB=ON \
  -DENABLE_AMRWB=ON
  
  cmake --build build-android --parallel 4
```
But AMR is not present in the payload when I test the sdk.
Should I buy it?
Can't I build it by myself and use it?

Thanks in advance.
