### ISSUE TITLE
MacOS: Attended Transfer broken

### ISSUE THREAD

**Issue by kobaz** [BelledonneCommunications/linphone-desktop#851]
When completing an attended transfer on mac, the call goes on hold and the SIP REFER does not get sent to the PBX.

**Comment by kobaz** [comment]
Hi,

This is still a problem.  Can you re-open and send the template.

**Comment by Ledjlale** [comment]
The only way to post an issue here is to pass trough the template.
So I don't know what your are missing. Did you read it?

**Comment by kobaz** [comment]
Hi.

Sorry, I posted a blank issue.  There was no template.  I found the bug report element.  I see what's needed now.  Thanks.

**Comment by Ledjlale** [comment]
Thanks for your reply.  I wasn't aware of this option and will be removed.
