### ISSUE TITLE
no sound can be heard when the use the linphone_core_add_all_to_conference function.

### ISSUE THREAD

**Issue by Charist** [BelledonneCommunications/linphone-desktop#86]
1、In p2p situtation , I use 'linphone_core_accept_call', It's OK for the two client.
2、In multip-call situtation. I need use 'linphone_core_add_all_to_conference' after the  'linphone_core_accept_call'. a client call another one, the windows client can't hear any thing, while the other client which not need call 'linphone_core_add_all_to_conference' could hear the sound.

**## the log :**
LinphoneCore has video disabled for both capture and display, but video policy is to start the call with video. This is a possible mis-use of the API. In this case, video is disabled in default LinphoneCallParams

QOSAddSocketToFlow failed to add a flow with error 87
cannot set echo limiter to mode [1] because no volume send
QOSAddSocketToFlow failed to add a flow with error 87
MKVPlayer: no default video track. Looking for first video track
MKVPlayer: no video track found
线程 0x1fe8 已退出，返回值为 0 (0x0)。
LinphoneCall[28B262D0] - advanced adaptive rate control requested but avpf is not activated in this stream. Reverting to basic rate control instead.
Opus encoder cannot set codec bitrate to [34000] because of maxaveragebitrate constraint or absolute maximum bitrate value. New network bitrate is [46000]
no such method on filter MSWASAPIWrite, fid=16394 method index=2
cannot set echo limiter to mode [1] because no volume send
QOSAddSocketToFlow failed to add a flow with error 87
QOSAddSocketToFlow failed to add a flow with error 1168

MS_DECODER_HAVE_PLC function not implemented by the decoder: enable default plc
no such method on filter MSWASAPIWrite, fid=16394 method index=2
SetEventHandle for MSWASAPI audio output interface failed [8007007b]

Getting reference signal but no echo to synchronize on.
Not enough ref samples, using zeroes
LinphoneCall[28B262D0] - advanced adaptive rate control requested but avpf is not activated in this stream. Reverting to basic rate control instead.
SetEventHandle for MSWASAPI audio output interface failed [8007007b]
Getting reference signal but no echo to synchronize on.
Not enough ref samples, using zeroes
belle_sip_dialog_new(): there is a to tag in the request. This is not allowed to create a dialog on such a transaction.
belle_sip_dialog_new(): there is a to tag in the request. This is not allowed to create a dialog on such a transaction.
belle_sip_dialog_new(): there is a to tag in the request. This is not allowed to create a dialog on such a transaction.
Too much data in channel 1, 130 ms in excess dropped
belle_sip_dialog_new(): there is a to tag in the request. This is not allowed to create a dialog on such a transaction.

Can anyone can help, very appreciated.

**Comment by Wescoeur** [comment]
Not a valid issue. Please to open an issue on linphone submodules or use the mailing list. :)
