### ISSUE TITLE
Add auto-answer feature

### ISSUE THREAD

**Issue by mightydok** [BelledonneCommunications/linphone-desktop#89]
It would be great if Linphone used the Alert-Info and Call-Info SIP headers to implement custom ringtones and auto-answer.

I know Linphone allows auto-answer, but it's an all-or-nothing deal.

It would be better if (once the auto-answer config option is enabled), Linphone would answer the call based on this header:
Call-Info: answer-after=N

Where N is the number of seconds to wait. With N=0, there is no ring. The user can still reject the call before the timeout passes.

And Alert-Info can be used to use custom ringtones. Unlike with Call-Info and auto-answer, it seems that there is no consensus on this header, but rfc 3261 has this example:
Alert-Info: <http://www.example.com/sounds/moo.wav>

**Comment by Wescoeur** [comment]
Sorry, after discussion this feature it is not planned in Linphone Desktop.
But it can be easily implemented with the internal linphone api if you want.
