### ISSUE TITLE
command line argument "-c" not working

### ISSUE THREAD

**Issue by FrankBuss** [BelledonneCommunications/linphone-desktop#91]
When I start the Qt version like this:
```
linphone.exe -c "call 10000"
```
it doesn't call the number as I would expect. Instead I can see this in the log:
```
2017-10-04 11:52:22:911 MESSAGE QT: "Received command from other application: `show`."
```
I tried it with the latest snapshot: https://www.linphone.org/snapshots/windows/Linphone-4.1.1-21-g3f18c42-win32.exe

**Comment by Wescoeur** [comment]
`-c` option has been removed in the last git version. Please use the format described by the `--cli-help` option.

**Comment by isleshocky77** [comment]
@Wescoeur I'm running the latest stable flatpak off the website (4.1.1) and it contains neither the "-c" option or the "--cli-help" option. Any help would be appreciated. Would rather not put another bug report in.

**Comment by Wescoeur** [comment]
Sorry, this option is not available in this release. You can use the master branch or wait for the 4.2. (No release plan for the moment.)

**Comment by isleshocky77** [comment]
@Wescoeur Thanks for clarifying. That's what I was thinking; however it was driving me nuts. I'll take a look at master when I have some time.
