### ISSUE TITLE
NO video in macOS High Sierra (10.13)

### ISSUE THREAD

**Issue by bubudrc** [BelledonneCommunications/linphone-desktop#95]
Working on a mac app... after I'm updated my app... I dont get video. I got audio, but, the video doesnt work

**Comment by Wescoeur** [comment]
I can't reproduce your crashes. (Tested on MacOs 10.13.2) Can you enable and send your log at ronan.abhamon@belledonne-communications.com ?

**Comment by Wescoeur** [comment]
I can't reproduce your issue. (Tested on MacOs 10.13.2) Can you enable and send your log at ronan.abhamon@belledonne-communications.com ?

**Comment by bubudrc** [comment]
Fixed... was a layout problem with the nsview. thanks

**Comment by Wescoeur** [comment]
Okay, thank you for your feedback!
