### ISSUE TITLE
Build issues on Solus

### ISSUE THREAD

**Issue by baimafeima** [BelledonneCommunications/linphone-desktop#96]
OS: Solus 3 (https://solus-project.com/)
Some time ago there was a request for Linphone to be added to the Solus repositories. One of the developers stated the following: 

> So after further review, I'm going to have to reject this. Linphone relies on the belle-sip library for it's SIP features. This library is actively maintained and has proper releases. However, belle-sip relies on the antlr3 library which hasn't seen a commit in over a year and a release in over 2 years. Since antlr3 isn't eligible for inclusion, I have to reject this by proxy.

A year later a maintainer stated: 
> No, the issue is still the same. Antlr4 is available and seems to be a rewrite of antlr3, however I can't find any discussion about them moving towards the antlr4 library.

Please clarify whether there are any plans to move towards the antlr4 library. You can track the discussion here: https://dev.solus-project.com/T941

**Comment by cinnamoner** [comment]
This is rather unfortunate 'cause I want it to work on Solus as well.

**Comment by ethoms** [comment]
I would argue with the decision by that Solus maintainer. Firstly, some software products can be a done product, and do not necessarily need maintenance. Antlr3 is used in some very high profile places. From Wikipedia:

> Here is a non-comprehensive list of software built using ANTLR:
> 
>     Groovy.[citation needed]
>     Jython.[citation needed]
>     Hibernate.[citation needed]
>     OpenJDK Compiler Grammar project experimental version of the javac compiler based upon a grammar written in ANTLR.[citation needed]
>     Apex, Salesforce.com's programming language.[citation needed]
>     The expression evaluator in Numbers, Apple's spreadsheet.[citation needed]
>     Twitter's search query language.[citation needed]
>     Weblogic server.[citation needed]
>     IntelliJ IDEA and Clion.[citation needed]
>     Apache Cassandra.[citation needed]
>     Processing.[citation needed]
>     JabRef.[citation needed]

 
Secondly, Antlr3 is a tool, used locally for language and grammar parsing etc. It's hardly susceptible to vulnerabilities.

Thridly, Antlr3 is only a build dependency, which means it doesn't even need to be in the repository, depending on the Solus build system of course. I maintain the Slackware SlackBuilds for Linphone (and belle-sip), the required build dependency antlr3.jar is only a source archive that gets thrown away after the build. It never gets installed to the users system.

I understand the Solus projects concerns with package quality, but it sounds to me like they use it as a excuse when packaging gets difficult. And trust me, packaging Linphone and it's components isn't so simple.

**Comment by Wescoeur** [comment]
Antlr3 is used to generate grammar in belle-sip, it must be replaced by `belr`... It's a lot of work! So a temporary solution is to push generated grammar files in the project. (It should be the case soon!)
