### ISSUE TITLE
Timeout after 30 seconds

### ISSUE THREAD

**Issue by BengtHagemeister** [BelledonneCommunications/linphone-desktop#98]
After 30 seconds linphone declines the call. Is it possible to change that value in the code? 
I only found maxtime for the notification but not for the call.

Thanks

**Comment by Wescoeur** [comment]
You can set the ring time in the linphonerc file at this line: `inc_timeout=30` in the `[sip]` part.

**Comment by S0U1SB4N3** [comment]
I had this issue and resolved it on the asterisk settings side its the keep alive if you aren't using linphone servers and using your own then you need to ensure your asterisk is getting the token
